ROSaic: GprmcParser Class Reference
GprmcParser Class Reference
Derived class for parsing RMC messages.
#include <gprmc.hpp>
Public Member Functions
GprmcParser ()
Constructor of the class GprmcParser.
const std::string getMessageID () const override
Returns the ASCII message ID, here "$GPRMC".
septentrio_gnss_driver::GprmcPtr parseASCII (const NMEASentence &sentence) noexcept(false) override
Parses one RMC message.
bool wasLastGPRMCValid () const
Tells us whether the last RMC message was valid/usable or not.
Public Member Functions inherited from BaseParser< septentrio_gnss_driver::GprmcPtr >
BaseParser ()=default
Default constructor of the class BaseParser.
virtual ~BaseParser ()=default
Default destructor of the class BaseParser.
septentrio_gnss_driver::GprmcPtr parseBinary (const SBFStructT &bin_msg) noexcept(false)
Converts bin_msg into a ROS message pointer (e.g. nmea_msgs::GpggaPtr) and returns it.
Static Public Attributes
static const std::string MESSAGE_ID = "$GPRMC"
Declares the string MESSAGE_ID.
static constexpr double KNOTS_TO_MPS = 0.5144444
Private Attributes
bool was_last_gprmc_valid_
Declares a boolean representing whether or not the last GPRMC message was valid.
Detailed Description
Derived class for parsing RMC messages.
Date
28/09/20
Definition at line 83 of file gprmc.hpp.
Constructor & Destructor Documentation
GprmcParser()
GprmcParser::GprmcParser () inline
Constructor of the class GprmcParser.
Definition at line 90 of file gprmc.hpp.
References getMessageID(), parseASCII(), and wasLastGPRMCValid().
 : BaseParser<septentrio_gnss_driver::GprmcPtr>(), was_last_gprmc_valid_(false) {}
Member Function Documentation
getMessageID()
const std::string GprmcParser::getMessageID () const override virtual
Returns the ASCII message ID, here "$GPRMC".
Returns
The message ID
Implements BaseParser< septentrio_gnss_driver::GprmcPtr >.
Definition at line 41 of file gprmc.cpp.
References MESSAGE_ID.
Referenced by GprmcParser().
 {
     return GprmcParser::MESSAGE_ID;
 }
parseASCII()
septentrio_gnss_driver::GprmcPtr GprmcParser::parseASCII (const NMEASentence & sentence) override virtual noexcept
Parses one RMC message.
Parameters
[in] sentence The RMC message to be parsed
Returns
A ROS message pointer of ROS type septentrio_gnss_driver::GprmcPtr
Caution: Due to the occurrence of the throw keyword, this method ParseASCII should be called within a try / catch framework... Note: This method is called from within the read() method of the RxMessage class by including the checksum part in the argument "sentence" here, though the checksum is never parsed: It would be sentence.get_body()[13] if anybody ever needs it. The status character can be 'A' (for Active) or 'V' (for Void), signaling whether the GPS was active when the positioning was made. If it is void, the GPS could not make a good positioning and you should thus ignore it. This usually occurs when the GPS is still searching for satellites. WasLastGPRMCValid() will return false in this case.
Reimplemented from BaseParser< septentrio_gnss_driver::GprmcPtr >.
Definition at line 54 of file gprmc.cpp.
References parsing_utilities::convertDMSToDegrees(), parsing_utilities::convertUTCDoubleToSeconds(), parsing_utilities::convertUTCtoUnix(), g_frame_id, g_use_gnss_time, KNOTS_TO_MPS, parsing_utilities::parseDouble(), parsing_utilities::parseFloat(), string_utilities::toDouble(), and was_last_gprmc_valid_.
Referenced by GprmcParser(), and io_comm_rx::RxMessage::read().
 {
     // Checking the length first, it should be between 13 and 14 elements
     const size_t LEN_MIN = 13;
     const size_t LEN_MAX = 14;
     if (sentence.get_body().size() > LEN_MAX ||
       sentence.get_body().size() < LEN_MIN)
     {
         std::stringstream error;
         error << "Expected GPRMC length is between " << LEN_MIN << " and "
             << LEN_MAX << ". The actual length is " << sentence.get_body().size();
         throw ParseException(error.str());
     }
     septentrio_gnss_driver::GprmcPtr msg = boost::make_shared<septentrio_gnss_driver::Gprmc>();
     msg->header.frame_id = g_frame_id;
     msg->message_id = sentence.get_body()[0];
     if (sentence.get_body()[1].empty() || sentence.get_body()[1] == "0")
     {
         msg->utc_seconds = 0;
     }
     else
     {
         double utc_double;
         if (string_utilities::toDouble(sentence.get_body()[1], utc_double))
         {
             msg->utc_seconds = parsing_utilities::convertUTCDoubleToSeconds(utc_double);
             if(g_use_gnss_time)
             {
                 // The Header's Unix Epoch time stamp
                 time_t unix_time_seconds = parsing_utilities::convertUTCtoUnix(utc_double);
                 // The following assumes that there are two digits after the decimal point in utc_double, i.e. in the NMEA UTC time.
                 uint32_t unix_time_nanoseconds = (static_cast<uint32_t>(utc_double*100)%100)*10000;
                 msg->header.stamp.sec = unix_time_seconds;
                 msg->header.stamp.nsec = unix_time_nanoseconds;
             }
             else
             {
                 ros::Time time_obj;
                 time_obj = ros::Time::now();
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
             }
         }
         else
         {
             throw ParseException("Error parsing UTC seconds in GPRMC"); // E.g. if one of the fields of the NMEA UTC string is empty
         }
     }
     bool valid = true;
     bool to_be_ignored = false;
     msg->position_status = sentence.get_body()[2];
     // Check to see whether this message should be ignored
     to_be_ignored &= !(sentence.get_body()[2].compare("A") == 0); // 0 : if both strings are equal.
     to_be_ignored &= (sentence.get_body()[3].empty() || sentence.get_body()[5].empty());
     double latitude = 0.0;
     valid = valid && parsing_utilities::parseDouble(sentence.get_body()[3], latitude);
     msg->lat = parsing_utilities::convertDMSToDegrees(latitude);
     double longitude = 0.0;
     valid = valid && parsing_utilities::parseDouble(sentence.get_body()[5], longitude);
     msg->lon = parsing_utilities::convertDMSToDegrees(longitude);
     msg->lat_dir = sentence.get_body()[4];
     msg->lon_dir = sentence.get_body()[6];
     valid = valid && parsing_utilities::parseFloat(sentence.get_body()[7], msg->speed);
     msg->speed *= KNOTS_TO_MPS;
     valid = valid && parsing_utilities::parseFloat(sentence.get_body()[8], msg->track);
     std::string date_str = sentence.get_body()[9];
     if (!date_str.empty())
     {
         msg->date = std::string("20") + date_str.substr(4, 2) +
                 std::string("-") + date_str.substr(2, 2) +
                 std::string("-") + date_str.substr(0, 2);
     }
     valid = valid && parsing_utilities::parseFloat(sentence.get_body()[10], msg->mag_var);
     msg->mag_var_direction = sentence.get_body()[11];
     if (sentence.get_body().size() == LEN_MAX)
     {
         msg->mode_indicator = sentence.get_body()[12];
     }
     if (!valid)
     {
         was_last_gprmc_valid_ = false;
         throw ParseException("Error parsing GPRMC message.");
     }
     was_last_gprmc_valid_ = !to_be_ignored;
     return msg;
 }
wasLastGPRMCValid()
bool GprmcParser::wasLastGPRMCValid () const
Tells us whether the last RMC message was valid/usable or not.
Returns
True if last RMC message was valid, false if not
E.g. if the status is V=Void, then this function will also return false.
Definition at line 158 of file gprmc.cpp.
References was_last_gprmc_valid_.
Referenced by GprmcParser().
 {
     return was_last_gprmc_valid_;
 }
Field Documentation
KNOTS_TO_MPS
constexpr double GprmcParser::KNOTS_TO_MPS = 0.5144444 static
1 kt = 0.51444444444 mps (meters per second) Note that constexpr is needed for in-class initialization of static data members.
Definition at line 120 of file gprmc.hpp.
Referenced by parseASCII().
MESSAGE_ID
const std::string GprmcParser::MESSAGE_ID = "$GPRMC" static
Declares the string MESSAGE_ID.
Definition at line 116 of file gprmc.hpp.
Referenced by getMessageID().
was_last_gprmc_valid_
bool GprmcParser::was_last_gprmc_valid_ private
Declares a boolean representing whether or not the last GPRMC message was valid.
Definition at line 126 of file gprmc.hpp.
Referenced by parseASCII(), and wasLastGPRMCValid().
The documentation for this class was generated from the following files:
include/septentrio_gnss_driver/parsers/nmea_parsers/gprmc.hpp
src/septentrio_gnss_driver/parsers/nmea_parsers/gprmc.cpp