ROSaic: GpggaParser Class Reference
GpggaParser Class Reference
Derived class for parsing GGA messages.
#include <gpgga.hpp>
Public Member Functions
GpggaParser ()
Constructor of the class GpggaParser.
const std::string getMessageID () const override
Returns the ASCII message ID, here "$GPGGA".
septentrio_gnss_driver::GpggaPtr parseASCII (const NMEASentence &sentence) noexcept(false) override
Parses one GGA message.
bool wasLastGPGGAValid () const
Tells us whether the last GGA message was valid or not.
Public Member Functions inherited from BaseParser< septentrio_gnss_driver::GpggaPtr >
BaseParser ()=default
Default constructor of the class BaseParser.
virtual ~BaseParser ()=default
Default destructor of the class BaseParser.
septentrio_gnss_driver::GpggaPtr parseBinary (const SBFStructT &bin_msg) noexcept(false)
Converts bin_msg into a ROS message pointer (e.g. nmea_msgs::GpggaPtr) and returns it.
Static Public Attributes
static const std::string MESSAGE_ID = "$GPGGA"
Declares the string MESSAGE_ID.
Private Attributes
bool was_last_gpgga_valid_
Declares a boolean representing whether or not the last GPGGA message was valid.
Detailed Description
Derived class for parsing GGA messages.
Date
13/08/20
Definition at line 83 of file gpgga.hpp.
Constructor & Destructor Documentation
GpggaParser()
GpggaParser::GpggaParser () inline
Constructor of the class GpggaParser.
Definition at line 90 of file gpgga.hpp.
References getMessageID(), parseASCII(), and wasLastGPGGAValid().
 : BaseParser<septentrio_gnss_driver::GpggaPtr>(), was_last_gpgga_valid_(false) {}
Member Function Documentation
getMessageID()
const std::string GpggaParser::getMessageID () const override virtual
Returns the ASCII message ID, here "$GPGGA".
Returns
The message ID
Implements BaseParser< septentrio_gnss_driver::GpggaPtr >.
Definition at line 41 of file gpgga.cpp.
References MESSAGE_ID.
Referenced by GpggaParser().
 {
     return GpggaParser::MESSAGE_ID;
 }
parseASCII()
septentrio_gnss_driver::GpggaPtr GpggaParser::parseASCII (const NMEASentence & sentence) override virtual noexcept
Parses one GGA message.
Parameters
[in] sentence The GGA message to be parsed
Returns
A ROS message pointer of ROS type septentrio_gnss_driver::GpggaPtr
Caution: Due to the occurrence of the throw keyword, this method parseASCII should be called within a try / catch framework... Note: This method is called from within the read() method of the RxMessage class by including the checksum part in the argument "sentence" here, though the checksum is never parsed: It would be sentence.get_body()[15] if anybody ever needs it.
Reimplemented from BaseParser< septentrio_gnss_driver::GpggaPtr >.
Definition at line 51 of file gpgga.cpp.
References parsing_utilities::convertDMSToDegrees(), parsing_utilities::convertUTCDoubleToSeconds(), parsing_utilities::convertUTCtoUnix(), g_frame_id, g_use_gnss_time, parsing_utilities::parseDouble(), parsing_utilities::parseFloat(), parsing_utilities::parseUInt32(), string_utilities::toDouble(), and was_last_gpgga_valid_.
Referenced by GpggaParser(), and io_comm_rx::RxMessage::read().
 {
     //ROS_DEBUG("Just testing that first entry is indeed what we expect it to be: %s", sentence.get_body()[0].c_str());
     // Check the length first, which should be 16 elements.
     const size_t LEN = 16;
     if (sentence.get_body().size() > LEN || sentence.get_body().size() < LEN)
     {
         std::stringstream error;
         error << "GGA parsing failed: Expected GPGGA length is " << LEN << ", but actual length is " << sentence.get_body().size();
         throw ParseException(error.str());
     }
     septentrio_gnss_driver::GpggaPtr msg = boost::make_shared<septentrio_gnss_driver::Gpgga>();
     msg->header.frame_id = g_frame_id;
     msg->message_id = sentence.get_body()[0];
     if (sentence.get_body()[1].empty() || sentence.get_body()[1] == "0")
     {
         msg->utc_seconds = 0;
     }
     else
     {
         double utc_double;
         if (string_utilities::toDouble(sentence.get_body()[1], utc_double))
         {
             if(g_use_gnss_time)
             {
                 //ROS_DEBUG("utc_double is %f", (float) utc_double);
                 msg->utc_seconds = parsing_utilities::convertUTCDoubleToSeconds(utc_double);
                 // The Header's Unix Epoch time stamp
                 time_t unix_time_seconds = parsing_utilities::convertUTCtoUnix(utc_double);
                 // The following assumes that there are two digits after the decimal point in utc_double, i.e. in the NMEA UTC time.
                 uint32_t unix_time_nanoseconds = (static_cast<uint32_t>(utc_double*100)%100)*10000;
                 msg->header.stamp.sec = unix_time_seconds;
                 msg->header.stamp.nsec = unix_time_nanoseconds;
             }
             else
             {
                 ros::Time time_obj;
                 time_obj = ros::Time::now();
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
             }
         }
         else
         {
             throw ParseException("Error parsing UTC seconds in GPGGA"); // E.g. if one of the fields of the NMEA UTC string is empty
         }
     }
     bool valid = true;
     double latitude = 0.0;
     valid = valid && parsing_utilities::parseDouble(sentence.get_body()[2], latitude);
     msg->lat = parsing_utilities::convertDMSToDegrees(latitude);
     double longitude = 0.0;
     valid = valid && parsing_utilities::parseDouble(sentence.get_body()[4], longitude);
     msg->lon = parsing_utilities::convertDMSToDegrees(longitude);
     msg->lat_dir = sentence.get_body()[3];
     msg->lon_dir = sentence.get_body()[5];
     valid = valid && parsing_utilities::parseUInt32(sentence.get_body()[6], msg->gps_qual);
     valid = valid && parsing_utilities::parseUInt32(sentence.get_body()[7], msg->num_sats);
     //ROS_INFO("Valid is %s so far with number of satellites in use being %s", valid ? "true" : "false", sentence.get_body()[7].c_str());
     valid = valid && parsing_utilities::parseFloat(sentence.get_body()[8], msg->hdop);
     valid = valid && parsing_utilities::parseFloat(sentence.get_body()[9], msg->alt);
     msg->altitude_units = sentence.get_body()[10];
     valid = valid && parsing_utilities::parseFloat(sentence.get_body()[11], msg->undulation);
     msg->undulation_units = sentence.get_body()[12];
     double diff_age_temp;
     valid = valid && parsing_utilities::parseDouble(sentence.get_body()[13], diff_age_temp);
     msg->diff_age = static_cast<uint32_t>(round(diff_age_temp));
     msg->station_id = sentence.get_body()[14];
     if (!valid)
     {
         was_last_gpgga_valid_ = false;
         throw ParseException("GPGGA message was invalid.");
     }
     // If we made it this far, we successfully parsed the message and will consider it to be valid.
     was_last_gpgga_valid_ = true;
     return msg;
 }
wasLastGPGGAValid()
bool GpggaParser::wasLastGPGGAValid () const
Tells us whether the last GGA message was valid or not.
Returns
True if last GGA message was valid, false if not
Definition at line 141 of file gpgga.cpp.
References was_last_gpgga_valid_.
Referenced by GpggaParser().
 {
     return was_last_gpgga_valid_;
 }
Field Documentation
MESSAGE_ID
const std::string GpggaParser::MESSAGE_ID = "$GPGGA" static
Declares the string MESSAGE_ID.
Definition at line 114 of file gpgga.hpp.
Referenced by getMessageID().
was_last_gpgga_valid_
bool GpggaParser::was_last_gpgga_valid_ private
Declares a boolean representing whether or not the last GPGGA message was valid.
Definition at line 120 of file gpgga.hpp.
Referenced by parseASCII(), and wasLastGPGGAValid().
The documentation for this class was generated from the following files:
include/septentrio_gnss_driver/parsers/nmea_parsers/gpgga.hpp
src/septentrio_gnss_driver/parsers/nmea_parsers/gpgga.cpp