MinROS: minros_driver::GpggaParser Class Reference
minros_driver::GpggaParser Class Reference
Derived class for parsing GGA messages.
#include <gpgga.hpp>
Public Member Functions
GpggaParser ()
Constructor of the class GpggaParser.
const std::string GetMessageID () const override
Returns the ASCII message ID, here "$GPGGA".
nmea_msgs::GpggaPtr ParseASCII (const NMEASentence &sentence) noexcept(false) override
Parses one GGA message.
bool WasLastGPGGAValid () const
Tells us whether the last GGA message was valid or not.
Public Member Functions inherited from minros_driver::BaseParser< nmea_msgs::GpggaPtr >
BaseParser ()=default
Default constructor of the class BaseParser.
virtual ~BaseParser ()=default
Default destructor of the class BaseParser.
virtual nmea_msgs::GpggaPtr ParseBinary (const SBFBlock &bin_msg) noexcept(false)
Converts bin_msg into a ROS message pointer (e.g. MinROS::GpggaPtr) and returns it.
Static Public Attributes
static const std::string MESSAGE_ID = "$GPGGA"
Declares the string MESSAGE_ID.
Private Attributes
bool was_last_gpgga_valid_
Declares a boolean representing whether or not the last GPGGA message was valid.
Detailed Description
Derived class for parsing GGA messages.
Here, the access-specifier is set to "public". Recall this type of inheritance: In public access mode, public members of the base class will become public in the derived class and protected members of the base class will become protected in the derived class.
Date
13/08/20
Definition at line 56 of file gpgga.hpp.
Constructor & Destructor Documentation
GpggaParser()
minros_driver::GpggaParser::GpggaParser () inline
Constructor of the class GpggaParser.
Here, we make use of the concept of member initialization lists: Instead of writing all the initialization specifications into {}, we can list all of these, delimited by commas, before the opening and closing bracket {}.
Definition at line 66 of file gpgga.hpp.
References GetMessageID(), ParseASCII(), and WasLastGPGGAValid().
                      : BaseParser<nmea_msgs::GpggaPtr>(), was_last_gpgga_valid_(false)
         {}
Member Function Documentation
GetMessageID()
const std::string minros_driver::GpggaParser::GetMessageID () const override virtual
Returns the ASCII message ID, here "$GPGGA".
Returns
The message ID
Implements minros_driver::BaseParser< nmea_msgs::GpggaPtr >.
Definition at line 44 of file gpgga.cpp.
References MESSAGE_ID.
Referenced by GpggaParser().
 {
     return minros_driver::GpggaParser::MESSAGE_ID;
 }
ParseASCII()
nmea_msgs::GpggaPtr minros_driver::GpggaParser::ParseASCII (const NMEASentence & sentence) override virtual noexcept
Parses one GGA message.
Parameters
[in] sentence The GGA message to be parsed
Returns
A ROS message pointer of ROS type nmea_msgs::GpggaPtr
Caution: Due to the occurrence of the throw keyword, this method ParseAscii should be called within a try / catch framework... Note: This method assumes that "sentence" does not include the checksum part of the GGA message.
Reimplemented from minros_driver::BaseParser< nmea_msgs::GpggaPtr >.
Definition at line 53 of file gpgga.cpp.
References minros_driver::ConvertDMSToDegrees(), frame_id, minros_driver::ParseDouble(), minros_driver::ParseFloat(), minros_driver::ParseUInt32(), string_utilities::ToDouble(), minros_driver::UTCDoubleToSeconds(), minros_driver::UTCtoUnix(), and was_last_gpgga_valid_.
Referenced by GpggaParser(), and io_comm_mosaic::mosaicMessage::read().
 {
     //ROS_DEBUG("Just testing that first entry is indeed what we expect it to: %s", sentence.get_body()[0].c_str());
     // Check the length first, which should be 15 elements (if station ID available, otherwise missing field, not empty field) or 14 elements (if station ID not avaiable).
     const size_t MAX_LEN = 15;
     const size_t MIN_LEN = 14;
     if (sentence.get_body().size() > MAX_LEN || sentence.get_body().size() < MIN_LEN)
     {
         std::stringstream error;
         error << "Expected GPGGA length " << MIN_LEN << "  <= length <= "
               << MAX_LEN << ", actual length = " << sentence.get_body().size();
         throw ParseException(error.str());
     }
     nmea_msgs::GpggaPtr msg = boost::make_shared<nmea_msgs::Gpgga>();
     msg->header.frame_id = frame_id;
     msg->message_id = sentence.get_body()[0];
     if (sentence.get_body()[1].empty() || sentence.get_body()[1] == "0")
     {
         msg->utc_seconds = 0;
     }
     else
     {
         double utc_double;
         if (string_utilities::ToDouble(sentence.get_body()[1], utc_double))
         {
             //ROS_DEBUG("utc_double is %f", (float) utc_double);
             msg->utc_seconds = UTCDoubleToSeconds(utc_double);
             // The Header's Unix Epoch time stamp
             time_t unix_time_seconds = UTCtoUnix(utc_double);
             uint32_t unix_time_nanoseconds = (static_cast<uint32_t>(utc_double*100)%100)*10000; // Assumes there are two digits after the decimal point in NMEA UTC time
             msg->header.stamp.sec = unix_time_seconds;
             msg->header.stamp.nsec = unix_time_nanoseconds;
         }
         else
         {
             throw minros_driver::ParseException("Error parsing UTC seconds in GPGGA"); // E.g. if one of the time fields of the string is empty
         }
     }
     bool valid = true;
     double latitude = 0.0;
     valid = valid && minros_driver::ParseDouble(sentence.get_body()[2], latitude);
     msg->lat = ConvertDMSToDegrees(latitude);
     double longitude = 0.0;
     valid = valid && minros_driver::ParseDouble(sentence.get_body()[4], longitude);
     msg->lon = ConvertDMSToDegrees(longitude);
     msg->lat_dir = sentence.get_body()[3];
     msg->lon_dir = sentence.get_body()[5];
     valid = valid && minros_driver::ParseUInt32(sentence.get_body()[6], msg->gps_qual);
     valid = valid && minros_driver::ParseUInt32(sentence.get_body()[7], msg->num_sats);
     //ROS_DEBUG("Valid is %s so far with number of satellites in use being %s", valid ? "true" : "false", sentence.get_body()[7].c_str());
     valid = valid && minros_driver::ParseFloat(sentence.get_body()[8], msg->hdop);
     valid = valid && minros_driver::ParseFloat(sentence.get_body()[9], msg->alt);
     msg->altitude_units = sentence.get_body()[10];
     valid = valid && minros_driver::ParseFloat(sentence.get_body()[11], msg->undulation);
     msg->undulation_units = sentence.get_body()[12];
     valid = valid && minros_driver::ParseUInt32(sentence.get_body()[13], msg->diff_age);
     if (sentence.get_body().size() == MAX_LEN)
     {
         msg->station_id = sentence.get_body()[14];
     }
     else
     {
         msg->station_id = "";
     }
     if (!valid)
     {
         was_last_gpgga_valid_ = false;
         throw ParseException("GPGGA message was invalid.");
     }
     // If we made it this far, we successfully parsed the message and will consider it to be valid.
     was_last_gpgga_valid_ = true;
     return msg;
 }
WasLastGPGGAValid()
bool minros_driver::GpggaParser::WasLastGPGGAValid () const
Tells us whether the last GGA message was valid or not.
Returns
True if last GGA message was valid, false if not
Definition at line 139 of file gpgga.cpp.
References was_last_gpgga_valid_.
Referenced by GpggaParser().
 {
     return was_last_gpgga_valid_;
 }
Field Documentation
MESSAGE_ID
const std::string minros_driver::GpggaParser::MESSAGE_ID = "$GPGGA" static
Declares the string MESSAGE_ID.
Definition at line 91 of file gpgga.hpp.
Referenced by GetMessageID().
was_last_gpgga_valid_
bool minros_driver::GpggaParser::was_last_gpgga_valid_ private
Declares a boolean representing whether or not the last GPGGA message was valid.
Definition at line 97 of file gpgga.hpp.
Referenced by ParseASCII(), and WasLastGPGGAValid().
The documentation for this class was generated from the following files:
include/MinROS/parsers/nmea_parsers/gpgga.hpp
src/MinROS/parsers/nmea_parsers/gpgga.cpp