ROSaic: io_comm_mosaic::CallbackHandlers Class Reference
io_comm_mosaic::CallbackHandlers Class Reference
Represents ensemble of (to be constructed) ROS messages, to be handled at once by this class.
#include <callbackhandlers.hpp>
Public Types
typedef std::multimap< std::string, boost::shared_ptr< AbstractCallbackHandler > > CallbackMap
Key is std::string and represents the ROS message key, value is boost::shared_ptr<CallbackHandler>
Public Member Functions
CallbackHandlers ()=default
template<typename T >
CallbackMap Insert (std::string message_key, typename CallbackHandler< T >::Callback callback)
void Handle (mosaicMessage &mMessage)
void ReadCallback (const uint8_t *data, std::size_t &size)
Searches for mosaic messages that could potentially be decoded/parsed/published.
Data Fields
CallbackMap callbackmap_
Static Private Attributes
static boost::mutex callback_mutex_
Detailed Description
Represents ensemble of (to be constructed) ROS messages, to be handled at once by this class.
Definition at line 178 of file callbackhandlers.hpp.
Member Typedef Documentation
CallbackMap
typedef std::multimap<std::string, boost::shared_ptr<AbstractCallbackHandler> > io_comm_mosaic::CallbackHandlers::CallbackMap
Key is std::string and represents the ROS message key, value is boost::shared_ptr<CallbackHandler>
Definition at line 184 of file callbackhandlers.hpp.
Constructor & Destructor Documentation
CallbackHandlers()
io_comm_mosaic::CallbackHandlers::CallbackHandlers () default
Member Function Documentation
Handle()
void io_comm_mosaic::CallbackHandlers::Handle (mosaicMessage & mMessage) inline
This method is called every time mMessage is found to contain some potentially useful message. The for loop forwards to a ROS message specific handle if the latter was added via callbackmap_.insert at some earlier point.
Definition at line 203 of file callbackhandlers.hpp.
References io_comm_mosaic::mosaicMessage::MessageID(), publish_gpsfix, publish_gpst, publish_navsatfix, and publish_posewithcovariancestamped.
             {
                 // Find the ROS message callback handler for equivalent mosaic message at hand & call it
                 boost::mutex::scoped_lock lock(callback_mutex_);
                 CallbackMap::key_type key = mMessage.MessageID();
                 std::string ID_temp = mMessage.MessageID();
                 if (!(ID_temp == "4013" || ID_temp == "4027" || ID_temp == "4001"|| ID_temp == "5908"))
                 // We only want to handle SatVisibility, ChannelStatus, DOP and VelCovGeodetic blocks in case GPSFix messages are to be published, see few lines below.
                 {
                     for (CallbackMap::iterator callback = callbackmap_.lower_bound(key); callback != callbackmap_.upper_bound(key); ++callback)
                     {
                         try
{
                             callback->second->Handle(mMessage, callback->first);
                         }
                         catch (std::runtime_error& e)
{
                             throw std::runtime_error(e.what());
                         }
                     }
                 }
                 // Call NavSatFix callback function if it was added
                 if (publish_navsatfix)
                 {
                     CallbackMap::key_type key = "NavSatFix";
                     std::string ID_temp = mMessage.MessageID();
                     if (ID_temp == "4007")  // If no new PVTGeodetic block is coming in, there is no need to publish NavSatFix anew.
                                             // It would be wasteful to also call the NavSatFix handle if the PosCovGeodetic block comes in.
                     {
                         for (CallbackMap::iterator callback = callbackmap_.lower_bound(key); callback != callbackmap_.upper_bound(key); ++callback)
{
                             try
{
                                 callback->second->Handle(mMessage, callback->first);
                             }
                             catch (std::runtime_error& e)
{
                                 throw std::runtime_error(e.what());
                             }
                         }
                     }
                 }
                 // Call geometry_msgs::PoseWithCovarianceStamped callback function if it was added
                 if (publish_posewithcovariancestamped)
                 {
                     CallbackMap::key_type key = "PoseWithCovarianceStamped";
                     std::string ID_temp = mMessage.MessageID();
                     if (ID_temp == "4007")  // If no new PVTGeodetic block is coming in, there is no need to publish PoseWithCovarianceStamped anew.
                                             // It would be wasteful to also call the PoseWithCovarianceStamped handle if the PosCovGeodetic block etc. comes in.
                     {
                         for (CallbackMap::iterator callback = callbackmap_.lower_bound(key); callback != callbackmap_.upper_bound(key); ++callback)
{
                             try
{
                                 callback->second->Handle(mMessage, callback->first);
                             }
                             catch (std::runtime_error& e)
{
                                 throw std::runtime_error(e.what());
                             }
                         }
                     }
                 }
                 // Call sensor_msgs::TimeReference (with GPST) callback function if it was added
                 if (publish_gpst)
                 {
                     CallbackMap::key_type key = "GPST";
                     std::string ID_temp = mMessage.MessageID();
                     if (ID_temp == "4007")  // If no new PVTGeodetic block is coming in, there is no need to publish PoseWithCovarianceStamped anew.
                                             // It would be wasteful to also call the PoseWithCovarianceStamped handle if the PosCovGeodetic block etc. comes in.
                     {
                         for (CallbackMap::iterator callback = callbackmap_.lower_bound(key); callback != callbackmap_.upper_bound(key); ++callback)
{
                             try
{
                                 callback->second->Handle(mMessage, callback->first);
                             }
                             catch (std::runtime_error& e)
{
                                 throw std::runtime_error(e.what());
                             }
                         }
                     }
                 }
                 // Call GPSFix callback function if it was added
                 if (publish_gpsfix)
                 {
                     CallbackMap::key_type key1 = "GPSFix";
                     std::string ID_temp = mMessage.MessageID();
                     if (ID_temp == "4007")  // If no new PVTGeodetic block is coming in, there is no need to publish GPSFix anew.
                                             // It would be wasteful to also call the GPSFix handle when any of the PosCovGeodetic, SatVisibility, ChannelStatus etc. blocks comes in.
                     {
                         for (CallbackMap::iterator callback = callbackmap_.lower_bound(key1); callback != callbackmap_.upper_bound(key1); ++callback)
{
                             try
{
                                 callback->second->Handle(mMessage, callback->first);
                             }
                             catch (std::runtime_error& e)
{
                                 throw std::runtime_error(e.what());
                             }
                         }
                     }
                     CallbackMap::key_type key2 = mMessage.MessageID();
                     if (ID_temp == "4013" || ID_temp == "4027" || ID_temp == "4001" || ID_temp == "5908")
                     // Even though we are not interested in publishing SatVisibility (4012) and ChannelStatus (4013) ROS messages, we have to save
                     // some contents of these incoming blocks in order to publish the GPSFix message. When these 2 blocks come in, the unchanged GPSFix message is published anew.
                     {
                         for (CallbackMap::iterator callback = callbackmap_.lower_bound(key2); callback != callbackmap_.upper_bound(key2); ++callback)
{
                             try
{
                                 callback->second->Handle(mMessage, callback->first);
                             }
                             catch (std::runtime_error& e)
{
                                 throw std::runtime_error(e.what());
                             }
                         }
                     }
                 }
             }
Insert()
template<typename T > CallbackMap io_comm_mosaic::CallbackHandlers::Insert (std::string message_key, typename CallbackHandler< T >::Callback callback) inline
Insert adds a pair to our multimap, with the message_ID being the key; this method is called by handlers_ in rosaic_node.cpp T would be a (custom or not) ROS message, e.g. rosaic::PVTGeodetic, or nmea_msgs::GPGGA
Definition at line 191 of file callbackhandlers.hpp.
Referenced by rosaic_node::ROSaicNode::DefineMessages().
             {
                 boost::mutex::scoped_lock lock(callback_mutex_);
                 CallbackHandler<T>* handler = new CallbackHandler<T>(callback); // Adding typename might be cleaner, but is optional again
                 callbackmap_.insert(std::make_pair(message_key, boost::shared_ptr<AbstractCallbackHandler>(handler)));
                 CallbackMap::key_type key = message_key;
                 ROS_DEBUG("Key successfully inserted to multimap: %s", ((unsigned int) callbackmap_.count(key)) ? "true" : "false");
                 return callbackmap_;
             }
ReadCallback()
void io_comm_mosaic::CallbackHandlers::ReadCallback (const uint8_t * data, std::size_t & size) inline
Searches for mosaic messages that could potentially be decoded/parsed/published.
Parameters
[in] data Buffer passed on from AsyncManager class
[in] size Size of the buffer
Definition at line 332 of file callbackhandlers.hpp.
References io_comm_mosaic::mosaicMessage::BlockLength(), cd_condition, cd_count, cd_mutex, cd_received, io_comm_mosaic::mosaicMessage::End(), io_comm_mosaic::mosaicMessage::Found(), io_comm_mosaic::AbstractCallbackHandler::Handle(), io_comm_mosaic::mosaicMessage::IsConnectionDescriptor(), io_comm_mosaic::mosaicMessage::IsErrorMessage(), io_comm_mosaic::mosaicMessage::IsNMEA(), io_comm_mosaic::mosaicMessage::IsResponse(), io_comm_mosaic::mosaicMessage::IsSBF(), io_comm_mosaic::mosaicMessage::MessageID(), mosaic_tcp_port, io_comm_mosaic::mosaicMessage::Pos(), response_condition, response_mutex, response_received, io_comm_mosaic::mosaicMessage::Search(), and io_comm_mosaic::mosaicMessage::SegmentEnd().
Referenced by io_comm_mosaic::Comm_IO::SetManager().
             {
                 mosaicMessage mMessage(data, size);
                 // Read !all! (there might be many) messages in the buffer
                 while (mMessage.Search() != mMessage.End() && mMessage.Found())
                 {
                     // Print the found message (if NMEA) or just show messageID (if SBF)..
                     if (mMessage.IsSBF())
                     {
                         unsigned long sbf_block_length;
                         sbf_block_length = (unsigned long) mMessage.BlockLength(); // C-like cast notation (since functional notation did not work, although https://www.cplusplus.com/doc/tutorial/typecasting/ suggests otherwise)
                         ROS_DEBUG("ROSaic reading SBF block %s with %lu bytes...", mMessage.MessageID().c_str(), sbf_block_length); // Recall: The long data type is at least 32 bits.
                         if (sbf_block_length < 15) // If the SBF block is so corrupted that not even its header's Length field could be properly read, don't bother to process the block, but technically not necessary here.
{
                             continue;
                         }
                     }
                     if (mMessage.IsNMEA())
                     {
                         boost::char_separator<char> sep("\r");
                         typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                         std::size_t nmea_size = std::min(mMessage.SegmentEnd(), static_cast<std::size_t>(89));
                         std::string block_in_string(reinterpret_cast<const char*>(mMessage.Pos()), nmea_size);  // Syntax: new_string_name (const char* s, size_t n); size_t is either 2 or 8 bytes, depending on your system
                         tokenizer tokens(block_in_string, sep);
                         ROS_DEBUG("The NMEA message is ready to be parsed. It reads: %s", (*tokens.begin()).c_str());
                     }
                     if (mMessage.IsResponse())
                     {
                         std::size_t response_size = mMessage.SegmentEnd();
                         std::string block_in_string(reinterpret_cast<const char*>(mMessage.Pos()), response_size);
                         ROS_DEBUG("mosaic's response contains %li bytes and reads:\n %s", response_size, block_in_string.c_str());
{
                             boost::mutex::scoped_lock lock(response_mutex);
                             response_received = true;
                             lock.unlock();
                             response_condition.notify_one();
                         }
                         if (mMessage.IsErrorMessage())
{
                             ROS_ERROR("Invalid command just sent to mosaic!");
                         }
                     }
                     if (mMessage.IsConnectionDescriptor())
                     {
                         std::string cd(reinterpret_cast<const char*>(mMessage.Pos()), 4);
                         mosaic_tcp_port = cd;
                         ROS_INFO_COND(cd_count == 0, "The connection descriptor for the TCP connection is %s", cd.c_str());
                         if (cd_count < 3) ++cd_count;
                         if (cd_count == 2)
{
                             boost::mutex::scoped_lock lock(cd_mutex);
                             cd_received = true;
                             lock.unlock();
                             cd_condition.notify_one();
                         }
                     }
                     //ROS_DEBUG("Handing over from readcallback to Handle while count is %d", mMessage.GetCount());
                     try
                     {
                         Handle(mMessage);
                     }
                     catch (std::runtime_error& e)
                     {
                         ROS_DEBUG("Without a (circular) buffer and a new thread, we would have faced an incomplete message right now. %s", e.what());
                         throw (static_cast<std::size_t>(mMessage.Pos() - data));
                     }
                 }
             }
Field Documentation
callback_mutex_
boost::mutex io_comm_mosaic::CallbackHandlers::callback_mutex_ static private
The "static" keyword resolves construct-by-copying issues related to this mutex by making it available throughout the code. The mutex constructor list contains "mutex (const mutex&) = delete", hence construct-by-copying a mutex is explicitly prohibited.
The get_handlers() method of the Comm_IO class forces us to make this mutex static, since otherwise, the method would need to construct-by-copy the mutex, which is strictly prohibited.
Definition at line 409 of file callbackhandlers.hpp.
callbackmap_
CallbackMap io_comm_mosaic::CallbackHandlers::callbackmap_
Callback handlers multimap for mosaic messages; it needs to be public since we copy-assign (did not work otherwise) new callbackmap_, after inserting a pair to the multimap within the DefineMessages() method of the ROSaicNode class, onto its old version.
Definition at line 403 of file callbackhandlers.hpp.
Referenced by rosaic_node::ROSaicNode::DefineMessages().
The documentation for this class was generated from the following files:
include/rosaic/communication/callbackhandlers.hpp
src/rosaic/nodelets/rosaic_node.cpp