MinROS: CallbackHandlers Class Reference
CallbackHandlers Class Reference
#include <minros.hpp>
Public Types
typedef boost::function< void(const T &)> Callback
Public Member Functions
template<typename T >
Callbacks::iterator insert (typename CallbackHandler_< T >::Callback callback, std::string message_ID)
void handle (mosaicMessage &mMessage)
template<typename T >
bool poll (T &message, std::string message_ID, const boost::posix_time::time_duration &timeout)
void readCallback (uint8_t *data, std::size_t &size)
Private Types
typedef std::multimap< std::string, boost::shared_ptr< CallbackHandler > > Callbacks
Private Attributes
Callbacks callbacks_
boost::mutex callback_mutex_
Detailed Description
Definition at line 196 of file minros.hpp.
Member Typedef Documentation
Callback
typedef boost::function<void(const T&)> CallbackHandlers::Callback
Definition at line 198 of file minros.hpp.
Callbacks
typedef std::multimap<std::string, boost::shared_ptr<CallbackHandler> > CallbackHandlers::Callbacks private
Definition at line 283 of file minros.hpp.
Member Function Documentation
handle()
void CallbackHandlers::handle (mosaicMessage & mMessage) inline
Definition at line 212 of file minros.hpp.
References mosaicMessage::MessageID().
         {
             // !!Find!! the callback handler for the message & decode it
             boost::mutex::scoped_lock lock(callback_mutex_);
             Callbacks::key_type key = mMessage.MessageID();
             for (Callbacks::iterator callback = callbacks_.lower_bound(key);
                 callback != callbacks_.upper_bound(key); ++callback)
                 callback->second->handle(mMessage);
         }
insert()
template<typename T > Callbacks::iterator CallbackHandlers::insert (typename CallbackHandler_< T >::Callback callback, std::string message_ID) inline
Definition at line 201 of file minros.hpp.
         {
             boost::mutex::scoped_lock lock(callback_mutex_);
             CallbackHandler_<T>* handler = new CallbackHandler_<T>(callback); // adding typename is cleaner
             Callbacks::iterator callback = callbacks_.insert(
             std::make_pair(message_ID,
                       boost::shared_ptr<CallbackHandler>(handler)));
             return callback;
         }
poll()
template<typename T > bool CallbackHandlers::poll (T & message, std::string message_ID, const boost::posix_time::time_duration & timeout) inline
Definition at line 225 of file minros.hpp.
References CallbackHandler_< T >::get(), and CallbackHandler::wait().
{
             bool result = false;
             // Create a callback handler for this message
             callback_mutex_.lock();
             CallbackHandler_<T>* handler = new CallbackHandler_<T>(); // this calls the constructor with empty function
             Callbacks::iterator callback = callbacks_.insert(std::make_pair(message_ID, boost::shared_ptr<CallbackHandler>(handler)));
             callback_mutex_.unlock();
             // Wait for the message
             if (handler->wait(timeout)) {
                 message = handler->get();
                 result = true;
             }
             // Remove the callback handler
             callback_mutex_.lock();
             callbacks_.erase(callback);
             callback_mutex_.unlock();
             return result;
         }
readCallback()
void CallbackHandlers::readCallback (uint8_t * data, std::size_t & size) inline
Definition at line 246 of file minros.hpp.
References mosaicMessage::block_length(), debug, mosaicMessage::end(), mosaicMessage::found(), CallbackHandler::handle(), mosaicMessage::MessageID(), mosaicMessage::pos(), mosaicMessage::search(), and SEP_SYNC_BYTE_2.
Referenced by io_comm_mosaic::Comm_IO::setManager().
         {
             mosaicMessage mMessage(data, size);
             // Read !all! (there might be many) the messages in buffer
             while (mMessage.search() != mMessage.end() && mMessage.found()) {
                 if (debug >= 3) {
                     // Print the received bytes, on level debug, or just show messageID..
                     if (mMessage.pos()[1] == SEP_SYNC_BYTE_2)
                     {
                         ROS_DEBUG("Driver reading SBF block %s with %lu bytes...", mMessage.MessageID(), unsigned long (mMessage.block_length())); //recall: long is at least 32 bits
                     }
                     else
                     {
                         std::ostringstream oss;
                         boost::char_separator<char> sep(",");
                         typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                         std::size_t end_point = std::min(static_cast<std::size_t>(mMessage.end() - mMessage.pos()), static_cast<std::size_t>(82));
                         std::string block_in_string(reinterpret_cast<char*>(mMessage.pos()), end_point);    // Syntax: string (const char* s, size_t n); size_t is either 2 or 8 bytes, depending on your system
                                                                                                             // NMEA 0183 messages are at most 82 characters long, , including the $ or ! starting character and the ending <LF>
                         tokenizer tokens(block_in_string, sep);
                         for (tokenizer::iterator it = tokens.begin();
                             *it != 0x0A; ++it)
                                 oss << boost::format("%s") % *it << " ";
                             ROS_DEBUG("Driver reading NMEA message:\n%s", oss.str());
                     }
                 }
                 handle(mMessage);
             }
             // delete read bytes from input buffer
             std::copy(mMessage.pos(), mMessage.end(), data); //Recall: The first and second parameter specify the range of elements to copy, while the third parameter specifies the beginning of the destination range.
             size -= mMessage.pos() - data; // data was never modified
         }
Field Documentation
callback_mutex_
boost::mutex CallbackHandlers::callback_mutex_ private
Definition at line 288 of file minros.hpp.
callbacks_
Callbacks CallbackHandlers::callbacks_ private
Definition at line 287 of file minros.hpp.
The documentation for this class was generated from the following file:
include/MinROS/minros.hpp