ROSaic: rosaic_node::ROSaicNode Class Reference
rosaic_node::ROSaicNode Class Reference
This class represents the ROsaic node, to be extended..
#include <rosaic_node.hpp>
Public Member Functions
ROSaicNode ()
void GetROSParams ()
Gets the node parameters from the ROS Parameter Server, parts of which are specified in a YAML file, other parts of which are specified via the command line.
void DefineMessages ()
Defines which mosaic messages to read and which ROS messages to publish.
void ConfigureMosaic ()
Configures mosaic: Which SBF/NMEA messages it should output and later correction settings.
void InitializeIO ()
Initializes the I/O handling.
void Reconnect (const ros::TimerEvent &event)
Attempts to (re)connect every reconnect_delay_s_ seconds.
Private Attributes
std::string device_
Device port.
uint32_t baudrate_
Baudrate.
std::string datum_
Datum to be used.
std::string ant_type_
Antenna type, from the list returned by the command "lstAntennaInfo, Overview".
std::string ant_serial_nr_
Serial number of your particular antenna.
unsigned polling_period_pvt_
Polling period for PVT-related SBF blocks.
unsigned polling_period_rest_
Polling period for all other SBF blocks and NMEA messages.
float reconnect_delay_s_
Delay in seconds between reconnection attempts to the connection type specified in the parameter connection_type.
float delta_e_
Marker-to-ARP offset in the eastward direction.
float delta_n_
Marker-to-ARP offset in the northward direction.
float delta_u_
Marker-to-ARP offset in the upward direction.
ros::Timer reconnect_timer_
Our ROS timer governing the reconnection.
bool connected_ = false
Whether or not connection has been successful so far.
Detailed Description
This class represents the ROsaic node, to be extended..
Definition at line 229 of file rosaic_node.hpp.
Constructor & Destructor Documentation
ROSaicNode()
rosaic_node::ROSaicNode::ROSaicNode ()
The constructor initializes and runs the Rosaic node, if all works out fine. It loads the user-defined ROS parameters, subscribes to mosaic messages, and publishes requested ROS messages...
Definition at line 39 of file rosaic_node.cpp.
References ConfigureMosaic(), DefineMessages(), GetROSParams(), InitializeIO(), and StringValues_Initialize().
 {
     ROS_DEBUG("Entered ROSaicNode() constructor..");
     // Parameters must be set before initializing IO
     GetROSParams();
     StringValues_Initialize();
     ROS_DEBUG("About to call InitializeIO() method");
     try
     {
         InitializeIO();
     }
     catch (std::runtime_error& e)
     {
         ROS_ERROR("InitializeIO() failed: %s", e.what());
     }
     // Subscribes to all requested mosaic messages and publish them raw or in composite form (e.g. NavSatFix)
     DefineMessages();
     // Communicates to mosaic which SBF/NMEA messages it should output and sets all its necessary corrections-related parameters
     ConfigureMosaic();
     ros::spin();
 }
Member Function Documentation
ConfigureMosaic()
void rosaic_node::ROSaicNode::ConfigureMosaic ()
Configures mosaic: Which SBF/NMEA messages it should output and later correction settings.
The Send() method of AsyncManager class is paramount for this purpose. Note that std::to_string() is from C++11 onwards only.
Definition at line 65 of file rosaic_node.cpp.
References ant_serial_nr_, ant_type_, datum_, delta_e_, delta_n_, delta_u_, device_, rosaic_node::IO, polling_period_pvt_, polling_period_rest_, publish_attcoveuler, publish_atteuler, publish_gpgga, publish_gpsfix, publish_poscovgeodetic, publish_pvtcartesian, publish_pvtgeodetic, response_condition, response_mutex, response_received, io_comm_mosaic::Comm_IO::Send(), and string_utilities::TrimString().
Referenced by ROSaicNode().
 {
     // It is imperative to hold a lock on the mutex "response_mutex" while modifying the variable "response_received".
     boost::mutex::scoped_lock lock(response_mutex);
     // Turning off all current SBF/NMEA output
     IO.Send("sso, all, none, none, off \x0D");
     response_condition.wait(lock, [](){return response_received;});
     response_received = false;
     IO.Send("sno, all, none, none, off \x0D");
     response_condition.wait(lock, [](){return response_received;});
     response_received = false;
     // Setting datum to be used by mosaic (not mosaic's NMEA output though, which only provides MSL and undulation (by default with respect to WGS84), but not ellipsoidal height)
     {
         std::stringstream ss;
         ss << "sgd, " << datum_ << "\x0D";
         IO.Send(ss.str());
     }
     response_condition.wait(lock, [](){return response_received;});
     response_received = false;
     // Setting the marker-to-ARP offsets
     {
         std::stringstream ss;
         ss << "sao, Main, " << string_utilities::TrimString(std::to_string(delta_e_)) << ", " << string_utilities::TrimString(std::to_string(delta_n_)) << ", " << string_utilities::TrimString(std::to_string(delta_u_)) << ", \"" << ant_type_ << "\", \"" << ant_serial_nr_ << "\", 0 \x0D";
         IO.Send(ss.str());
     }
     response_condition.wait(lock, [](){return response_received;});
     response_received = false;
     // Setting SBF/NMEA output of mosaic
     unsigned stream = 1;
     boost::smatch match;
     boost::regex_match(device_, match, boost::regex("(tcp|udp)://(.+):(\\d+)"));
     std::string proto(match[1]);
     std::string mosaic_port;
     if (proto == "tcp")
     {
         mosaic_port = "IP10";
     }
     else
     {
         mosaic_port = "USB1";
     }
     if (publish_gpgga == true)
     {
         std::stringstream ss;
         ss << "sno, Stream" << std::to_string(stream) << ", " << mosaic_port << ", GGA, sec" << std::to_string(polling_period_rest_) << "\x0D";
         IO.Send(ss.str());
         ++stream;
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
     }
     if (publish_pvtcartesian == true)
     {
         std::stringstream ss;
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", PVTCartesian, sec" << std::to_string(polling_period_pvt_) << "\x0D";
         IO.Send(ss.str());
         ++stream;
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
     }
     if (publish_pvtgeodetic == true)
     {
         std::stringstream ss;
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", PVTGeodetic, sec" << std::to_string(polling_period_pvt_) << "\x0D";
         IO.Send(ss.str());
         ++stream;
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
     }
     if (publish_poscovgeodetic == true)
     {
         std::stringstream ss;
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", PosCovGeodetic, sec" << std::to_string(polling_period_pvt_) << "\x0D";
         IO.Send(ss.str());
         ++stream;
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
     }
     if (publish_atteuler == true)
     {
         std::stringstream ss;
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", AttEuler, sec" << std::to_string(polling_period_rest_) << "\x0D";
         IO.Send(ss.str());
         ++stream;
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
     }
     if (publish_attcoveuler == true)
     {
         std::stringstream ss;
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", AttCovEuler, sec" << std::to_string(polling_period_rest_) << "\x0D";
         IO.Send(ss.str());
         ++stream;
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
     }
     if (publish_gpsfix == true)
     {
         std::stringstream ss;
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", ChannelStatus, sec" << std::to_string(polling_period_rest_) << "\x0D";
         IO.Send(ss.str());
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
         ++stream;
         ss.str(std::string()); // avoids invoking the std::string constructor
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", MeasEpoch, sec" << std::to_string(polling_period_rest_) << "\x0D";
         IO.Send(ss.str());
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
         ++stream;
         ss.str(std::string());
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", DOP, sec" << std::to_string(polling_period_rest_) << "\x0D";
         IO.Send(ss.str());
         response_condition.wait(lock, [](){return response_received;});
         response_received = false;
         ++stream;
         ss.str(std::string());
         ss << "sso, Stream" << std::to_string(stream) << ", " << mosaic_port << ", VelCovGeodetic, sec" << std::to_string(polling_period_rest_) << "\x0D";
         IO.Send(ss.str());
         ++stream;
     }
 }
DefineMessages()
void rosaic_node::ROSaicNode::DefineMessages ()
Defines which mosaic messages to read and which ROS messages to publish.
InitializeSerial is not self-contained: The for loop in Callbackhandlers' handle method would never open a specific handler unless the handler is added (=inserted) to the C++ map via this function. This way, the specific handler can be called, in which in turn mosaicMessage's read() method is called, thereby "message" occupied, and func_ (the handler we insert in this function) called with this "message".
Definition at line 285 of file rosaic_node.cpp.
References io_comm_mosaic::CallbackHandlers::callbackmap_, io_comm_mosaic::Comm_IO::GetHandlers(), io_comm_mosaic::Comm_IO::handlers_, io_comm_mosaic::CallbackHandlers::Insert(), rosaic_node::IO, publish_attcoveuler, publish_atteuler, publish_gpgga, publish_gpsfix, publish_navsatfix, publish_poscovgeodetic, publish_pvtcartesian, and publish_pvtgeodetic.
Referenced by ROSaicNode().
 {
     ROS_DEBUG("Entered DefineMessages() method");
     if (publish_gpgga == true)
     {
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<rosaic::Gpgga>("$GPGGA", boost::bind(Publish<rosaic::Gpgga>, _1, "/gpgga"));
         //std::multimap<std::string, boost::shared_ptr<io_comm_mosaic::AbstractCallbackHandler> >::key_type key = "$GPGGA";
         //ROS_DEBUG("Back to DefineMessages() method: The element exists in our map: %u", (unsigned int) IO.handlers_.callbackmap_.count(key));
     }
     if (publish_pvtcartesian == true)
     {
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<rosaic::PVTCartesian>("4006", boost::bind(Publish<rosaic::PVTCartesian>, _1, "/pvtcartesian"));
     }
     if (publish_pvtgeodetic == true)
     {
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<rosaic::PVTGeodetic>("4007", boost::bind(Publish<rosaic::PVTGeodetic>, _1, "/pvtgeodetic"));
     }
     if (publish_poscovgeodetic == true)
     {
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<rosaic::PosCovGeodetic>("5906", boost::bind(Publish<rosaic::PosCovGeodetic>, _1, "/poscovgeodetic"));
     }
     if (publish_atteuler == true)
     {
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<rosaic::AttEuler>("5938", boost::bind(Publish<rosaic::AttEuler>, _1, "/atteuler"));
     }
     if (publish_attcoveuler == true)
     {
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<rosaic::AttCovEuler>("5939", boost::bind(Publish<rosaic::AttCovEuler>, _1, "/attcoveuler"));
     }
     if (publish_navsatfix == true)
     {
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<sensor_msgs::NavSatFix>("NavSatFix", boost::bind(Publish<sensor_msgs::NavSatFix>, _1, "/navsatfix"));
     }
     if (publish_gpsfix == true)
     {
         typedef boost::function<void(int32_t)> Empty;
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<gps_common::GPSFix>("GPSFix", boost::bind(Publish<gps_common::GPSFix>, _1, "/gpsfix"));
         // The following blocks are never published, yet are needed for the construction of the GPSFix message, hence we have empty callbacks.
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<int32_t>("4013", Empty()); // ChannelStatus block
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<int32_t>("4027", Empty()); // MeasEpoch block
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<int32_t>("4001", Empty()); // DOP block
         IO.handlers_.callbackmap_ = IO.GetHandlers().Insert<int32_t>("5908", Empty()); // VelCovGeodetic block
     }
     ROS_DEBUG("Leaving DefineMessages() method");
     // and so on
 }
GetROSParams()
void rosaic_node::ROSaicNode::GetROSParams ()
Gets the node parameters from the ROS Parameter Server, parts of which are specified in a YAML file, other parts of which are specified via the command line.
Definition at line 190 of file rosaic_node.cpp.
References ant_serial_nr_, ant_type_, baudrate_, datum_, delta_e_, delta_n_, delta_u_, device_, rosaic_node::GetROSInt(), rosaic_node::nh, polling_period_pvt_, and polling_period_rest_.
Referenced by ROSaicNode().
 {
     // Communication parameters
     nh->param("device", device_, std::string("/dev/ttyACM0"));
     GetROSInt("serial/baudrate", baudrate_, static_cast<uint32_t>(115200));
     // Polling period parameters
     GetROSInt("polling_period/pvt", polling_period_pvt_, static_cast<unsigned>(1));
     GetROSInt("polling_period/rest", polling_period_rest_, static_cast<unsigned>(1));
     // Datum and marker-to-ARP offset
     nh->param("datum", datum_, std::string("ETRS89"));
     nh->param("ant_type", ant_type_, std::string("Unknown"));
     nh->param("ant_serial_nr", ant_serial_nr_, std::string("Unknown"));
     nh->param("marker_to_arp/delta_e", delta_e_, 0.0f);
     nh->param("marker_to_arp/delta_n", delta_n_, 0.0f);
     nh->param("marker_to_arp/delta_u", delta_u_, 0.0f);
     // To be implemented: RTCM, setting datum, raw data settings, PPP, SBAS, fix mode...
     ROS_DEBUG("Finished GetROSParams() method");
 }
InitializeIO()
void rosaic_node::ROSaicNode::InitializeIO ()
Initializes the I/O handling.
Definition at line 214 of file rosaic_node.cpp.
References baudrate_, device_, io_comm_mosaic::Comm_IO::InitializeSerial(), io_comm_mosaic::Comm_IO::InitializeTCP(), and rosaic_node::IO.
Referenced by ROSaicNode().
 {
     ROS_DEBUG("Called InitializeIO() method");
     boost::smatch match;
     // In fact: smatch is a typedef of match_results<string::const_iterator>
     if (boost::regex_match(device_, match, boost::regex("(tcp|udp)://(.+):(\\d+)")))
     // \d means decimal, however, in the regular expression, the \ is a special character, which needs to be escaped on its own as well..
     // Note that regex_match can be used with a smatch object to store results, or without. In any case, true is returned if and only if it matches the !complete! string.
     {
         // The first sub_match (index 0) contained in a match_result always represents the full match within a target sequence made by a regex,
         // and subsequent sub_matches represent sub-expression matches corresponding in sequence to the left parenthesis delimiting the sub-expression in the regex,
         // i.e. $n Perl is equivalent to m[n] in boost regex.
         std::string proto(match[1]);
         if (proto == "tcp")
         {
             std::string host(match[2]);
             std::string port(match[3]);
             ROS_INFO("Connecting to %s://%s:%s ...", proto.c_str(), host.c_str(), port.c_str());
             try
             {
                 IO.InitializeTCP(host, port);
             }
             catch (std::runtime_error& e)
             {
                 throw std::runtime_error("IO.InitializeTCP() failed for host " + host + " on port " + port + " due to: " + e.what());
             }
         }
         else
         {
             throw std::runtime_error("Protocol '" + proto + "' is unsupported");
         }
     }
     else
     {
         // To be modified here, or clarified: how to use reconnect_delay_s properly? Is respawn (roslaunch parameter) enough?
         //ROS_DEBUG("Setting timer for calling InitializeSerial() method");
         //nh->param("reconnect_delay_s", reconnect_delay_s_, 0.5f);
         //reconnect_timer_ = nh->createTimer(ros::Duration(reconnect_delay_s_), &ROSaicNode::Reconnect, this);
         //reconnect_timer_.start();
         //ROS_DEBUG("Started timer"); //not printed if error in callback of course
         //ros::spin(); // otherwise callback will never be called, with ros::spin i cannot leave InitializeIO(), yet with ros::spinOnce can enter reconnect() even once
         try
         {
             IO.InitializeSerial(device_, baudrate_);
         }
         catch (std::runtime_error& e)
         {
             throw std::runtime_error("IO.InitializeSerial() failed for device " + device_ + " due to: " + e.what());
         }
     }
     ROS_DEBUG("Leaving InitializeIO()");
 }
Reconnect()
void rosaic_node::ROSaicNode::Reconnect (const ros::TimerEvent & event)
Attempts to (re)connect every reconnect_delay_s_ seconds.
Definition at line 267 of file rosaic_node.cpp.
References baudrate_, connected_, device_, io_comm_mosaic::Comm_IO::InitializeSerial(), rosaic_node::IO, and reconnect_timer_.
 {
     ROS_DEBUG("Inside reconnect");
     if(IO.InitializeSerial(device_, baudrate_))
     {
         connected_ = true;
     }
     if (connected_ == true)
     {
         reconnect_timer_.stop();
         ROS_DEBUG("Ended timer");
     }
     ROS_DEBUG("Leaving reconnect");
 }
Field Documentation
ant_serial_nr_
std::string rosaic_node::ROSaicNode::ant_serial_nr_ private
Serial number of your particular antenna.
Definition at line 273 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), and GetROSParams().
ant_type_
std::string rosaic_node::ROSaicNode::ant_type_ private
Antenna type, from the list returned by the command "lstAntennaInfo, Overview".
Definition at line 271 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), and GetROSParams().
baudrate_
uint32_t rosaic_node::ROSaicNode::baudrate_ private
Baudrate.
Definition at line 267 of file rosaic_node.hpp.
Referenced by GetROSParams(), InitializeIO(), and Reconnect().
connected_
bool rosaic_node::ROSaicNode::connected_ = false private
Whether or not connection has been successful so far.
Definition at line 289 of file rosaic_node.hpp.
Referenced by Reconnect().
datum_
std::string rosaic_node::ROSaicNode::datum_ private
Datum to be used.
Definition at line 269 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), and GetROSParams().
delta_e_
float rosaic_node::ROSaicNode::delta_e_ private
Marker-to-ARP offset in the eastward direction.
Definition at line 281 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), and GetROSParams().
delta_n_
float rosaic_node::ROSaicNode::delta_n_ private
Marker-to-ARP offset in the northward direction.
Definition at line 283 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), and GetROSParams().
delta_u_
float rosaic_node::ROSaicNode::delta_u_ private
Marker-to-ARP offset in the upward direction.
Definition at line 285 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), and GetROSParams().
device_
std::string rosaic_node::ROSaicNode::device_ private
Device port.
Definition at line 265 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), GetROSParams(), InitializeIO(), and Reconnect().
polling_period_pvt_
unsigned rosaic_node::ROSaicNode::polling_period_pvt_ private
Polling period for PVT-related SBF blocks.
Definition at line 275 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), and GetROSParams().
polling_period_rest_
unsigned rosaic_node::ROSaicNode::polling_period_rest_ private
Polling period for all other SBF blocks and NMEA messages.
Definition at line 277 of file rosaic_node.hpp.
Referenced by ConfigureMosaic(), and GetROSParams().
reconnect_delay_s_
float rosaic_node::ROSaicNode::reconnect_delay_s_ private
Delay in seconds between reconnection attempts to the connection type specified in the parameter connection_type.
Definition at line 279 of file rosaic_node.hpp.
reconnect_timer_
ros::Timer rosaic_node::ROSaicNode::reconnect_timer_ private
Our ROS timer governing the reconnection.
Definition at line 287 of file rosaic_node.hpp.
Referenced by Reconnect().
The documentation for this class was generated from the following files:
include/rosaic/nodelets/rosaic_node.hpp
src/rosaic/nodelets/rosaic_node.cpp