ROSaic: GpgsvParser Class Reference
GpgsvParser Class Reference
Derived class for parsing GSV messages.
#include <gpgsv.hpp>
Public Member Functions
GpgsvParser ()
Constructor of the class GpgsvParser.
const std::string getMessageID () const override
Returns the ASCII message ID, here "$GPGSV".
septentrio_gnss_driver::GpgsvPtr parseASCII (const NMEASentence &sentence) noexcept(false) override
Parses one GSV message.
Public Member Functions inherited from BaseParser< septentrio_gnss_driver::GpgsvPtr >
BaseParser ()=default
Default constructor of the class BaseParser.
virtual ~BaseParser ()=default
Default destructor of the class BaseParser.
septentrio_gnss_driver::GpgsvPtr parseBinary (const SBFStructT &bin_msg) noexcept(false)
Converts bin_msg into a ROS message pointer (e.g. nmea_msgs::GpggaPtr) and returns it.
Static Public Attributes
static const std::string MESSAGE_ID = "$GPGSV"
Declares the string MESSAGE_ID.
Detailed Description
Derived class for parsing GSV messages.
Date
29/09/20
Definition at line 82 of file gpgsv.hpp.
Constructor & Destructor Documentation
GpgsvParser()
GpgsvParser::GpgsvParser () inline
Constructor of the class GpgsvParser.
Definition at line 89 of file gpgsv.hpp.
References getMessageID(), and parseASCII().
 : BaseParser<septentrio_gnss_driver::GpgsvPtr>() {}
Member Function Documentation
getMessageID()
const std::string GpgsvParser::getMessageID () const override virtual
Returns the ASCII message ID, here "$GPGSV".
Returns
The message ID
Implements BaseParser< septentrio_gnss_driver::GpgsvPtr >.
Definition at line 41 of file gpgsv.cpp.
References MESSAGE_ID.
Referenced by GpgsvParser().
 {
     return GpgsvParser::MESSAGE_ID;
 }
parseASCII()
septentrio_gnss_driver::GpgsvPtr GpgsvParser::parseASCII (const NMEASentence & sentence) override virtual noexcept
Parses one GSV message.
Parameters
[in] sentence The GSV message to be parsed
Returns
A ROS message pointer of ROS type nmea_msgs::GpgsvPtr
Caution: Due to the occurrence of the throw keyword, this method parseASCII should be called within a try / catch framework... Note: This method is called from within the read() method of the RxMessage class by including the checksum part in the argument "sentence" here, though the checksum is never parsed: E.g. for message with 4 Svs it would be sentence.get_body()[20] if anybody ever needs it.
Reimplemented from BaseParser< septentrio_gnss_driver::GpgsvPtr >.
Definition at line 52 of file gpgsv.cpp.
References g_frame_id, parsing_utilities::parseFloat(), and parsing_utilities::parseUInt8().
Referenced by GpgsvParser(), and io_comm_rx::RxMessage::read().
 {
     const size_t MIN_LENGTH = 4;
     // Checking that the message is at least as long as a GPGSV with no satellites
     if (sentence.get_body().size() < MIN_LENGTH)
     {
         std::stringstream error;
         error << "Expected GSV length is at least " << MIN_LENGTH
           << ". The actual length is " << sentence.get_body().size();
         throw ParseException(error.str());
     }
     septentrio_gnss_driver::GpgsvPtr msg = boost::make_shared<septentrio_gnss_driver::Gpgsv>();
     msg->header.frame_id = g_frame_id;
     msg->message_id = sentence.get_body()[0];
     if (!parsing_utilities::parseUInt8(sentence.get_body()[1], msg->n_msgs))
     {
         throw ParseException("Error parsing n_msgs in GSV.");
     }
     if (msg->n_msgs > 9)  // Checking that the number of messages is smaller or equal to 9
     {
         std::stringstream error;
         error << "n_msgs in GSV is too large: " << msg->n_msgs << ".";
         throw ParseException(error.str());
     }
     if (!parsing_utilities::parseUInt8(sentence.get_body()[2], msg->msg_number))
     {
         throw ParseException("Error parsing msg_number in GSV.");
     }
     if (msg->msg_number > msg->n_msgs)  // Checking that this message is within the sequence range
     {
         std::stringstream error;
         error << "msg_number in GSV is larger than n_msgs: " << msg->msg_number << " > " << msg->n_msgs << ".";
         throw ParseException(error.str());
     }
     if (!parsing_utilities::parseUInt8(sentence.get_body()[3], msg->n_satellites))
     {
         throw ParseException("Error parsing n_satellites in GSV.");
     }
     // Figuring out how many satellites should be described in this sentence
     size_t n_sats_in_sentence = 4;
     if (msg->msg_number == msg->n_msgs)
     {
         n_sats_in_sentence = msg->n_satellites % static_cast<uint8_t>(4);
         if (msg->n_satellites % static_cast<uint8_t>(4) == 0)
         {
             n_sats_in_sentence = 4;
         }
         if (msg->n_satellites == 0)
         {
             n_sats_in_sentence = 0;
         }
         if (msg->msg_number == 1)
         {
             n_sats_in_sentence = msg->n_satellites;
         }
     }
     // Checking that the sentence is the right length for the number of satellites
     size_t expected_length = MIN_LENGTH + 4 * n_sats_in_sentence + 1;
     // Note that we add +1 due to the checksum data being part of the argument "sentence".
     if (n_sats_in_sentence == 0)
     {
         // Even if the number of sats is 0, the message will still have enough
         // blank fields for 1 satellite.
         expected_length += 4;
     }
     //ROS_DEBUG("number of sats is %u but nsats in sentence if msg_number = max is %u and msg->msg_number == msg->n_msgs is %s and nsats in sentence is %li", msg->n_satellites, msg->n_satellites % static_cast<uint8_t>(4), msg->msg_number == msg->n_msgs ? "true" : "false", n_sats_in_sentence);
     if (sentence.get_body().size() != expected_length && sentence.get_body().size() != expected_length - 1)
     {
         std::stringstream ss;
         for (size_t i = 0; i < sentence.get_body().size(); ++i)
         {
             ss << sentence.get_body()[i];
             if ((i+1) < sentence.get_body().size())
             {
                 ss << ",";
             }
         }
         std::stringstream error;
         error << "Expected GSV length is " << expected_length << " for message with "
             << n_sats_in_sentence << " satellites. The actual length is "
             << sentence.get_body().size() << ".\n" << ss.str().c_str();
         throw ParseException(error.str());
     }
     // Parsing information about n_sats_in_sentence SVs..
     msg->satellites.resize(n_sats_in_sentence);
     for (size_t sat = 0, index=MIN_LENGTH; sat < n_sats_in_sentence; ++sat, index += 4)
     {
         if (!parsing_utilities::parseUInt8(sentence.get_body()[index], msg->satellites[sat].prn))
         {
             std::stringstream error;
             error << "Error parsing PRN for satellite " << sat << " in GSV.";
             throw ParseException(error.str());
         }
         float elevation;
         if (!parsing_utilities::parseFloat(sentence.get_body()[index + 1], elevation))
         {
             std::stringstream error;
             error << "Error parsing elevation for satellite " << sat << " in GSV.";
             throw ParseException(error.str());
         }
         msg->satellites[sat].elevation = static_cast<uint8_t>(elevation);
         float azimuth;
         if (!parsing_utilities::parseFloat(sentence.get_body()[index + 2], azimuth))
         {
             std::stringstream error;
             error << "Error parsing azimuth for satellite " << sat << " in GSV.";
             throw ParseException(error.str());
         }
         msg->satellites[sat].azimuth = static_cast<uint16_t>(azimuth);
         if ((index + 3) >= sentence.get_body().size() || sentence.get_body()[index + 3].empty())
         {
             msg->satellites[sat].snr = -1;
         }
         else
         {
             uint8_t snr;
             if (!parsing_utilities::parseUInt8(sentence.get_body()[index + 3], snr))
             {
                 std::stringstream error;
                 error << "Error parsing snr for satellite " << sat << " in GSV.";
                 throw ParseException(error.str());
             }
             msg->satellites[sat].snr = static_cast<int8_t>(snr);
         }
     }
     return msg;
 }
Field Documentation
MESSAGE_ID
const std::string GpgsvParser::MESSAGE_ID = "$GPGSV" static
Declares the string MESSAGE_ID.
Definition at line 107 of file gpgsv.hpp.
Referenced by getMessageID().
The documentation for this class was generated from the following files:
include/septentrio_gnss_driver/parsers/nmea_parsers/gpgsv.hpp
src/septentrio_gnss_driver/parsers/nmea_parsers/gpgsv.cpp