MinROS: Manager Class Reference
Manager Class Reference abstract
Interface (in C++ terms), that could be used for any I/O manager, synchronous and asynchronous alike.
#include <async_manager.hpp>
Public Types
typedef boost::function< void(uint8_t *, std::size_t &)> Callback
Public Member Functions
virtual ~Manager ()
virtual void setCallback (const Callback &callback)=0
virtual void wait (const boost::posix_time::time_duration &timeout)=0
virtual bool isOpen () const =0
Detailed Description
Interface (in C++ terms), that could be used for any I/O manager, synchronous and asynchronous alike.
Definition at line 52 of file async_manager.hpp.
Member Typedef Documentation
Callback
typedef boost::function<void(uint8_t*, std::size_t&)> Manager::Callback
Definition at line 54 of file async_manager.hpp.
Constructor & Destructor Documentation
~Manager()
virtual Manager::~Manager () inline virtual
Definition at line 55 of file async_manager.hpp.
References isOpen(), setCallback(), and wait().
 {}
Member Function Documentation
isOpen()
virtual bool Manager::isOpen () const pure virtual
Implemented in AsyncManager< StreamT >.
Referenced by ~Manager().
setCallback()
virtual void Manager::setCallback (const Callback & callback) pure virtual
Implemented in AsyncManager< StreamT >.
Referenced by ~Manager().
wait()
virtual void Manager::wait (const boost::posix_time::time_duration & timeout) pure virtual
Implemented in AsyncManager< StreamT >.
Referenced by AsyncManager< StreamT >::setCallback(), and ~Manager().
The documentation for this class was generated from the following file:
include/MinROS/communication/async_manager.hpp