ROSaic: CircularBuffer Class Reference
CircularBuffer Class Reference
Class for creating, writing to and reading from a circular buffer.
#include <circular_buffer.hpp>
Public Member Functions
CircularBuffer (std::size_t capacity)
Constructor of CircularBuffer.
~CircularBuffer ()
Destructor of CircularBuffer.
std::size_t size () const
Returns size_.
std::size_t capacity () const
Returns capacity_.
std::size_t write (const uint8_t *data, std::size_t bytes)
Returns number of bytes written.
std::size_t read (uint8_t *data, std::size_t bytes)
Returns number of bytes read.
Private Attributes
std::size_t head_
Specifies where we start writing.
std::size_t tail_
Specifies where we start reading.
std::size_t size_
Number of bytes that have been written but not yet read.
std::size_t capacity_
Capacity of the circular buffer.
uint8_t * data_
Pointer that always points to the same memory address, hence could be const pointer.
Detailed Description
Class for creating, writing to and reading from a circular buffer.
Definition at line 51 of file circular_buffer.hpp.
Constructor & Destructor Documentation
CircularBuffer()
CircularBuffer::CircularBuffer (std::size_t capacity) explicit
Constructor of CircularBuffer.
Definition at line 39 of file circular_buffer.cpp.
References capacity(), and data_.
                                                 : head_(0), tail_(0), size_(0), capacity_(capacity)
 {
     data_ = new uint8_t[capacity];
 }
~CircularBuffer()
CircularBuffer::~CircularBuffer ()
Destructor of CircularBuffer.
The destructor frees memory (first line) and points the dangling pointer to NULL (second line).
Definition at line 45 of file circular_buffer.cpp.
References data_.
 {
     delete [] data_;
     data_ = NULL;
 }
Member Function Documentation
capacity()
std::size_t CircularBuffer::capacity () const inline
Returns capacity_.
Definition at line 61 of file circular_buffer.hpp.
References capacity_, read(), and write().
Referenced by CircularBuffer(), read(), and write().
 { return capacity_; }
read()
std::size_t CircularBuffer::read (uint8_t * data, std::size_t bytes)
Returns number of bytes read.
Definition at line 86 of file circular_buffer.cpp.
References capacity(), capacity_, data_, size_, and tail_.
Referenced by capacity().
 {
     //ROS_DEBUG("Called CircularBuffer::read() method..");
     if (bytes == 0) return 0;
     std::size_t capacity = capacity_;
     std::size_t bytes_to_read = std::min(bytes, size_);
     //ROS_DEBUG("Number of bytes_to_read is %li.", bytes_to_read);
     if (bytes_to_read != bytes)
     {
         ROS_ERROR("You are trying to read parts of the circular buffer that have not yet been written!");
     }
     // Read in a single step
     if (bytes_to_read <= capacity - tail_)  // Note that it is not size_ - tail_:
                                             // If write() hasn't written something into all of capacity yet (first round of writing), we would still read those unknown bytes..
     {
         memcpy(data, data_ + tail_, bytes_to_read);
         tail_ += bytes_to_read;
         if (tail_ == capacity) tail_ = 0; // Same here?
     }
     // Read in two steps
     else
     {
         std::size_t size_1 = capacity - tail_;
         memcpy(data, data_ + tail_, size_1);
         std::size_t size_2 = bytes_to_read - size_1;
         memcpy(data + size_1, data_, size_2);
         tail_ = size_2;
     }
     size_ -= bytes_to_read;
     //ROS_DEBUG("Leaving CircularBuffer::read() method..");
     return bytes_to_read;
 }
size()
std::size_t CircularBuffer::size () const inline
Returns size_.
Definition at line 59 of file circular_buffer.hpp.
References size_.
 { return size_; }
write()
std::size_t CircularBuffer::write (const uint8_t * data, std::size_t bytes)
Returns number of bytes written.
Definition at line 51 of file circular_buffer.cpp.
References capacity(), capacity_, data_, head_, and size_.
Referenced by io_comm_rx::AsyncManager< StreamT >::asyncReadSomeHandler(), and capacity().
 {
     //ROS_DEBUG("Called CircularBuffer::write() method..");
     if (bytes == 0) return 0;
     std::size_t capacity = capacity_;
     std::size_t bytes_to_write = std::min(bytes, capacity - size_);
     //ROS_DEBUG("Number of bytes_to_write is %li.", bytes_to_write);
     if (bytes_to_write != bytes)
     {
         ROS_ERROR("You are trying to overwrite parts of the circular buffer that have not yet been read!");
     }
     // Writes in a single step
     if (bytes_to_write <= capacity - head_)
     {
         memcpy(data_ + head_, data, bytes_to_write);
         head_ += bytes_to_write;
         if (head_ == capacity) head_ = 0;
     }
     // Writes in two steps. Here the circular nature comes to the surface
     else
     {
         std::size_t size_1 = capacity - head_;
         memcpy(data_ + head_, data, size_1);
         std::size_t size_2 = bytes_to_write - size_1;
         memcpy(data_, data + size_1, size_2);
         head_ = size_2; // Hence setting head_ = 0 three lines above was not necessary.
     }
     size_ += bytes_to_write;
     //ROS_DEBUG("Leaving CircularBuffer::write() method..");
     return bytes_to_write;
 }
Field Documentation
capacity_
std::size_t CircularBuffer::capacity_ private
Capacity of the circular buffer.
Definition at line 75 of file circular_buffer.hpp.
Referenced by capacity(), read(), and write().
data_
uint8_t* CircularBuffer::data_ private
Pointer that always points to the same memory address, hence could be const pointer.
Definition at line 77 of file circular_buffer.hpp.
Referenced by CircularBuffer(), read(), write(), and ~CircularBuffer().
head_
std::size_t CircularBuffer::head_ private
Specifies where we start writing.
Definition at line 69 of file circular_buffer.hpp.
Referenced by write().
size_
std::size_t CircularBuffer::size_ private
Number of bytes that have been written but not yet read.
Definition at line 73 of file circular_buffer.hpp.
Referenced by read(), size(), and write().
tail_
std::size_t CircularBuffer::tail_ private
Specifies where we start reading.
Definition at line 71 of file circular_buffer.hpp.
Referenced by read().
The documentation for this class was generated from the following files:
include/septentrio_gnss_driver/communication/circular_buffer.hpp
src/septentrio_gnss_driver/communication/circular_buffer.cpp