ROSaic: io_comm_rx::Manager Class Reference
io_comm_rx::Manager Class Reference abstract
Interface (in C++ terms), that could be used for any I/O manager, synchronous and asynchronous alike.
#include <async_manager.hpp>
Public Types
typedef boost::function< void(const uint8_t *, std::size_t &)> Callback
Public Member Functions
virtual ~Manager ()
virtual void setCallback (const Callback &callback)=0
Sets the callback function.
virtual bool send (std::string cmd, std::size_t size)=0
Sends commands to the receiver.
virtual void wait (uint16_t *count)=0
Waits count seconds before throwing ROS_INFO message in case no message from the receiver arrived.
virtual bool isOpen () const =0
Determines whether or not the connection is open.
Detailed Description
Interface (in C++ terms), that could be used for any I/O manager, synchronous and asynchronous alike.
Definition at line 90 of file async_manager.hpp.
Member Typedef Documentation
Callback
typedef boost::function<void(const uint8_t*, std::size_t&)> io_comm_rx::Manager::Callback
Definition at line 92 of file async_manager.hpp.
Constructor & Destructor Documentation
~Manager()
virtual io_comm_rx::Manager::~Manager () inline virtual
Definition at line 93 of file async_manager.hpp.
References isOpen(), send(), setCallback(), and wait().
 {}
Member Function Documentation
isOpen()
virtual bool io_comm_rx::Manager::isOpen () const pure virtual
Determines whether or not the connection is open.
Implemented in io_comm_rx::AsyncManager< StreamT >.
Referenced by ~Manager().
send()
virtual bool io_comm_rx::Manager::send (std::string cmd, std::size_t size) pure virtual
Sends commands to the receiver.
Implemented in io_comm_rx::AsyncManager< StreamT >.
Referenced by io_comm_rx::AsyncManager< StreamT >::setCallback(), and ~Manager().
setCallback()
virtual void io_comm_rx::Manager::setCallback (const Callback & callback) pure virtual
Sets the callback function.
Implemented in io_comm_rx::AsyncManager< StreamT >.
Referenced by ~Manager().
wait()
virtual void io_comm_rx::Manager::wait (uint16_t * count) pure virtual
Waits count seconds before throwing ROS_INFO message in case no message from the receiver arrived.
Implemented in io_comm_rx::AsyncManager< StreamT >.
Referenced by io_comm_rx::AsyncManager< StreamT >::setCallback(), and ~Manager().
The documentation for this class was generated from the following file:
include/septentrio_gnss_driver/communication/async_manager.hpp