ROSaic: rosaic_driver::GpggaParser Class Reference
rosaic_driver::GpggaParser Class Reference
Derived class for parsing GGA messages.
#include <gpgga.hpp>
Public Member Functions
GpggaParser ()
Constructor of the class GpggaParser.
const std::string GetMessageID () const override
Returns the ASCII message ID, here "$GPGGA".
rosaic::GpggaPtr ParseASCII (const NMEASentence &sentence) noexcept(false) override
Parses one GGA message.
bool WasLastGPGGAValid () const
Tells us whether the last GGA message was valid or not.
Public Member Functions inherited from rosaic_driver::BaseParser< rosaic::GpggaPtr >
BaseParser ()=default
Default constructor of the class BaseParser.
virtual ~BaseParser ()=default
Default destructor of the class BaseParser.
rosaic::GpggaPtr ParseBinary (const SBFStructT &bin_msg) noexcept(false)
Converts bin_msg into a ROS message pointer (e.g. nmea_msgs::GpggaPtr) and returns it.
Static Public Attributes
static const std::string MESSAGE_ID = "$GPGGA"
Declares the string MESSAGE_ID.
Private Attributes
bool was_last_gpgga_valid_
Declares a boolean representing whether or not the last GPGGA message was valid.
Detailed Description
Derived class for parsing GGA messages.
Date
13/08/20
Definition at line 86 of file gpgga.hpp.
Constructor & Destructor Documentation
GpggaParser()
rosaic_driver::GpggaParser::GpggaParser () inline
Constructor of the class GpggaParser.
Definition at line 93 of file gpgga.hpp.
References GetMessageID(), ParseASCII(), and WasLastGPGGAValid().
 : BaseParser<rosaic::GpggaPtr>(), was_last_gpgga_valid_(false) {}
Member Function Documentation
GetMessageID()
const std::string rosaic_driver::GpggaParser::GetMessageID () const override virtual
Returns the ASCII message ID, here "$GPGGA".
Returns
The message ID
Implements rosaic_driver::BaseParser< rosaic::GpggaPtr >.
Definition at line 41 of file gpgga.cpp.
References MESSAGE_ID.
Referenced by GpggaParser().
 {
     return rosaic_driver::GpggaParser::MESSAGE_ID;
 }
ParseASCII()
rosaic::GpggaPtr rosaic_driver::GpggaParser::ParseASCII (const NMEASentence & sentence) override virtual noexcept
Parses one GGA message.
Parameters
[in] sentence The GGA message to be parsed
Returns
A ROS message pointer of ROS type rosaic::GpggaPtr
Caution: Due to the occurrence of the throw keyword, this method ParseASCII should be called within a try / catch framework... Note: This method is called from within the read() method of the mosaicMessage class by including the checksum part in the argument "sentence" here, though the checksum is never parsed: It would be sentence.get_body()[15] if anybody ever needs it.
Reimplemented from rosaic_driver::BaseParser< rosaic::GpggaPtr >.
Definition at line 51 of file gpgga.cpp.
References rosaic_driver::ConvertDMSToDegrees(), frame_id, rosaic_driver::ParseDouble(), rosaic_driver::ParseFloat(), rosaic_driver::ParseUInt32(), string_utilities::ToDouble(), rosaic_driver::UTCDoubleToSeconds(), rosaic_driver::UTCtoUnix(), and was_last_gpgga_valid_.
Referenced by GpggaParser(), and io_comm_mosaic::mosaicMessage::Read().
 {
     //ROS_DEBUG("Just testing that first entry is indeed what we expect it to: %s", sentence.get_body()[0].c_str());
     // Check the length first, which should be 16 elements.
     const size_t LEN = 16;
     if (sentence.get_body().size() > LEN || sentence.get_body().size() < LEN)
     {
         std::stringstream error;
         error << "GGA parsing failed: Expected GPGGA length is " << LEN << ", but actual length is " << sentence.get_body().size();
         throw ParseException(error.str());
     }
     rosaic::GpggaPtr msg = boost::make_shared<rosaic::Gpgga>();
     msg->header.frame_id = frame_id;
     msg->message_id = sentence.get_body()[0];
     if (sentence.get_body()[1].empty() || sentence.get_body()[1] == "0")
     {
         msg->utc_seconds = 0;
     }
     else
     {
         double utc_double;
         if (string_utilities::ToDouble(sentence.get_body()[1], utc_double))
         {
             //ROS_DEBUG("utc_double is %f", (float) utc_double);
             msg->utc_seconds = UTCDoubleToSeconds(utc_double);
             // The Header's Unix Epoch time stamp
             time_t unix_time_seconds = UTCtoUnix(utc_double);
             // The following assumes that there are two digits after the decimal point in utc_double, i.e. in the NMEA UTC time.
             uint32_t unix_time_nanoseconds = (static_cast<uint32_t>(utc_double*100)%100)*10000;
             msg->header.stamp.sec = unix_time_seconds;
             msg->header.stamp.nsec = unix_time_nanoseconds;
         }
         else
         {
             throw rosaic_driver::ParseException("Error parsing UTC seconds in GPGGA"); // E.g. if one of the fields of the NMEA UTC string is empty
         }
     }
     bool valid = true;
     double latitude = 0.0;
     valid = valid && rosaic_driver::ParseDouble(sentence.get_body()[2], latitude);
     msg->lat = ConvertDMSToDegrees(latitude);
     double longitude = 0.0;
     valid = valid && rosaic_driver::ParseDouble(sentence.get_body()[4], longitude);
     msg->lon = ConvertDMSToDegrees(longitude);
     msg->lat_dir = sentence.get_body()[3];
     msg->lon_dir = sentence.get_body()[5];
     valid = valid && rosaic_driver::ParseUInt32(sentence.get_body()[6], msg->gps_qual);
     valid = valid && rosaic_driver::ParseUInt32(sentence.get_body()[7], msg->num_sats);
     //ROS_INFO("Valid is %s so far with number of satellites in use being %s", valid ? "true" : "false", sentence.get_body()[7].c_str());
     valid = valid && rosaic_driver::ParseFloat(sentence.get_body()[8], msg->hdop);
     valid = valid && rosaic_driver::ParseFloat(sentence.get_body()[9], msg->alt);
     msg->altitude_units = sentence.get_body()[10];
     valid = valid && rosaic_driver::ParseFloat(sentence.get_body()[11], msg->undulation);
     msg->undulation_units = sentence.get_body()[12];
     double diff_age_temp;
     valid = valid && rosaic_driver::ParseDouble(sentence.get_body()[13], diff_age_temp);
     msg->diff_age = static_cast<uint32_t>(round(diff_age_temp));
     msg->station_id = sentence.get_body()[14];
     if (!valid)
     {
         was_last_gpgga_valid_ = false;
         throw ParseException("GPGGA message was invalid.");
     }
     // If we made it this far, we successfully parsed the message and will consider it to be valid.
     was_last_gpgga_valid_ = true;
     return msg;
 }
WasLastGPGGAValid()
bool rosaic_driver::GpggaParser::WasLastGPGGAValid () const
Tells us whether the last GGA message was valid or not.
Returns
True if last GGA message was valid, false if not
Definition at line 131 of file gpgga.cpp.
References was_last_gpgga_valid_.
Referenced by GpggaParser().
 {
     return was_last_gpgga_valid_;
 }
Field Documentation
MESSAGE_ID
const std::string rosaic_driver::GpggaParser::MESSAGE_ID = "$GPGGA" static
Declares the string MESSAGE_ID.
Definition at line 117 of file gpgga.hpp.
Referenced by GetMessageID().
was_last_gpgga_valid_
bool rosaic_driver::GpggaParser::was_last_gpgga_valid_ private
Declares a boolean representing whether or not the last GPGGA message was valid.
Definition at line 123 of file gpgga.hpp.
Referenced by ParseASCII(), and WasLastGPGGAValid().
The documentation for this class was generated from the following files:
include/rosaic/parsers/nmea_parsers/gpgga.hpp
src/rosaic/parsers/nmea_parsers/gpgga.cpp