ROSaic: GpgsaParser Class Reference
GpgsaParser Class Reference
Derived class for parsing GSA messages.
#include <gpgsa.hpp>
Public Member Functions
GpgsaParser ()
Constructor of the class GpgsaParser.
const std::string getMessageID () const override
Returns the ASCII message ID, here "$GPGSA".
septentrio_gnss_driver::GpgsaPtr parseASCII (const NMEASentence &sentence) noexcept(false) override
Parses one GSA message.
Public Member Functions inherited from BaseParser< septentrio_gnss_driver::GpgsaPtr >
BaseParser ()=default
Default constructor of the class BaseParser.
virtual ~BaseParser ()=default
Default destructor of the class BaseParser.
septentrio_gnss_driver::GpgsaPtr parseBinary (const SBFStructT &bin_msg) noexcept(false)
Converts bin_msg into a ROS message pointer (e.g. nmea_msgs::GpggaPtr) and returns it.
Static Public Attributes
static const std::string MESSAGE_ID = "$GPGSA"
Declares the string MESSAGE_ID.
Detailed Description
Derived class for parsing GSA messages.
Date
29/09/20
Definition at line 82 of file gpgsa.hpp.
Constructor & Destructor Documentation
GpgsaParser()
GpgsaParser::GpgsaParser () inline
Constructor of the class GpgsaParser.
Definition at line 89 of file gpgsa.hpp.
References getMessageID(), and parseASCII().
 : BaseParser<septentrio_gnss_driver::GpgsaPtr>() {}
Member Function Documentation
getMessageID()
const std::string GpgsaParser::getMessageID () const override virtual
Returns the ASCII message ID, here "$GPGSA".
Returns
The message ID
Implements BaseParser< septentrio_gnss_driver::GpgsaPtr >.
Definition at line 41 of file gpgsa.cpp.
References MESSAGE_ID.
Referenced by GpgsaParser().
 {
     return GpgsaParser::MESSAGE_ID;
 }
parseASCII()
septentrio_gnss_driver::GpgsaPtr GpgsaParser::parseASCII (const NMEASentence & sentence) override virtual noexcept
Parses one GSA message.
Parameters
[in] sentence The GSA message to be parsed
Returns
A ROS message pointer of ROS type septentrio_gnss_driver::GpgsaPtr
Caution: Due to the occurrence of the throw keyword, this method ParseASCII should be called within a try / catch framework... Note: This method is called from within the read() method of the RxMessage class by including the checksum part in the argument "sentence" here, though the checksum is never parsed: It would be sentence.get_body()[18] if anybody ever needs it.
Reimplemented from BaseParser< septentrio_gnss_driver::GpgsaPtr >.
Definition at line 51 of file gpgsa.cpp.
References g_frame_id, parsing_utilities::parseFloat(), and parsing_utilities::parseUInt8().
Referenced by GpgsaParser(), and io_comm_rx::RxMessage::read().
 {
     // Checking the length first, it should be 19 elements
     const size_t LENGTH = 19;
     if (sentence.get_body().size() != LENGTH)
     {
         std::stringstream error;
         error << "Expected GPGSA length is " << LENGTH
             << ". The actual length is " << sentence.get_body().size();
         throw ParseException(error.str());
     }
     septentrio_gnss_driver::GpgsaPtr msg = boost::make_shared<septentrio_gnss_driver::Gpgsa>();
     msg->header.frame_id = g_frame_id;
     msg->message_id = sentence.get_body()[0];
     msg->auto_manual_mode = sentence.get_body()[1];
     parsing_utilities::parseUInt8(sentence.get_body()[2], msg->fix_mode);
     // Words 3-14 of the sentence are SV PRNs. Copying only the non-null strings..
     // 0 is the character needed to fill the new character space, in case 12 (first argument) is larger than sv_ids.
     msg->sv_ids.resize(12, 0);
     size_t n_svs = 0;
     for (std::vector<std::string>::const_iterator id = sentence.get_body().begin()+3; id < sentence.get_body().begin()+15; ++id)
     {
         if (! id->empty())
         {
             parsing_utilities::parseUInt8(*id, msg->sv_ids[n_svs]);
             ++n_svs;
         }
     }
     msg->sv_ids.resize(n_svs);
     parsing_utilities::parseFloat(sentence.get_body()[15], msg->pdop);
     parsing_utilities::parseFloat(sentence.get_body()[16], msg->hdop);
     parsing_utilities::parseFloat(sentence.get_body()[17], msg->vdop);
     return msg;
 }
Field Documentation
MESSAGE_ID
const std::string GpgsaParser::MESSAGE_ID = "$GPGSA" static
Declares the string MESSAGE_ID.
Definition at line 107 of file gpgsa.hpp.
Referenced by getMessageID().
The documentation for this class was generated from the following files:
include/septentrio_gnss_driver/parsers/nmea_parsers/gpgsa.hpp
src/septentrio_gnss_driver/parsers/nmea_parsers/gpgsa.cpp