ROSaic: io_comm_rx::CallbackHandlers Class Reference
io_comm_rx::CallbackHandlers Class Reference
Represents ensemble of (to be constructed) ROS messages, to be handled at once by this class.
#include <callback_handlers.hpp>
Public Types
typedef std::multimap< std::string, boost::shared_ptr< AbstractCallbackHandler > > CallbackMap
Key is std::string and represents the ROS message key, value is boost::shared_ptr<CallbackHandler>
Public Member Functions
CallbackHandlers ()=default
template<typename T >
CallbackMap insert (std::string message_key)
Adds a pair to the multimap "callbackmap_", with the message_key being the key.
void handle (RxMessage &rx_message)
Ćalled every time rx_message is found to contain some potentially useful message.
void readCallback (const uint8_t *data, std::size_t &size)
Searches for Rx messages that could potentially be decoded/parsed/published.
Data Fields
CallbackMap callbackmap_
Private Types
typedef std::map< std::string, uint32_t > GPSFixMap
Shorthand for the map responsible for matching ROS message identifiers relevant for GPSFix to a uint32_t.
typedef std::map< std::string, uint32_t > NavSatFixMap
Shorthand for the map responsible for matching ROS message identifiers relevant for NavSatFix to a uint32_t.
typedef std::map< std::string, uint32_t > PoseWithCovarianceStampedMap
typedef std::map< std::string, uint32_t > DiagnosticArrayMap
Static Private Attributes
static boost::mutex callback_mutex_
static std::string do_gpsfix_ = "4007"
static std::string do_navsatfix_ = "4007"
static std::string do_pose_ = "4007"
static std::string do_diagnostics_ = "4014"
static GPSFixMap gpsfix_map
static NavSatFixMap navsatfix_map
static PoseWithCovarianceStampedMap pose_map
static DiagnosticArrayMap diagnosticarray_map
Detailed Description
Represents ensemble of (to be constructed) ROS messages, to be handled at once by this class.
Definition at line 207 of file callback_handlers.hpp.
Member Typedef Documentation
CallbackMap
typedef std::multimap<std::string, boost::shared_ptr<AbstractCallbackHandler> > io_comm_rx::CallbackHandlers::CallbackMap
Key is std::string and represents the ROS message key, value is boost::shared_ptr<CallbackHandler>
Definition at line 213 of file callback_handlers.hpp.
DiagnosticArrayMap
typedef std::map<std::string, uint32_t> io_comm_rx::CallbackHandlers::DiagnosticArrayMap private
Shorthand for the map responsible for matching ROS message identifiers relevant for DiagnosticArray to a uint32_t
Definition at line 307 of file callback_handlers.hpp.
GPSFixMap
typedef std::map<std::string, uint32_t> io_comm_rx::CallbackHandlers::GPSFixMap private
Shorthand for the map responsible for matching ROS message identifiers relevant for GPSFix to a uint32_t.
Definition at line 284 of file callback_handlers.hpp.
NavSatFixMap
typedef std::map<std::string, uint32_t> io_comm_rx::CallbackHandlers::NavSatFixMap private
Shorthand for the map responsible for matching ROS message identifiers relevant for NavSatFix to a uint32_t.
Definition at line 291 of file callback_handlers.hpp.
PoseWithCovarianceStampedMap
typedef std::map<std::string, uint32_t> io_comm_rx::CallbackHandlers::PoseWithCovarianceStampedMap private
Shorthand for the map responsible for matching ROS message identifiers relevant for PoseWithCovarianceStamped to a uint32_t
Definition at line 299 of file callback_handlers.hpp.
Constructor & Destructor Documentation
CallbackHandlers()
io_comm_rx::CallbackHandlers::CallbackHandlers () default
Member Function Documentation
handle()
void io_comm_rx::CallbackHandlers::handle (RxMessage & rx_message)
Ćalled every time rx_message is found to contain some potentially useful message.
Parameters
rx_message The for loop forwards to a ROS message specific handle if the latter was added via callbackmap_.insert at some earlier point.
Definition at line 90 of file callback_handlers.cpp.
References callback_mutex_, callbackmap_, do_diagnostics_, do_gpsfix_, do_navsatfix_, do_pose_, g_publish_diagnostics, g_publish_gpsfix, g_publish_gpst, g_publish_navsatfix, g_publish_pose, and io_comm_rx::RxMessage::messageID().
Referenced by readCallback().
     {
         // Find the ROS message callback handler for the equivalent Rx message (SBF/NMEA) at hand & call it
         boost::mutex::scoped_lock lock(callback_mutex_);
         CallbackMap::key_type key = rx_message.messageID();
         std::string ID_temp = rx_message.messageID();
         if (!(ID_temp == "4013" || ID_temp == "4027" || ID_temp == "4001"|| ID_temp == "5908" ||
             ID_temp == "4014" || ID_temp == "4082" || ID_temp == "5902"))
         // We only want to handle ChannelStatus, MeasEpoch, DOP, VelCovGeodetic, ReceiverStatus,
         // QualityInd and ReceiverSetup blocks in case GPSFix and DiagnosticArray messages are to
         // be published, respectively, see few lines below.
         {
             for (CallbackMap::iterator callback = callbackmap_.lower_bound(key); callback !=
                 callbackmap_.upper_bound(key); ++callback)
             {
                 try
                 {
                     callback->second->handle(rx_message, callback->first);
                 }
                 catch (std::runtime_error& e)
                 {
                     throw std::runtime_error(e.what());
                 }
             }
         }
         // Call NavSatFix callback function if it was added
         if (g_publish_navsatfix)
         {
             CallbackMap::key_type key = "NavSatFix";
             std::string ID_temp = rx_message.messageID();
             if (ID_temp == do_navsatfix_)
             // The last incoming block among PVTGeodetic and PosCovGeodetic triggers the publishing of NavSatFix.
             {
                 for (CallbackMap::iterator callback = callbackmap_.lower_bound(key); callback !=
                     callbackmap_.upper_bound(key); ++callback)
                 {
                     try
                     {
                         callback->second->handle(rx_message, callback->first);
                     }
                     catch (std::runtime_error& e)
                     {
                         throw std::runtime_error(e.what());
                     }
                 }
                 do_navsatfix_ = std::string();
             }
         }
         // Call geometry_msgs::PoseWithCovarianceStamped callback function if it was added
         if (g_publish_pose)
         {
             CallbackMap::key_type key = "PoseWithCovarianceStamped";
             std::string ID_temp = rx_message.messageID();
             if (ID_temp == do_pose_)
             // The last incoming block among PVTGeodetic, PosCovGeodetic, AttEuler and AttCovEuler triggers
             // the publishing of PoseWithCovarianceStamped.
             {
                 for (CallbackMap::iterator callback = callbackmap_.lower_bound(key); callback !=
                     callbackmap_.upper_bound(key); ++callback)
                 {
                     try
                     {
                         callback->second->handle(rx_message, callback->first);
                     }
                     catch (std::runtime_error& e)
                     {
                         throw std::runtime_error(e.what());
                     }
                 }
                 do_pose_ = std::string();
             }
         }
         // Call diagnostic_msgs::DiagnosticArray callback function if it was added
         if (g_publish_diagnostics)
         {
             CallbackMap::key_type key1 = rx_message.messageID();
             std::string ID_temp = rx_message.messageID();
             if (ID_temp == "4014" || ID_temp == "4082" || ID_temp == "5902")
             {
                 for (CallbackMap::iterator callback = callbackmap_.lower_bound(key1); callback !=
                     callbackmap_.upper_bound(key1); ++callback)
                 {
                     try
                     {
                         callback->second->handle(rx_message, callback->first);
                     }
                     catch (std::runtime_error& e)
                     {
                         throw std::runtime_error(e.what());
                     }
                 }
             }
             CallbackMap::key_type key2 = "DiagnosticArray";
             if (ID_temp == do_diagnostics_)
             // The last incoming block among ReceiverStatus, QualityInd and ReceiverSetup triggers
             // the publishing of DiagnosticArray.
             {
                 for (CallbackMap::iterator callback = callbackmap_.lower_bound(key2); callback !=
                     callbackmap_.upper_bound(key2); ++callback)
                 {
                     try
                     {
                         callback->second->handle(rx_message, callback->first);
                     }
                     catch (std::runtime_error& e)
                     {
                         throw std::runtime_error(e.what());
                     }
                 }
                 do_diagnostics_ = std::string();
             }
         }
         // Call sensor_msgs::TimeReference (with GPST) callback function if it was added
         if (g_publish_gpst)
         {
             CallbackMap::key_type key1 = "GPST";
             std::string ID_temp = rx_message.messageID();
             // If no new PVTGeodetic block is coming in, there is no need to publish sensor_msgs::TimeReference (with GPST) anew.
             if (ID_temp == "4007")
             {
                 for (CallbackMap::iterator callback = callbackmap_.lower_bound(key1); callback !=
                     callbackmap_.upper_bound(key1); ++callback)
                 {
                     try
                     {
                         callback->second->handle(rx_message, callback->first);
                     }
                     catch (std::runtime_error& e)
                     {
                         throw std::runtime_error(e.what());
                     }
                 }
             }
         }
         // Call GPSFix callback function if it was added
         if (g_publish_gpsfix)
         {
             std::string ID_temp = rx_message.messageID();
             CallbackMap::key_type key1 = rx_message.messageID();
             if (ID_temp == "4013" || ID_temp == "4027" || ID_temp == "4001" || ID_temp == "5908")
             // Even though we are not interested in publishing ChannelStatus (4013), MeasEpoch (4027), DOP (4001)
             // and VelCovGeodetic (5908) ROS messages, we have to save some contents of these incoming blocks
             // in order to publish the GPSFix message.
             {
                 for (CallbackMap::iterator callback = callbackmap_.lower_bound(key1); callback !=
                     callbackmap_.upper_bound(key1); ++callback)
                 {
                     try
                     {
                         callback->second->handle(rx_message, callback->first);
                     }
                     catch (std::runtime_error& e)
                     {
                         throw std::runtime_error(e.what());
                     }
                 }
             }
             CallbackMap::key_type key2 = "GPSFix";
             if (ID_temp == do_gpsfix_)
             // The last incoming block among ChannelStatus (4013), MeasEpoch (4027), DOP (4001) and
             // VelCovGeodetic (5908) triggers the publishing of GPSFix.
             {
                 for (CallbackMap::iterator callback = callbackmap_.lower_bound(key2); callback !=
                     callbackmap_.upper_bound(key2); ++callback)
                 {
                     try
                     {
                         callback->second->handle(rx_message, callback->first);
                     }
                     catch (std::runtime_error& e)
                     {
                         throw std::runtime_error(e.what());
                     }
                 }
                 do_gpsfix_ = std::string();
             }
         }
     }
insert()
template<typename T > CallbackMap io_comm_rx::CallbackHandlers::insert (std::string message_key) inline
Adds a pair to the multimap "callbackmap_", with the message_key being the key.
This method is called by "handlers_" in rosaic_node.cpp. T would be a (custom or not) ROS message, e.g. septentrio_gnss_driver::PVTGeodetic, or nmea_msgs::GPGGA. Note that "typename" could be omitted in the argument.
Parameters
message_key The pair's key
callback The key's counterpart
Returns
The modified multimap "callbackmap_"
Definition at line 228 of file callback_handlers.hpp.
References io_comm_rx::AbstractCallbackHandler::handle().
Referenced by rosaic_node::ROSaicNode::defineMessages().
             {
                 boost::mutex::scoped_lock lock(callback_mutex_);
                 // Adding typename might be cleaner, but is optional again
                 CallbackHandler<T>* handler = new CallbackHandler<T>();
                 callbackmap_.insert(std::make_pair(message_key, boost::shared_ptr<AbstractCallbackHandler>(handler)));
                 CallbackMap::key_type key = message_key;
                 ROS_DEBUG("Key %s successfully inserted into multimap: %s", message_key.c_str(),
                     ((unsigned int) callbackmap_.count(key)) ? "true" : "false");
                 return callbackmap_;
             }
readCallback()
void io_comm_rx::CallbackHandlers::readCallback (const uint8_t * data, std::size_t & size)
Searches for Rx messages that could potentially be decoded/parsed/published.
Parameters
[in] data Buffer passed on from AsyncManager class
[in] size Size of the buffer
Definition at line 269 of file callback_handlers.cpp.
References diagnosticarray_map, do_diagnostics_, do_gpsfix_, do_navsatfix_, do_pose_, io_comm_rx::RxMessage::found(), g_attcoveuler_has_arrived_gpsfix, g_attcoveuler_has_arrived_pose, g_atteuler_has_arrived_gpsfix, g_atteuler_has_arrived_pose, g_cd_condition, g_cd_count, g_cd_mutex, g_cd_received, g_channelstatus_has_arrived_gpsfix, g_dop_has_arrived_gpsfix, g_measepoch_has_arrived_gpsfix, g_poscovgeodetic_has_arrived_gpsfix, g_poscovgeodetic_has_arrived_navsatfix, g_poscovgeodetic_has_arrived_pose, g_publish_diagnostics, g_publish_gpsfix, g_publish_navsatfix, g_publish_pose, g_pvtgeodetic_has_arrived_gpsfix, g_pvtgeodetic_has_arrived_navsatfix, g_pvtgeodetic_has_arrived_pose, g_qualityind_has_arrived_diagnostics, g_receiverstatus_has_arrived_diagnostics, g_response_condition, g_response_mutex, g_response_received, g_rx_tcp_port, g_velcovgeodetic_has_arrived_gpsfix, io_comm_rx::RxMessage::getBlockLength(), io_comm_rx::RxMessage::getCount(), io_comm_rx::RxMessage::getEndBuffer(), io_comm_rx::RxMessage::getPosBuffer(), gpsfix_map, handle(), io_comm_rx::RxMessage::isConnectionDescriptor(), io_comm_rx::RxMessage::isErrorMessage(), io_comm_rx::RxMessage::isNMEA(), io_comm_rx::RxMessage::isResponse(), io_comm_rx::RxMessage::isSBF(), MAX_NMEA_SIZE, io_comm_rx::RxMessage::messageID(), io_comm_rx::RxMessage::messageSize(), navsatfix_map, pose_map, and io_comm_rx::RxMessage::search().
Referenced by io_comm_rx::Comm_IO::setManager().
     {
         RxMessage rx_message(data, size);
         // Read !all! (there might be many) messages in the buffer
         while (rx_message.search() != rx_message.getEndBuffer() && rx_message.found())
         {
             // Print the found message (if NMEA) or just show messageID (if SBF)..
             if (rx_message.isSBF())
             {
                 std::size_t sbf_block_length;
                 std::string ID_temp = rx_message.messageID();
                 sbf_block_length = static_cast<std::size_t>(rx_message.getBlockLength());
                 ROS_DEBUG("ROSaic reading SBF block %s made up of %li bytes...", ID_temp.c_str(), sbf_block_length);
                 // If full message did not yet arrive, throw an error message.
                 if (sbf_block_length > rx_message.getCount())
                 {
                     ROS_DEBUG("Not a valid SBF block, parts of the SBF block are yet to be received. Ignore..");
                     throw (static_cast<std::size_t>(rx_message.getPosBuffer() - data));
                 }
                 if (g_publish_gpsfix == true && (ID_temp == "4013" || ID_temp == "4027" ||
                     ID_temp == "4001" || ID_temp == "4007" || ID_temp == "5906" || ID_temp == "5908" ||
                     ID_temp == "5938" || ID_temp == "5939"))
                 {
                     std::vector<bool> gpsfix_vec = {g_channelstatus_has_arrived_gpsfix, g_measepoch_has_arrived_gpsfix,
                         g_dop_has_arrived_gpsfix, g_pvtgeodetic_has_arrived_gpsfix, g_poscovgeodetic_has_arrived_gpsfix,
                         g_velcovgeodetic_has_arrived_gpsfix, g_atteuler_has_arrived_gpsfix,
                         g_attcoveuler_has_arrived_gpsfix};
                     gpsfix_vec.erase(gpsfix_vec.begin() + gpsfix_map[ID_temp]);
                     // Checks whether all entries in gpsfix_vec are true
                     if (std::all_of(gpsfix_vec.begin(), gpsfix_vec.end(), [](bool v) { return v; }) == true)
                     {
                         do_gpsfix_ = ID_temp;
                     }
                 }
                 if (g_publish_navsatfix == true && (ID_temp == "4007" || ID_temp == "5906"))
                 {
                     std::vector<bool> navsatfix_vec = {g_pvtgeodetic_has_arrived_navsatfix,
                         g_poscovgeodetic_has_arrived_navsatfix };
                     navsatfix_vec.erase(navsatfix_vec.begin() + navsatfix_map[ID_temp]);
                     // Checks whether all entries in navsatfix_vec are true
                     if (std::all_of(navsatfix_vec.begin(), navsatfix_vec.end(), [](bool v) { return v; }) == true)
                     {
                         do_navsatfix_ = ID_temp;
                     }
                 }
                 if (g_publish_pose == true && (ID_temp == "4007" || ID_temp == "5906" ||
                     ID_temp == "5938" || ID_temp == "5939"))
                 {
                     std::vector<bool> pose_vec = {g_pvtgeodetic_has_arrived_pose, g_poscovgeodetic_has_arrived_pose,
                         g_atteuler_has_arrived_pose, g_attcoveuler_has_arrived_pose};
                     pose_vec.erase(pose_vec.begin() + pose_map[ID_temp]);
                     // Checks whether all entries in pose_vec are true
                     if (std::all_of(pose_vec.begin(), pose_vec.end(), [](bool v) { return v; }) == true)
                     {
                         do_pose_ = ID_temp;
                     }
                 }
                 if (g_publish_diagnostics == true && (ID_temp == "4014" || ID_temp == "4082"))
                 {
                     std::vector<bool> diagnostics_vec = {g_receiverstatus_has_arrived_diagnostics,
                         g_qualityind_has_arrived_diagnostics};
                     diagnostics_vec.erase(diagnostics_vec.begin() + diagnosticarray_map[ID_temp]);
                     // Checks whether all entries in diagnostics_vec are true
                     if (std::all_of(diagnostics_vec.begin(), diagnostics_vec.end(), [](bool v) { return v; }) == true)
                     {
                         do_diagnostics_ = ID_temp;
                     }
                 }
             }
             if (rx_message.isNMEA())
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = rx_message.messageSize();
                 if (nmea_size < MIN_NMEA_SIZE || nmea_size > MAX_NMEA_SIZE)
                 {
                     ROS_DEBUG("Not a valid NMEA message, parts of the message are yet to be received. Ignore..");
                     throw (static_cast<std::size_t>(rx_message.getPosBuffer() - data));
                 }
                 // Syntax: new_string_name (const char* s, size_t n); size_t is either 2 or 8 bytes, depending on your system
                 std::string block_in_string(reinterpret_cast<const char*>(rx_message.getPosBuffer()), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 ROS_DEBUG("The NMEA message is ready to be parsed. It reads: %s", (*tokens.begin()).c_str());
             }
             if (rx_message.isResponse()) // If the response is not sent at once, only first part is ROS_DEBUG-printed
             {
                 std::size_t response_size = rx_message.messageSize();
                 std::string block_in_string(reinterpret_cast<const char*>(rx_message.getPosBuffer()), response_size);
                 ROS_DEBUG("The Rx's response contains %li bytes and reads:\n %s", response_size, block_in_string.c_str());
                 {
                     boost::mutex::scoped_lock lock(g_response_mutex);
                     g_response_received = true;
                     lock.unlock();
                     g_response_condition.notify_one();
                 }
                 if (rx_message.isErrorMessage())
                 {
                     ROS_ERROR("Invalid command just sent to the Rx!");
                 }
                 continue;
             }
             if (rx_message.isConnectionDescriptor())
             {
                 std::string cd(reinterpret_cast<const char*>(rx_message.getPosBuffer()), 4);
                 g_rx_tcp_port = cd;
                 ROS_INFO_COND(g_cd_count == 0, "The connection descriptor for the TCP connection is %s", cd.c_str());
                 if (g_cd_count < 3) ++g_cd_count;
                 if (g_cd_count == 2)
                 {
                     boost::mutex::scoped_lock lock(g_cd_mutex);
                     g_cd_received = true;
                     lock.unlock();
                     g_cd_condition.notify_one();
                 }
                 continue;
             }
             //ROS_DEBUG("Handing over from readcallback to handle while count is %li", rx_message.getCount());
             try
             {
                 handle(rx_message);
             }
             catch (std::runtime_error& e)
             {
                 ROS_DEBUG("Without a (circular) buffer and a new thread, we would have faced an incomplete message right now. %s", e.what());
                 throw (static_cast<std::size_t>(rx_message.getPosBuffer() - data));
             }
         }
     }
Field Documentation
callback_mutex_
boost::mutex io_comm_rx::CallbackHandlers::callback_mutex_ static private
The "static" keyword resolves construct-by-copying issues related to this mutex by making it available throughout the code unit. The mutex constructor list contains "mutex (const mutex&) = delete", hence construct-by-copying a mutex is explicitly prohibited. The get_handlers() method of the Comm_IO class hence forces us to make this mutex static.
Definition at line 265 of file callback_handlers.hpp.
Referenced by handle().
callbackmap_
CallbackMap io_comm_rx::CallbackHandlers::callbackmap_
Callback handlers multimap for Rx messages; it needs to be public since we copy-assign (did not work otherwise) new callbackmap_, after inserting a pair to the multimap within the DefineMessages() method of the ROSaicNode class, onto its old version.
Definition at line 257 of file callback_handlers.hpp.
Referenced by rosaic_node::ROSaicNode::defineMessages(), and handle().
diagnosticarray_map
CallbackHandlers::DiagnosticArrayMap io_comm_rx::CallbackHandlers::diagnosticarray_map static private
All instances of the CallbackHandlers class shall have access to the map without reinitializing it, hence static
Definition at line 311 of file callback_handlers.hpp.
Referenced by readCallback().
do_diagnostics_
std::string io_comm_rx::CallbackHandlers::do_diagnostics_ = "4014" static private
Determines which of the SBF blocks necessary for the diagnostic_msgs/DiagnosticArray ROS message arrives last and thus launches its construction
Definition at line 281 of file callback_handlers.hpp.
Referenced by handle(), and readCallback().
do_gpsfix_
std::string io_comm_rx::CallbackHandlers::do_gpsfix_ = "4007" static private
Determines which of the SBF blocks necessary for the gps_common::GPSFix ROS message arrives last and thus launches its construction
Definition at line 269 of file callback_handlers.hpp.
Referenced by handle(), and readCallback().
do_navsatfix_
std::string io_comm_rx::CallbackHandlers::do_navsatfix_ = "4007" static private
Determines which of the SBF blocks necessary for the sensor_msgs::NavSatFix ROS message arrives last and thus launches its construction
Definition at line 273 of file callback_handlers.hpp.
Referenced by handle(), and readCallback().
do_pose_
std::string io_comm_rx::CallbackHandlers::do_pose_ = "4007" static private
Determines which of the SBF blocks necessary for the geometry_msgs/PoseWithCovarianceStamped ROS message arrives last and thus launches its construction
Definition at line 277 of file callback_handlers.hpp.
Referenced by handle(), and readCallback().
gpsfix_map
CallbackHandlers::GPSFixMap io_comm_rx::CallbackHandlers::gpsfix_map static private
All instances of the CallbackHandlers class shall have access to the map without reinitializing it, hence static
Definition at line 288 of file callback_handlers.hpp.
Referenced by readCallback().
navsatfix_map
CallbackHandlers::NavSatFixMap io_comm_rx::CallbackHandlers::navsatfix_map static private
All instances of the CallbackHandlers class shall have access to the map without reinitializing it, hence static
Definition at line 295 of file callback_handlers.hpp.
Referenced by readCallback().
pose_map
CallbackHandlers::PoseWithCovarianceStampedMap io_comm_rx::CallbackHandlers::pose_map static private
All instances of the CallbackHandlers class shall have access to the map without reinitializing it, hence static
Definition at line 303 of file callback_handlers.hpp.
Referenced by readCallback().
The documentation for this class was generated from the following files:
include/septentrio_gnss_driver/communication/callback_handlers.hpp
src/septentrio_gnss_driver/communication/callback_handlers.cpp