ROSaic: io_comm_rx::RxMessage Class Reference
io_comm_rx::RxMessage Class Reference
Can search buffer for messages, read/parse them, and so on.
#include <rx_message.hpp>
Public Member Functions
RxMessage (const uint8_t *data, std::size_t &size)
Constructor of the RxMessage class.
bool isMessage (const uint16_t ID)
Determines whether data_ points to the SBF block with ID "ID", e.g. 5003.
bool isMessage (std::string ID)
Determines whether data_ points to the NMEA message with ID "ID", e.g. "$GPGGA".
bool isSBF ()
Determines whether data_ currently points to an SBF block.
bool isNMEA ()
Determines whether data_ currently points to an NMEA message.
bool isResponse ()
Determines whether data_ currently points to an NMEA message.
bool isConnectionDescriptor ()
bool isErrorMessage ()
Determines whether data_ currently points to an error message reply from the Rx.
std::size_t messageSize ()
Determines size of the message (also command reply) that data_ is currently pointing at.
std::string messageID ()
std::size_t getCount ()
Returns the count_ variable.
const uint8_t * search ()
Searches the buffer for the beginning of the next message (NMEA or SBF)
uint16_t getBlockLength ()
Gets the length of the SBF block.
const uint8_t * getPosBuffer ()
Gets the current position in the read buffer.
const uint8_t * getEndBuffer ()
Gets the end position in the read buffer.
bool found ()
Has an NMEA message, SBF block or command reply been found in the buffer?
void next ()
Goes to the start of the next message based on the calculated length of current message.
template<typename T >
bool read (typename boost::call_traits< T >::reference message, std::string message_key, bool search=false)
Performs the CRC check (if SBF) and populates ROS message "message" with the necessary content.
Data Fields
bool found_
Whether or not a message has been found.
Private Types
typedef std::map< uint16_t, TypeOfPVT_Enum > TypeOfPVTMap
Shorthand for the map responsible for matching PVTGeodetic's Mode field to an enum value.
typedef std::map< std::string, RxID_Enum > RxIDMap
Shorthand for the map responsible for matching ROS message identifiers to an enum value.
Private Member Functions
septentrio_gnss_driver::PVTCartesianPtr PVTCartesianCallback (PVTCartesian &data)
Callback function when reading PVTCartesian blocks.
septentrio_gnss_driver::PVTGeodeticPtr PVTGeodeticCallback (PVTGeodetic &data)
Callback function when reading PVTGeodetic blocks.
septentrio_gnss_driver::PosCovCartesianPtr PosCovCartesianCallback (PosCovCartesian &data)
Callback function when reading PosCovCartesian blocks.
septentrio_gnss_driver::PosCovGeodeticPtr PosCovGeodeticCallback (PosCovGeodetic &data)
Callback function when reading PosCovGeodetic blocks.
septentrio_gnss_driver::AttEulerPtr AttEulerCallback (AttEuler &data)
Callback function when reading AttEuler blocks.
septentrio_gnss_driver::AttCovEulerPtr AttCovEulerCallback (AttCovEuler &data)
Callback function when reading AttCovEuler blocks.
sensor_msgs::NavSatFixPtr NavSatFixCallback ()
"Callback" function when constructing NavSatFix messages
gps_common::GPSFixPtr GPSFixCallback ()
"Callback" function when constructing GPSFix messages
geometry_msgs::PoseWithCovarianceStampedPtr PoseWithCovarianceStampedCallback ()
"Callback" function when constructing PoseWithCovarianceStamped messages
diagnostic_msgs::DiagnosticArrayPtr DiagnosticArrayCallback ()
"Callback" function when constructing diagnostic_msgs::DiagnosticArray messages
Private Attributes
const uint8_t * data_
Pointer to the buffer of messages.
std::size_t count_
Number of unread bytes in the buffer.
bool crc_check_
Whether the CRC check as evaluated in the read() method was successful or not is stored here.
std::size_t message_size_
Helps to determine size of response message / NMEA message / SBF block.
Static Private Attributes
static uint32_t count_gpsfix_ = 0
Number of times the gps_common::GPSFix message has been published.
static PVTGeodetic last_pvtgeodetic_ = PVTGeodetic()
Since NavSatFix etc. need PVTGeodetic, incoming PVTGeodetic blocks need to be stored.
static PosCovGeodetic last_poscovgeodetic_ = PosCovGeodetic()
Since NavSatFix etc. need PosCovGeodetic, incoming PosCovGeodetic blocks need to be stored.
static AttEuler last_atteuler_ = AttEuler()
Since GPSFix etc. need AttEuler, incoming AttEuler blocks need to be stored.
static AttCovEuler last_attcoveuler_ = AttCovEuler()
Since GPSFix etc. need AttCovEuler, incoming AttCovEuler blocks need to be stored.
static ChannelStatus last_channelstatus_ = ChannelStatus()
Since GPSFix needs ChannelStatus, incoming ChannelStatus blocks need to be stored.
static MeasEpoch last_measepoch_ = MeasEpoch()
Since GPSFix needs MeasEpoch (for SNRs), incoming MeasEpoch blocks need to be stored.
static DOP last_dop_ = DOP()
Since GPSFix needs DOP, incoming DOP blocks need to be stored.
static VelCovGeodetic last_velcovgeodetic_ = VelCovGeodetic()
Since GPSFix needs VelCovGeodetic, incoming VelCovGeodetic blocks need to be stored.
static ReceiverStatus last_receiverstatus_ = ReceiverStatus()
Since DiagnosticArray needs ReceiverStatus, incoming ReceiverStatus blocks need to be stored.
static QualityInd last_qualityind_ = QualityInd()
Since DiagnosticArray needs QualityInd, incoming QualityInd blocks need to be stored.
static ReceiverSetup last_receiversetup_ = ReceiverSetup()
Since DiagnosticArray needs ReceiverSetup, incoming ReceiverSetup blocks need to be stored.
static TypeOfPVTMap type_of_pvt_map
All instances of the RxMessage class shall have access to the map without reinitializing it, hence static.
static RxIDMap rx_id_map
All instances of the RxMessage class shall have access to the map without reinitializing it, hence static.
Detailed Description
Can search buffer for messages, read/parse them, and so on.
Definition at line 200 of file rx_message.hpp.
Member Typedef Documentation
RxIDMap
typedef std::map<std::string, RxID_Enum> io_comm_rx::RxMessage::RxIDMap private
Shorthand for the map responsible for matching ROS message identifiers to an enum value.
Definition at line 384 of file rx_message.hpp.
TypeOfPVTMap
typedef std::map<uint16_t, TypeOfPVT_Enum> io_comm_rx::RxMessage::TypeOfPVTMap private
Shorthand for the map responsible for matching PVTGeodetic's Mode field to an enum value.
Definition at line 376 of file rx_message.hpp.
Constructor & Destructor Documentation
RxMessage()
io_comm_rx::RxMessage::RxMessage (const uint8_t * data, std::size_t & size) inline
Constructor of the RxMessage class.
One can always provide a non-const value where a const one was expected. The const-ness of the argument just means the function promises not to change it.. Recall: static_cast by the way can remove or add const-ness, no other C++ cast is capable of removing it (not even reinterpret_cast)
Parameters
[in] data Pointer to the buffer that is about to be analyzed
[in] size Size of the buffer (as handed over by async_read_some)
Definition at line 213 of file rx_message.hpp.
References crc_check_, found_, isConnectionDescriptor(), isErrorMessage(), isMessage(), isNMEA(), isResponse(), isSBF(), message_size_, messageID(), and messageSize().
                                                            : data_(data), count_(size)
             {found_ = false; crc_check_ = false; message_size_ = 0;}
Member Function Documentation
AttCovEulerCallback()
septentrio_gnss_driver::AttCovEulerPtr io_comm_rx::RxMessage::AttCovEulerCallback (AttCovEuler & data) private
Callback function when reading AttCovEuler blocks.
Parameters
[in] data The (packed and aligned) struct instance used to populate the ROS message AttCovEuler
Returns
A smart pointer to the ROS message AttCovEuler just created
Definition at line 252 of file rx_message.cpp.
References AttCovEuler::block_header, AttCovEuler::cov_headhead, AttCovEuler::cov_headpitch, AttCovEuler::cov_headroll, AttCovEuler::cov_pitchpitch, AttCovEuler::cov_pitchroll, AttCovEuler::cov_rollroll, BlockHeader_t::crc, AttCovEuler::error, BlockHeader_t::id, BlockHeader_t::length, BlockHeader_t::sync_1, BlockHeader_t::sync_2, AttCovEuler::tow, and AttCovEuler::wnc.
Referenced by read().
 {
     septentrio_gnss_driver::AttCovEulerPtr msg = boost::make_shared<septentrio_gnss_driver::AttCovEuler>();
     msg->block_header.sync_1 = data.block_header.sync_1;
     msg->block_header.sync_2 = data.block_header.sync_2;
     msg->block_header.crc = data.block_header.crc;
     msg->block_header.id = data.block_header.id;
     msg->block_header.length = data.block_header.length;
     msg->block_header.tow = data.tow;
     msg->block_header.wnc = data.wnc;
     msg->error = data.error;
     msg->cov_headhead = data.cov_headhead;
     msg->cov_pitchpitch = data.cov_pitchpitch;
     msg->cov_rollroll = data.cov_rollroll;
     msg->cov_headpitch = data.cov_headpitch;
     msg->cov_headroll = data.cov_headroll;
     msg->cov_pitchroll = data.cov_pitchroll;
     return msg;
 };
AttEulerCallback()
septentrio_gnss_driver::AttEulerPtr io_comm_rx::RxMessage::AttEulerCallback (AttEuler & data) private
Callback function when reading AttEuler blocks.
Parameters
[in] data The (packed and aligned) struct instance used to populate the ROS message AttEuler
Returns
A smart pointer to the ROS message AttEuler just created
Definition at line 230 of file rx_message.cpp.
References AttEuler::block_header, BlockHeader_t::crc, AttEuler::error, AttEuler::heading, AttEuler::heading_dot, BlockHeader_t::id, BlockHeader_t::length, AttEuler::mode, AttEuler::nr_sv, AttEuler::pitch, AttEuler::pitch_dot, AttEuler::roll, AttEuler::roll_dot, BlockHeader_t::sync_1, BlockHeader_t::sync_2, AttEuler::tow, and AttEuler::wnc.
Referenced by read().
 {
     septentrio_gnss_driver::AttEulerPtr msg = boost::make_shared<septentrio_gnss_driver::AttEuler>();
     msg->block_header.sync_1 = data.block_header.sync_1;
     msg->block_header.sync_2 = data.block_header.sync_2;
     msg->block_header.crc = data.block_header.crc;
     msg->block_header.id = data.block_header.id;
     msg->block_header.length = data.block_header.length;
     msg->block_header.tow = data.tow;
     msg->block_header.wnc = data.wnc;
     msg->nr_sv = data.nr_sv;
     msg->error = data.error;
     msg->mode = data.mode;
     msg->heading = data.heading;
     msg->pitch = data.pitch;
     msg->roll = data.roll;
     msg->pitch_dot = data.pitch_dot;
     msg->roll_dot = data.roll_dot;
     msg->heading_dot = data.heading_dot;
     return msg;
 };
DiagnosticArrayCallback()
diagnostic_msgs::DiagnosticArrayPtr io_comm_rx::RxMessage::DiagnosticArrayCallback () private
"Callback" function when constructing diagnostic_msgs::DiagnosticArray messages
Returns
A smart pointer to the ROS message diagnostic_msgs::DiagnosticArray just created
Definition at line 332 of file rx_message.cpp.
References QualityInd::indicators, last_qualityind_, last_receiversetup_, last_receiverstatus_, QualityInd::n, ReceiverStatus::rx_error, and ReceiverSetup::rx_serial_number.
Referenced by read().
 {
     diagnostic_msgs::DiagnosticArrayPtr msg = boost::make_shared<diagnostic_msgs::DiagnosticArray>();
     std::string serialnumber(last_receiversetup_.rx_serial_number);
     diagnostic_msgs::DiagnosticStatusPtr gnss_status = boost::make_shared<diagnostic_msgs::DiagnosticStatus>();
     // Constructing the "level of operation" field
     uint16_t indicators_type_mask = static_cast<uint16_t>(255);
     uint16_t indicators_value_mask = static_cast<uint16_t>(3840);
     uint16_t qualityind_pos;
     for(uint16_t i = static_cast<uint16_t>(0); i != last_qualityind_.n; ++i)
     {
         if((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(0))
         {
             qualityind_pos = i;
             if(((last_qualityind_.indicators[i] & indicators_value_mask) >> 8) == static_cast<uint16_t>(0))
             {
                 gnss_status->level = diagnostic_msgs::DiagnosticStatus::STALE;
             }
             else if(((last_qualityind_.indicators[i] & indicators_value_mask) >> 8) == static_cast<uint16_t>(1)
                 || ((last_qualityind_.indicators[i] & indicators_value_mask) >> 8)== static_cast<uint16_t>(2))
             {
                 gnss_status->level = diagnostic_msgs::DiagnosticStatus::WARN;
             }
             else
             {
                 gnss_status->level = diagnostic_msgs::DiagnosticStatus::OK;
             }
             break;
         }
     }
     // If the ReceiverStatus's RxError field is not 0, then at least one error has been detected.
     if(last_receiverstatus_.rx_error != static_cast<uint32_t>(0))
     {
         gnss_status->level = diagnostic_msgs::DiagnosticStatus::ERROR;
     }
     // Creating an array of values associated with the GNSS status
     gnss_status->values.resize(static_cast<uint16_t>(last_qualityind_.n-1));
     for(uint16_t i = static_cast<uint16_t>(0); i != static_cast<uint16_t>(last_qualityind_.n); ++i)
     {
         if(i == qualityind_pos)
         {
             continue;
         }
         if((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(1))
         {
             gnss_status->values[i].key = "GNSS Signals, Main Antenna";
             gnss_status->values[i].value = std::to_string((last_qualityind_.indicators[i] & indicators_value_mask) >> 8);
         }
         else if((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(2))
         {
             gnss_status->values[i].key = "GNSS Signals, Aux1 Antenna";
             gnss_status->values[i].value = std::to_string((last_qualityind_.indicators[i] & indicators_value_mask) >> 8);
         }
         else if((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(11))
         {
             gnss_status->values[i].key = "RF Power, Main Antenna";
             gnss_status->values[i].value = std::to_string((last_qualityind_.indicators[i] & indicators_value_mask) >> 8);
         }
         else if((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(12))
         {
             gnss_status->values[i].key = "RF Power, Aux1 Antenna";
             gnss_status->values[i].value = std::to_string((last_qualityind_.indicators[i] & indicators_value_mask) >> 8);
         }
         else if((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(21))
         {
             gnss_status->values[i].key = "CPU Headroom";
             gnss_status->values[i].value = std::to_string((last_qualityind_.indicators[i] & indicators_value_mask) >> 8);
         }
         else if((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(25))
         {
             gnss_status->values[i].key = "OCXO Stability";
             gnss_status->values[i].value = std::to_string((last_qualityind_.indicators[i] & indicators_value_mask) >> 8);
         }
         else if((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(30))
         {
             gnss_status->values[i].key = "Base Station Measurements";
             gnss_status->values[i].value = std::to_string((last_qualityind_.indicators[i] & indicators_value_mask) >> 8);
         }
         else
         {
             assert ((last_qualityind_.indicators[i] & indicators_type_mask) == static_cast<uint16_t>(31));
             gnss_status->values[i].key = "RTK Post-Processing";
             gnss_status->values[i].value = std::to_string((last_qualityind_.indicators[i] & indicators_value_mask) >> 8);
         }
     }
     gnss_status->hardware_id = serialnumber;
     gnss_status->name = "GNSS";
     gnss_status->message = "Quality Indicators (from 0 for low quality to 10 for high quality, 15 if unknown)";
     msg->status.push_back(*gnss_status);
     return msg;
 }
found()
bool io_comm_rx::RxMessage::found ()
Has an NMEA message, SBF block or command reply been found in the buffer?
Returns
True if a message with the correct header & length has been found
Definition at line 820 of file rx_message.cpp.
References found_, g_read_cd, isConnectionDescriptor(), isNMEA(), isResponse(), and isSBF().
Referenced by getCount(), next(), read(), and io_comm_rx::CallbackHandlers::readCallback().
 {
     if (found_) return true;
     // Verify header bytes
     if (!this->isSBF() && !this->isNMEA() && !this->isResponse() && !(g_read_cd && this->isConnectionDescriptor()))
     {
         return false;
     }
     found_ = true;
     return true;
 }
getBlockLength()
uint16_t io_comm_rx::RxMessage::getBlockLength ()
Gets the length of the SBF block.
It determines the length from the header of the SBF block. The block length thus includes the header length.
Returns
The length of the SBF block
Definition at line 1066 of file rx_message.cpp.
References data_, and isSBF().
Referenced by getCount(), next(), and io_comm_rx::CallbackHandlers::readCallback().
 {
     if (this->isSBF())
     {
         uint16_t block_length;
         // Note that static_cast<uint16_t>(data_[6]) would just take the one byte "data_[6]"
         // and cast it as requested, !neglecting! the byte "data_[7]".
         block_length = *(reinterpret_cast<const uint16_t*>(data_ + 6));
         return block_length;
     }
     else
     {
         return 0;
     }
 }
getCount()
std::size_t io_comm_rx::RxMessage::getCount () inline
Returns the count_ variable.
Returns
The variable count_
Definition at line 241 of file rx_message.hpp.
References count_, found(), getBlockLength(), getEndBuffer(), getPosBuffer(), next(), read(), and search().
Referenced by io_comm_rx::CallbackHandlers::readCallback().
 {return count_;};
getEndBuffer()
const uint8_t * io_comm_rx::RxMessage::getEndBuffer ()
Gets the end position in the read buffer.
Returns
A pointer pointing to just after the read buffer (matches search()'s final pointer in case no valid message is found)
Definition at line 1061 of file rx_message.cpp.
References count_, and data_.
Referenced by getCount(), and io_comm_rx::CallbackHandlers::readCallback().
 {
     return data_ + count_;
 }
getPosBuffer()
const uint8_t * io_comm_rx::RxMessage::getPosBuffer ()
Gets the current position in the read buffer.
Returns
The current position of the read buffer
Definition at line 1056 of file rx_message.cpp.
References data_.
Referenced by getCount(), and io_comm_rx::CallbackHandlers::readCallback().
 {
     return data_;
 }
GPSFixCallback()
gps_common::GPSFixPtr io_comm_rx::RxMessage::GPSFixCallback () private
"Callback" function when constructing GPSFix messages
Returns
A smart pointer to the ROS message GPSFix just created
For some unknown reason, the first 2 entries of the GPSStatus field's arrays are not shown properly when published. Please consult section 4.1.9 of the firmware (at least for mosaic-x5) to understand the meaning of the SV identifiers used in the arrays of the GPSStatus field. Note that the field "dip" denotes the local magnetic inclination in degrees (positive when the magnetic field points downwards (into the Earth)). This quantity cannot be calculated by most Septentrio receivers. We assume that for the ROS field "err_time", we are requested to provide the 2 sigma uncertainty on the clock bias estimate in square meters, not the clock drift estimate (latter would be "2*std::sqrt(static_cast<double>(last_velcovgeodetic_.Cov_DtDt))"). The "err_track" entry is calculated via the Gaussian error propagation formula from the eastward and the northward velocities. For the formula's usage we have to assume that the eastward and the northward velocities are independent variables. Note that elevations and azimuths of visible satellites are taken from the ChannelStatus block, which provides 1 degree precision, while the SatVisibility block could provide hundredths of degrees precision. Change if imperative for your application... Definition of "visible satellite" adopted here: We define a visible satellite as being !up to! "in sync" mode with the receiver, which corresponds to last_measepoch_.N (signal-to-noise ratios are thereby available for these), though not last_channelstatus_.N, which also includes those "in search". In case certain values appear unphysical, please consult the firmware, since those most likely refer to Do-Not-Use values.
Definition at line 519 of file rx_message.cpp.
References ChannelSatInfo::az_rise_set, ChannelStatus::block_header, MeasEpoch::block_header, MeasEpochChannelType1::cn0, PVTGeodetic::cog, PosCovGeodetic::cov_bb, PosCovGeodetic::cov_hgthgt, PosCovGeodetic::cov_lathgt, PosCovGeodetic::cov_latlat, PosCovGeodetic::cov_latlon, PosCovGeodetic::cov_lonhgt, PosCovGeodetic::cov_lonlon, AttCovEuler::cov_pitchpitch, AttCovEuler::cov_rollroll, VelCovGeodetic::cov_veve, VelCovGeodetic::cov_vnvn, VelCovGeodetic::cov_vuvu, ChannelStatus::data, MeasEpoch::data, ChannelSatInfo::elev, evDGPS, evFixed, evMovingBaseRTKFixed, evMovingBaseRTKFloat, evNoPVT, evPPP, evRTKFixed, evRTKFloat, evSBAS, evStandAlone, DOP::hdop, PVTGeodetic::height, last_attcoveuler_, last_atteuler_, last_channelstatus_, last_dop_, last_measepoch_, last_poscovgeodetic_, last_pvtgeodetic_, last_velcovgeodetic_, PVTGeodetic::latitude, PVTGeodetic::longitude, PVTGeodetic::mode, ChannelStatus::n, MeasEpoch::n, ChannelSatInfo::n2, MeasEpochChannelType1::n_type2, PVTGeodetic::nr_sv, DOP::pdop, AttEuler::pitch, ChannelStateInfo::pvt_status, PVTGeodetic::reference_id, AttEuler::roll, ChannelStatus::sb1_size, MeasEpoch::sb1_size, ChannelStatus::sb2_size, MeasEpoch::sb2_size, ChannelSatInfo::sv_id, MeasEpochChannelType1::sv_id, BlockHeader_t::sync_1, DOP::tdop, PVTGeodetic::tow, MeasEpochChannelType1::type, type_of_pvt_map, DOP::vdop, PVTGeodetic::ve, PVTGeodetic::vn, PVTGeodetic::vu, and PVTGeodetic::wnc.
Referenced by read().
 {
     gps_common::GPSFixPtr msg = boost::make_shared<gps_common::GPSFix>();
     msg->status.satellites_used = static_cast<uint16_t>(last_pvtgeodetic_.nr_sv);
     // MeasEpoch Processing
     std::vector<int32_t> cno_tracked;
     std::vector<int32_t> svid_in_sync;
     {
         uint8_t sb1_size = last_measepoch_.sb1_size;
         uint8_t sb2_size = last_measepoch_.sb2_size;
         uint8_t *sb_start = &last_measepoch_.data[0];
         int32_t index = sb_start - &last_measepoch_.block_header.sync_1;
         for (int32_t i = 0; i < static_cast<int32_t>(last_measepoch_.n); ++i)
         {
             // Define MeasEpochChannelType1 struct for the corresponding sub-block
             MeasEpochChannelType1 *measepoch_channel_type1  =
                 reinterpret_cast<MeasEpochChannelType1*>(&last_measepoch_.block_header.sync_1 + index);
             svid_in_sync.push_back(static_cast<int32_t>(measepoch_channel_type1->sv_id));
             uint8_t type_mask = 15; // We extract the first four bits using this mask.
             if (((measepoch_channel_type1->type & type_mask) == static_cast<uint8_t>(1)) ||
                 ((measepoch_channel_type1->type & type_mask) == static_cast<uint8_t>(2)))
             {
                 cno_tracked.push_back(static_cast<int32_t>(measepoch_channel_type1->cn0)/4);
             }
             else
             {
                 cno_tracked.push_back(static_cast<int32_t>(measepoch_channel_type1->cn0)/4+static_cast<int32_t>(10));
             }
             index += sb1_size;
             for (int32_t j = 0; j < static_cast<int32_t>(measepoch_channel_type1->n_type2); j++)
             {
                 index += sb2_size;
             }
         }
     }
     // ChannelStatus Processing
     std::vector<int32_t> svid_in_sync_2;
     std::vector<int32_t> elevation_tracked;
     std::vector<int32_t> azimuth_tracked;
     std::vector<int32_t> svid_pvt;
     svid_pvt.clear();
     std::vector<int32_t> ordering;
     {
         uint8_t sb1_size = last_channelstatus_.sb1_size;
         uint8_t sb2_size = last_channelstatus_.sb2_size;
         uint8_t *sb_start = &last_channelstatus_.data[0];
         int32_t index = sb_start - &last_channelstatus_.block_header.sync_1;
         //ROS_DEBUG("index is %i", index); // yields 20, as expected
         uint16_t azimuth_mask = 511;
         for (int32_t i = 0; i < static_cast<int32_t>(last_channelstatus_.n); i++)
         {
             // Define ChannelSatInfo struct for the corresponding sub-block
             ChannelSatInfo *channel_sat_info  =
                 reinterpret_cast<ChannelSatInfo*>(&last_channelstatus_.block_header.sync_1 + index);
             bool to_be_added = false;
             for (int32_t j = 0; j < static_cast<int32_t>(svid_in_sync.size()); ++j)
             {
                 if (svid_in_sync[j] == static_cast<int32_t>(channel_sat_info->sv_id))
                 {
                     ordering.push_back(j);
                     to_be_added = true;
                     break;
                 }
             }
             if (to_be_added)
             {
                 svid_in_sync_2.push_back(static_cast<int32_t>(channel_sat_info->sv_id));
                 elevation_tracked.push_back(static_cast<int32_t>(channel_sat_info->elev));
                 azimuth_tracked.push_back(static_cast<int32_t>((channel_sat_info->az_rise_set & azimuth_mask)));
             }
             index += sb1_size;
             for (int32_t j = 0; j < static_cast<int32_t>(channel_sat_info->n2); j++)
             {
                 // Define ChannelStateInfo struct for the corresponding sub-block
                 ChannelStateInfo *channel_state_info  =
                     reinterpret_cast<ChannelStateInfo*>(&last_channelstatus_.block_header.sync_1 + index);
                 bool pvt_status = false;
                 uint16_t pvt_status_mask = std::pow(2,15)+std::pow(2,14);
                 for(int k = 15; k != -1; k -= 2)
                 {
                     uint16_t pvt_status_value = (channel_state_info->pvt_status & pvt_status_mask) >> k-1;
                     if (pvt_status_value == 2)
                     {
                         pvt_status = true;
                     }
                     if (k > 1)
                     {
                         pvt_status_mask = pvt_status_mask - std::pow(2,k) - std::pow(2,k-1)
                             + std::pow(2,k-2) + std::pow(2,k-3);
                     }
                 }
                 if (pvt_status)
                 {
                     svid_pvt.push_back(static_cast<int32_t>(channel_sat_info->sv_id));
                 }
                 index += sb2_size;
             }
         }
     }
     msg->status.satellite_used_prn = svid_pvt; // Entries such as int32[] in ROS messages are to be treated as std::vectors.
     msg->status.satellites_visible = static_cast<uint16_t>(svid_in_sync.size());
     msg->status.satellite_visible_prn = svid_in_sync_2;
     msg->status.satellite_visible_z = elevation_tracked;
     msg->status.satellite_visible_azimuth = azimuth_tracked;
     // Reordering CNO vector to that of all previous arrays
     std::vector<int32_t> cno_tracked_reordered;
     if (static_cast<int32_t>(last_channelstatus_.n) != 0)
     {
         for (int32_t k = 0; k < static_cast<int32_t>(ordering.size()); ++k)
         {
             cno_tracked_reordered.push_back(cno_tracked[ordering[k]]);
         }
     }
     msg->status.satellite_visible_snr = cno_tracked_reordered;
     // PVT Status Analysis
     uint16_t status_mask = 15; // We extract the first four bits using this mask.
     uint16_t type_of_pvt = ((uint16_t) (last_pvtgeodetic_.mode)) & status_mask;
     switch(type_of_pvt_map[type_of_pvt])
     {
         case evNoPVT:
         {
             msg->status.status = gps_common::GPSStatus::STATUS_NO_FIX;
             break;
         }
         case evStandAlone: case evFixed:
         {
             msg->status.status = gps_common::GPSStatus::STATUS_FIX;
             break;
         }
         case evDGPS: case evRTKFixed: case evRTKFloat: case evMovingBaseRTKFixed: case evMovingBaseRTKFloat: case evPPP:
         {
             msg->status.status = gps_common::GPSStatus::STATUS_GBAS_FIX;
             break;
         }
         case evSBAS:
         {
             uint16_t reference_id = last_pvtgeodetic_.reference_id;
             // Here come the PRNs of the 4 WAAS satellites..
             if (reference_id == 131 || reference_id == 133 || reference_id == 135 || reference_id == 135)
             {
                 msg->status.status = gps_common::GPSStatus::STATUS_WAAS_FIX;
             }
             else
             {
                 msg->status.status = gps_common::GPSStatus::STATUS_SBAS_FIX;
             }
             break;
         }
         default:
         {
             throw std::runtime_error("PVTGeodetic's Mode field contains an invalid type of PVT solution.");
         }
     }
     // Doppler is not used when calculating the velocities of, say, mosaic-x5, hence:
     msg->status.motion_source = gps_common::GPSStatus::SOURCE_POINTS;
     // Doppler is not used when calculating the orientation of, say, mosaic-x5, hence:
     msg->status.orientation_source = gps_common::GPSStatus::SOURCE_POINTS;
     msg->status.position_source = gps_common::GPSStatus::SOURCE_GPS;
     msg->latitude = static_cast<double>(last_pvtgeodetic_.latitude)*360/(2*boost::math::constants::pi<double>());
     msg->longitude = static_cast<double>(last_pvtgeodetic_.longitude)*360/(2*boost::math::constants::pi<double>());
     msg->altitude = static_cast<double>(last_pvtgeodetic_.height);
     // Note that cog is of type float32 while track is of type float64.
     msg->track = static_cast<double>(last_pvtgeodetic_.cog);
     msg->speed = std::sqrt(std::pow(static_cast<double>(last_pvtgeodetic_.vn), 2) +
         std::pow(static_cast<double>(last_pvtgeodetic_.ve), 2));
     msg->climb = static_cast<double>(last_pvtgeodetic_.vu);
     msg->pitch = static_cast<double>(last_atteuler_.pitch);
     msg->roll = static_cast<double>(last_atteuler_.roll);
     if (last_dop_.pdop == static_cast<uint16_t>(0) || last_dop_.tdop == static_cast<uint16_t>(0))
     {
         msg->gdop = static_cast<double>(-1);
     }
     else
     {
         msg->gdop = std::sqrt(std::pow(static_cast<double>(last_dop_.pdop)/100, 2) +
             std::pow(static_cast<double>(last_dop_.tdop)/100, 2));
     }
     if (last_dop_.pdop == static_cast<uint16_t>(0))
     {
         msg->pdop = static_cast<double>(-1);
     }
     else
     {
         msg->pdop = static_cast<double>(last_dop_.pdop)/100;
     }
     if (last_dop_.hdop == static_cast<uint16_t>(0))
     {
         msg->hdop = static_cast<double>(-1);
     }
     else
     {
         msg->hdop = static_cast<double>(last_dop_.hdop)/100;
     }
     if (last_dop_.vdop == static_cast<uint16_t>(0))
     {
         msg->vdop = static_cast<double>(-1);
     }
     else
     {
         msg->vdop = static_cast<double>(last_dop_.vdop)/100;
     }
     if (last_dop_.tdop == static_cast<uint16_t>(0))
     {
         msg->tdop = static_cast<double>(-1);
     }
     else
     {
         msg->tdop = static_cast<double>(last_dop_.tdop)/100;
     }
     msg->time = static_cast<double>(last_pvtgeodetic_.tow)/1000 + static_cast<double>(last_pvtgeodetic_.wnc*7*24*60*60);
     msg->err = 2*(std::sqrt(static_cast<double>(last_poscovgeodetic_.cov_latlat) +
         static_cast<double>(last_poscovgeodetic_.cov_lonlon) + static_cast<double>(last_poscovgeodetic_.cov_hgthgt)));
     msg->err_horz = 2*(std::sqrt(static_cast<double>(last_poscovgeodetic_.cov_latlat) +
         static_cast<double>(last_poscovgeodetic_.cov_lonlon)));
     msg->err_vert = 2*std::sqrt(static_cast<double>(last_poscovgeodetic_.cov_hgthgt));
     msg->err_track = 2*(std::sqrt(std::pow(static_cast<double>(1)/(static_cast<double>(last_pvtgeodetic_.vn) +
         std::pow(static_cast<double>(last_pvtgeodetic_.ve),2)/static_cast<double>(last_pvtgeodetic_.vn)),2)*
         static_cast<double>(last_poscovgeodetic_.cov_lonlon)+std::pow((static_cast<double>(last_pvtgeodetic_.ve))/
         (std::pow(static_cast<double>(last_pvtgeodetic_.vn),2)+std::pow(static_cast<double>(last_pvtgeodetic_.ve),2)),2)*
         static_cast<double>(last_poscovgeodetic_.cov_latlat)));
     msg->err_speed = 2*(std::sqrt(static_cast<double>(last_velcovgeodetic_.cov_vnvn) +
         static_cast<double>(last_velcovgeodetic_.cov_veve)));
     msg->err_climb = 2*std::sqrt(static_cast<double>(last_velcovgeodetic_.cov_vuvu));
     msg->err_time = 2*std::sqrt(static_cast<double>(last_poscovgeodetic_.cov_bb));
     msg->err_pitch = 2*std::sqrt(static_cast<double>(last_attcoveuler_.cov_pitchpitch));
     msg->err_roll = 2*std::sqrt(static_cast<double>(last_attcoveuler_.cov_rollroll));
     msg->position_covariance[0] = static_cast<double>(last_poscovgeodetic_.cov_lonlon);
     msg->position_covariance[1] = static_cast<double>(last_poscovgeodetic_.cov_latlon);
     msg->position_covariance[2] = static_cast<double>(last_poscovgeodetic_.cov_lonhgt);
     msg->position_covariance[3] = static_cast<double>(last_poscovgeodetic_.cov_latlon);
     msg->position_covariance[4] = static_cast<double>(last_poscovgeodetic_.cov_latlat);
     msg->position_covariance[5] = static_cast<double>(last_poscovgeodetic_.cov_lathgt);
     msg->position_covariance[6] = static_cast<double>(last_poscovgeodetic_.cov_lonhgt);
     msg->position_covariance[7] = static_cast<double>(last_poscovgeodetic_.cov_lathgt);
     msg->position_covariance[8] = static_cast<double>(last_poscovgeodetic_.cov_hgthgt);
     msg->position_covariance_type = sensor_msgs::NavSatFix::COVARIANCE_TYPE_KNOWN;
     return msg;
 }
isConnectionDescriptor()
bool io_comm_rx::RxMessage::isConnectionDescriptor ()
Determines whether data_ currently points to a connection descriptor (right after initiating a TCP connection)
Definition at line 991 of file rx_message.cpp.
References CONNECTION_DESCRIPTOR_BYTE_1, CONNECTION_DESCRIPTOR_BYTE_2, count_, and data_.
Referenced by found(), next(), io_comm_rx::CallbackHandlers::readCallback(), RxMessage(), and search().
 {
     if (count_ >= 2)
     {
         if (data_[0] == CONNECTION_DESCRIPTOR_BYTE_1 && data_[1] == CONNECTION_DESCRIPTOR_BYTE_2)
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
isErrorMessage()
bool io_comm_rx::RxMessage::isErrorMessage ()
Determines whether data_ currently points to an error message reply from the Rx.
Definition at line 1010 of file rx_message.cpp.
References count_, data_, RESPONSE_SYNC_BYTE_1, RESPONSE_SYNC_BYTE_2, and RESPONSE_SYNC_BYTE_3.
Referenced by io_comm_rx::CallbackHandlers::readCallback(), and RxMessage().
 {
     if (count_ >= 3)
     {
         if (data_[0] == RESPONSE_SYNC_BYTE_1 && data_[1] == RESPONSE_SYNC_BYTE_2 && data_[2] == RESPONSE_SYNC_BYTE_3)
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
isMessage() [1/2]
bool io_comm_rx::RxMessage::isMessage (const uint16_t ID)
Determines whether data_ points to the SBF block with ID "ID", e.g. 5003.
Definition at line 886 of file rx_message.cpp.
References data_, and isSBF().
Referenced by RxMessage().
 {
     if (this->isSBF())
     {
         uint16_t mask = 8191;
         if (*(reinterpret_cast<const uint16_t *>(data_ + 4)) & mask == static_cast<const uint16_t>(id))
         // Caution: reinterpret_cast is the most dangerous cast. It's used primarily for particularly
         // weird conversions and bit manipulations, like turning a raw data stream into actual data.
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
isMessage() [2/2]
bool io_comm_rx::RxMessage::isMessage (std::string ID)
Determines whether data_ points to the NMEA message with ID "ID", e.g. "$GPGGA".
Definition at line 909 of file rx_message.cpp.
References data_, isNMEA(), and messageSize().
 {
     if (this->isNMEA())
     {
         boost::char_separator<char> sep(",");
         typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
         std::size_t nmea_size = this->messageSize();
         std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
         tokenizer tokens(block_in_string,sep);
         if (*tokens.begin() == id)
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
isNMEA()
bool io_comm_rx::RxMessage::isNMEA ()
Determines whether data_ currently points to an NMEA message.
Definition at line 952 of file rx_message.cpp.
References count_, data_, NMEA_SYNC_BYTE_1, NMEA_SYNC_BYTE_2_1, and NMEA_SYNC_BYTE_2_2.
Referenced by found(), isMessage(), messageID(), next(), io_comm_rx::CallbackHandlers::readCallback(), RxMessage(), and search().
 {
     if (count_ >= 2)
     {
         if ((data_[0] == NMEA_SYNC_BYTE_1 && data_[1] == NMEA_SYNC_BYTE_2_1) || (data_[0] == NMEA_SYNC_BYTE_1
             && data_[1] == NMEA_SYNC_BYTE_2_2))
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
isResponse()
bool io_comm_rx::RxMessage::isResponse ()
Determines whether data_ currently points to an NMEA message.
Definition at line 972 of file rx_message.cpp.
References count_, data_, RESPONSE_SYNC_BYTE_1, and RESPONSE_SYNC_BYTE_2.
Referenced by found(), messageSize(), next(), io_comm_rx::CallbackHandlers::readCallback(), RxMessage(), and search().
 {
     if (count_ >= 2)
     {
         if (data_[0] == RESPONSE_SYNC_BYTE_1 && data_[1] == RESPONSE_SYNC_BYTE_2)
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
isSBF()
bool io_comm_rx::RxMessage::isSBF ()
Determines whether data_ currently points to an SBF block.
Definition at line 933 of file rx_message.cpp.
References count_, data_, SBF_SYNC_BYTE_1, and SBF_SYNC_BYTE_2.
Referenced by found(), getBlockLength(), isMessage(), messageID(), next(), read(), io_comm_rx::CallbackHandlers::readCallback(), RxMessage(), and search().
 {
     if (count_ >= 2)
     {
         if (data_[0] == SBF_SYNC_BYTE_1 && data_[1] == SBF_SYNC_BYTE_2)
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
messageID()
std::string io_comm_rx::RxMessage::messageID ()
Returns the message ID of the message where data_ is pointing at at the moment, SBF identifiers embellished with inverted commas, e.g. "5003"
Definition at line 1029 of file rx_message.cpp.
References data_, isNMEA(), isSBF(), and messageSize().
Referenced by io_comm_rx::CallbackHandler< T >::handle(), io_comm_rx::CallbackHandlers::handle(), read(), io_comm_rx::CallbackHandlers::readCallback(), and RxMessage().
 {
     if (this->isSBF())
     {
         // Defines bit mask..
         // It is not as stated in the firmware: !first! three bits are for revision (not last 3), and rest for block number
         uint16_t mask = 8191;
         // Bitwise AND gives us all but first 3 bits set to zero, rest unchanged
         uint16_t value = (*(reinterpret_cast<const uint16_t*>(data_+4))) & mask;
         std::stringstream ss;
         ss << value;
         return ss.str();
     }
     if (this->isNMEA())
     {
         boost::char_separator<char> sep(",");
         typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
         std::size_t nmea_size = this->messageSize();
         std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
         tokenizer tokens(block_in_string,sep);
         return *tokens.begin();
     }
     return std::string(); // less CPU work than return "";
 }
messageSize()
std::size_t io_comm_rx::RxMessage::messageSize ()
Determines size of the message (also command reply) that data_ is currently pointing at.
Definition at line 852 of file rx_message.cpp.
References CARRIAGE_RETURN, count_, data_, isResponse(), LINE_FEED, and message_size_.
Referenced by isMessage(), messageID(), read(), io_comm_rx::CallbackHandlers::readCallback(), and RxMessage().
 {
     uint16_t pos = 0;
     message_size_ = 0;
     std::size_t count_copy = count_;
     if (this->isResponse())
     {
         do
         {
             ++message_size_;
             ++pos;
             --count_copy;
             if (count_copy == 0) break;
         } while(!((data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED)) ||
             (data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED && data_[pos+2] == 0x20
             && data_[pos+3] == 0x20 && data_[pos+4] == 0x4E) || (data_[pos] == CARRIAGE_RETURN &&
             data_[pos+1] == LINE_FEED && data_[pos+2] == 0x20 && data_[pos+3] == 0x20 && data_[pos+4] == 0x53) ||
             (data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED && data_[pos+2] == 0x20 && data_[pos+3] == 0x20
             && data_[pos+4] == 0x52));
     }
     else
     {
         do
         {
             ++message_size_;
             ++pos;
             --count_copy;
             if (count_copy == 0) break;
         } while(!((data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED) || data_[pos] == CARRIAGE_RETURN
             || data_[pos] == LINE_FEED));
     }
     return message_size_;
 }
NavSatFixCallback()
sensor_msgs::NavSatFixPtr io_comm_rx::RxMessage::NavSatFixCallback () private
"Callback" function when constructing NavSatFix messages
Returns
A smart pointer to the ROS message NavSatFix just created
The position_covariance array is populated in row-major order, where the basis of the corresponding matrix is ENU (so Cov_lonlon is in location 11 of the matrix). The B2b signal type of BeiDou is not checked for usage, since the SignalInfo field of the PVTGeodetic block does not disclose it. For that, one would need to go to the ObsInfo field of the MeasEpochChannelType1 sub-block.
Definition at line 430 of file rx_message.cpp.
References PosCovGeodetic::cov_hgthgt, PosCovGeodetic::cov_lathgt, PosCovGeodetic::cov_latlat, PosCovGeodetic::cov_latlon, PosCovGeodetic::cov_lonhgt, PosCovGeodetic::cov_lonlon, evDGPS, evFixed, evMovingBaseRTKFixed, evMovingBaseRTKFloat, evNoPVT, evPPP, evRTKFixed, evRTKFloat, evSBAS, evStandAlone, PVTGeodetic::height, last_poscovgeodetic_, last_pvtgeodetic_, PVTGeodetic::latitude, PVTGeodetic::longitude, PVTGeodetic::mode, PVTGeodetic::signal_info, and type_of_pvt_map.
Referenced by read().
 {
     sensor_msgs::NavSatFixPtr msg = boost::make_shared<sensor_msgs::NavSatFix>();
     uint16_t mask = 15; // We extract the first four bits using this mask.
     uint16_t type_of_pvt = ((uint16_t) (last_pvtgeodetic_.mode)) & mask;
     switch(type_of_pvt_map[type_of_pvt])
     {
         case evNoPVT:
         {
             msg->status.status = sensor_msgs::NavSatStatus::STATUS_NO_FIX;
             break;
         }
         case evStandAlone: case evFixed:
         {
             msg->status.status = sensor_msgs::NavSatStatus::STATUS_FIX;
             break;
         }
         case evDGPS: case evRTKFixed: case evRTKFloat: case evMovingBaseRTKFixed: case evMovingBaseRTKFloat: case evPPP:
         {
             msg->status.status = sensor_msgs::NavSatStatus::STATUS_GBAS_FIX;
             break;
         }
         case evSBAS:
         {
             msg->status.status = sensor_msgs::NavSatStatus::STATUS_SBAS_FIX;
             break;
         }
         default:
         {
             throw std::runtime_error("PVTGeodetic's Mode field contains an invalid type of PVT solution.");
         }
     }
     bool gps_in_pvt = false;
     bool glo_in_pvt = false;
     bool com_in_pvt = false;
     bool gal_in_pvt = false;
     uint32_t mask_2 = 1;
     for(int bit = 0; bit != 31; ++bit)
     {
         bool in_use = last_pvtgeodetic_.signal_info & mask_2;
         if (bit <= 5 && in_use)
         {
             gps_in_pvt = true;
         }
         if (8   <= bit && bit <= 12 && in_use) glo_in_pvt = true;
         if (((13 <= bit && bit <= 14) || (28 <= bit && bit <= 30)) && in_use) com_in_pvt = true;
         if ((bit == 17 || (19 <= bit && bit <= 22)) && in_use) gal_in_pvt = true;
         mask_2 *= 2;
     }
     // Below, booleans will be promoted to integers automatically.
     uint16_t service = gps_in_pvt*1+glo_in_pvt*2+com_in_pvt*4+gal_in_pvt*8;
     msg->status.service = service;
     msg->latitude = last_pvtgeodetic_.latitude*360/(2*boost::math::constants::pi<double>());
     msg->longitude = last_pvtgeodetic_.longitude*360/(2*boost::math::constants::pi<double>());
     msg->altitude = last_pvtgeodetic_.height;
     msg->position_covariance[0] = static_cast<double>(last_poscovgeodetic_.cov_lonlon);
     msg->position_covariance[1] = static_cast<double>(last_poscovgeodetic_.cov_latlon);
     msg->position_covariance[2] = static_cast<double>(last_poscovgeodetic_.cov_lonhgt);
     msg->position_covariance[3] = static_cast<double>(last_poscovgeodetic_.cov_latlon);
     msg->position_covariance[4] = static_cast<double>(last_poscovgeodetic_.cov_latlat);
     msg->position_covariance[5] = static_cast<double>(last_poscovgeodetic_.cov_lathgt);
     msg->position_covariance[6] = static_cast<double>(last_poscovgeodetic_.cov_lonhgt);
     msg->position_covariance[7] = static_cast<double>(last_poscovgeodetic_.cov_lathgt);
     msg->position_covariance[8] = static_cast<double>(last_poscovgeodetic_.cov_hgthgt);
     msg->position_covariance_type = sensor_msgs::NavSatFix::COVARIANCE_TYPE_KNOWN;
     return msg;
 }
next()
void io_comm_rx::RxMessage::next ()
Goes to the start of the next message based on the calculated length of current message.
This method won't make data_ jump to the next message if the current one is an NMEA message or a command reply. In that case, search() will check the bytes one by one for the new message's sync bytes ($P, $G or $R).
Definition at line 1086 of file rx_message.cpp.
References count_, crc_check_, data_, found(), found_, g_cd_count, g_read_cd, getBlockLength(), isConnectionDescriptor(), isNMEA(), isResponse(), and isSBF().
Referenced by getCount(), and search().
 {
     std::size_t jump_size;
     if (found())
     {
         if (this->isNMEA() || this->isResponse() || (g_read_cd && this->isConnectionDescriptor()))
         {
             if (g_read_cd && this->isConnectionDescriptor() && g_cd_count == 2)
             {
                 g_read_cd = false;
             }
             jump_size = static_cast<uint32_t>(1);
         }
         if (this->isSBF())
         {
             if (crc_check_)
             {
                 jump_size = static_cast<std::size_t>(this->getBlockLength());
                 // Some corrupted messages that survive the CRC check (this happened) could tell ROSaic their size is 0,
                 // which would lead to an endless while loop in the ReadCallback() method of the CallbackHandlers class.
                 if (jump_size == 0) jump_size = static_cast<std::size_t>(1);
             }
             else
             {
                 jump_size = static_cast<std::size_t>(1);
             }
         }
     }
     found_ = false;
     data_ += jump_size; count_ -= jump_size;
     //ROS_DEBUG("Jump about to happen with jump size %li and count after jump being %li.", jump_size, count_);
     return; // For readability
 }
PosCovCartesianCallback()
septentrio_gnss_driver::PosCovCartesianPtr io_comm_rx::RxMessage::PosCovCartesianCallback (PosCovCartesian & data) private
Callback function when reading PosCovCartesian blocks.
Parameters
[in] data The (packed and aligned) struct instance used to populate the ROS message PosCovCartesian
Returns
A smart pointer to the ROS message PosCovCartesian just created
Definition at line 179 of file rx_message.cpp.
References PosCovCartesian::block_header, PosCovCartesian::cov_bb, PosCovCartesian::cov_xb, PosCovCartesian::cov_xx, PosCovCartesian::cov_xy, PosCovCartesian::cov_xz, PosCovCartesian::cov_yb, PosCovCartesian::cov_yy, PosCovCartesian::cov_yz, PosCovCartesian::cov_zb, PosCovCartesian::cov_zz, BlockHeader_t::crc, PosCovCartesian::error, BlockHeader_t::id, BlockHeader_t::length, PosCovCartesian::mode, BlockHeader_t::sync_1, BlockHeader_t::sync_2, PosCovCartesian::tow, and PosCovCartesian::wnc.
Referenced by read().
 {
     septentrio_gnss_driver::PosCovCartesianPtr msg = boost::make_shared<septentrio_gnss_driver::PosCovCartesian>();
     msg->block_header.sync_1 = data.block_header.sync_1;
     msg->block_header.sync_2 = data.block_header.sync_2;
     msg->block_header.crc = data.block_header.crc;
     msg->block_header.id = data.block_header.id;
     msg->block_header.length = data.block_header.length;
     msg->block_header.tow = data.tow;
     msg->block_header.wnc = data.wnc;
     msg->mode = data.mode;
     msg->error = data.error;
     msg->cov_xx = data.cov_xx;
     msg->cov_yy = data.cov_yy;
     msg->cov_zz = data.cov_zz;
     msg->cov_bb = data.cov_bb;
     msg->cov_xy = data.cov_xy;
     msg->cov_xz = data.cov_xz;
     msg->cov_xb = data.cov_xb;
     msg->cov_yz = data.cov_yz;
     msg->cov_yb = data.cov_yb;
     msg->cov_zb = data.cov_zb;
     return msg;
 }
PosCovGeodeticCallback()
septentrio_gnss_driver::PosCovGeodeticPtr io_comm_rx::RxMessage::PosCovGeodeticCallback (PosCovGeodetic & data) private
Callback function when reading PosCovGeodetic blocks.
Parameters
[in] data The (packed and aligned) struct instance used to populate the ROS message PosCovGeodetic
Returns
A smart pointer to the ROS message PosCovGeodetic just created
Definition at line 205 of file rx_message.cpp.
References PosCovGeodetic::block_header, PosCovGeodetic::cov_bb, PosCovGeodetic::cov_hb, PosCovGeodetic::cov_hgthgt, PosCovGeodetic::cov_latb, PosCovGeodetic::cov_lathgt, PosCovGeodetic::cov_latlat, PosCovGeodetic::cov_latlon, PosCovGeodetic::cov_lonb, PosCovGeodetic::cov_lonhgt, PosCovGeodetic::cov_lonlon, BlockHeader_t::crc, PosCovGeodetic::error, BlockHeader_t::id, BlockHeader_t::length, PosCovGeodetic::mode, BlockHeader_t::sync_1, BlockHeader_t::sync_2, PosCovGeodetic::tow, and PosCovGeodetic::wnc.
Referenced by read().
 {
     septentrio_gnss_driver::PosCovGeodeticPtr msg = boost::make_shared<septentrio_gnss_driver::PosCovGeodetic>();
     msg->block_header.sync_1 = data.block_header.sync_1;
     msg->block_header.sync_2 = data.block_header.sync_2;
     msg->block_header.crc = data.block_header.crc;
     msg->block_header.id = data.block_header.id;
     msg->block_header.length = data.block_header.length;
     msg->block_header.tow = data.tow;
     msg->block_header.wnc = data.wnc;
     msg->mode = data.mode;
     msg->error = data.error;
     msg->cov_latlat = data.cov_latlat;
     msg->cov_lonlon = data.cov_lonlon;
     msg->cov_hgthgt = data.cov_hgthgt;
     msg->cov_bb = data.cov_bb;
     msg->cov_latlon = data.cov_latlon;
     msg->cov_lathgt = data.cov_lathgt;
     msg->cov_latb = data.cov_latb;
     msg->cov_lonhgt = data.cov_lonhgt;
     msg->cov_lonb = data.cov_lonb;
     msg->cov_hb = data.cov_hb;
     return msg;
 }
PoseWithCovarianceStampedCallback()
geometry_msgs::PoseWithCovarianceStampedPtr io_comm_rx::RxMessage::PoseWithCovarianceStampedCallback () private
"Callback" function when constructing PoseWithCovarianceStamped messages
Returns
A smart pointer to the ROS message PoseWithCovarianceStamped just created
The position_covariance array is populated in row-major order, where the basis of the correspond matrix is (E, N, U, Roll, Pitch, Heading). Important: The Euler angles (Roll, Pitch, Heading) are with respect to a vehicle-fixed (e.g. for mosaic-x5 in moving base mode via the command setAntennaLocation, ...) !local! NED frame. Thus the orientation is !not! given with respect to the same frame as the position is given in. The cross-covariances are hence (apart from the fact that e.g. mosaic receivers do not calculate these quantities) set to zero. The position and the partial (with 2 antennas) or full (for INS receivers) orientation have covariances matrices available e.g. in the PosCovGeodetic or AttCovEuler blocks, yet those are separate computations.
Definition at line 282 of file rx_message.cpp.
References parsing_utilities::convertEulerToQuaternion(), AttCovEuler::cov_headhead, AttCovEuler::cov_headpitch, AttCovEuler::cov_headroll, PosCovGeodetic::cov_hgthgt, PosCovGeodetic::cov_lathgt, PosCovGeodetic::cov_latlat, PosCovGeodetic::cov_latlon, PosCovGeodetic::cov_lonhgt, PosCovGeodetic::cov_lonlon, AttCovEuler::cov_pitchpitch, AttCovEuler::cov_pitchroll, AttCovEuler::cov_rollroll, AttEuler::heading, PVTGeodetic::height, last_attcoveuler_, last_atteuler_, last_poscovgeodetic_, last_pvtgeodetic_, PVTGeodetic::latitude, PVTGeodetic::longitude, AttEuler::pitch, and AttEuler::roll.
Referenced by read().
 {
     geometry_msgs::PoseWithCovarianceStampedPtr msg = boost::make_shared<geometry_msgs::PoseWithCovarianceStamped>();
     // Filling in the pose data
     msg->pose.pose.orientation = parsing_utilities::convertEulerToQuaternion(static_cast<double>(last_atteuler_.heading),
         static_cast<double>(last_atteuler_.pitch), static_cast<double>(last_atteuler_.roll));
     msg->pose.pose.position.x = static_cast<double>(last_pvtgeodetic_.longitude)*360/(2*boost::math::constants::pi<double>());
     msg->pose.pose.position.y = static_cast<double>(last_pvtgeodetic_.latitude)*360/(2*boost::math::constants::pi<double>());
     msg->pose.pose.position.z = static_cast<double>(last_pvtgeodetic_.height);
     // Filling in the covariance data in row-major order
     msg->pose.covariance[0] = static_cast<double>(last_poscovgeodetic_.cov_lonlon);
     msg->pose.covariance[1] = static_cast<double>(last_poscovgeodetic_.cov_latlon);
     msg->pose.covariance[2] = static_cast<double>(last_poscovgeodetic_.cov_lonhgt);
     msg->pose.covariance[3] = 0;
     msg->pose.covariance[4] = 0;
     msg->pose.covariance[5] = 0;
     msg->pose.covariance[6] = static_cast<double>(last_poscovgeodetic_.cov_latlon);
     msg->pose.covariance[7] = static_cast<double>(last_poscovgeodetic_.cov_latlat);
     msg->pose.covariance[8] = static_cast<double>(last_poscovgeodetic_.cov_lathgt);
     msg->pose.covariance[9] = 0;
     msg->pose.covariance[10] = 0;
     msg->pose.covariance[11] = 0;
     msg->pose.covariance[12] = static_cast<double>(last_poscovgeodetic_.cov_lonhgt);
     msg->pose.covariance[13] = static_cast<double>(last_poscovgeodetic_.cov_lathgt);
     msg->pose.covariance[14] = static_cast<double>(last_poscovgeodetic_.cov_hgthgt);
     msg->pose.covariance[15] = 0;
     msg->pose.covariance[16] = 0;
     msg->pose.covariance[17] = 0;
     msg->pose.covariance[18] = 0;
     msg->pose.covariance[19] = 0;
     msg->pose.covariance[20] = 0;
     msg->pose.covariance[21] = static_cast<double>(last_attcoveuler_.cov_rollroll);
     msg->pose.covariance[22] = static_cast<double>(last_attcoveuler_.cov_pitchroll);
     msg->pose.covariance[23] = static_cast<double>(last_attcoveuler_.cov_headroll);
     msg->pose.covariance[24] = 0;
     msg->pose.covariance[25] = 0;
     msg->pose.covariance[26] = 0;
     msg->pose.covariance[27] = static_cast<double>(last_attcoveuler_.cov_pitchroll);
     msg->pose.covariance[28] = static_cast<double>(last_attcoveuler_.cov_pitchpitch);
     msg->pose.covariance[29] = static_cast<double>(last_attcoveuler_.cov_headpitch);
     msg->pose.covariance[30] = 0;
     msg->pose.covariance[31] = 0;
     msg->pose.covariance[32] = 0;
     msg->pose.covariance[33] = static_cast<double>(last_attcoveuler_.cov_headroll);
     msg->pose.covariance[34] = static_cast<double>(last_attcoveuler_.cov_pitchroll);
     msg->pose.covariance[35] = static_cast<double>(last_attcoveuler_.cov_headhead);
     return msg;
 }
PVTCartesianCallback()
septentrio_gnss_driver::PVTCartesianPtr io_comm_rx::RxMessage::PVTCartesianCallback (PVTCartesian & data) private
Callback function when reading PVTCartesian blocks.
Parameters
[in] data The (packed and aligned) struct instance used to populate the ROS message PVTCartesian
Returns
A smart pointer to the ROS message PVTCartesian just created
Definition at line 140 of file rx_message.cpp.
References PVTCartesian::alert_flag, PVTCartesian::block_header, PVTCartesian::cog, BlockHeader_t::crc, PVTCartesian::datum, PVTCartesian::error, PVTCartesian::h_accuracy, BlockHeader_t::id, PVTCartesian::latency, BlockHeader_t::length, PVTCartesian::mean_corr_age, PVTCartesian::misc, PVTCartesian::mode, PVTCartesian::nr_bases, PVTCartesian::nr_sv, PVTCartesian::ppp_info, PVTCartesian::reference_id, PVTCartesian::rx_clk_bias, PVTCartesian::rx_clk_drift, PVTCartesian::signal_info, BlockHeader_t::sync_1, BlockHeader_t::sync_2, PVTCartesian::time_system, PVTCartesian::tow, PVTCartesian::undulation, PVTCartesian::v_accuracy, PVTCartesian::vx, PVTCartesian::vy, PVTCartesian::vz, PVTCartesian::wa_corr_info, PVTCartesian::wnc, PVTCartesian::x, PVTCartesian::y, and PVTCartesian::z.
Referenced by read().
 {
     septentrio_gnss_driver::PVTCartesianPtr msg = boost::make_shared<septentrio_gnss_driver::PVTCartesian>();
     msg->block_header.sync_1 = data.block_header.sync_1;
     msg->block_header.sync_2 = data.block_header.sync_2;
     msg->block_header.crc = data.block_header.crc;
     msg->block_header.id = data.block_header.id;
     msg->block_header.length = data.block_header.length;
     msg->block_header.tow = data.tow;
     msg->block_header.wnc = data.wnc;
     msg->mode = data.mode;
     msg->error = data.error;
     msg->x = data.x;
     msg->y = data.y;
     msg->z = data.z;
     msg->undulation = data.undulation;
     msg->vx = data.vx;
     msg->vy = data.vy;
     msg->vz = data.vz;
     msg->cog = data.cog;
     msg->rx_clk_bias = data.rx_clk_bias;
     msg->rx_clk_drift = data.rx_clk_drift;
     msg->time_system = data.time_system;
     msg->datum = data.datum;
     msg->nr_sv = data.nr_sv;
     msg->wa_corr_info = data.wa_corr_info;
     msg->reference_id = data.reference_id;
     msg->mean_corr_age = data.mean_corr_age;
     msg->signal_info = data.signal_info;
     msg->alert_flag = data.alert_flag;
     msg->nr_bases = data.nr_bases;
     msg->ppp_info = data.ppp_info;
     msg->latency = data.latency;
     msg->h_accuracy = data.h_accuracy;
     msg->v_accuracy = data.v_accuracy;
     msg->misc = data.misc;
     return msg;
 }
PVTGeodeticCallback()
septentrio_gnss_driver::PVTGeodeticPtr io_comm_rx::RxMessage::PVTGeodeticCallback (PVTGeodetic & data) private
Callback function when reading PVTGeodetic blocks.
Parameters
[in] data The (packed and aligned) struct instance used to populate the ROS message PVTGeodetic
Returns
A smart pointer to the ROS message PVTGeodetic just created
Definition at line 100 of file rx_message.cpp.
References PVTGeodetic::alert_flag, PVTGeodetic::block_header, PVTGeodetic::cog, BlockHeader_t::crc, PVTGeodetic::datum, PVTGeodetic::error, PVTGeodetic::h_accuracy, PVTGeodetic::height, BlockHeader_t::id, PVTGeodetic::latency, PVTGeodetic::latitude, BlockHeader_t::length, PVTGeodetic::longitude, PVTGeodetic::mean_corr_age, PVTGeodetic::misc, PVTGeodetic::mode, PVTGeodetic::nr_bases, PVTGeodetic::nr_sv, PVTGeodetic::ppp_info, PVTGeodetic::reference_id, PVTGeodetic::rx_clk_bias, PVTGeodetic::rx_clk_drift, PVTGeodetic::signal_info, BlockHeader_t::sync_1, BlockHeader_t::sync_2, PVTGeodetic::time_system, PVTGeodetic::tow, PVTGeodetic::undulation, PVTGeodetic::v_accuracy, PVTGeodetic::ve, PVTGeodetic::vn, PVTGeodetic::vu, PVTGeodetic::wa_corr_info, and PVTGeodetic::wnc.
Referenced by read().
 {
     septentrio_gnss_driver::PVTGeodeticPtr msg = boost::make_shared<septentrio_gnss_driver::PVTGeodetic>();
     msg->block_header.sync_1 = data.block_header.sync_1;
     msg->block_header.sync_2 = data.block_header.sync_2;
     msg->block_header.crc = data.block_header.crc;
     msg->block_header.id = data.block_header.id;
     msg->block_header.length = data.block_header.length;
     msg->block_header.tow = data.tow;
     msg->block_header.wnc = data.wnc;
     msg->mode = data.mode;
     msg->error = data.error;
     msg->latitude = data.latitude;
     msg->longitude = data.longitude;
     msg->height = data.height;
     msg->undulation = data.undulation;
     msg->vn = data.vn;
     msg->ve = data.ve;
     msg->vu = data.vu;
     msg->cog = data.cog;
     msg->rx_clk_bias = data.rx_clk_bias;
     msg->rx_clk_drift = data.rx_clk_drift;
     msg->time_system = data.time_system;
     msg->datum = data.datum;
     msg->nr_sv = data.nr_sv;
     msg->wa_corr_info = data.wa_corr_info;
     msg->reference_id = data.reference_id;
     msg->mean_corr_age = data.mean_corr_age;
     msg->signal_info = data.signal_info;
     msg->alert_flag = data.alert_flag;
     msg->nr_bases = data.nr_bases;
     msg->ppp_info = data.ppp_info;
     msg->latency = data.latency;
     msg->h_accuracy = data.h_accuracy;
     msg->v_accuracy = data.v_accuracy;
     msg->misc = data.misc;
     return msg;
 }
read()
template<typename T > bool io_comm_rx::RxMessage::read (typename boost::call_traits< T >::reference message, std::string message_key, bool search = false)
Performs the CRC check (if SBF) and populates ROS message "message" with the necessary content.
Returns
True if read was successful, false otherwise
Note that the boost::call_traits<T>::reference is more robust than the traditional T&. Note that this function can also deal with the appropriate !derived! parser in case T is an NMEA message. Note that putting the default in the definition's argument list instead of the declaration's is an added extra that is not available for function templates, hence no search = false here. Also note that it is bad practice (one gets undefined reference to .. error) to separate the definition of template functions into the source file and declarations into header file. Also note that the SBF block header part of the SBF-echoing ROS messages have ID fields that only show the block number as found in the firmware (e.g. 4007 for PVTGeodetic), without the revision number. NMEA 0183 messages are at most 82 characters long in principle, but most Septentrio Rxs by default increase precision on lat/lon s.t. the maximum allowed e.g. for GGA seems to be 89 on a mosaic-x5. Luckily, when parsing we do not care since we just search for <LF><CR>.
Definition at line 477 of file rx_message.hpp.
References AttCovEulerCallback(), AttEulerCallback(), count_gpsfix_, crc_check_, data_, DiagnosticArrayCallback(), evAttCovEuler, evAttEuler, evChannelStatus, evDiagnosticArray, evDOP, evGAGSV, evGLGSV, evGPGGA, evGPGSA, evGPGSV, evGPRMC, evGPSFix, evGPST, evMeasEpoch, evNavSatFix, evPosCovCartesian, evPosCovGeodetic, evPoseWithCovarianceStamped, evPVTCartesian, evPVTGeodetic, evQualityInd, evReceiverSetup, evReceiverStatus, evVelCovGeodetic, found(), g_attcoveuler_has_arrived_gpsfix, g_attcoveuler_has_arrived_pose, g_atteuler_has_arrived_gpsfix, g_atteuler_has_arrived_pose, g_channelstatus_has_arrived_gpsfix, g_dop_has_arrived_gpsfix, g_frame_id, g_measepoch_has_arrived_gpsfix, g_nh, g_poscovgeodetic_has_arrived_gpsfix, g_poscovgeodetic_has_arrived_navsatfix, g_poscovgeodetic_has_arrived_pose, g_pvtgeodetic_has_arrived_gpsfix, g_pvtgeodetic_has_arrived_navsatfix, g_pvtgeodetic_has_arrived_pose, g_qualityind_has_arrived_diagnostics, g_receiverstatus_has_arrived_diagnostics, g_ROS_QUEUE_SIZE, g_use_gnss_time, g_velcovgeodetic_has_arrived_gpsfix, GPSFixCallback(), isSBF(), isValid(), last_attcoveuler_, last_atteuler_, last_channelstatus_, last_dop_, last_measepoch_, last_poscovgeodetic_, last_pvtgeodetic_, last_qualityind_, last_receiversetup_, last_receiverstatus_, last_velcovgeodetic_, messageID(), messageSize(), NavSatFixCallback(), GpgsaParser::parseASCII(), GpgsvParser::parseASCII(), GpggaParser::parseASCII(), GprmcParser::parseASCII(), PosCovCartesianCallback(), PosCovGeodeticCallback(), PoseWithCovarianceStampedCallback(), PVTCartesianCallback(), PVTGeodeticCallback(), rx_id_map, search(), io_comm_rx::timestampSBF(), and PVTGeodetic::tow.
Referenced by getCount(), and io_comm_rx::CallbackHandler< T >::handle().
     {
         if (search) this->search();
         if (!found()) return false;
         if (this->isSBF())
         {
             // If the CRC check is unsuccessful, throw an error message.
             crc_check_ = isValid(data_);
             if (!crc_check_)
             {
                 throw std::runtime_error("CRC Check returned False. Not a valid data block, perhaps noisy. Ignore..");
             }
         }
         switch(rx_id_map[message_key])
         {
             case evPVTCartesian: // Position and velocity in XYZ
             {   // The curly bracket here is crucial: Declarations inside a block remain inside, and will die at
                 // the end of the block. Otherwise variable overloading etc.
                 septentrio_gnss_driver::PVTCartesianPtr msg = boost::make_shared<septentrio_gnss_driver::PVTCartesian>();
                 PVTCartesian pvtcartesian;
                 memcpy(&pvtcartesian, data_, sizeof(pvtcartesian));
                 msg = PVTCartesianCallback(pvtcartesian);
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->block_header.id = 4006;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::PVTCartesian>("/pvtcartesian", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evPVTGeodetic: // Position and velocity in geodetic coordinate frame (ENU frame)
             {
                 septentrio_gnss_driver::PVTGeodeticPtr msg = boost::make_shared<septentrio_gnss_driver::PVTGeodetic>();
                 memcpy(&last_pvtgeodetic_, data_, sizeof(last_pvtgeodetic_));
                 msg = PVTGeodeticCallback(last_pvtgeodetic_);
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->block_header.id = 4007;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 g_pvtgeodetic_has_arrived_gpsfix = true;
                 g_pvtgeodetic_has_arrived_navsatfix = true;
                 g_pvtgeodetic_has_arrived_pose = true;
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::PVTGeodetic>("/pvtgeodetic", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evPosCovCartesian:
             {
                 septentrio_gnss_driver::PosCovCartesianPtr msg = boost::make_shared<septentrio_gnss_driver::PosCovCartesian>();
                 PosCovCartesian poscovcartesian;
                 memcpy(&poscovcartesian, data_, sizeof(poscovcartesian));
                 msg = PosCovCartesianCallback(poscovcartesian);
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->block_header.id = 5905;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::PosCovCartesian>("/poscovcartesian", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evPosCovGeodetic:
             {
                 septentrio_gnss_driver::PosCovGeodeticPtr msg = boost::make_shared<septentrio_gnss_driver::PosCovGeodetic>();
                 memcpy(&last_poscovgeodetic_, data_, sizeof(last_poscovgeodetic_));
                 msg = PosCovGeodeticCallback(last_poscovgeodetic_);
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->block_header.id = 5906;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 g_poscovgeodetic_has_arrived_gpsfix = true;
                 g_poscovgeodetic_has_arrived_navsatfix = true;
                 g_poscovgeodetic_has_arrived_pose = true;
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::PosCovGeodetic>("/poscovgeodetic", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evAttEuler:
             {
                 septentrio_gnss_driver::AttEulerPtr msg = boost::make_shared<septentrio_gnss_driver::AttEuler>();
                 memcpy(&last_atteuler_, data_, sizeof(last_atteuler_));
                 msg = AttEulerCallback(last_atteuler_);
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->block_header.id = 5938;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 g_atteuler_has_arrived_gpsfix = true;
                 g_atteuler_has_arrived_pose = true;
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::AttEuler>("/atteuler", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evAttCovEuler:
             {
                 septentrio_gnss_driver::AttCovEulerPtr msg = boost::make_shared<septentrio_gnss_driver::AttCovEuler>();
                 memcpy(&last_attcoveuler_, data_, sizeof(last_attcoveuler_));
                 msg = AttCovEulerCallback(last_attcoveuler_);
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->block_header.id = 5939;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 g_attcoveuler_has_arrived_gpsfix = true;
                 g_attcoveuler_has_arrived_pose = true;
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::AttCovEuler>("/attcoveuler", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evGPST:
             {
                 sensor_msgs::TimeReferencePtr msg = boost::make_shared<sensor_msgs::TimeReference>();
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, true); // We need the GPS time, hence true
                 msg->time_ref.sec = time_obj.sec;
                 msg->time_ref.nsec = time_obj.nsec;
                 msg->source = "GPST";
                 memcpy(&message, msg.get(), sizeof(*msg));
                 static ros::Publisher publisher = g_nh->advertise<sensor_msgs::TimeReference>("/gpst", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evGPGGA:
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = this->messageSize();
                 std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 std::string id = this->messageID();
                 std::string one_message = *tokens.begin();
                 // No kept delimiters, hence "". Also, we specify that empty tokens should show up in the output
                 // when two delimiters are next to each other.
                 // Hence we also append the checksum part of the GGA message to "body" below, though it is not parsed.
                 boost::char_separator<char> sep_2(",*", "", boost::keep_empty_tokens);
                 tokenizer tokens_2(one_message, sep_2);
                 std::vector<std::string> body;
                 for (tokenizer::iterator tok_iter = tokens_2.begin(); tok_iter != tokens_2.end(); ++tok_iter)
                 {
                     body.push_back(*tok_iter);
                 }
                 // Create NmeaSentence struct to pass to GpggaParser::parseASCII
                 NMEASentence gga_message(id, body);
                 septentrio_gnss_driver::GpggaPtr msg = boost::make_shared<septentrio_gnss_driver::Gpgga>();
                 GpggaParser parser_obj;
                 try
                 {
                     msg = parser_obj.parseASCII(gga_message);
                 }
                 catch (ParseException& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 memcpy(&message, msg.get(), sizeof(*msg));
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::Gpgga>("/gpgga", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evGPRMC:
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = this->messageSize();
                 std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 std::string id = this->messageID();
                 std::string one_message = *tokens.begin();
                 boost::char_separator<char> sep_2(",*", "", boost::keep_empty_tokens);
                 tokenizer tokens_2(one_message, sep_2);
                 std::vector<std::string> body;
                 for (tokenizer::iterator tok_iter = tokens_2.begin(); tok_iter != tokens_2.end(); ++tok_iter)
                 {
                     body.push_back(*tok_iter);
                 }
                 // Create NmeaSentence struct to pass to GprmcParser::parseASCII
                 NMEASentence rmc_message(id, body);
                 septentrio_gnss_driver::GprmcPtr msg = boost::make_shared<septentrio_gnss_driver::Gprmc>();
                 GprmcParser parser_obj;
                 try
                 {
                     msg = parser_obj.parseASCII(rmc_message);
                 }
                 catch (ParseException& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 memcpy(&message, msg.get(), sizeof(*msg));
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::Gprmc>("/gprmc", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evGPGSA:
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = this->messageSize();
                 std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 std::string id = this->messageID();
                 std::string one_message = *tokens.begin();
                 boost::char_separator<char> sep_2(",*", "", boost::keep_empty_tokens);
                 tokenizer tokens_2(one_message, sep_2);
                 std::vector<std::string> body;
                 for (tokenizer::iterator tok_iter = tokens_2.begin(); tok_iter != tokens_2.end(); ++tok_iter)
                 {
                     body.push_back(*tok_iter);
                 }
                 // Create NmeaSentence struct to pass to GpgsaParser::parseASCII
                 NMEASentence gsa_message(id, body);
                 septentrio_gnss_driver::GpgsaPtr msg = boost::make_shared<septentrio_gnss_driver::Gpgsa>();
                 GpgsaParser parser_obj;
                 try
                 {
                     msg = parser_obj.parseASCII(gsa_message);
                 }
                 catch (ParseException& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 uint32_t tow = last_pvtgeodetic_.tow;
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::Gpgsa>("/gpgsa", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evGPGSV: case evGLGSV: case evGAGSV:
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = this->messageSize();
                 std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 std::string id = this->messageID();
                 std::string one_message = *tokens.begin();
                 boost::char_separator<char> sep_2(",*", "", boost::keep_empty_tokens);
                 tokenizer tokens_2(one_message, sep_2);
                 std::vector<std::string> body;
                 for (tokenizer::iterator tok_iter = tokens_2.begin(); tok_iter != tokens_2.end(); ++tok_iter)
                 {
                     body.push_back(*tok_iter);
                 }
                 // Create NmeaSentence struct to pass to GpgsvParser::parseASCII
                 NMEASentence gsv_message(id, body);
                 septentrio_gnss_driver::GpgsvPtr msg = boost::make_shared<septentrio_gnss_driver::Gpgsv>();
                 GpgsvParser parser_obj;
                 try
                 {
                     msg = parser_obj.parseASCII(gsv_message);
                 }
                 catch (ParseException& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 uint32_t tow = last_pvtgeodetic_.tow;
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 static ros::Publisher publisher = g_nh->advertise<septentrio_gnss_driver::Gpgsv>("/gpgsv", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evNavSatFix:
             {
                 sensor_msgs::NavSatFixPtr msg = boost::make_shared<sensor_msgs::NavSatFix>();
                 try
                 {
                     msg = NavSatFixCallback();
                 }
                 catch (std::runtime_error& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 g_pvtgeodetic_has_arrived_navsatfix = false;
                 g_poscovgeodetic_has_arrived_navsatfix = false;
                 static ros::Publisher publisher = g_nh->advertise<sensor_msgs::NavSatFix>("/navsatfix", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evGPSFix:
             {
                 gps_common::GPSFixPtr msg = boost::make_shared<gps_common::GPSFix>();
                 try
                 {
                     msg = GPSFixCallback();
                 }
                 catch (std::runtime_error& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 msg->status.header.seq = count_gpsfix_;
                 msg->header.frame_id = g_frame_id;
                 msg->status.header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->status.header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->status.header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 ++count_gpsfix_;
                 g_channelstatus_has_arrived_gpsfix = false;
                 g_measepoch_has_arrived_gpsfix = false;
                 g_dop_has_arrived_gpsfix = false;
                 g_pvtgeodetic_has_arrived_gpsfix = false;
                 g_poscovgeodetic_has_arrived_gpsfix = false;
                 g_velcovgeodetic_has_arrived_gpsfix = false;
                 g_atteuler_has_arrived_gpsfix = false;
                 g_attcoveuler_has_arrived_gpsfix = false;
                 static ros::Publisher publisher = g_nh->advertise<gps_common::GPSFix>("/gpsfix", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evPoseWithCovarianceStamped:
             {
                 geometry_msgs::PoseWithCovarianceStampedPtr msg = boost::make_shared<geometry_msgs::PoseWithCovarianceStamped>();
                 try
                 {
                     msg = PoseWithCovarianceStampedCallback();
                 }
                 catch (std::runtime_error& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 g_pvtgeodetic_has_arrived_pose = false;
                 g_poscovgeodetic_has_arrived_pose = false;
                 g_atteuler_has_arrived_pose = false;
                 g_attcoveuler_has_arrived_pose = false;
                 static ros::Publisher publisher = g_nh->advertise<geometry_msgs::PoseWithCovarianceStamped>("/pose", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evChannelStatus:
             {
                 memcpy(&last_channelstatus_, data_, sizeof(last_channelstatus_));
                 g_channelstatus_has_arrived_gpsfix = true;
                 break;
             }
             case evMeasEpoch:
             {
                 memcpy(&last_measepoch_, data_, sizeof(last_measepoch_));
                 g_measepoch_has_arrived_gpsfix = true;
                 break;
             }
             case evDOP:
             {
                 memcpy(&last_dop_, data_, sizeof(last_dop_));
                 g_dop_has_arrived_gpsfix = true;
                 break;
             }
             case evVelCovGeodetic:
             {
                 memcpy(&last_velcovgeodetic_, data_, sizeof(last_velcovgeodetic_));
                 g_velcovgeodetic_has_arrived_gpsfix = true;
                 break;
             }
             case evDiagnosticArray:
             {
                 diagnostic_msgs::DiagnosticArrayPtr msg = boost::make_shared<diagnostic_msgs::DiagnosticArray>();
                 try
                 {
                     msg = DiagnosticArrayCallback();
                 }
                 catch (std::runtime_error& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 msg->header.frame_id = g_frame_id;
                 uint32_t tow = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = timestampSBF(tow, g_use_gnss_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 g_receiverstatus_has_arrived_diagnostics = false;
                 g_qualityind_has_arrived_diagnostics = false;
                 static ros::Publisher publisher = g_nh->advertise<diagnostic_msgs::DiagnosticArray>("/diagnostics", g_ROS_QUEUE_SIZE);
                 publisher.publish(*msg);
                 break;
             }
             case evReceiverStatus:
             {
                 memcpy(&last_receiverstatus_, data_, sizeof(last_receiverstatus_));
                 g_receiverstatus_has_arrived_diagnostics = true;
                 break;
             }
             case evQualityInd:
             {
                 memcpy(&last_qualityind_, data_, sizeof(last_qualityind_));
                 g_qualityind_has_arrived_diagnostics = true;
                 break;
             }
             case evReceiverSetup:
             {
                 memcpy(&last_receiversetup_, data_, sizeof(last_receiversetup_));
                 break;
             }
             // Many more to be implemented...
         }
         return true;
     }
search()
const uint8_t * io_comm_rx::RxMessage::search ()
Searches the buffer for the beginning of the next message (NMEA or SBF)
Returns
A pointer to the start of the next message.
Definition at line 834 of file rx_message.cpp.
References count_, data_, found_, g_read_cd, isConnectionDescriptor(), isNMEA(), isResponse(), isSBF(), and next().
Referenced by getCount(), read(), and io_comm_rx::CallbackHandlers::readCallback().
 {
     if (found_)
     {
         next();
     }
     // Search for message or a response header
     for( ; count_ > 0; --count_, ++data_)
     {
         if (this->isSBF() || this->isNMEA() || this->isResponse() || (g_read_cd && this->isConnectionDescriptor()))
         {
             break;
         }
     }
     found_ = true;
     return data_;
 }
Field Documentation
count_
std::size_t io_comm_rx::RxMessage::count_ private
Number of unread bytes in the buffer.
Definition at line 303 of file rx_message.hpp.
Referenced by getCount(), getEndBuffer(), isConnectionDescriptor(), isErrorMessage(), isNMEA(), isResponse(), isSBF(), messageSize(), next(), and search().
count_gpsfix_
uint32_t io_comm_rx::RxMessage::count_gpsfix_ = 0 static private
Number of times the gps_common::GPSFix message has been published.
Definition at line 318 of file rx_message.hpp.
Referenced by read().
crc_check_
bool io_comm_rx::RxMessage::crc_check_ private
Whether the CRC check as evaluated in the read() method was successful or not is stored here.
Definition at line 308 of file rx_message.hpp.
Referenced by next(), read(), and RxMessage().
data_
const uint8_t* io_comm_rx::RxMessage::data_ private
Pointer to the buffer of messages.
Definition at line 298 of file rx_message.hpp.
Referenced by getBlockLength(), getEndBuffer(), getPosBuffer(), isConnectionDescriptor(), isErrorMessage(), isMessage(), isNMEA(), isResponse(), isSBF(), messageID(), messageSize(), next(), read(), and search().
found_
bool io_comm_rx::RxMessage::found_
Whether or not a message has been found.
Definition at line 291 of file rx_message.hpp.
Referenced by found(), next(), RxMessage(), and search().
last_attcoveuler_
AttCovEuler io_comm_rx::RxMessage::last_attcoveuler_ = AttCovEuler() static private
Since GPSFix etc. need AttCovEuler, incoming AttCovEuler blocks need to be stored.
Definition at line 338 of file rx_message.hpp.
Referenced by GPSFixCallback(), PoseWithCovarianceStampedCallback(), and read().
last_atteuler_
AttEuler io_comm_rx::RxMessage::last_atteuler_ = AttEuler() static private
Since GPSFix etc. need AttEuler, incoming AttEuler blocks need to be stored.
Definition at line 333 of file rx_message.hpp.
Referenced by GPSFixCallback(), PoseWithCovarianceStampedCallback(), and read().
last_channelstatus_
ChannelStatus io_comm_rx::RxMessage::last_channelstatus_ = ChannelStatus() static private
Since GPSFix needs ChannelStatus, incoming ChannelStatus blocks need to be stored.
Definition at line 343 of file rx_message.hpp.
Referenced by GPSFixCallback(), and read().
last_dop_
DOP io_comm_rx::RxMessage::last_dop_ = DOP() static private
Since GPSFix needs DOP, incoming DOP blocks need to be stored.
Definition at line 353 of file rx_message.hpp.
Referenced by GPSFixCallback(), and read().
last_measepoch_
MeasEpoch io_comm_rx::RxMessage::last_measepoch_ = MeasEpoch() static private
Since GPSFix needs MeasEpoch (for SNRs), incoming MeasEpoch blocks need to be stored.
Definition at line 348 of file rx_message.hpp.
Referenced by GPSFixCallback(), and read().
last_poscovgeodetic_
PosCovGeodetic io_comm_rx::RxMessage::last_poscovgeodetic_ = PosCovGeodetic() static private
Since NavSatFix etc. need PosCovGeodetic, incoming PosCovGeodetic blocks need to be stored.
Definition at line 328 of file rx_message.hpp.
Referenced by GPSFixCallback(), NavSatFixCallback(), PoseWithCovarianceStampedCallback(), and read().
last_pvtgeodetic_
PVTGeodetic io_comm_rx::RxMessage::last_pvtgeodetic_ = PVTGeodetic() static private
Since NavSatFix etc. need PVTGeodetic, incoming PVTGeodetic blocks need to be stored.
Definition at line 323 of file rx_message.hpp.
Referenced by GPSFixCallback(), NavSatFixCallback(), PoseWithCovarianceStampedCallback(), and read().
last_qualityind_
QualityInd io_comm_rx::RxMessage::last_qualityind_ = QualityInd() static private
Since DiagnosticArray needs QualityInd, incoming QualityInd blocks need to be stored.
Definition at line 368 of file rx_message.hpp.
Referenced by DiagnosticArrayCallback(), and read().
last_receiversetup_
ReceiverSetup io_comm_rx::RxMessage::last_receiversetup_ = ReceiverSetup() static private
Since DiagnosticArray needs ReceiverSetup, incoming ReceiverSetup blocks need to be stored.
Definition at line 373 of file rx_message.hpp.
Referenced by DiagnosticArrayCallback(), and read().
last_receiverstatus_
ReceiverStatus io_comm_rx::RxMessage::last_receiverstatus_ = ReceiverStatus() static private
Since DiagnosticArray needs ReceiverStatus, incoming ReceiverStatus blocks need to be stored.
Definition at line 363 of file rx_message.hpp.
Referenced by DiagnosticArrayCallback(), and read().
last_velcovgeodetic_
VelCovGeodetic io_comm_rx::RxMessage::last_velcovgeodetic_ = VelCovGeodetic() static private
Since GPSFix needs VelCovGeodetic, incoming VelCovGeodetic blocks need to be stored.
Definition at line 358 of file rx_message.hpp.
Referenced by GPSFixCallback(), and read().
message_size_
std::size_t io_comm_rx::RxMessage::message_size_ private
Helps to determine size of response message / NMEA message / SBF block.
Definition at line 313 of file rx_message.hpp.
Referenced by messageSize(), and RxMessage().
rx_id_map
io_comm_rx::RxMessage::RxIDMap io_comm_rx::RxMessage::rx_id_map static private
All instances of the RxMessage class shall have access to the map without reinitializing it, hence static.
This map is for mapping ROS message, SBF and NMEA identifiers to an enumeration and makes the switch-case formalism in rx_message.hpp more explicit.
Definition at line 392 of file rx_message.hpp.
Referenced by read().
type_of_pvt_map
io_comm_rx::RxMessage::TypeOfPVTMap io_comm_rx::RxMessage::type_of_pvt_map static private
All instances of the RxMessage class shall have access to the map without reinitializing it, hence static.
Definition at line 381 of file rx_message.hpp.
Referenced by GPSFixCallback(), and NavSatFixCallback().
The documentation for this class was generated from the following files:
include/septentrio_gnss_driver/communication/rx_message.hpp
src/septentrio_gnss_driver/communication/rx_message.cpp