ROSaic: io_comm_rx::Comm_IO Class Reference
io_comm_rx::Comm_IO Class Reference
Handles communication with and configuration of the mosaic (and beyond) receiver(s)
#include <communication_core.hpp>
Public Member Functions
Comm_IO ()
Default constructor of the class Comm_IO.
virtual ~Comm_IO ()=default
Default destructor of the class Comm_IO.
bool initializeSerial (std::string port, uint32_t baudrate=115200, std::string flowcontrol="None")
Initializes the serial port.
bool initializeTCP (std::string host, std::string port)
Initializes the TCP I/O.
void setManager (const boost::shared_ptr< Manager > &manager)
Set the I/O manager.
void resetSerial (std::string port)
Reset the Serial I/O port, e.g. after a Rx reset.
CallbackHandlers getHandlers () const
void send (std::string cmd)
Data Fields
CallbackHandlers handlers_
Callback handlers for the inwards streaming messages.
Private Attributes
std::string serial_port_
Saves the port description.
boost::shared_ptr< Manager > manager_
uint32_t baudrate_
Baudrate at the moment, unless InitializeSerial or ResetSerial fail.
std::string host_
Host currently connected to.
std::string port_
Port over which TCP/IP connection is currently established.
Static Private Attributes
static const unsigned int SET_BAUDRATE_SLEEP_ = 500000
Friends
class CallbackHandlers
class RxMessage
Detailed Description
Handles communication with and configuration of the mosaic (and beyond) receiver(s)
Definition at line 102 of file communication_core.hpp.
Constructor & Destructor Documentation
Comm_IO()
io_comm_rx::Comm_IO::Comm_IO ()
Default constructor of the class Comm_IO.
Definition at line 39 of file communication_core.cpp.
 : handlers_() {}
~Comm_IO()
virtual io_comm_rx::Comm_IO::~Comm_IO () virtual default
Default destructor of the class Comm_IO.
Member Function Documentation
getHandlers()
CallbackHandlers io_comm_rx::Comm_IO::getHandlers () const inline
Definition at line 147 of file communication_core.hpp.
References handlers_, and send().
Referenced by rosaic_node::ROSaicNode::defineMessages().
 {return handlers_;}
initializeSerial()
bool io_comm_rx::Comm_IO::initializeSerial (std::string port, uint32_t baudrate = 115200, std::string flowcontrol = "None")
Initializes the serial port.
Parameters
[in] port The device's port address
[in] baudrate The chosen baud rate of the port
[in] flowcontrol Default is "None", set variable (not yet checked) to "RTS|CTS" to activate hardware flow control (only for serial ports COM1, COM2 and COM3 (for mosaic))
Returns
True if connection could be established, false otherwise
Definition at line 101 of file communication_core.cpp.
References baudrate_, io_comm_rx::BAUDRATES, manager_, serial_port_, SET_BAUDRATE_SLEEP_, and setManager().
Referenced by rosaic_node::ROSaicNode::reconnect().
 {
     ROS_DEBUG("Calling initializeSerial() method..");
     serial_port_ = port;
     baudrate_ = baudrate;
     // The io_context, of which io_service is a typedef of; it represents your program's link to the
     // operating system's I/O services.
     boost::shared_ptr<boost::asio::io_service> io_service(new boost::asio::io_service);
     // To perform I/O operations the program needs an I/O object, here "serial".
     boost::shared_ptr<boost::asio::serial_port> serial(new boost::asio::serial_port(*io_service));
     // We attempt the opening of the serial port..
     try
     {
         serial->open(serial_port_);
     }
     catch (std::runtime_error& e)
     {
         // and return an error message in case it fails.
         throw std::runtime_error("Could not open serial port : " + serial_port_ + ": " + e.what());
         return false;
     }
     ROS_INFO("Opened serial port %s", serial_port_.c_str());
     ROS_DEBUG("Our boost version is %u.", BOOST_VERSION);
     if(BOOST_VERSION < 106600) // E.g. for ROS melodic (i.e. Ubuntu 18.04), the version is 106501, standing for 1.65.1.
     {
         // Workaround to set some options for the port manually,
         // cf. https://github.com/mavlink/mavros/pull/971/files
         // This function native_handle() may be used to obtain
         // the underlying representation of the serial port.
         // Conversion from type native_handle_type to int is done implicitly.
         int fd = serial->native_handle();
         termios tio;
         // Get terminal attribute, follows the syntax
         // int tcgetattr(int fd, struct termios *termios_p);
         tcgetattr(fd, &tio);
         // Hardware flow control settings..
         if (flowcontrol == "RTS|CTS")
         {
             tio.c_iflag &= ~(IXOFF | IXON);
             tio.c_cflag |= CRTSCTS;
         }
         else
         {
             tio.c_iflag &= ~(IXOFF | IXON);
             tio.c_cflag &= ~CRTSCTS;
         }
         // Setting serial port to "raw" mode to prevent EOF exit..
         cfmakeraw(&tio);
         // Commit settings, syntax is
         // int tcsetattr(int fd, int optional_actions, const struct termios *termios_p);
         tcsetattr(fd, TCSANOW, &tio);
     }
     // Set the I/O manager
     if (manager_)
     {
         ROS_ERROR("You have called the initializeSerial() method though an AsyncManager object is already available! Start all anew..");
         return false;
     }
     ROS_DEBUG("Creating new Async-Manager object..");
     setManager(boost::shared_ptr<Manager>(new AsyncManager<boost::asio::serial_port>(serial, io_service)));
     // Setting the baudrate, incrementally..
     ROS_DEBUG("Gradually increasing the baudrate to the desired value...");
     boost::asio::serial_port_base::baud_rate current_baudrate;
     ROS_DEBUG("Initiated current_baudrate object...");
     try
     {
         serial->get_option(current_baudrate); // Note that this sets current_baudrate.value() often to 115200, since by default, all Rx COM ports,
         // at least for mosaic Rxs, are set to a baudrate of 115200 baud, using 8 data-bits, no parity and 1 stop-bit.
     } catch(boost::system::system_error& e)
     {
         ROS_ERROR("get_option failed due to %s", e.what());
         ROS_INFO("Additional info about error is %s", boost::diagnostic_information(e).c_str());
         /*
         boost::system::error_code e_loop;
         do // Caution: Might cause infinite loop..
         {
             serial->get_option(current_baudrate, e_loop);
         } while(e_loop);
         */
         return false;
     }
     // Gradually increase the baudrate to the desired value
     // The desired baudrate can be lower or larger than the
     // current baudrate; the for loop takes care of both scenarios.
     ROS_DEBUG("Current baudrate is %u", current_baudrate.value());
     for (uint8_t i = 0; i < sizeof(BAUDRATES)/sizeof(BAUDRATES[0]); i++)
     {
         if (current_baudrate.value() == baudrate_)
         {
             break; // Break if the desired baudrate has been reached.
         }
         if(current_baudrate.value() >= BAUDRATES[i] && baudrate_ > BAUDRATES[i])
         {
             continue;
         }
         // Increment until Baudrate[i] matches current_baudrate.
         try
         {
             serial->set_option(boost::asio::serial_port_base::baud_rate(BAUDRATES[i]));
         } catch(boost::system::system_error& e)
         {
             ROS_ERROR("set_option failed due to %s", e.what());
             ROS_INFO("Additional info about error is %s", boost::diagnostic_information(e).c_str());
             return false;
         }
         usleep(SET_BAUDRATE_SLEEP_);
         //boost::this_thread::sleep(boost::posix_time::milliseconds(SET_BAUDRATE_SLEEP_*1000));
         // Boost's sleep would yield an error message with exit code -7 the second time it is called, hence we use sleep() or usleep().
         try
         {
             serial->get_option(current_baudrate);
         } catch(boost::system::system_error& e)
         {
             ROS_ERROR("get_option failed due to %s", e.what());
             ROS_INFO("Additional info about error is %s", boost::diagnostic_information(e).c_str());
             /*
             boost::system::error_code e_loop;
             do // Caution: Might cause infinite loop..
             {
                 serial->get_option(current_baudrate, e_loop);
             } while(e_loop);
             */
             return false;
         }
         ROS_DEBUG("Set ASIO baudrate to %u", current_baudrate.value());
     }
     ROS_INFO("Set ASIO baudrate to %u, leaving InitializeSerial() method", current_baudrate.value());
     return true;
 }
initializeTCP()
bool io_comm_rx::Comm_IO::initializeTCP (std::string host, std::string port)
Initializes the TCP I/O.
Parameters
[in] host The TCP host
[in] port The TCP port
Returns
True if connection could be established, false otherwise
Definition at line 47 of file communication_core.cpp.
References host_, manager_, port_, and setManager().
Referenced by rosaic_node::ROSaicNode::reconnect().
 {
     ROS_DEBUG("Calling initializeTCP() method..");
     host_ = host;
     port_ = port;
     // The io_context, of which io_service is a typedef of; it represents your program's link to the
     // operating system's I/O services.
     boost::shared_ptr<boost::asio::io_service> io_service(new boost::asio::io_service);
     boost::asio::ip::tcp::resolver::iterator endpoint;
     try
     {
         boost::asio::ip::tcp::resolver resolver(*io_service);
         // Note that tcp::resolver::query takes the host to resolve or the IP as the first parameter and
         // the name of the service (as defined e.g. in /etc/services on Unix hosts) as second parameter.
         // For the latter, one can also use a numeric service identifier (aka port number). In any case,
         // it returns a list of possible endpoints, as there might be several entries for a single host.
         endpoint = resolver.resolve(boost::asio::ip::tcp::resolver::query(host, port)); // Resolves query object..
     }
     catch (std::runtime_error& e)
     {
         throw std::runtime_error("Could not resolve " + host + " on port " + port + ": " + e.what());
         return false;
     }
     boost::shared_ptr<boost::asio::ip::tcp::socket> socket(new boost::asio::ip::tcp::socket(*io_service));
     try
     {
         // The list of endpoints obtained above may contain both IPv4 and IPv6 endpoints, so we need to
         // try each of them until we find one that works. This keeps the client program independent of
         // a specific IP version. The boost::asio::connect() function does this for us automatically.
         socket->connect(*endpoint);
     }
     catch (std::runtime_error& e)
     {
         throw std::runtime_error("Could not connect to " + endpoint->host_name() + ": " +
             endpoint->service_name() + ": " + e.what());
         return false;
     }
     ROS_INFO("Connected to %s: %s.", endpoint->host_name().c_str(), endpoint->service_name().c_str());
     if (manager_)
     {
         ROS_ERROR("You have called the InitializeTCP() method though an AsyncManager object is already available! Start all anew..");
         return false;
     }
     setManager(boost::shared_ptr<Manager>(new AsyncManager<boost::asio::ip::tcp::socket>(socket, io_service)));
     ROS_DEBUG("Leaving initializeTCP() method..");
     return true;
 }
resetSerial()
void io_comm_rx::Comm_IO::resetSerial (std::string port)
Reset the Serial I/O port, e.g. after a Rx reset.
Parameters
[in] port The device's port address
Definition at line 249 of file communication_core.cpp.
References baudrate_, manager_, serial_port_, and setManager().
 {
     serial_port_ = port;
     boost::shared_ptr<boost::asio::io_service> io_service(new boost::asio::io_service);
     boost::shared_ptr<boost::asio::serial_port> serial(new boost::asio::serial_port(*io_service));
     // Try to open serial port
     try
     {
         serial->open(serial_port_);
     } catch (std::runtime_error& e)
     {
         throw std::runtime_error("Could not open serial port :"
                              + serial_port_ + " " + e.what());
     }
     ROS_INFO("Reset serial port %s", serial_port_.c_str());
     // Sets the I/O worker
     if (manager_) return;
     setManager(boost::shared_ptr<Manager>(new AsyncManager<boost::asio::serial_port>(serial, io_service)));
     // Set the baudrate
     serial->set_option(boost::asio::serial_port_base::baud_rate(baudrate_));
 }
send()
void io_comm_rx::Comm_IO::send (std::string cmd)
Definition at line 41 of file communication_core.cpp.
References manager_.
Referenced by rosaic_node::ROSaicNode::configureRx(), and getHandlers().
 {
     // Determine byte size of cmd and hand over to send() method of manager_
     manager_.get()->send(cmd, cmd.size());
 }
setManager()
void io_comm_rx::Comm_IO::setManager (const boost::shared_ptr< Manager > & manager)
Set the I/O manager.
Parameters
[in] manager An I/O handler
Definition at line 240 of file communication_core.cpp.
References handlers_, manager_, and io_comm_rx::CallbackHandlers::readCallback().
Referenced by initializeSerial(), initializeTCP(), and resetSerial().
 {
     ROS_DEBUG("Called setManager() method");
     if (manager_) return;
     manager_ = manager;
     manager_->setCallback(boost::bind(&CallbackHandlers::readCallback, &handlers_, _1, _2));
     ROS_DEBUG("Leaving setManager() method");
 }
Friends And Related Function Documentation
CallbackHandlers
friend class CallbackHandlers friend
Definition at line 164 of file communication_core.hpp.
RxMessage
friend class RxMessage friend
Definition at line 165 of file communication_core.hpp.
Field Documentation
baudrate_
uint32_t io_comm_rx::Comm_IO::baudrate_ private
Baudrate at the moment, unless InitializeSerial or ResetSerial fail.
Definition at line 162 of file communication_core.hpp.
Referenced by initializeSerial(), and resetSerial().
handlers_
CallbackHandlers io_comm_rx::Comm_IO::handlers_
Callback handlers for the inwards streaming messages.
Definition at line 152 of file communication_core.hpp.
Referenced by rosaic_node::ROSaicNode::defineMessages(), getHandlers(), and setManager().
host_
std::string io_comm_rx::Comm_IO::host_ private
Host currently connected to.
Definition at line 168 of file communication_core.hpp.
Referenced by initializeTCP().
manager_
boost::shared_ptr<Manager> io_comm_rx::Comm_IO::manager_ private
Processes I/O stream data This declaration is deliberately stream-independent (Serial or TCP).
Definition at line 160 of file communication_core.hpp.
Referenced by initializeSerial(), initializeTCP(), resetSerial(), send(), and setManager().
port_
std::string io_comm_rx::Comm_IO::port_ private
Port over which TCP/IP connection is currently established.
Definition at line 170 of file communication_core.hpp.
Referenced by initializeTCP().
serial_port_
std::string io_comm_rx::Comm_IO::serial_port_ private
Saves the port description.
Definition at line 157 of file communication_core.hpp.
Referenced by initializeSerial(), and resetSerial().
SET_BAUDRATE_SLEEP_
const unsigned int io_comm_rx::Comm_IO::SET_BAUDRATE_SLEEP_ = 500000 static private
Sleep time in microseconds (there is no Unix command for milliseconds) after setting the baudrate to certain value (important between increments)
Definition at line 173 of file communication_core.hpp.
Referenced by initializeSerial().
The documentation for this class was generated from the following files:
include/septentrio_gnss_driver/communication/communication_core.hpp
src/septentrio_gnss_driver/communication/communication_core.cpp