ROSaic: io_comm_mosaic::Comm_IO Class Reference
io_comm_mosaic::Comm_IO Class Reference
Handles communication with and configuration of the mosaic-x5 device(s)
#include <communication_core.hpp>
Public Member Functions
Comm_IO ()
Default constructor of the class Comm_IO.
virtual ~Comm_IO ()=default
Default destructor of the class Comm_IO.
bool InitializeSerial (std::string port, uint32_t baudrate=115200, std::string flowcontrol="None")
Initializes the serial port.
void InitializeTCP (std::string host, std::string port)
Initializes the TCP I/O.
template<typename T >
bool poll (T &message, std::string message_ID, const boost::posix_time::time_duration &timeout)
Read an NMEA message or SBF block of the given type T, e.g. PVTGeodetic.
void setManager (const boost::shared_ptr< Manager > &manager)
Set the I/O manager.
void resetSerial (std::string port)
Reset the Serial I/O port, e.g. after mosaic reset.
CallbackHandlers get_handlers () const
Data Fields
CallbackHandlers handlers_
Callback handlers for the inwards streaming messages.
Static Public Attributes
static const int SetBaudrateSleepMs = 500
Private Attributes
std::string serial_port_
Saves the port description.
boost::shared_ptr< Manager > manager_
Processes I/O stream data.
uint32_t baudrate_
Baudrate at the moment, unless InitializeSerial or ResetSerial fail.
uint32_t read_count_
Number of times the "read" method of the mosiacMessage class has been called.
std::string host_
Host currently connected to.
std::string port_
Port over which TCP/IP connection is currently established.
Friends
class CallbackHandlers
class mosaicMessage
Detailed Description
Handles communication with and configuration of the mosaic-x5 device(s)
Definition at line 115 of file communication_core.hpp.
Constructor & Destructor Documentation
Comm_IO()
io_comm_mosaic::Comm_IO::Comm_IO ()
Default constructor of the class Comm_IO.
Definition at line 38 of file communication_core.cpp.
 : handlers_() {}
~Comm_IO()
virtual io_comm_mosaic::Comm_IO::~Comm_IO () virtual default
Default destructor of the class Comm_IO.
Member Function Documentation
get_handlers()
CallbackHandlers io_comm_mosaic::Comm_IO::get_handlers () const inline
Definition at line 171 of file communication_core.hpp.
References handlers_.
Referenced by rosaic_node::ROSaicNode::Subscribe().
 {return handlers_;}
InitializeSerial()
bool io_comm_mosaic::Comm_IO::InitializeSerial (std::string port, uint32_t baudrate = 115200, std::string flowcontrol = "None")
Initializes the serial port.
Parameters
[in] port The device's port address
[in] baudrate The chosen baud rate of the port
[in] flowcontrol Default is "None", set variable to "RTS|CTS" to activate hardware flow control (only for ports COM1, COM2 and COM3)
Definition at line 87 of file communication_core.cpp.
References baudrate_, io_comm_mosaic::Baudrates, manager_, serial_port_, SetBaudrateSleepMs, and setManager().
Referenced by rosaic_node::ROSaicNode::InitializeIO(), and rosaic_node::ROSaicNode::Reconnect().
 {
     //ROS_DEBUG("Current debug value after calling initializeserial() method is %u", io_comm_mosaic::debug);
     ROS_DEBUG("mosaic: Calling InitializeSerial method..");
     serial_port_ = port;
     baudrate_ = baudrate;
     // The io_context, of which io_service is a typedef of; it represents your program's link to the operating system's I/O services.
     boost::shared_ptr<boost::asio::io_service> io_service(new boost::asio::io_service);
     // To perform I/O operations the program needs an I/O object, here "serial".
     boost::shared_ptr<boost::asio::serial_port> serial(new boost::asio::serial_port(*io_service));
     // We attempt the opening of the serial port..
     try
     {
         serial->open(serial_port_);
     }
     catch (std::runtime_error& e)
     {
         // and return an error message in case it fails.
         throw std::runtime_error("mosaic-X5: Could not open serial port : " + serial_port_ + ": " + e.what());
         return false;
     }
     ROS_INFO("mosaic-X5: Opened serial port %s", serial_port_.c_str());
     ROS_DEBUG("Our boost version is %u.", BOOST_VERSION);
     if(BOOST_VERSION < 106600) // e.g. for ROS melodic (i.e. Ubuntu 18.04) it is 106501, standing for 1.65.1
     {
         // Workaround to set some options for the port manually,
         // cf. https://github.com/mavlink/mavros/pull/971/files
         // This function native_handle() may be used to obtain
         // the underlying representation of the serial port.
         // Conversion from type native_handle_type to int is done implicitly.
         int fd = serial->native_handle();
         termios tio;
         // Get terminal attribute, follows the syntax
         // int tcgetattr(int fd, struct termios *termios_p);
         tcgetattr(fd, &tio);
         // Setting hardware flow control settings..
         if (flowcontrol == "RTS|CTS") {
             tio.c_iflag &= ~(IXOFF | IXON);
             tio.c_cflag |= CRTSCTS;
         } else {
             tio.c_iflag &= ~(IXOFF | IXON);
             tio.c_cflag &= ~CRTSCTS;
         }
         // Setting serial port to "raw" mode to prevent EOF exit..
         cfmakeraw(&tio);
         // Commit settings, syntax is
         // int tcsetattr(int fd, int optional_actions,
         //      const struct termios *termios_p);
         tcsetattr(fd, TCSANOW, &tio);
     }
     // Set the I/O manager
     if (manager_)
     {
         ROS_ERROR("You have called InitializeSerial twice! Start all anew or call ResetSerial..");
         return false;
     }
     ROS_DEBUG("Creating new Async-Manager..");
     setManager(boost::shared_ptr<Manager>(new AsyncManager<boost::asio::serial_port>(serial, io_service)));
     //ROS_DEBUG("Finished creating new Async-Manager, have not yet called its read_callback_, since that will only be populated by the readCallback method of the CallbackHandlers class momentarily..");
     // Setting the baudrate, incrementally..
     ROS_DEBUG("Gradually increasing the baudrate to the desired value...");
     boost::asio::serial_port_base::baud_rate current_baudrate;
     ROS_DEBUG("Initiated current_baudrate object...");
     try
     {
         serial->get_option(current_baudrate);   // Embed with throw to catch bad file descriptor error or similar ones..
                                                 // Often sets current_baudrate.value() magically to 115200
     } catch(boost::system::system_error& e)
     {
         ROS_ERROR("get_option failed due to %s", e.what());
         ROS_INFO("Additional info about error is %s", boost::diagnostic_information(e).c_str());
         /*
         boost::system::error_code e_loop;
         do // Caution: Might cause infinite loop..
         {
             serial->get_option(current_baudrate, e_loop);
         } while(e_loop);
         */
         return 1;
     }
     // Gradually increase the baudrate to the desired value
     // The desired baudrate can be lower or larger than the
     // current baudrate; the for loop takes care of both scenarios.
     ROS_DEBUG("Current baudrate is %u", current_baudrate.value());
     for (uint8_t i = 0; i < sizeof(Baudrates)/sizeof(Baudrates[0]); i++)
     {
         if (current_baudrate.value() == baudrate_)
             break;
             // Break if the desired baudrate has been reached
         if(current_baudrate.value() > Baudrates[i] && baudrate_ > Baudrates[i])
             continue;
             // Increment until Baudrate[i] matches current_baudrate
         serial->set_option(boost::asio::serial_port_base::baud_rate(Baudrates[i]));
         boost::this_thread::sleep(boost::posix_time::milliseconds(SetBaudrateSleepMs));
         serial->get_option(current_baudrate);
         ROS_DEBUG("mosaic: Set ASIO baudrate to %u", current_baudrate.value());
     }
     ROS_INFO("mosaic: Set ASIO baudrate to %u, leaving InitializeSerial() method", current_baudrate.value());
     return true;
 }
InitializeTCP()
void io_comm_mosaic::Comm_IO::InitializeTCP (std::string host, std::string port)
Initializes the TCP I/O.
Parameters
[in] host The TCP host
[in] port The TCP port
Definition at line 47 of file communication_core.cpp.
References host_, manager_, port_, and setManager().
Referenced by rosaic_node::ROSaicNode::InitializeIO().
 {
     host_ = host;
     port_ = port;
     // The io_context, of which io_service is a typedef of; it represents your program's link to the operating system's I/O services.
     boost::shared_ptr<boost::asio::io_service> io_service(new boost::asio::io_service);
     boost::asio::ip::tcp::resolver::iterator endpoint;
     try
     {
         boost::asio::ip::tcp::resolver resolver(*io_service);
         // Note that tcp::resolver::query takes the host to resolve or the IP as the first parameter and the name of the service (as defined e.g. in /etc/services on Unix hosts) as second parameter.
         // For the latter, one can also use a numeric service identifier (aka port number). In any case, it returns a list of possible endpoints, as there might be several entries for a single host.
         endpoint = resolver.resolve(boost::asio::ip::tcp::resolver::query(host, port)); // Resolves query object..
     }
     catch (std::runtime_error& e)
     {
         throw std::runtime_error("mosaic: Could not resolve " + host + " on port " + port + ": " + e.what());
     }
     boost::shared_ptr<boost::asio::ip::tcp::socket> socket(new boost::asio::ip::tcp::socket(*io_service));
     try
     {
         // The list of endpoints obtained above may contain both IPv4 and IPv6 endpoints, so we need to try each of them until we find one that works.
         // This keeps the client program independent of a specific IP version. The boost::asio::connect() function does this for us automatically.
         socket->connect(*endpoint);
     }
     catch (std::runtime_error& e)
     {
         throw std::runtime_error("mosaic: Could not connect to " + endpoint->host_name() + ": " + endpoint->service_name() + ": " + e.what());
     }
     ROS_INFO("mosaic: Connected to %s: %s.", endpoint->host_name().c_str(), endpoint->service_name().c_str());
     if (manager_) return;
     setManager(boost::shared_ptr<Manager>(new AsyncManager<boost::asio::ip::tcp::socket>(socket, io_service)));
 }
poll()
template<typename T > bool io_comm_mosaic::Comm_IO::poll (T & message, std::string message_ID, const boost::posix_time::time_duration & timeout)
Read an NMEA message or SBF block of the given type T, e.g. PVTGeodetic.
InitializeSerial is not self-contained: The for loop in Callbackhandlers' handle method would never open a specific handler unless the handler is added (=inserted) to the map via this function. This way (since specific handle exists), the specific handler is opened, hence mosaicMessage's read method is called, "message" occupied (we allow for some time for this to happen), and func_ is called with the same, now occupied, "message", before control is handed back to bool read, which just returns true after deleting the specific handler. Outline: mosaic_node calls both InitializeSerial and e.g. bool read(GPGGA to_be_published) and then publish it!
Parameters
[out] message The received message
[in] timeout The amount of time to wait for the desired message (before callback-handler is erased without populating message)
Definition at line 41 of file communication_core.cpp.
References handlers_, manager_, and io_comm_mosaic::CallbackHandlers::poll().
 {
     if (!manager_) return false;
     return handlers_.poll(message, message_ID, timeout);
 }
resetSerial()
void io_comm_mosaic::Comm_IO::resetSerial (std::string port)
Reset the Serial I/O port, e.g. after mosaic reset.
Parameters
[in] port The device's port address
Needs to be checked..
Definition at line 208 of file communication_core.cpp.
References baudrate_, manager_, serial_port_, and setManager().
 {
     serial_port_ = port;
     boost::shared_ptr<boost::asio::io_service> io_service(new boost::asio::io_service);
     boost::shared_ptr<boost::asio::serial_port> serial(new boost::asio::serial_port(*io_service));
     // Try to open serial port
     try
     {
         serial->open(serial_port_);
     } catch (std::runtime_error& e)
     {
         throw std::runtime_error("mosaic: Could not open serial port :"
                              + serial_port_ + " " + e.what());
     }
     ROS_INFO("mosaic: Reset serial port %s", serial_port_.c_str());
     // Sets the I/O worker
     if (manager_) return;
     setManager(boost::shared_ptr<Manager>(new AsyncManager<boost::asio::serial_port>(serial, io_service)));
     /*
     // Polls ReceiverStatus block
     std::vector<uint8_t> receiverstatus;
     if (!poll(..., receiverstatus))
     {
         ROS_ERROR("Resetting Serial Port: Could not poll ReceiverStatus");
         return;
     }
     ReceiverStatus struct_object;
     if(!read(struct_object, ...default_timeout_))
     {
         ROS_ERROR("Resetting Serial Port: Could not read polled ReceiverStatus");
         return;
     }
     */
     // Set the baudrate
     serial->set_option(boost::asio::serial_port_base::baud_rate(baudrate_));
 }
setManager()
void io_comm_mosaic::Comm_IO::setManager (const boost::shared_ptr< Manager > & manager)
Set the I/O manager.
Parameters
[in] manager An I/O handler
Definition at line 196 of file communication_core.cpp.
References handlers_, manager_, and io_comm_mosaic::CallbackHandlers::readCallback().
Referenced by InitializeSerial(), InitializeTCP(), and resetSerial().
{
     ROS_DEBUG("Entered setManager");
     if (manager_) return;
     manager_ = manager;
     ROS_DEBUG("About to call setCallback");
     manager_->setCallback(boost::bind(&CallbackHandlers::readCallback, &handlers_, _1, _2));
 }
Friends And Related Function Documentation
CallbackHandlers
friend class CallbackHandlers friend
Definition at line 185 of file communication_core.hpp.
mosaicMessage
friend class mosaicMessage friend
Definition at line 186 of file communication_core.hpp.
Field Documentation
baudrate_
uint32_t io_comm_mosaic::Comm_IO::baudrate_ private
Baudrate at the moment, unless InitializeSerial or ResetSerial fail.
Definition at line 183 of file communication_core.hpp.
Referenced by InitializeSerial(), and resetSerial().
handlers_
CallbackHandlers io_comm_mosaic::Comm_IO::handlers_
Callback handlers for the inwards streaming messages.
Definition at line 174 of file communication_core.hpp.
Referenced by get_handlers(), poll(), setManager(), and rosaic_node::ROSaicNode::Subscribe().
host_
std::string io_comm_mosaic::Comm_IO::host_ private
Host currently connected to.
Definition at line 191 of file communication_core.hpp.
Referenced by InitializeTCP().
manager_
boost::shared_ptr<Manager> io_comm_mosaic::Comm_IO::manager_ private
Processes I/O stream data.
Definition at line 181 of file communication_core.hpp.
Referenced by InitializeSerial(), InitializeTCP(), poll(), resetSerial(), and setManager().
port_
std::string io_comm_mosaic::Comm_IO::port_ private
Port over which TCP/IP connection is currently established.
Definition at line 193 of file communication_core.hpp.
Referenced by InitializeTCP().
read_count_
uint32_t io_comm_mosaic::Comm_IO::read_count_ private
Number of times the "read" method of the mosiacMessage class has been called.
Definition at line 188 of file communication_core.hpp.
serial_port_
std::string io_comm_mosaic::Comm_IO::serial_port_ private
Saves the port description.
Definition at line 179 of file communication_core.hpp.
Referenced by InitializeSerial(), and resetSerial().
SetBaudrateSleepMs
const int io_comm_mosaic::Comm_IO::SetBaudrateSleepMs = 500 static
Definition at line 118 of file communication_core.hpp.
Referenced by InitializeSerial().
The documentation for this class was generated from the following files:
include/rosaic/communication/communication_core.hpp
src/rosaic/communication/communication_core.cpp