ROSaic: io_comm_mosaic::Manager Class Reference
io_comm_mosaic::Manager Class Reference abstract
Interface (in C++ terms), that could be used for any I/O manager, synchronous and asynchronous alike.
#include <async_manager.hpp>
Public Types
typedef boost::function< void(const uint8_t *, std::size_t &)> Callback
Public Member Functions
virtual ~Manager ()
virtual void SetCallback (const Callback &callback)=0
Sets the callback function.
virtual bool Send (std::string cmd, std::size_t size)=0
Sends commands to the receiver.
virtual void Wait (uint16_t *count)=0
Waits count seconds before throwing ROS_INFO message in case no message from the receiver arrived.
virtual bool IsOpen () const =0
Determines whether or not the connection is open.
Detailed Description
Interface (in C++ terms), that could be used for any I/O manager, synchronous and asynchronous alike.
Definition at line 88 of file async_manager.hpp.
Member Typedef Documentation
Callback
typedef boost::function<void(const uint8_t*, std::size_t&)> io_comm_mosaic::Manager::Callback
Definition at line 90 of file async_manager.hpp.
Constructor & Destructor Documentation
~Manager()
virtual io_comm_mosaic::Manager::~Manager () inline virtual
Definition at line 91 of file async_manager.hpp.
References IsOpen(), Send(), SetCallback(), and Wait().
 {}
Member Function Documentation
IsOpen()
virtual bool io_comm_mosaic::Manager::IsOpen () const pure virtual
Determines whether or not the connection is open.
Implemented in io_comm_mosaic::AsyncManager< StreamT >.
Referenced by ~Manager().
Send()
virtual bool io_comm_mosaic::Manager::Send (std::string cmd, std::size_t size) pure virtual
Sends commands to the receiver.
Implemented in io_comm_mosaic::AsyncManager< StreamT >.
Referenced by io_comm_mosaic::AsyncManager< StreamT >::SetCallback(), and ~Manager().
SetCallback()
virtual void io_comm_mosaic::Manager::SetCallback (const Callback & callback) pure virtual
Sets the callback function.
Implemented in io_comm_mosaic::AsyncManager< StreamT >.
Referenced by ~Manager().
Wait()
virtual void io_comm_mosaic::Manager::Wait (uint16_t * count) pure virtual
Waits count seconds before throwing ROS_INFO message in case no message from the receiver arrived.
Implemented in io_comm_mosaic::AsyncManager< StreamT >.
Referenced by io_comm_mosaic::AsyncManager< StreamT >::SetCallback(), and ~Manager().
The documentation for this class was generated from the following file:
include/rosaic/communication/async_manager.hpp