ROSaic: io_comm_mosaic::CallbackHandler< T > Class Template Reference
io_comm_mosaic::CallbackHandler< T > Class Template Reference
Abstract class representing a generic callback handler, includes high-level functionality such as wait.
#include <callbackhandlers.hpp>
Public Types
typedef boost::function< void(const T &)> Callback
Public Member Functions
CallbackHandler (const Callback &func=Callback())
virtual const T & Get ()
void Handle (mosaicMessage &mMessage, std::string message_key)
Public Member Functions inherited from io_comm_mosaic::AbstractCallbackHandler
bool Wait (const boost::posix_time::time_duration &timeout)
Private Attributes
Callback func_
T message_
Additional Inherited Members
Protected Attributes inherited from io_comm_mosaic::AbstractCallbackHandler
boost::mutex mutex_
boost::condition_variable condition_
Detailed Description
template<typename T>
class io_comm_mosaic::CallbackHandler< T >
Abstract class representing a generic callback handler, includes high-level functionality such as wait.
Derived class operating on a ROS message level.
Definition at line 123 of file callbackhandlers.hpp.
Member Typedef Documentation
Callback
template<typename T> typedef boost::function<void(const T&)> io_comm_mosaic::CallbackHandler< T >::Callback
Definition at line 126 of file callbackhandlers.hpp.
Constructor & Destructor Documentation
CallbackHandler()
template<typename T> io_comm_mosaic::CallbackHandler< T >::CallbackHandler (const Callback & func = Callback()) inline
Definition at line 128 of file callbackhandlers.hpp.
 : func_(func) {}
Member Function Documentation
Get()
template<typename T> virtual const T& io_comm_mosaic::CallbackHandler< T >::Get () inline virtual
Definition at line 130 of file callbackhandlers.hpp.
Referenced by io_comm_mosaic::CallbackHandlers::Poll().
 { return message_; }
Handle()
template<typename T> void io_comm_mosaic::CallbackHandler< T >::Handle (mosaicMessage & mMessage, std::string message_key) inline virtual
Implements io_comm_mosaic::AbstractCallbackHandler.
Definition at line 132 of file callbackhandlers.hpp.
References io_comm_mosaic::AbstractCallbackHandler::condition_, io_comm_mosaic::mosaicMessage::MessageID(), io_comm_mosaic::AbstractCallbackHandler::mutex_, and io_comm_mosaic::mosaicMessage::Read().
             {
                 boost::mutex::scoped_lock lock(mutex_);
                 try
                 {
                     if (!mMessage.Read<T>(message_, message_key))
                     {
                         std::ostringstream ss;
                         ss << "Read unsuccessful: mosaic decoder error for message with ID (empty field if non-determinable" << mMessage.MessageID() << ". ";
                         ROS_INFO_COND(debug >= 2, "%s", ss.str().c_str());
                         return;
                     }
                 } catch (std::runtime_error& e)
                 {
                     std::ostringstream ss;
                     ss << "Read unsuccessful: mosaic decoder error for message with ID " << mMessage.MessageID() << ".\nReason: " << e.what();
                     ROS_INFO_COND(debug >= 2, "%s", ss.str().c_str());
                     return;
                 }
                 condition_.notify_all();
                 if (func_) func_(message_);
             }
Field Documentation
func_
template<typename T> Callback io_comm_mosaic::CallbackHandler< T >::func_ private
Definition at line 157 of file callbackhandlers.hpp.
message_
template<typename T> T io_comm_mosaic::CallbackHandler< T >::message_ private
Definition at line 158 of file callbackhandlers.hpp.
The documentation for this class was generated from the following file:
include/rosaic/communication/callbackhandlers.hpp