ROSaic: io_comm_mosaic::mosaicMessage Class Reference
io_comm_mosaic::mosaicMessage Class Reference
Can search buffer for messages, read/parse them, and so on.
#include <mosaicMessage.hpp>
Public Member Functions
mosaicMessage (const uint8_t *data, std::size_t &size)
Constructor of the mosaicMessage class.
bool IsMessage (const uint16_t ID)
Determines whether data_ points to the SBF block with ID "ID", e.g. 5003.
bool IsMessage (std::string ID)
Determines whether data_ points to the NMEA message with ID "ID", e.g. "$GPGGA".
bool IsSBF ()
Determines whether data_ currently points to an SBF block.
bool IsNMEA ()
Determines whether data_ currently points to an NMEA message.
bool IsResponse ()
Determines whether data_ currently points to an NMEA message.
bool IsConnectionDescriptor ()
Determines whether data_ currently points to a connection descriptor (right after initiating TCP connection)
bool IsErrorMessage ()
Determines whether data_ currently points to an error message reply from mosaic.
std::size_t SegmentEnd ()
Determines size of message that data_ is currently pointing at.
std::string MessageID ()
Returns the MessageID of the message where data_ is pointing at at the moment, SBF identifiers embellished with inverted commas, e.g. "5003".
uint32_t GetCount ()
Returns the count_ variable.
const uint8_t * Search ()
Searches the buffer for the beginning of the next message (NMEA or SBF)
uint16_t BlockLength ()
Gets the length of the SBF block.
const uint8_t * Pos ()
Gets the current position in the read buffer.
const uint8_t * End ()
Gets the end position in the read buffer.
bool Found ()
Has an NMEA message or SBF block been found in the buffer?
const uint8_t * Next ()
Goes to the start of the next message based on the calculated length of current message.
template<typename T >
bool Read (typename boost::call_traits< T >::reference message, std::string message_key, bool search=false)
Performs the CRC check (if SBF block) and populates message with the necessary content (mapped 1-to-1 if SBF, parsed if NMEA), works for pure ROS message mapping.
Data Fields
bool found_
Whether or not a message has been found.
Private Member Functions
rosaic::PVTCartesianPtr PVTCartesianCallback (PVTCartesian &data)
Callback function when reading PVTCartesian blocks.
rosaic::PVTGeodeticPtr PVTGeodeticCallback (PVTGeodetic &data)
Callback function when reading PVTGeodetic blocks.
rosaic::PosCovCartesianPtr PosCovCartesianCallback (PosCovCartesian &data)
Callback function when reading PosCovCartesian blocks.
rosaic::PosCovGeodeticPtr PosCovGeodeticCallback (PosCovGeodetic &data)
Callback function when reading PosCovGeodetic blocks.
rosaic::AttEulerPtr AttEulerCallback (AttEuler &data)
Callback function when reading AttEuler blocks.
rosaic::AttCovEulerPtr AttCovEulerCallback (AttCovEuler &data)
Callback function when reading AttCovEuler blocks.
sensor_msgs::NavSatFixPtr NavSatFixCallback ()
"Callback" function when constructing NavSatFix messages
gps_common::GPSFixPtr GPSFixCallback ()
"Callback" function when constructing GPSFix messages
geometry_msgs::PoseWithCovarianceStampedPtr PoseWithCovarianceStampedCallback ()
"Callback" function when constructing PoseWithCovarianceStamped messages
Private Attributes
const uint8_t * data_
The pointer to the buffer of messages.
uint32_t count_
The number of bytes in the buffer, decremented as the buffer is read (so it is the buffer's size in the beginning)
bool CRCcheck_
Whether the CRC check as evaluated in the read() method was successful or not is stored here.
std::size_t segment_size_
Helps to determine size of response message / NMEA message / SBF block.
Static Private Attributes
static uint32_t count_gpsfix_ = 0
Number of times the gps_common::GPSFix message has been published.
static PVTGeodetic last_pvtgeodetic_ = PVTGeodetic()
Since NavSatFix etc. need PVTGeodetic, incoming PVTGeodetic blocks need to be stored.
static PosCovGeodetic last_poscovgeodetic_ = PosCovGeodetic()
Since NavSatFix etc. need PosCovGeodetic, incoming PosCovGeodetic blocks need to be stored.
static AttEuler last_atteuler_ = AttEuler()
Since GPSFix etc. need AttEuler, incoming AttEuler blocks need to be stored.
static AttCovEuler last_attcoveuler_ = AttCovEuler()
Since GPSFix etc. need AttCovEuler, incoming AttCovEuler blocks need to be stored.
static ChannelStatus last_channelstatus_ = ChannelStatus()
Since GPSFix etc. need ChannelStatus, incoming ChannelStatus blocks need to be stored.
static MeasEpoch last_measepoch_ = MeasEpoch()
Since GPSFix etc. need MeasEpoch (for signal-to-noise ratios), incoming MeasEpoch blocks need to be stored.
static DOP last_dop_ = DOP()
Since GPSFix etc. need DOP, incoming DOP blocks need to be stored.
static VelCovGeodetic last_velcovgeodetic_ = VelCovGeodetic()
Since GPSFix etc. need VelCovGeodetic (for signal-to-noise ratios), incoming VelCovGeodetic blocks need to be stored.
Detailed Description
Can search buffer for messages, read/parse them, and so on.
Definition at line 205 of file mosaicMessage.hpp.
Constructor & Destructor Documentation
mosaicMessage()
io_comm_mosaic::mosaicMessage::mosaicMessage (const uint8_t * data, std::size_t & size) inline
Constructor of the mosaicMessage class.
One can always provide a non-const value where a const one was expected. The const-ness of the argument just means the function promises not to change it.. Recall: static_cast by the way can remove or add const-ness, no other C++ cast is capable of removing it (not even reinterpret_cast)
Parameters
[in] data Pointer to the buffer that is about to be analyzed
[in] size Size of the buffer (as handed over by async_read_some)
Definition at line 216 of file mosaicMessage.hpp.
References CRCcheck_, found_, IsConnectionDescriptor(), IsErrorMessage(), IsMessage(), IsNMEA(), IsResponse(), IsSBF(), MessageID(), segment_size_, and SegmentEnd().
 : data_(data), count_(size) {found_ = false; CRCcheck_ = false; segment_size_ = 0;}
Member Function Documentation
AttCovEulerCallback()
rosaic::AttCovEulerPtr io_comm_mosaic::mosaicMessage::AttCovEulerCallback (AttCovEuler & data) private
Callback function when reading AttCovEuler blocks.
Parameters
[in] data The (packed and aligned) struct instance that we use to populate our ROS message rosaic::AttCovEuler
Returns
A smart pointer to the ROS message rosaic::AttCovEuler just created
Definition at line 202 of file mosaicMessage.cpp.
References AttCovEuler::Block_Header, AttCovEuler::Cov_HeadHead, AttCovEuler::Cov_HeadPitch, AttCovEuler::Cov_HeadRoll, AttCovEuler::Cov_PitchPitch, AttCovEuler::Cov_PitchRoll, AttCovEuler::Cov_RollRoll, BlockHeader_t::CRC, AttCovEuler::Error, BlockHeader_t::ID, BlockHeader_t::Length, BlockHeader_t::SYNC1, BlockHeader_t::SYNC2, AttCovEuler::TOW, and AttCovEuler::WNc.
Referenced by Read().
 {
     rosaic::AttCovEulerPtr msg = boost::make_shared<rosaic::AttCovEuler>();
     msg->Block_Header.SYNC1 = data.Block_Header.SYNC1;
     msg->Block_Header.SYNC2 = data.Block_Header.SYNC2;
     msg->Block_Header.CRC = data.Block_Header.CRC;
     msg->Block_Header.ID = data.Block_Header.ID;
     msg->Block_Header.Length = data.Block_Header.Length;
     msg->Block_Header.TOW = data.TOW;
     msg->Block_Header.WNc = data.WNc;
     msg->Error = data.Error;
     msg->Cov_HeadHead = data.Cov_HeadHead;
     msg->Cov_PitchPitch = data.Cov_PitchPitch;
     msg->Cov_RollRoll = data.Cov_RollRoll;
     msg->Cov_HeadPitch = data.Cov_HeadPitch;
     msg->Cov_HeadRoll = data.Cov_HeadRoll;
     msg->Cov_PitchRoll = data.Cov_PitchRoll;
     return msg;
 };
AttEulerCallback()
rosaic::AttEulerPtr io_comm_mosaic::mosaicMessage::AttEulerCallback (AttEuler & data) private
Callback function when reading AttEuler blocks.
Parameters
[in] data The (packed and aligned) struct instance that we use to populate our ROS message rosaic::AttEuler
Returns
A smart pointer to the ROS message rosaic::AttEuler just created
Definition at line 180 of file mosaicMessage.cpp.
References AttEuler::Block_Header, BlockHeader_t::CRC, AttEuler::Error, AttEuler::Heading, AttEuler::HeadingDot, BlockHeader_t::ID, BlockHeader_t::Length, AttEuler::Mode, AttEuler::NrSV, AttEuler::Pitch, AttEuler::PitchDot, AttEuler::Roll, AttEuler::RollDot, BlockHeader_t::SYNC1, BlockHeader_t::SYNC2, AttEuler::TOW, and AttEuler::WNc.
Referenced by Read().
 {
     rosaic::AttEulerPtr msg = boost::make_shared<rosaic::AttEuler>();
     msg->Block_Header.SYNC1 = data.Block_Header.SYNC1;
     msg->Block_Header.SYNC2 = data.Block_Header.SYNC2;
     msg->Block_Header.CRC = data.Block_Header.CRC;
     msg->Block_Header.ID = data.Block_Header.ID;
     msg->Block_Header.Length = data.Block_Header.Length;
     msg->Block_Header.TOW = data.TOW;
     msg->Block_Header.WNc = data.WNc;
     msg->NrSV = data.NrSV;
     msg->Error = data.Error;
     msg->Mode = data.Mode;
     msg->Heading = data.Heading;
     msg->Pitch = data.Pitch;
     msg->Roll = data.Roll;
     msg->PitchDot = data.PitchDot;
     msg->RollDot = data.RollDot;
     msg->HeadingDot = data.HeadingDot;
     return msg;
 };
BlockLength()
uint16_t io_comm_mosaic::mosaicMessage::BlockLength ()
Gets the length of the SBF block.
It determines the length from the header of the SBF block. The block length thus includes the header length.
Returns
The length of the SBF block
Definition at line 853 of file mosaicMessage.cpp.
References data_, and IsSBF().
Referenced by GetCount(), Next(), Read(), and io_comm_mosaic::CallbackHandlers::ReadCallback().
 {
     if (this->IsSBF())
     {
         uint16_t block_length;
         // Note that static_cast<uint16_t>(data_[6]) would just take the one byte "data_[6]" and cast it as requested, !neglecting! the byte "data_[7]".
         block_length = *(reinterpret_cast<const uint16_t*>(data_ + 6));
         return block_length;
     }
     else
     {
         return 0;
     }
 }
End()
const uint8_t * io_comm_mosaic::mosaicMessage::End ()
Gets the end position in the read buffer.
Returns
A pointer pointing to just after the read buffer (matches search()'s pointer if no valid message is found)
Definition at line 848 of file mosaicMessage.cpp.
References count_, and data_.
Referenced by GetCount(), and io_comm_mosaic::CallbackHandlers::ReadCallback().
 {
     return data_ + count_;
 }
Found()
bool io_comm_mosaic::mosaicMessage::Found ()
Has an NMEA message or SBF block been found in the buffer?
Returns
True if a message with the correct header & length has been found.
Definition at line 652 of file mosaicMessage.cpp.
References found_, IsConnectionDescriptor(), IsNMEA(), IsResponse(), IsSBF(), and read_cd.
Referenced by GetCount(), Next(), Read(), and io_comm_mosaic::CallbackHandlers::ReadCallback().
 {
     if (found_) return true;
     // Verify header bytes
     if (!this->IsSBF() && !this->IsNMEA() && !this->IsResponse() && !(read_cd && this->IsConnectionDescriptor()))
     {
         return false;
     }
     found_ = true;
     return true;
 }
GetCount()
uint32_t io_comm_mosaic::mosaicMessage::GetCount () inline
Returns the count_ variable.
Returns
The variable count_
Definition at line 241 of file mosaicMessage.hpp.
References BlockLength(), count_, End(), Found(), Next(), Pos(), Read(), and Search().
 {return count_;};
GPSFixCallback()
gps_common::GPSFixPtr io_comm_mosaic::mosaicMessage::GPSFixCallback () private
"Callback" function when constructing GPSFix messages
Returns
A smart pointer to the ROS message gps_common::GPSFix just created
For some unknown reason, the first 2 entries of the GPSStatus field's arrays are not shown properly when published. Please consult section 4.1.9 of the firmware to understand the meaning of the satellite identifiers used in the arrays of the GPSStatus field. Note that the field "dip" denotes the local magnetic inclination in degrees (positive when the magnetic field points downwards (into the Earth)). This quantity cannot be calculated by mosaic receivers. We assume that for the ROS field "err_time", we are requested to provide the 2 sigma uncertainty on the clock bias estimate in square meters, not the clock drift estimate (latter would be "2*std::sqrt(static_cast<double>(last_velcovgeodetic_.Cov_DtDt))"). The "err_track" entry is calculated via the Gaussian error propagation formula from the eastward and the northward velocities. For its usage we have to assume that the eastward and the northward velocities are independent variables. Note that elevations and azimuths of visible satellites are taken from the ChannelStatus block, which provides 1 degree precision, while the SatVisibility block could provide hundredths of degrees precision. Change if imperative for your application.. Definition of "visible satellite" adopted: Here, we define a visible satellite as being up to "in sync" mode with the receiver, which corresponds to last_measepoch_.N (signal-to-noise ratios are thereby available for these), though not last_channelstatus_.N, which also includes those "in search".
Definition at line 365 of file mosaicMessage.cpp.
References ChannelSatInfo::Az_RiseSet, ChannelStatus::Block_Header, MeasEpoch::Block_Header, MeasEpochChannelType1::CN0, PVTGeodetic::COG, PosCovGeodetic::Cov_bb, PosCovGeodetic::Cov_hgthgt, PosCovGeodetic::Cov_lathgt, PosCovGeodetic::Cov_latlat, PosCovGeodetic::Cov_latlon, PosCovGeodetic::Cov_lonhgt, PosCovGeodetic::Cov_lonlon, AttCovEuler::Cov_PitchPitch, AttCovEuler::Cov_RollRoll, VelCovGeodetic::Cov_VeVe, VelCovGeodetic::Cov_VnVn, VelCovGeodetic::Cov_VuVu, ChannelStatus::Data, MeasEpoch::Data, ChannelSatInfo::Elev, DOP::HDOP, PVTGeodetic::Height, last_attcoveuler_, last_atteuler_, last_channelstatus_, last_dop_, last_measepoch_, last_poscovgeodetic_, last_pvtgeodetic_, last_velcovgeodetic_, PVTGeodetic::Latitude, PVTGeodetic::Longitude, PVTGeodetic::Mode, ChannelStatus::N, MeasEpoch::N, ChannelSatInfo::N2, MeasEpochChannelType1::N_Type2, PVTGeodetic::NrSV, DOP::PDOP, AttEuler::Pitch, ChannelStateInfo::PVTStatus, PVTGeodetic::ReferenceID, AttEuler::Roll, ChannelStatus::SB1Size, MeasEpoch::SB1Size, ChannelStatus::SB2Size, MeasEpoch::SB2Size, ChannelSatInfo::SVID, MeasEpochChannelType1::SVID, svid_pvt, BlockHeader_t::SYNC1, DOP::TDOP, PVTGeodetic::TOW, MeasEpochChannelType1::Type, DOP::VDOP, PVTGeodetic::Ve, PVTGeodetic::Vn, PVTGeodetic::Vu, and PVTGeodetic::WNc.
Referenced by Read().
 {
     gps_common::GPSFixPtr msg = boost::make_shared<gps_common::GPSFix>();
     msg->status.satellites_used = static_cast<uint16_t>(last_pvtgeodetic_.NrSV);
     // MeasEpoch Processing
     std::vector<int32_t> cno_tracked;
     std::vector<int32_t> svid_in_sync;
     {
         uint8_t sb1_size = last_measepoch_.SB1Size;
         uint8_t sb2_size = last_measepoch_.SB2Size;
         uint8_t *sb_start = &last_measepoch_.Data[0];
         int32_t index = sb_start - &last_measepoch_.Block_Header.SYNC1;
         for (int32_t i = 0; i < static_cast<int32_t>(last_measepoch_.N); ++i)
         {
             // Define MeasEpochChannelType1 struct for the corresponding sub-block
             MeasEpochChannelType1 *measepoch_channel_type1  = reinterpret_cast<MeasEpochChannelType1*>(&last_measepoch_.Block_Header.SYNC1 + index);
             svid_in_sync.push_back(static_cast<int32_t>(measepoch_channel_type1->SVID));
             uint8_t type_mask = 15; // We extract the first four bits using this mask.
             if (measepoch_channel_type1->Type & type_mask == static_cast<uint8_t>(1) || measepoch_channel_type1->Type & type_mask == static_cast<uint8_t>(2))
             {
                 cno_tracked.push_back(static_cast<int32_t>(measepoch_channel_type1->CN0)/4);
             }
             else
             {
                 cno_tracked.push_back(static_cast<int32_t>(measepoch_channel_type1->CN0)/4+static_cast<int32_t>(10));
             }
             //ROS_DEBUG("static_cast<int32_t>(measepoch_channel_type1->SVID)) is %i", static_cast<int32_t>(measepoch_channel_type1->SVID));
             index += sb1_size;
             for (int32_t j = 0; j < static_cast<int32_t>(measepoch_channel_type1->N_Type2); j++)
             {
                 index += sb2_size;
             }
         }
     }
     // ChannelStatus Processing
     std::vector<int32_t> svid_in_sync_2;
     std::vector<int32_t> elevation_tracked;
     std::vector<int32_t> azimuth_tracked;
     std::vector<int32_t> svid_pvt;
     svid_pvt.clear();
     std::vector<int32_t> ordering;
     {
         uint8_t sb1_size = last_channelstatus_.SB1Size;
         uint8_t sb2_size = last_channelstatus_.SB2Size;
         uint8_t *sb_start = &last_channelstatus_.Data[0];
         int32_t index = sb_start - &last_channelstatus_.Block_Header.SYNC1;
         //ROS_DEBUG("index is %i", index); // yields 20, as expected
         uint16_t azimuth_mask = 511;
         for (int32_t i = 0; i < static_cast<int32_t>(last_channelstatus_.N); i++)
         {
             // Define ChannelSatInfo struct for the corresponding sub-block
             ChannelSatInfo *channel_sat_info  = reinterpret_cast<ChannelSatInfo*>(&last_channelstatus_.Block_Header.SYNC1 + index);
             bool to_be_added = false;
             for (int32_t j = 0; j < static_cast<int32_t>(svid_in_sync.size()); ++j)
             {
                 if (svid_in_sync[j] == static_cast<int32_t>(channel_sat_info->SVID))
                 {
                     ordering.push_back(j);
                     to_be_added = true;
                     break;
                 }
             }
             if (to_be_added)
             {
                 svid_in_sync_2.push_back(static_cast<int32_t>(channel_sat_info->SVID));
                 elevation_tracked.push_back(static_cast<int32_t>(channel_sat_info->Elev));
                 azimuth_tracked.push_back(static_cast<int32_t>((channel_sat_info->Az_RiseSet & azimuth_mask)));
             }
             index += sb1_size;
             for (int32_t j = 0; j < static_cast<int32_t>(channel_sat_info->N2); j++)
             {
                 // Define ChannelStateInfo struct for the corresponding sub-block
                 ChannelStateInfo *channel_state_info  = reinterpret_cast<ChannelStateInfo*>(&last_channelstatus_.Block_Header.SYNC1 + index);
                 bool pvt_status = false;
                 uint16_t pvt_status_mask = std::pow(2,15)+std::pow(2,14);
                 for(int k = 15; k != -1; k -= 2)
                 {
                     uint16_t pvt_status_value = (channel_state_info->PVTStatus & pvt_status_mask) >> k-1;
                     //ROS_DEBUG("value is %u and channel_state_info->PVTStatus is %u", pvt_status_value, channel_state_info->PVTStatus);
                     if (pvt_status_value == 2)
                     {
                         pvt_status = true;
                     }
                     if (k > 1)
                     {
                         pvt_status_mask = pvt_status_mask - std::pow(2,k) - std::pow(2,k-1) + std::pow(2,k-2) + std::pow(2,k-3);
                     }
                 }
                 if (pvt_status)
                 {
                     svid_pvt.push_back(static_cast<int32_t>(channel_sat_info->SVID));
                 }
                 index += sb2_size;
             }
         }
     }
     msg->status.satellite_used_prn = svid_pvt; // Entries such as int32[] in ROS messages are to be treated as std::vectors.
     msg->status.satellites_visible = static_cast<uint16_t>(svid_in_sync.size());
     msg->status.satellite_visible_prn = svid_in_sync_2;
     msg->status.satellite_visible_z = elevation_tracked;
     msg->status.satellite_visible_azimuth = azimuth_tracked;
     // Reordering CNO vector to that of all previous arrays
     std::vector<int32_t> cno_tracked_reordered;
     //ROS_DEBUG("size svid_in_sync is %i, size of cno_tracked is %i, size of svid_in_sync_2 is %i", static_cast<int32_t>(svid_in_sync.size()), static_cast<int32_t>(cno_tracked.size()), static_cast<int32_t>(svid_in_sync_2.size()));
     if (static_cast<int32_t>(last_channelstatus_.N) != 0)
     {
         for (int32_t k = 0; k < static_cast<int32_t>(ordering.size()); ++k)
         {
             cno_tracked_reordered.push_back(cno_tracked[ordering[k]]);
         }
     }
     msg->status.satellite_visible_snr = cno_tracked_reordered;
     // PVT Status Analysis
     uint16_t status_mask = 15; // We extract the first four bits using this mask.
     uint16_t type_of_pvt = ((uint16_t) (last_pvtgeodetic_.Mode)) & status_mask;
     switch(type_of_pvt)
     {
         case 0:
         {
             msg->status.status = gps_common::GPSStatus::STATUS_NO_FIX;
             break;
         }
         case 1: case 3:
         {
             msg->status.status = gps_common::GPSStatus::STATUS_FIX;
             break;
         }
         case 2: case 4: case 5: case 7: case 8: case 10:
         {
             msg->status.status = gps_common::GPSStatus::STATUS_GBAS_FIX;
             break;
         }
         case 6:
         {
             uint16_t reference_id = last_pvtgeodetic_.ReferenceID;
             if (reference_id == 131 || reference_id == 133 || reference_id == 135 || reference_id == 135) // PRNs of the 4 WAAS satellites
             {
                 msg->status.status = gps_common::GPSStatus::STATUS_WAAS_FIX;
             }
             else
             {
                 msg->status.status = gps_common::GPSStatus::STATUS_SBAS_FIX;
             }
             break;
         }
         default:
         {
             throw std::runtime_error("PVTGeodetic's Mode field contains an invalid type of PVT solution.");
         }
     }
     msg->status.motion_source = gps_common::GPSStatus::SOURCE_POINTS; // Doppler is not used when calculating the velocities of mosaic.
     msg->status.orientation_source = gps_common::GPSStatus::SOURCE_POINTS; // Doppler is not used when calculating the orientation of mosaic.
     msg->status.position_source = gps_common::GPSStatus::SOURCE_GPS;
     msg->latitude = static_cast<double>(last_pvtgeodetic_.Latitude)*360/(2*boost::math::constants::pi<double>());
     msg->longitude = static_cast<double>(last_pvtgeodetic_.Longitude)*360/(2*boost::math::constants::pi<double>());
     msg->altitude = static_cast<double>(last_pvtgeodetic_.Height);
     msg->track = static_cast<double>(last_pvtgeodetic_.COG); // Note that COG is of type float32 while track is of type float64.
     msg->speed = std::sqrt(std::pow(static_cast<double>(last_pvtgeodetic_.Vn), 2) + std::pow(static_cast<double>(last_pvtgeodetic_.Ve), 2));
     msg->climb = static_cast<double>(last_pvtgeodetic_.Vu);
     msg->pitch = static_cast<double>(last_atteuler_.Pitch);
     msg->roll = static_cast<double>(last_atteuler_.Roll);
     if (last_dop_.PDOP == static_cast<uint16_t>(0) || last_dop_.TDOP == static_cast<uint16_t>(0))
     {
         msg->gdop = static_cast<double>(-1);
     }
     else
     {
         msg->gdop = std::sqrt(std::pow(static_cast<double>(last_dop_.PDOP)/100, 2) + std::pow(static_cast<double>(last_dop_.TDOP)/100, 2));
     }
     if (last_dop_.PDOP == static_cast<uint16_t>(0))
     {
         msg->pdop = static_cast<double>(-1);
     }
     else
     {
         msg->pdop = static_cast<double>(last_dop_.PDOP)/100;
     }
     if (last_dop_.HDOP == static_cast<uint16_t>(0))
     {
         msg->hdop = static_cast<double>(-1);
     }
     else
     {
         msg->hdop = static_cast<double>(last_dop_.HDOP)/100;
     }
     if (last_dop_.VDOP == static_cast<uint16_t>(0))
     {
         msg->vdop = static_cast<double>(-1);
     }
     else
     {
         msg->vdop = static_cast<double>(last_dop_.VDOP)/100;
     }
     if (last_dop_.TDOP == static_cast<uint16_t>(0))
     {
         msg->tdop = static_cast<double>(-1);
     }
     else
     {
         msg->tdop = static_cast<double>(last_dop_.TDOP)/100;
     }
     msg->time = static_cast<double>(last_pvtgeodetic_.TOW)/1000 + static_cast<double>(last_pvtgeodetic_.WNc*7*24*60*60);
     msg->err = 2*(std::sqrt(static_cast<double>(last_poscovgeodetic_.Cov_latlat) + static_cast<double>(last_poscovgeodetic_.Cov_lonlon) + static_cast<double>(last_poscovgeodetic_.Cov_hgthgt)));
     msg->err_horz = 2*(std::sqrt(static_cast<double>(last_poscovgeodetic_.Cov_latlat) + static_cast<double>(last_poscovgeodetic_.Cov_lonlon)));
     msg->err_vert = 2*std::sqrt(static_cast<double>(last_poscovgeodetic_.Cov_hgthgt));
     msg->err_track = 2*(std::sqrt(std::pow(static_cast<double>(1)/(static_cast<double>(last_pvtgeodetic_.Vn)+std::pow(static_cast<double>(last_pvtgeodetic_.Ve),2)/static_cast<double>(last_pvtgeodetic_.Vn)),2)*static_cast<double>(last_poscovgeodetic_.Cov_lonlon)+std::pow((static_cast<double>(last_pvtgeodetic_.Ve))/(std::pow(static_cast<double>(last_pvtgeodetic_.Vn),2)+std::pow(static_cast<double>(last_pvtgeodetic_.Ve),2)),2)*static_cast<double>(last_poscovgeodetic_.Cov_latlat)));
     msg->err_speed = 2*(std::sqrt(static_cast<double>(last_velcovgeodetic_.Cov_VnVn) + static_cast<double>(last_velcovgeodetic_.Cov_VeVe)));
     msg->err_climb = 2*std::sqrt(static_cast<double>(last_velcovgeodetic_.Cov_VuVu));
     msg->err_time = 2*std::sqrt(static_cast<double>(last_poscovgeodetic_.Cov_bb));
     msg->err_pitch = 2*std::sqrt(static_cast<double>(last_attcoveuler_.Cov_PitchPitch));
     msg->err_roll = 2*std::sqrt(static_cast<double>(last_attcoveuler_.Cov_RollRoll));
     msg->position_covariance[0] = static_cast<double>(last_poscovgeodetic_.Cov_lonlon);
     msg->position_covariance[1] = static_cast<double>(last_poscovgeodetic_.Cov_latlon);
     msg->position_covariance[2] = static_cast<double>(last_poscovgeodetic_.Cov_lonhgt);
     msg->position_covariance[3] = static_cast<double>(last_poscovgeodetic_.Cov_latlon);
     msg->position_covariance[4] = static_cast<double>(last_poscovgeodetic_.Cov_latlat);
     msg->position_covariance[5] = static_cast<double>(last_poscovgeodetic_.Cov_lathgt);
     msg->position_covariance[6] = static_cast<double>(last_poscovgeodetic_.Cov_lonhgt);
     msg->position_covariance[7] = static_cast<double>(last_poscovgeodetic_.Cov_lathgt);
     msg->position_covariance[8] = static_cast<double>(last_poscovgeodetic_.Cov_hgthgt);
     msg->position_covariance_type = sensor_msgs::NavSatFix::COVARIANCE_TYPE_KNOWN;
     return msg;
 }
IsConnectionDescriptor()
bool io_comm_mosaic::mosaicMessage::IsConnectionDescriptor ()
Determines whether data_ currently points to a connection descriptor (right after initiating TCP connection)
Definition at line 794 of file mosaicMessage.cpp.
References CONNECTION_DESCRIPTOR_BYTE_1, CONNECTION_DESCRIPTOR_BYTE_2, and data_.
Referenced by Found(), mosaicMessage(), Next(), io_comm_mosaic::CallbackHandlers::ReadCallback(), and Search().
 {
     if (data_[0] == CONNECTION_DESCRIPTOR_BYTE_1 && data_[1] == CONNECTION_DESCRIPTOR_BYTE_2)
     {
         return true;
     }
     else
     {
         return false;
     }
 }
IsErrorMessage()
bool io_comm_mosaic::mosaicMessage::IsErrorMessage ()
Determines whether data_ currently points to an error message reply from mosaic.
Definition at line 806 of file mosaicMessage.cpp.
References data_, RESPONSE_SYNC_BYTE_1, RESPONSE_SYNC_BYTE_2, and RESPONSE_SYNC_BYTE_3.
Referenced by mosaicMessage(), and io_comm_mosaic::CallbackHandlers::ReadCallback().
 {
     if (data_[0] == RESPONSE_SYNC_BYTE_1 && data_[1] == RESPONSE_SYNC_BYTE_2 && data_[2] == RESPONSE_SYNC_BYTE_3)
     {
         return true;
     }
     else
     {
         return false;
     }
 }
IsMessage() [1/2]
bool io_comm_mosaic::mosaicMessage::IsMessage (const uint16_t ID)
Determines whether data_ points to the SBF block with ID "ID", e.g. 5003.
Definition at line 712 of file mosaicMessage.cpp.
References data_, and IsSBF().
Referenced by mosaicMessage().
 {
     if (this->IsSBF())
     {
         uint16_t mask = 8191;
         if (*(reinterpret_cast<const uint16_t *>(data_ + 4)) & mask == static_cast<const uint16_t>(ID))
         // Caution: reinterpret_cast is the most dangerous cast, It's used primarily for particularly weird conversions and bit manipulations, like turning a raw data stream into actual data
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
IsMessage() [2/2]
bool io_comm_mosaic::mosaicMessage::IsMessage (std::string ID)
Determines whether data_ points to the NMEA message with ID "ID", e.g. "$GPGGA".
Definition at line 734 of file mosaicMessage.cpp.
References data_, IsNMEA(), and SegmentEnd().
 {
     if (this->IsNMEA())
     {
         boost::char_separator<char> sep(",");
         typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
         std::size_t nmea_size = std::min(this->SegmentEnd(), static_cast<std::size_t>(89));
         std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
         tokenizer tokens(block_in_string,sep);
         if (*tokens.begin() == ID)
         {
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
IsNMEA()
bool io_comm_mosaic::mosaicMessage::IsNMEA ()
Determines whether data_ currently points to an NMEA message.
Definition at line 770 of file mosaicMessage.cpp.
References data_, NMEA_SYNC_BYTE_1, NMEA_SYNC_BYTE_2_1, and NMEA_SYNC_BYTE_2_2.
Referenced by Found(), IsMessage(), MessageID(), mosaicMessage(), Next(), io_comm_mosaic::CallbackHandlers::ReadCallback(), and Search().
 {
     if ((data_[0] == NMEA_SYNC_BYTE_1 && data_[1] == NMEA_SYNC_BYTE_2_1) || (data_[0] == NMEA_SYNC_BYTE_1 && data_[1] == NMEA_SYNC_BYTE_2_2))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
IsResponse()
bool io_comm_mosaic::mosaicMessage::IsResponse ()
Determines whether data_ currently points to an NMEA message.
Definition at line 782 of file mosaicMessage.cpp.
References data_, RESPONSE_SYNC_BYTE_1, and RESPONSE_SYNC_BYTE_2.
Referenced by Found(), mosaicMessage(), Next(), io_comm_mosaic::CallbackHandlers::ReadCallback(), Search(), and SegmentEnd().
 {
     if (data_[0] == RESPONSE_SYNC_BYTE_1 && data_[1] == RESPONSE_SYNC_BYTE_2)
     {
         return true;
     }
     else
     {
         return false;
     }
 }
IsSBF()
bool io_comm_mosaic::mosaicMessage::IsSBF ()
Determines whether data_ currently points to an SBF block.
Definition at line 758 of file mosaicMessage.cpp.
References data_, SBF_SYNC_BYTE_1, and SBF_SYNC_BYTE_2.
Referenced by BlockLength(), Found(), IsMessage(), MessageID(), mosaicMessage(), Next(), Read(), io_comm_mosaic::CallbackHandlers::ReadCallback(), and Search().
 {
     if (data_[0] == SBF_SYNC_BYTE_1 && data_[1] == SBF_SYNC_BYTE_2)
     {
         return true;
     }
     else
     {
         return false;
     }
 }
MessageID()
std::string io_comm_mosaic::mosaicMessage::MessageID ()
Returns the MessageID of the message where data_ is pointing at at the moment, SBF identifiers embellished with inverted commas, e.g. "5003".
Definition at line 818 of file mosaicMessage.cpp.
References data_, IsNMEA(), IsSBF(), and SegmentEnd().
Referenced by io_comm_mosaic::CallbackHandler< T >::Handle(), io_comm_mosaic::CallbackHandlers::Handle(), mosaicMessage(), Read(), and io_comm_mosaic::CallbackHandlers::ReadCallback().
 {
     if (this->IsSBF())
     {
         // Define bit mask:
         uint16_t mask = 8191; // It is not as stated in the firmware: !first! three bits are for revision (not last 3), and rest for block number
         uint16_t value = (*(reinterpret_cast<const uint16_t*>(data_+4))) & mask; // Bitwise AND gives us all but first 3 bits set to zero, rest unchanged
         std::stringstream ss;
         ss << value;
         return ss.str();
     }
     if (this->IsNMEA())
     {
         boost::char_separator<char> sep(",");
         typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
         std::size_t nmea_size = std::min(this->SegmentEnd(), static_cast<std::size_t>(89));
         std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
         tokenizer tokens(block_in_string,sep);
         return *tokens.begin();
     }
     return std::string(); // less CPU work than return "";
 }
NavSatFixCallback()
sensor_msgs::NavSatFixPtr io_comm_mosaic::mosaicMessage::NavSatFixCallback () private
"Callback" function when constructing NavSatFix messages
Returns
A smart pointer to the ROS message sensor_msgs::NavSatFix just created
The position_covariance array is populated in row-major order, where the basis of the corresponding matrix is ENU (so Cov_lonlon is in location 11 of the matrix). The B2b signal type of BeiDou is not checked for usage, since the SignalInfo field of the PVTGeodetic block does not disclose it. For that, one would need to go to the ObsInfo field of the MeasEpochChannelType1 sub-block.
Definition at line 283 of file mosaicMessage.cpp.
References PosCovGeodetic::Cov_hgthgt, PosCovGeodetic::Cov_lathgt, PosCovGeodetic::Cov_latlat, PosCovGeodetic::Cov_latlon, PosCovGeodetic::Cov_lonhgt, PosCovGeodetic::Cov_lonlon, PVTGeodetic::Height, last_poscovgeodetic_, last_pvtgeodetic_, PVTGeodetic::Latitude, PVTGeodetic::Longitude, PVTGeodetic::Mode, and PVTGeodetic::SignalInfo.
Referenced by Read().
 {
     sensor_msgs::NavSatFixPtr msg = boost::make_shared<sensor_msgs::NavSatFix>();
     uint16_t mask = 15; // We extract the first four bits using this mask.
     uint16_t type_of_pvt = ((uint16_t) (last_pvtgeodetic_.Mode)) & mask;
     switch(type_of_pvt)
     {
         case 0:
         {
             msg->status.status = sensor_msgs::NavSatStatus::STATUS_NO_FIX;
             break;
         }
         case 1: case 3:
         {
             msg->status.status = sensor_msgs::NavSatStatus::STATUS_FIX;
             break;
         }
         case 2: case 4: case 5: case 7: case 8: case 10:
         {
             msg->status.status = sensor_msgs::NavSatStatus::STATUS_GBAS_FIX;
             break;
         }
         case 6:
         {
             msg->status.status = sensor_msgs::NavSatStatus::STATUS_SBAS_FIX;
             break;
         }
         default:
         {
             throw std::runtime_error("PVTGeodetic's Mode field contains an invalid type of PVT solution.");
         }
     }
     bool gps_in_pvt = false;
     bool glo_in_pvt = false;
     bool com_in_pvt = false;
     bool gal_in_pvt = false;
     uint32_t mask_2 = 1;
     for(int bit = 0; bit != 31; ++bit)
     {
         bool in_use = last_pvtgeodetic_.SignalInfo & mask_2;
         if (bit <= 5 && in_use)
         {
             gps_in_pvt = true;
         }
         if (8   <= bit && bit <= 12 && in_use) glo_in_pvt = true;
         if (((13 <= bit && bit <= 14) || (28 <= bit && bit <= 30)) && in_use) com_in_pvt = true;
         if ((bit == 17 || (19 <= bit && bit <= 22)) && in_use) gal_in_pvt = true;
         mask_2 *= 2;
     }
     //ROS_DEBUG("GPS is in use: %s, GLO is in use: %s, COM is in use: %s, GAL is in use: %s", gps_in_pvt ? "true" : "false", glo_in_pvt ? "true" : "false", com_in_pvt ? "true" : "false", gal_in_pvt ? "true" : "false");
     uint16_t service = gps_in_pvt*1+glo_in_pvt*2+com_in_pvt*4+gal_in_pvt*8; // booleans will be promoted to integers automatically
     msg->status.service = service;
     msg->latitude = last_pvtgeodetic_.Latitude*360/(2*boost::math::constants::pi<double>());
     msg->longitude = last_pvtgeodetic_.Longitude*360/(2*boost::math::constants::pi<double>());
     msg->altitude = last_pvtgeodetic_.Height;
     msg->position_covariance[0] = static_cast<double>(last_poscovgeodetic_.Cov_lonlon);
     msg->position_covariance[1] = static_cast<double>(last_poscovgeodetic_.Cov_latlon);
     msg->position_covariance[2] = static_cast<double>(last_poscovgeodetic_.Cov_lonhgt);
     msg->position_covariance[3] = static_cast<double>(last_poscovgeodetic_.Cov_latlon);
     msg->position_covariance[4] = static_cast<double>(last_poscovgeodetic_.Cov_latlat);
     msg->position_covariance[5] = static_cast<double>(last_poscovgeodetic_.Cov_lathgt);
     msg->position_covariance[6] = static_cast<double>(last_poscovgeodetic_.Cov_lonhgt);
     msg->position_covariance[7] = static_cast<double>(last_poscovgeodetic_.Cov_lathgt);
     msg->position_covariance[8] = static_cast<double>(last_poscovgeodetic_.Cov_hgthgt);
     msg->position_covariance_type = sensor_msgs::NavSatFix::COVARIANCE_TYPE_KNOWN;
     return msg;
 }
Next()
const uint8_t * io_comm_mosaic::mosaicMessage::Next ()
Goes to the start of the next message based on the calculated length of current message.
This method won't make data_ jump to the next message if the current one is an NMEA message or a command reply. In that case, search() will check the bytes one by one for the new message's sync bytes ($P, $G or $R).
Definition at line 872 of file mosaicMessage.cpp.
References BlockLength(), cd_count, count_, CRCcheck_, data_, Found(), found_, IsConnectionDescriptor(), IsNMEA(), IsResponse(), IsSBF(), and read_cd.
Referenced by GetCount(), and Search().
 {
     if (Found())
     {
         if (this->IsNMEA() || this->IsResponse() || (read_cd && this->IsConnectionDescriptor()))
         {
             if (read_cd && this->IsConnectionDescriptor() && cd_count == 2)
             {
                 read_cd = false;
             }
             --count_;
             ++data_;
             found_ = false;
             return data_;
         }
         if (this->IsSBF())
         {
             uint32_t jump_size;
             if (CRCcheck_)
             {
                 jump_size = this->BlockLength();
                 if (jump_size == 0) jump_size = 1;  // Some corrupted messages that survive the CRC check (this happened) could tell ROSaic their size is 0,
                                                     // which would lead to an endless while loop in the ReadCallback() method of the CallbackHandlers class.
             }
             else
             {
                 jump_size = 1;
             }
             //ROS_DEBUG("Jump about to happen with jump size %u", jump_size);
             data_ += jump_size; count_ -= jump_size;
             found_ = false;
             return data_;
         }
     }
     found_ = false;
     --count_;
     ++data_;
     return data_;
 }
Pos()
const uint8_t * io_comm_mosaic::mosaicMessage::Pos ()
Gets the current position in the read buffer.
Returns
The current position of the read buffer
Definition at line 843 of file mosaicMessage.cpp.
References data_.
Referenced by GetCount(), and io_comm_mosaic::CallbackHandlers::ReadCallback().
 {
     return data_;
 }
PosCovCartesianCallback()
rosaic::PosCovCartesianPtr io_comm_mosaic::mosaicMessage::PosCovCartesianCallback (PosCovCartesian & data) private
Callback function when reading PosCovCartesian blocks.
Parameters
[in] data The (packed and aligned) struct instance that we use to populate our ROS message rosaic::PosCovCartesian
Returns
A smart pointer to the ROS message rosaic::PosCovCartesian just created
Definition at line 129 of file mosaicMessage.cpp.
References PosCovCartesian::Block_Header, PosCovCartesian::Cov_bb, PosCovCartesian::Cov_xb, PosCovCartesian::Cov_xx, PosCovCartesian::Cov_xy, PosCovCartesian::Cov_xz, PosCovCartesian::Cov_yb, PosCovCartesian::Cov_yy, PosCovCartesian::Cov_yz, PosCovCartesian::Cov_zb, PosCovCartesian::Cov_zz, BlockHeader_t::CRC, PosCovCartesian::Error, BlockHeader_t::ID, BlockHeader_t::Length, PosCovCartesian::Mode, BlockHeader_t::SYNC1, BlockHeader_t::SYNC2, PosCovCartesian::TOW, and PosCovCartesian::WNc.
Referenced by Read().
 {
     rosaic::PosCovCartesianPtr msg = boost::make_shared<rosaic::PosCovCartesian>();
     msg->Block_Header.SYNC1 = data.Block_Header.SYNC1;
     msg->Block_Header.SYNC2 = data.Block_Header.SYNC2;
     msg->Block_Header.CRC = data.Block_Header.CRC;
     msg->Block_Header.ID = data.Block_Header.ID;
     msg->Block_Header.Length = data.Block_Header.Length;
     msg->Block_Header.TOW = data.TOW;
     msg->Block_Header.WNc = data.WNc;
     msg->Mode = data.Mode;
     msg->Error = data.Error;
     msg->Cov_xx = data.Cov_xx;
     msg->Cov_yy = data.Cov_yy;
     msg->Cov_zz = data.Cov_zz;
     msg->Cov_bb = data.Cov_bb;
     msg->Cov_xy = data.Cov_xy;
     msg->Cov_xz = data.Cov_xz;
     msg->Cov_xb = data.Cov_xb;
     msg->Cov_yz = data.Cov_yz;
     msg->Cov_yb = data.Cov_yb;
     msg->Cov_zb = data.Cov_zb;
     return msg;
 }
PosCovGeodeticCallback()
rosaic::PosCovGeodeticPtr io_comm_mosaic::mosaicMessage::PosCovGeodeticCallback (PosCovGeodetic & data) private
Callback function when reading PosCovGeodetic blocks.
Parameters
[in] data The (packed and aligned) struct instance that we use to populate our ROS message rosaic::PosCovGeodetic
Returns
A smart pointer to the ROS message rosaic::PosCovGeodetic just created
Definition at line 155 of file mosaicMessage.cpp.
References PosCovGeodetic::Block_Header, PosCovGeodetic::Cov_bb, PosCovGeodetic::Cov_hb, PosCovGeodetic::Cov_hgthgt, PosCovGeodetic::Cov_latb, PosCovGeodetic::Cov_lathgt, PosCovGeodetic::Cov_latlat, PosCovGeodetic::Cov_latlon, PosCovGeodetic::Cov_lonb, PosCovGeodetic::Cov_lonhgt, PosCovGeodetic::Cov_lonlon, BlockHeader_t::CRC, PosCovGeodetic::Error, BlockHeader_t::ID, BlockHeader_t::Length, PosCovGeodetic::Mode, BlockHeader_t::SYNC1, BlockHeader_t::SYNC2, PosCovGeodetic::TOW, and PosCovGeodetic::WNc.
Referenced by Read().
 {
     rosaic::PosCovGeodeticPtr msg = boost::make_shared<rosaic::PosCovGeodetic>();
     msg->Block_Header.SYNC1 = data.Block_Header.SYNC1;
     msg->Block_Header.SYNC2 = data.Block_Header.SYNC2;
     msg->Block_Header.CRC = data.Block_Header.CRC;
     msg->Block_Header.ID = data.Block_Header.ID;
     msg->Block_Header.Length = data.Block_Header.Length;
     msg->Block_Header.TOW = data.TOW;
     msg->Block_Header.WNc = data.WNc;
     msg->Mode = data.Mode;
     msg->Error = data.Error;
     msg->Cov_latlat = data.Cov_latlat;
     msg->Cov_lonlon = data.Cov_lonlon;
     msg->Cov_hgthgt = data.Cov_hgthgt;
     msg->Cov_bb = data.Cov_bb;
     msg->Cov_latlon = data.Cov_latlon;
     msg->Cov_lathgt = data.Cov_lathgt;
     msg->Cov_latb = data.Cov_latb;
     msg->Cov_lonhgt = data.Cov_lonhgt;
     msg->Cov_lonb = data.Cov_lonb;
     msg->Cov_hb = data.Cov_hb;
     return msg;
 }
PoseWithCovarianceStampedCallback()
geometry_msgs::PoseWithCovarianceStampedPtr io_comm_mosaic::mosaicMessage::PoseWithCovarianceStampedCallback () private
"Callback" function when constructing PoseWithCovarianceStamped messages
Returns
A smart pointer to the ROS message geometry_msgs::PoseWithCovarianceStamped just created
Todo:
Replaces the zeros in the covariance fields with proper estimations of those quantities
The position_covariance array is populated in row-major order, where the basis of the correspond matrix is (E, N, U, Roll, Pitch, Heading). Important: The Euler angles (Roll, Pitch, Heading) are with respect to a vehicle-fixed (e.g. for mosaic-x5 in moving base mode via the command setAntennaLocation, ...) !local! NED frame. Thus the orientation is !not! given with respect to the same frame as the position is given in. The cross-covariances are hence (apart from the fact that e.g. mosaic receivers do not calculate these quantities) set to zero. The position and the partial (with 2 antennas) or full (for INS receivers) orientation have covariances matrices available e.g. in the PosCovGeodetic or AttCovEuler blocks, yet those are separate computations.
Definition at line 229 of file mosaicMessage.cpp.
References AttCovEuler::Cov_HeadHead, AttCovEuler::Cov_HeadPitch, AttCovEuler::Cov_HeadRoll, PosCovGeodetic::Cov_hgthgt, PosCovGeodetic::Cov_lathgt, PosCovGeodetic::Cov_latlat, PosCovGeodetic::Cov_latlon, PosCovGeodetic::Cov_lonhgt, PosCovGeodetic::Cov_lonlon, AttCovEuler::Cov_PitchPitch, AttCovEuler::Cov_PitchRoll, AttCovEuler::Cov_RollRoll, AttEuler::Heading, PVTGeodetic::Height, last_attcoveuler_, last_atteuler_, last_poscovgeodetic_, last_pvtgeodetic_, PVTGeodetic::Latitude, PVTGeodetic::Longitude, AttEuler::Pitch, AttEuler::Roll, and parsing_utilities::ToQuaternion().
Referenced by Read().
 {
     geometry_msgs::PoseWithCovarianceStampedPtr msg = boost::make_shared<geometry_msgs::PoseWithCovarianceStamped>();
     // Filling in the pose data
     msg->pose.pose.orientation = parsing_utilities::ToQuaternion(static_cast<double>(last_atteuler_.Heading), static_cast<double>(last_atteuler_.Pitch), static_cast<double>(last_atteuler_.Roll));
     msg->pose.pose.position.x = static_cast<double>(last_pvtgeodetic_.Longitude)*360/(2*boost::math::constants::pi<double>());
     msg->pose.pose.position.y = static_cast<double>(last_pvtgeodetic_.Latitude)*360/(2*boost::math::constants::pi<double>());
     msg->pose.pose.position.z = static_cast<double>(last_pvtgeodetic_.Height);
     // Filling in the covariance data in row-major order
     msg->pose.covariance[0] = static_cast<double>(last_poscovgeodetic_.Cov_lonlon);
     msg->pose.covariance[1] = static_cast<double>(last_poscovgeodetic_.Cov_latlon);
     msg->pose.covariance[2] = static_cast<double>(last_poscovgeodetic_.Cov_lonhgt);
     msg->pose.covariance[3] = 0;
     msg->pose.covariance[4] = 0;
     msg->pose.covariance[5] = 0;
     msg->pose.covariance[6] = static_cast<double>(last_poscovgeodetic_.Cov_latlon);
     msg->pose.covariance[7] = static_cast<double>(last_poscovgeodetic_.Cov_latlat);
     msg->pose.covariance[8] = static_cast<double>(last_poscovgeodetic_.Cov_lathgt);
     msg->pose.covariance[9] = 0;
     msg->pose.covariance[10] = 0;
     msg->pose.covariance[11] = 0;
     msg->pose.covariance[12] = static_cast<double>(last_poscovgeodetic_.Cov_lonhgt);
     msg->pose.covariance[13] = static_cast<double>(last_poscovgeodetic_.Cov_lathgt);
     msg->pose.covariance[14] = static_cast<double>(last_poscovgeodetic_.Cov_hgthgt);
     msg->pose.covariance[15] = 0;
     msg->pose.covariance[16] = 0;
     msg->pose.covariance[17] = 0;
     msg->pose.covariance[18] = 0;
     msg->pose.covariance[19] = 0;
     msg->pose.covariance[20] = 0;
     msg->pose.covariance[21] = static_cast<double>(last_attcoveuler_.Cov_RollRoll);
     msg->pose.covariance[22] = static_cast<double>(last_attcoveuler_.Cov_PitchRoll);
     msg->pose.covariance[23] = static_cast<double>(last_attcoveuler_.Cov_HeadRoll);
     msg->pose.covariance[24] = 0;
     msg->pose.covariance[25] = 0;
     msg->pose.covariance[26] = 0;
     msg->pose.covariance[27] = static_cast<double>(last_attcoveuler_.Cov_PitchRoll);
     msg->pose.covariance[28] = static_cast<double>(last_attcoveuler_.Cov_PitchPitch);
     msg->pose.covariance[29] = static_cast<double>(last_attcoveuler_.Cov_HeadPitch);
     msg->pose.covariance[30] = 0;
     msg->pose.covariance[31] = 0;
     msg->pose.covariance[32] = 0;
     msg->pose.covariance[33] = static_cast<double>(last_attcoveuler_.Cov_HeadRoll);
     msg->pose.covariance[34] = static_cast<double>(last_attcoveuler_.Cov_PitchRoll);
     msg->pose.covariance[35] = static_cast<double>(last_attcoveuler_.Cov_HeadHead);
     return msg;
 }
PVTCartesianCallback()
rosaic::PVTCartesianPtr io_comm_mosaic::mosaicMessage::PVTCartesianCallback (PVTCartesian & data) private
Callback function when reading PVTCartesian blocks.
Parameters
[in] data The (packed and aligned) struct instance that we use to populate our ROS message rosaic::PVTCartesian
Returns
A smart pointer to the ROS message rosaic::PVTCartesian just created
Definition at line 90 of file mosaicMessage.cpp.
References PVTCartesian::AlertFlag, PVTCartesian::Block_Header, PVTCartesian::COG, BlockHeader_t::CRC, PVTCartesian::Datum, PVTCartesian::Error, PVTCartesian::HAccuracy, BlockHeader_t::ID, PVTCartesian::Latency, BlockHeader_t::Length, PVTCartesian::MeanCorrAge, PVTCartesian::Misc, PVTCartesian::Mode, PVTCartesian::NrBases, PVTCartesian::NrSV, PVTCartesian::PPPInfo, PVTCartesian::ReferenceID, PVTCartesian::RxClkBias, PVTCartesian::RxClkDrift, PVTCartesian::SignalInfo, BlockHeader_t::SYNC1, BlockHeader_t::SYNC2, PVTCartesian::TimeSystem, PVTCartesian::TOW, PVTCartesian::Undulation, PVTCartesian::VAccuracy, PVTCartesian::Vx, PVTCartesian::Vy, PVTCartesian::Vz, PVTCartesian::WACorrInfo, PVTCartesian::WNc, PVTCartesian::X, PVTCartesian::Y, and PVTCartesian::Z.
Referenced by Read().
 {
     rosaic::PVTCartesianPtr msg = boost::make_shared<rosaic::PVTCartesian>();
     msg->Block_Header.SYNC1 = data.Block_Header.SYNC1;
     msg->Block_Header.SYNC2 = data.Block_Header.SYNC2;
     msg->Block_Header.CRC = data.Block_Header.CRC;
     msg->Block_Header.ID = data.Block_Header.ID;
     msg->Block_Header.Length = data.Block_Header.Length;
     msg->Block_Header.TOW = data.TOW;
     msg->Block_Header.WNc = data.WNc;
     msg->Mode = data.Mode;
     msg->Error = data.Error;
     msg->X = data.X;
     msg->Y = data.Y;
     msg->Z = data.Z;
     msg->Undulation = data.Undulation;
     msg->Vx = data.Vx;
     msg->Vy = data.Vy;
     msg->Vz = data.Vz;
     msg->COG = data.COG;
     msg->RxClkBias = data.RxClkBias;
     msg->RxClkDrift = data.RxClkDrift;
     msg->TimeSystem = data.TimeSystem;
     msg->Datum = data.Datum;
     msg->NrSV = data.NrSV;
     msg->WACorrInfo = data.WACorrInfo;
     msg->ReferenceID = data.ReferenceID;
     msg->MeanCorrAge = data.MeanCorrAge;
     msg->SignalInfo = data.SignalInfo;
     msg->AlertFlag = data.AlertFlag;
     msg->NrBases = data.NrBases;
     msg->PPPInfo = data.PPPInfo;
     msg->Latency = data.Latency;
     msg->HAccuracy = data.HAccuracy;
     msg->VAccuracy = data.VAccuracy;
     msg->Misc = data.Misc;
     return msg;
 }
PVTGeodeticCallback()
rosaic::PVTGeodeticPtr io_comm_mosaic::mosaicMessage::PVTGeodeticCallback (PVTGeodetic & data) private
Callback function when reading PVTGeodetic blocks.
Parameters
[in] data The (packed and aligned) struct instance that we use to populate our ROS message rosaic::PVTGeodetic
Returns
A smart pointer to the ROS message rosaic::PVTGeodetic just created
Definition at line 50 of file mosaicMessage.cpp.
References PVTGeodetic::AlertFlag, PVTGeodetic::Block_Header, PVTGeodetic::COG, BlockHeader_t::CRC, PVTGeodetic::Datum, PVTGeodetic::Error, PVTGeodetic::HAccuracy, PVTGeodetic::Height, BlockHeader_t::ID, PVTGeodetic::Latency, PVTGeodetic::Latitude, BlockHeader_t::Length, PVTGeodetic::Longitude, PVTGeodetic::MeanCorrAge, PVTGeodetic::Misc, PVTGeodetic::Mode, PVTGeodetic::NrBases, PVTGeodetic::NrSV, PVTGeodetic::PPPInfo, PVTGeodetic::ReferenceID, PVTGeodetic::RxClkBias, PVTGeodetic::RxClkDrift, PVTGeodetic::SignalInfo, BlockHeader_t::SYNC1, BlockHeader_t::SYNC2, PVTGeodetic::TimeSystem, PVTGeodetic::TOW, PVTGeodetic::Undulation, PVTGeodetic::VAccuracy, PVTGeodetic::Ve, PVTGeodetic::Vn, PVTGeodetic::Vu, PVTGeodetic::WACorrInfo, and PVTGeodetic::WNc.
Referenced by Read().
 {
     rosaic::PVTGeodeticPtr msg = boost::make_shared<rosaic::PVTGeodetic>();
     msg->Block_Header.SYNC1 = data.Block_Header.SYNC1;
     msg->Block_Header.SYNC2 = data.Block_Header.SYNC2;
     msg->Block_Header.CRC = data.Block_Header.CRC;
     msg->Block_Header.ID = data.Block_Header.ID;
     msg->Block_Header.Length = data.Block_Header.Length;
     msg->Block_Header.TOW = data.TOW;
     msg->Block_Header.WNc = data.WNc;
     msg->Mode = data.Mode;
     msg->Error = data.Error;
     msg->Latitude = data.Latitude;
     msg->Longitude = data.Longitude;
     msg->Height = data.Height;
     msg->Undulation = data.Undulation;
     msg->Vn = data.Vn;
     msg->Ve = data.Ve;
     msg->Vu = data.Vu;
     msg->COG = data.COG;
     msg->RxClkBias = data.RxClkBias;
     msg->RxClkDrift = data.RxClkDrift;
     msg->TimeSystem = data.TimeSystem;
     msg->Datum = data.Datum;
     msg->NrSV = data.NrSV;
     msg->WACorrInfo = data.WACorrInfo;
     msg->ReferenceID = data.ReferenceID;
     msg->MeanCorrAge = data.MeanCorrAge;
     msg->SignalInfo = data.SignalInfo;
     msg->AlertFlag = data.AlertFlag;
     msg->NrBases = data.NrBases;
     msg->PPPInfo = data.PPPInfo;
     msg->Latency = data.Latency;
     msg->HAccuracy = data.HAccuracy;
     msg->VAccuracy = data.VAccuracy;
     msg->Misc = data.Misc;
     return msg;
 }
Read()
template<typename T > bool io_comm_mosaic::mosaicMessage::Read (typename boost::call_traits< T >::reference message, std::string message_key, bool search = false)
Performs the CRC check (if SBF block) and populates message with the necessary content (mapped 1-to-1 if SBF, parsed if NMEA), works for pure ROS message mapping.
Returns
True if read was successful, false otherwise
Note that boost::call_traits<T>::reference is more robust than traditional T&. Note that this function also assigns the appropriate derived parser in case T is an NMEA message. Note that putting the default in the definition's argument list instead of the declaration's is an added extra that is not available for function templates, hence no search = false here. Finally note that it is bad practice (one gets undefined reference to .. error) to separate the definition of template functions into the source file and declarations into header file. Also note that the SBF block header part of the SBF-echoing ROS messages have ID fields that only show the block number as found in the firmware (e.g. 4007 for PVTGeodetic), without the revision number. NMEA 0183 messages are at most 82 characters long in principle, but mosaic by default increases precision on lat/lon s.t. the maximum allowed e.g. for GGA seems to be 89. Luckily, when parsing we do not care since we just search for <LF><CR>.
Definition at line 432 of file mosaicMessage.hpp.
References AttCovEulerCallback(), AttEulerCallback(), BlockLength(), count_, count_gpsfix_, CRCcheck_, CRCIsValid(), data_, evAttCovEuler, evAttEuler, evChannelStatus, evDOP, evGAGSV, evGLGSV, evGPGGA, evGPGSA, evGPGSV, evGPRMC, evGPSFix, evGPST, evMeasEpoch, evNavSatFix, evPosCovCartesian, evPosCovGeodetic, evPoseWithCovarianceStamped, evPVTCartesian, evPVTGeodetic, evVelCovGeodetic, Found(), frame_id, GPSFixCallback(), IsSBF(), last_attcoveuler_, last_atteuler_, last_channelstatus_, last_dop_, last_measepoch_, last_poscovgeodetic_, last_pvtgeodetic_, last_velcovgeodetic_, MessageID(), NavSatFixCallback(), GpggaParser::ParseASCII(), GpgsvParser::ParseASCII(), GprmcParser::ParseASCII(), GpgsaParser::ParseASCII(), PosCovCartesianCallback(), PosCovGeodeticCallback(), PoseWithCovarianceStampedCallback(), PVTCartesianCallback(), PVTGeodeticCallback(), Search(), SegmentEnd(), io_comm_mosaic::TimestampSBF(), PVTGeodetic::TOW, and use_GNSS_time.
Referenced by GetCount(), and io_comm_mosaic::CallbackHandler< T >::Handle().
     {
         //ROS_DEBUG("message key is %s", message_key.c_str());
         if (search) this->Search();
         if (!Found()) return false;
         if (this->IsSBF())
         {
             // If the CRC check is unsuccessful, throw an error message.
             CRCcheck_ = CRCIsValid(data_);
             if (!CRCcheck_)
             {
                 throw std::runtime_error("CRC Check returned False. Not a valid data block, perhaps noisy. Ignore..");
             }
             // If full message did not yet arrive, throw an error message.
             if (this->BlockLength() > count_)
             {
                 throw std::runtime_error("Not a valid data block, parts of the SBF block are not yet received. Ignore..");
             }
         }
         switch(StringValues[message_key])
         {
             case evPVTCartesian: // Position and velocity in XYZ
             {   // The curly bracket here is crucial: Declarations inside a block remain inside, and will die at the end of the block. Otherwise variable overloading etc.
                 rosaic::PVTCartesianPtr msg = boost::make_shared<rosaic::PVTCartesian>();
                 PVTCartesian pvtcartesian;
                 memcpy(&pvtcartesian, data_, sizeof(pvtcartesian));
                 msg = PVTCartesianCallback(pvtcartesian);
                 msg->header.frame_id = frame_id;
                 uint32_t TOW = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->Block_Header.ID = 4006;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evPVTGeodetic: // Position and velocity in geodetic coordinate frame (ENU frame)
             {
                 rosaic::PVTGeodeticPtr msg = boost::make_shared<rosaic::PVTGeodetic>();
                 memcpy(&last_pvtgeodetic_, data_, sizeof(last_pvtgeodetic_));
                 msg = PVTGeodeticCallback(last_pvtgeodetic_);
                 msg->header.frame_id = frame_id;
                 uint32_t TOW = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->Block_Header.ID = 4007;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evPosCovCartesian:
             {
                 rosaic::PosCovCartesianPtr msg = boost::make_shared<rosaic::PosCovCartesian>();
                 PosCovCartesian poscovcartesian;
                 memcpy(&poscovcartesian, data_, sizeof(poscovcartesian));
                 msg = PosCovCartesianCallback(poscovcartesian);
                 msg->header.frame_id = frame_id;
                 uint32_t TOW = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->Block_Header.ID = 5905;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evPosCovGeodetic:
             {
                 rosaic::PosCovGeodeticPtr msg = boost::make_shared<rosaic::PosCovGeodetic>();
                 memcpy(&last_poscovgeodetic_, data_, sizeof(last_poscovgeodetic_));
                 msg = PosCovGeodeticCallback(last_poscovgeodetic_);
                 msg->header.frame_id = frame_id;
                 uint32_t TOW = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->Block_Header.ID = 5906;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evAttEuler:
             {
                 rosaic::AttEulerPtr msg = boost::make_shared<rosaic::AttEuler>();
                 memcpy(&last_atteuler_, data_, sizeof(last_atteuler_));
                 msg = AttEulerCallback(last_atteuler_);
                 msg->header.frame_id = frame_id;
                 uint32_t TOW = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->Block_Header.ID = 5938;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evAttCovEuler:
             {
                 rosaic::AttCovEulerPtr msg = boost::make_shared<rosaic::AttCovEuler>();
                 memcpy(&last_attcoveuler_, data_, sizeof(last_attcoveuler_));
                 msg = AttCovEulerCallback(last_attcoveuler_);
                 msg->header.frame_id = frame_id;
                 uint32_t TOW = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->Block_Header.ID = 5939;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evGPST:
             {
                 sensor_msgs::TimeReferencePtr msg = boost::make_shared<sensor_msgs::TimeReference>();
                 uint32_t TOW = *(reinterpret_cast<const uint32_t *>(data_ + 8));
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, true); // We need the GPS time, hence true
                 msg->time_ref.sec = time_obj.sec;
                 msg->time_ref.nsec = time_obj.nsec;
                 msg->source = "GPST";
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evGPGGA:
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = std::min(this->SegmentEnd(), static_cast<std::size_t>(89));
                 std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 std::string id = this->MessageID();
                 std::string one_message = *tokens.begin();
                 boost::char_separator<char> sep_2(",*", "", boost::keep_empty_tokens);  // No kept delimiters, hence "". Also, we specify that empty tokens should show up in the output when two delimiters are next to each other.
                                                                                         // Hence we also append the checksum part of the GGA message to "body" below, though it is not parsed.
                 tokenizer tokens_2(one_message, sep_2);
                 std::vector<std::string> body;
                 for (tokenizer::iterator tok_iter = tokens_2.begin(); tok_iter != tokens_2.end(); ++tok_iter) // perhaps str.erase from <string.h> would be faster, but i would not know what exactly to do..
                 {
                     body.push_back(*tok_iter);
                 }
                 // Create NmeaSentence struct to pass to GpggaParser::ParseASCII
                 NMEASentence gga_message(id, body);
                 rosaic::GpggaPtr gpgga_ros_message_ptr;
                 GpggaParser parser_obj;
                 try
                 {
                     gpgga_ros_message_ptr = parser_obj.ParseASCII(gga_message);
                 }
                 catch (ParseException& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 //ROS_DEBUG("ID is %s, size of message is %lu and sizeof ptr is %lu", gpgga_ros_message_ptr->message_id.c_str(), sizeof(message), sizeof(*gpgga_ros_message_ptr));
                 memcpy(&message, gpgga_ros_message_ptr.get(), sizeof(*gpgga_ros_message_ptr));
                 break;
             }
             case evGPRMC:
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = std::min(this->SegmentEnd(), static_cast<std::size_t>(89));
                 std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 std::string id = this->MessageID();
                 std::string one_message = *tokens.begin();
                 boost::char_separator<char> sep_2(",*", "", boost::keep_empty_tokens);  // No kept delimiters, hence "". Also, we specify that empty tokens should show up in the output when two delimiters are next to each other.
                                                                                         // Hence we also append the checksum part of the GGA message to "body" below, though it is not parsed.
                 tokenizer tokens_2(one_message, sep_2);
                 std::vector<std::string> body;
                 for (tokenizer::iterator tok_iter = tokens_2.begin(); tok_iter != tokens_2.end(); ++tok_iter) // perhaps str.erase from <string.h> would be faster, but i would not know what exactly to do..
                 {
                     body.push_back(*tok_iter);
                 }
                 // Create NmeaSentence struct to pass to GprmcParser::ParseASCII
                 NMEASentence rmc_message(id, body);
                 rosaic::GprmcPtr msg = boost::make_shared<rosaic::Gprmc>();
                 GprmcParser parser_obj;
                 try
                 {
                     msg = parser_obj.ParseASCII(rmc_message);
                 }
                 catch (ParseException& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 //ROS_DEBUG("ID is %s, size of message is %lu and sizeof ptr is %lu", gprmc_ros_message_ptr->message_id.c_str(), sizeof(message), sizeof(*gprmc_ros_message_ptr));
                 //ROS_DEBUG("size of message is currently %li and to be copied is %li", sizeof(message), sizeof(*msg));
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evGPGSA:
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = std::min(this->SegmentEnd(), static_cast<std::size_t>(89));
                 std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 std::string id = this->MessageID();
                 std::string one_message = *tokens.begin();
                 boost::char_separator<char> sep_2(",*", "", boost::keep_empty_tokens);  // No kept delimiters, hence "". Also, we specify that empty tokens should show up in the output when two delimiters are next to each other.
                                                                                         // Hence we also append the checksum part of the GGA message to "body" below, though it is not parsed.
                 tokenizer tokens_2(one_message, sep_2);
                 std::vector<std::string> body;
                 for (tokenizer::iterator tok_iter = tokens_2.begin(); tok_iter != tokens_2.end(); ++tok_iter) // perhaps str.erase from <string.h> would be faster, but i would not know what exactly to do..
                 {
                     body.push_back(*tok_iter);
                 }
                 // Create NmeaSentence struct to pass to GpgsaParser::ParseASCII
                 NMEASentence gsa_message(id, body);
                 rosaic::GpgsaPtr msg = boost::make_shared<rosaic::Gpgsa>();
                 GpgsaParser parser_obj;
                 try
                 {
                     msg = parser_obj.ParseASCII(gsa_message);
                 }
                 catch (ParseException& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 uint32_t TOW = last_pvtgeodetic_.TOW;
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 //ROS_DEBUG("ID is %s, size of message is %lu and sizeof ptr is %lu", gprmc_ros_message_ptr->message_id.c_str(), sizeof(message), sizeof(*gprmc_ros_message_ptr));
                 //ROS_DEBUG("size of message is currently %li and to be copied is %li", sizeof(message), sizeof(*msg));
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evGPGSV: case evGLGSV: case evGAGSV:
             {
                 boost::char_separator<char> sep("\r");
                 typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
                 std::size_t nmea_size = std::min(this->SegmentEnd(), static_cast<std::size_t>(89));
                 std::string block_in_string(reinterpret_cast<const char*>(data_), nmea_size);
                 tokenizer tokens(block_in_string, sep);
                 std::string id = this->MessageID();
                 std::string one_message = *tokens.begin();
                 boost::char_separator<char> sep_2(",*", "", boost::keep_empty_tokens);  // No kept delimiters, hence "". Also, we specify that empty tokens should show up in the output when two delimiters are next to each other.
                                                                                         // Hence we also append the checksum part of the GGA message to "body" below, though it is not parsed.
                 tokenizer tokens_2(one_message, sep_2);
                 std::vector<std::string> body;
                 for (tokenizer::iterator tok_iter = tokens_2.begin(); tok_iter != tokens_2.end(); ++tok_iter) // perhaps str.erase from <string.h> would be faster, but i would not know what exactly to do..
                 {
                     body.push_back(*tok_iter);
                 }
                 // Create NmeaSentence struct to pass to GpgsvParser::ParseASCII
                 NMEASentence gsv_message(id, body);
                 rosaic::GpgsvPtr msg = boost::make_shared<rosaic::Gpgsv>();
                 GpgsvParser parser_obj;
                 try
                 {
                     msg = parser_obj.ParseASCII(gsv_message);
                 }
                 catch (ParseException& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 uint32_t TOW = last_pvtgeodetic_.TOW;
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 //ROS_DEBUG("ID is %s, size of message is %lu and sizeof ptr is %lu", gprmc_ros_message_ptr->message_id.c_str(), sizeof(message), sizeof(*gprmc_ros_message_ptr));
                 //ROS_DEBUG("size of message is currently %li and to be copied is %li", sizeof(message), sizeof(*msg));
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evNavSatFix:
             {
                 sensor_msgs::NavSatFixPtr msg = boost::make_shared<sensor_msgs::NavSatFix>();
                 try
                 {
                     msg = NavSatFixCallback();
                 }
                 catch (std::runtime_error& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 msg->header.frame_id = frame_id;
                 uint32_t TOW = last_pvtgeodetic_.TOW;
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evGPSFix:
             {
                 gps_common::GPSFixPtr msg = boost::make_shared<gps_common::GPSFix>();
                 try
                 {
                     msg = GPSFixCallback();
                 }
                 catch (std::runtime_error& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 msg->status.header.seq = count_gpsfix_;
                 msg->header.frame_id = frame_id;
                 msg->status.header.frame_id = frame_id;
                 uint32_t TOW = last_pvtgeodetic_.TOW;
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->status.header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 msg->status.header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 ++count_gpsfix_;
                 break;
             }
             case evPoseWithCovarianceStamped:
             {
                 geometry_msgs::PoseWithCovarianceStampedPtr msg = boost::make_shared<geometry_msgs::PoseWithCovarianceStamped>();
                 try
                 {
                     msg = PoseWithCovarianceStampedCallback();
                 }
                 catch (std::runtime_error& e)
                 {
                     throw std::runtime_error(e.what());
                 }
                 msg->header.frame_id = frame_id;
                 uint32_t TOW = last_pvtgeodetic_.TOW;
                 ros::Time time_obj;
                 time_obj = TimestampSBF(TOW, use_GNSS_time);
                 msg->header.stamp.sec = time_obj.sec;
                 msg->header.stamp.nsec = time_obj.nsec;
                 memcpy(&message, msg.get(), sizeof(*msg));
                 break;
             }
             case evChannelStatus:
             {
                 memcpy(&last_channelstatus_, data_, sizeof(last_channelstatus_));
                 break;
             }
             case evMeasEpoch:
             {
                 memcpy(&last_measepoch_, data_, sizeof(last_measepoch_));
                 break;
             }
             case evDOP:
             {
                 memcpy(&last_dop_, data_, sizeof(last_dop_));
                 break;
             }
             case evVelCovGeodetic:
             {
                 memcpy(&last_velcovgeodetic_, data_, sizeof(last_velcovgeodetic_));
                 break;
             }
             // Many more to be implemented...
         }
         return true;
     }
Search()
const uint8_t * io_comm_mosaic::mosaicMessage::Search ()
Searches the buffer for the beginning of the next message (NMEA or SBF)
Returns
A pointer to the start of the next message.
Definition at line 666 of file mosaicMessage.cpp.
References count_, data_, found_, IsConnectionDescriptor(), IsNMEA(), IsResponse(), IsSBF(), Next(), and read_cd.
Referenced by GetCount(), Read(), and io_comm_mosaic::CallbackHandlers::ReadCallback().
 {
     if (found_)
     {
         Next();
     }
     // Search for message or a response header
     for( ; count_ > 0; --count_, ++data_)
     {
         if (this->IsSBF() || this->IsNMEA() || this->IsResponse() || (read_cd && this->IsConnectionDescriptor()))
         {
             break;
         }
     }
     found_ = true;
     return data_;
 }
SegmentEnd()
std::size_t io_comm_mosaic::mosaicMessage::SegmentEnd ()
Determines size of message that data_ is currently pointing at.
Definition at line 684 of file mosaicMessage.cpp.
References CARRIAGE_RETURN, count_, data_, IsResponse(), LINE_FEED, and segment_size_.
Referenced by IsMessage(), MessageID(), mosaicMessage(), Read(), and io_comm_mosaic::CallbackHandlers::ReadCallback().
 {
     uint16_t pos = 0;
     segment_size_ = 0;
     uint32_t count_copy = count_;
     if (this->IsResponse())
     {
         do
         {
             ++segment_size_;
             ++pos;
             --count_copy;
             if (count_copy == 0) break;
         } while(!((data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED)) || (data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED && data_[pos+2] == 0x20 && data_[pos+3] == 0x20 && data_[pos+4] == 0x4E) || (data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED && data_[pos+2] == 0x20 && data_[pos+3] == 0x20 && data_[pos+4] == 0x53) || (data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED && data_[pos+2] == 0x20 && data_[pos+3] == 0x20 && data_[pos+4] == 0x52));
     }
     else
     {
         do
         {
             ++segment_size_;
             ++pos;
             --count_copy;
             if (count_copy == 0) break;
         } while(!((data_[pos] == CARRIAGE_RETURN && data_[pos+1] == LINE_FEED) || data_[pos] == CARRIAGE_RETURN || data_[pos] == LINE_FEED));
     }
     return segment_size_;
 }
Field Documentation
count_
uint32_t io_comm_mosaic::mosaicMessage::count_ private
The number of bytes in the buffer, decremented as the buffer is read (so it is the buffer's size in the beginning)
Definition at line 301 of file mosaicMessage.hpp.
Referenced by End(), GetCount(), Next(), Read(), Search(), and SegmentEnd().
count_gpsfix_
uint32_t io_comm_mosaic::mosaicMessage::count_gpsfix_ = 0 static private
Number of times the gps_common::GPSFix message has been published.
Number of times the "read" method of the mosaicMessage class has been called.
Definition at line 316 of file mosaicMessage.hpp.
Referenced by Read().
CRCcheck_
bool io_comm_mosaic::mosaicMessage::CRCcheck_ private
Whether the CRC check as evaluated in the read() method was successful or not is stored here.
Definition at line 306 of file mosaicMessage.hpp.
Referenced by mosaicMessage(), Next(), and Read().
data_
const uint8_t* io_comm_mosaic::mosaicMessage::data_ private
The pointer to the buffer of messages.
Definition at line 296 of file mosaicMessage.hpp.
Referenced by BlockLength(), End(), IsConnectionDescriptor(), IsErrorMessage(), IsMessage(), IsNMEA(), IsResponse(), IsSBF(), MessageID(), Next(), Pos(), Read(), Search(), and SegmentEnd().
found_
bool io_comm_mosaic::mosaicMessage::found_
Whether or not a message has been found.
Definition at line 289 of file mosaicMessage.hpp.
Referenced by Found(), mosaicMessage(), Next(), and Search().
last_attcoveuler_
AttCovEuler io_comm_mosaic::mosaicMessage::last_attcoveuler_ = AttCovEuler() static private
Since GPSFix etc. need AttCovEuler, incoming AttCovEuler blocks need to be stored.
Definition at line 336 of file mosaicMessage.hpp.
Referenced by GPSFixCallback(), PoseWithCovarianceStampedCallback(), and Read().
last_atteuler_
AttEuler io_comm_mosaic::mosaicMessage::last_atteuler_ = AttEuler() static private
Since GPSFix etc. need AttEuler, incoming AttEuler blocks need to be stored.
Definition at line 331 of file mosaicMessage.hpp.
Referenced by GPSFixCallback(), PoseWithCovarianceStampedCallback(), and Read().
last_channelstatus_
ChannelStatus io_comm_mosaic::mosaicMessage::last_channelstatus_ = ChannelStatus() static private
Since GPSFix etc. need ChannelStatus, incoming ChannelStatus blocks need to be stored.
Definition at line 341 of file mosaicMessage.hpp.
Referenced by GPSFixCallback(), and Read().
last_dop_
DOP io_comm_mosaic::mosaicMessage::last_dop_ = DOP() static private
Since GPSFix etc. need DOP, incoming DOP blocks need to be stored.
Definition at line 351 of file mosaicMessage.hpp.
Referenced by GPSFixCallback(), and Read().
last_measepoch_
MeasEpoch io_comm_mosaic::mosaicMessage::last_measepoch_ = MeasEpoch() static private
Since GPSFix etc. need MeasEpoch (for signal-to-noise ratios), incoming MeasEpoch blocks need to be stored.
Definition at line 346 of file mosaicMessage.hpp.
Referenced by GPSFixCallback(), and Read().
last_poscovgeodetic_
PosCovGeodetic io_comm_mosaic::mosaicMessage::last_poscovgeodetic_ = PosCovGeodetic() static private
Since NavSatFix etc. need PosCovGeodetic, incoming PosCovGeodetic blocks need to be stored.
Definition at line 326 of file mosaicMessage.hpp.
Referenced by GPSFixCallback(), NavSatFixCallback(), PoseWithCovarianceStampedCallback(), and Read().
last_pvtgeodetic_
PVTGeodetic io_comm_mosaic::mosaicMessage::last_pvtgeodetic_ = PVTGeodetic() static private
Since NavSatFix etc. need PVTGeodetic, incoming PVTGeodetic blocks need to be stored.
Definition at line 321 of file mosaicMessage.hpp.
Referenced by GPSFixCallback(), NavSatFixCallback(), PoseWithCovarianceStampedCallback(), and Read().
last_velcovgeodetic_
VelCovGeodetic io_comm_mosaic::mosaicMessage::last_velcovgeodetic_ = VelCovGeodetic() static private
Since GPSFix etc. need VelCovGeodetic (for signal-to-noise ratios), incoming VelCovGeodetic blocks need to be stored.
Definition at line 356 of file mosaicMessage.hpp.
Referenced by GPSFixCallback(), and Read().
segment_size_
std::size_t io_comm_mosaic::mosaicMessage::segment_size_ private
Helps to determine size of response message / NMEA message / SBF block.
Definition at line 311 of file mosaicMessage.hpp.
Referenced by mosaicMessage(), and SegmentEnd().
The documentation for this class was generated from the following files:
include/rosaic/communication/mosaicMessage.hpp
src/rosaic/communication/mosaicMessage.cpp