ROSaic: include/rosaic/crc/crc.h File Reference
crc.h File Reference
Declares the functions to compute and validate the CRC of a buffer.
#include <rosaic/packed_structs/ssntypes.hpp>
#include <rosaic/packed_structs/sbf_structs.hpp>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
Typedefs
typedef BlockHeader_t VoidBlock_t
Functions
uint16_t FW_EXPORT CRC_compute16CCITT (const void *buf, size_t buf_length)
This function computes the CRC-8-CCITT (Cyclic Redundancy Check) of a buffer "buf" of "buf_length" bytes.
bool FW_EXPORT CRCIsValid (const void *Block)
This function validates whether the calculated CRC of the SBF block at hand matches the CRC field that is part of the streamed SBF block.
Detailed Description
Declares the functions to compute and validate the CRC of a buffer.
Date
17/08/20
Definition in file crc.h.
Typedef Documentation
VoidBlock_t
typedef BlockHeader_t VoidBlock_t
Definition at line 74 of file crc.h.
Function Documentation
CRC_compute16CCITT()
uint16_t FW_EXPORT CRC_compute16CCITT (const void * buf, size_t buf_length)
This function computes the CRC-8-CCITT (Cyclic Redundancy Check) of a buffer "buf" of "buf_length" bytes.
Parameters
[in] buf The buffer at hand
[in] buf_length Number of bytes in "buf"
Returns
Returns the calculated CRC
Note that a void pointer is a pointer that has no associated data type with it. A void pointer can hold address of any type and can be typcasted to any type.
Definition at line 42 of file crc.c.
Referenced by CRCIsValid().
 {
     uint32_t  i;  // since i might become rather large, after all..
     uint16_t  crc = 0; // seed is 0, as suggested by ref guide. computed in the forward direction
     const uint8_t  *buf8 = (const uint8_t *) buf; // Convert the type to access by byte. RHS is pointer to constant type uint8_t, pointing to the address buf
                                                 // later in the code this address buf8 is used to write/read an actual uint8_t value to/from there.
                                                 // uint8_t x = address_at_eeprom_location[3]: This would read the 3rd uint8_t starting from address 10 (so at address 13, since addresses work byte-wise) in ram into the variable x
     for (i=0; i<buf_length; i++) {
         crc = (crc << 8) ^ CRCLookUp[ (crc >> 8) ^ buf8[i] ];
     // The ^ (bitwise XOR) in C or C++ takes two numbers as operands and does XOR on every bit of two numbers. The result of XOR is 1 if the two bits are different.
     // The << (left shift) in C or C++ takes two numbers, left shifts the bits of the first operand, the second operand decides the number of places to shift.
     // The >> (right shift) in C or C++ takes two numbers, right shifts the bits of the first operand, the second operand decides the number of places to shift; you can just loose the smallest values if big-endian
     // The left shift and right shift operators should not be used for negative numbers
     // The left-shift and right-shift operators are equivalent to multiplication and division by 2 respectively, hence only rightshift is non-exact (remainder is not retained)
     // CRC_SBF_LookUp contains is constructed from truncated polynomial (divisor)
     // The above implements a kind of CRC 32 algorithm: efficient, fast
     }
     return crc;
 }
CRCIsValid()
bool FW_EXPORT CRCIsValid (const void * Block)
This function validates whether the calculated CRC of the SBF block at hand matches the CRC field that is part of the streamed SBF block.
Parameters
Block The SBF block that we are interested in
Returns
Returns true if the CRC check of the SBFBlock has passed, false otherwise
Definition at line 63 of file crc.c.
References BlockHeader_t::CRC, CRC_compute16CCITT(), BlockHeader_t::ID, and BlockHeader_t::Length.
Referenced by io_comm_mosaic::mosaicMessage::Read().
 {
     const VoidBlock_t * Block2 = (const VoidBlock_t *) Block; // Convert to access the generic header fields. Otherwise Block2->ID would not work.
     uint16_t crc;
     crc = CRC_compute16CCITT ( &(Block2->ID), Block2->Length-2*sizeof(uint16_t) ); // need address of ID, then all the message except for first 4 bytes (Sync and CRC)
     return (crc ==  Block2->CRC) ? true:false;
 }