ROSaic: io_comm_mosaic Namespace Reference
io_comm_mosaic Namespace Reference
Data Structures
class AsyncManager
This is the central interface between this ROS driver and the mosaic receiver(s), managing I/O operations such as reading messages and sending commands..
class CallbackHandler
Abstract class representing a generic callback handler, top-level functionality such as wait.
class CallbackHandler_
Derived class operating on a mosaic message level.
class CallbackHandlers
Represents ensemble of messages, to be handled at once by this class.
class Comm_IO
Handles communication with and configuration of the mosaic-x5 device(s)
class Manager
Interface (in C++ terms), that could be used for any I/O manager, synchronous and asynchronous alike.
class mosaicMessage
Can search buffer for messages, jump to next one (in case of SBF block), and so on.
Functions
rosaic::PVTCartesianPtr PVTCartesianCallback (PVTCartesian &data)
Callback function when reading PVTCartesian blocks.
rosaic::PVTGeodeticPtr PVTGeodeticCallback (PVTGeodetic &data)
Callback function when reading PVTCartesian blocks.
ros::Time timestampSBF (uint32_t TOW, bool use_GNSS)
Calculates the timestamp, in the Unix Epoch time format, either using the TOW as transmitted with the SBF block, or using the current time.
Variables
int debug
static const uint32_t Baudrates []
Detailed Description
This namespace is for the communication interface, handling all aspects related to serial and TCP/IP communication..
Function Documentation
PVTCartesianCallback()
rosaic::PVTCartesianPtr io_comm_mosaic::PVTCartesianCallback (PVTCartesian & data)
Callback function when reading PVTCartesian blocks.
Parameters
[in] data The (packed and aligned) struct instance that we use to populate our ROS message rosaic::PVTCartesian
Returns
A smart pointer to the ROS message rosaic::PVTCartesian just created
Definition at line 79 of file mosaicMessage.cpp.
References PVTCartesian::AlertFlag, PVTCartesian::Block_Header, PVTCartesian::COG, BlockHeader_t::CRC, PVTCartesian::Datum, PVTCartesian::Error, PVTCartesian::HAccuracy, BlockHeader_t::ID, PVTCartesian::Latency, BlockHeader_t::Length, PVTCartesian::MeanCorrAge, PVTCartesian::Misc, PVTCartesian::Mode, PVTCartesian::NrBases, PVTCartesian::NrSV, PVTCartesian::PPPInfo, PVTCartesian::ReferenceID, PVTCartesian::RxClkBias, PVTCartesian::RxClkDrift, PVTCartesian::SignalInfo, BlockHeader_t::SYNC1, BlockHeader_t::SYNC2, PVTCartesian::TimeSystem, PVTCartesian::TOW, PVTCartesian::Undulation, PVTCartesian::VAccuracy, PVTCartesian::Vx, PVTCartesian::Vy, PVTCartesian::Vz, PVTCartesian::WACorrInfo, PVTCartesian::WNc, PVTCartesian::X, PVTCartesian::Y, and PVTCartesian::Z.
Referenced by io_comm_mosaic::mosaicMessage::read(), and StringValues_Initialize().
 {
     rosaic::PVTCartesianPtr msg = boost::make_shared<rosaic::PVTCartesian>();
     msg->Block_Header.SYNC1 = data.Block_Header.SYNC1;
     msg->Block_Header.SYNC2 = data.Block_Header.SYNC2;
     msg->Block_Header.CRC = data.Block_Header.CRC;
     msg->Block_Header.ID = data.Block_Header.ID;
     msg->Block_Header.Length = data.Block_Header.Length;
     msg->Block_Header.TOW = data.TOW;
     msg->Block_Header.WNc = data.WNc;
     msg->Mode = data.Mode;
     msg->Error = data.Error;
     msg->X = data.X;
     msg->Y = data.Y;
     msg->Z = data.Z;
     msg->Undulation = data.Undulation;
     msg->Vx = data.Vx;
     msg->Vy = data.Vy;
     msg->Vz = data.Vz;
     msg->COG = data.COG;
     msg->RxClkBias = data.RxClkBias;
     msg->RxClkDrift = data.RxClkDrift;
     msg->TimeSystem = data.TimeSystem;
     msg->Datum = data.Datum;
     msg->NrSV = data.NrSV;
     msg->WACorrInfo = data.WACorrInfo;
     msg->ReferenceID = data.ReferenceID;
     msg->MeanCorrAge = data.MeanCorrAge;
     msg->SignalInfo = data.SignalInfo;
     msg->AlertFlag = data.AlertFlag;
     msg->NrBases = data.NrBases;
     msg->PPPInfo = data.PPPInfo;
     msg->Latency = data.Latency;
     msg->HAccuracy = data.HAccuracy;
     msg->VAccuracy = data.VAccuracy;
     msg->Misc = data.Misc;
     return msg;
 }
PVTGeodeticCallback()
rosaic::PVTGeodeticPtr io_comm_mosaic::PVTGeodeticCallback (PVTGeodetic & data)
Callback function when reading PVTCartesian blocks.
Parameters
[in] data The (packed and aligned) struct instance that we use to populate our ROS message rosaic::PVTCartesian
Returns
A smart pointer to the ROS message rosaic::PVTCartesian just created
Definition at line 39 of file mosaicMessage.cpp.
References PVTGeodetic::AlertFlag, PVTGeodetic::Block_Header, PVTGeodetic::COG, BlockHeader_t::CRC, PVTGeodetic::Datum, PVTGeodetic::Error, PVTGeodetic::HAccuracy, PVTGeodetic::Height, BlockHeader_t::ID, PVTGeodetic::Latency, PVTGeodetic::Latitude, BlockHeader_t::Length, PVTGeodetic::Longitude, PVTGeodetic::MeanCorrAge, PVTGeodetic::Misc, PVTGeodetic::Mode, PVTGeodetic::NrBases, PVTGeodetic::NrSV, PVTGeodetic::PPPInfo, PVTGeodetic::ReferenceID, PVTGeodetic::RxClkBias, PVTGeodetic::RxClkDrift, PVTGeodetic::SignalInfo, BlockHeader_t::SYNC1, BlockHeader_t::SYNC2, PVTGeodetic::TimeSystem, PVTGeodetic::TOW, PVTGeodetic::Undulation, PVTGeodetic::VAccuracy, PVTGeodetic::Ve, PVTGeodetic::Vn, PVTGeodetic::Vu, PVTGeodetic::WACorrInfo, and PVTGeodetic::WNc.
Referenced by io_comm_mosaic::mosaicMessage::read(), and StringValues_Initialize().
 {
     rosaic::PVTGeodeticPtr msg = boost::make_shared<rosaic::PVTGeodetic>();
     msg->Block_Header.SYNC1 = data.Block_Header.SYNC1;
     msg->Block_Header.SYNC2 = data.Block_Header.SYNC2;
     msg->Block_Header.CRC = data.Block_Header.CRC;
     msg->Block_Header.ID = data.Block_Header.ID;
     msg->Block_Header.Length = data.Block_Header.Length;
     msg->Block_Header.TOW = data.TOW;
     msg->Block_Header.WNc = data.WNc;
     msg->Mode = data.Mode;
     msg->Error = data.Error;
     msg->Latitude = data.Latitude;
     msg->Longitude = data.Longitude;
     msg->Height = data.Height;
     msg->Undulation = data.Undulation;
     msg->Vn = data.Vn;
     msg->Ve = data.Ve;
     msg->Vu = data.Vu;
     msg->COG = data.COG;
     msg->RxClkBias = data.RxClkBias;
     msg->RxClkDrift = data.RxClkDrift;
     msg->TimeSystem = data.TimeSystem;
     msg->Datum = data.Datum;
     msg->NrSV = data.NrSV;
     msg->WACorrInfo = data.WACorrInfo;
     msg->ReferenceID = data.ReferenceID;
     msg->MeanCorrAge = data.MeanCorrAge;
     msg->SignalInfo = data.SignalInfo;
     msg->AlertFlag = data.AlertFlag;
     msg->NrBases = data.NrBases;
     msg->PPPInfo = data.PPPInfo;
     msg->Latency = data.Latency;
     msg->HAccuracy = data.HAccuracy;
     msg->VAccuracy = data.VAccuracy;
     msg->Misc = data.Misc;
     return msg;
 }
timestampSBF()
ros::Time io_comm_mosaic::timestampSBF (uint32_t TOW, bool use_GNSS)
Calculates the timestamp, in the Unix Epoch time format, either using the TOW as transmitted with the SBF block, or using the current time.
Parameters
[in] TOW Number of milliseconds that elapsed since the beginning of the current GPS week as transmitted by the SBF block
[in] use_GNSS_time If true, the TOW as transmitted with the SBF block is used, otherwise the current time
Returns
ros::Time object containing seconds and nanoseconds since last epoch
If the current time shall be employed, it is calculated via BOOST, using the type boost::gregorian::date. At the time of writing the code (2020), the GPS time was ahead of UTC time by 18 (leap) seconds. Adapt accordingly as soon as the next leap second is inserted into the UTC time.
Definition at line 122 of file mosaicMessage.cpp.
References string_utilities::ToDouble(), and rosaic_driver::UTCtoUnix().
Referenced by io_comm_mosaic::mosaicMessage::read(), and StringValues_Initialize().
 {
     if (use_GNSS)
     {
         uint16_t hh = (TOW%(1000*60*60*24))/(60*60*1000);
         uint16_t mm = ((TOW%(1000*60*60*24))-hh*(60*60*1000))/(60*1000);
         uint16_t ss = ((TOW%(1000*60*60*24))-hh*(60*60*1000)-mm*(60*1000))/(1000);
         uint16_t hs = ((TOW%(1000*60*60*24))-hh*(60*60*1000)-mm*(60*1000)-ss*1000)/10; // hundredths of a second
         if (ss >= 18)
         {
             ss = ss - 18;
         }
         else
         {
             if (mm >= 1)
             {
                 --mm;
                 ss = 60 - (18 - ss);
             }
             else
             {
                 if (hh >= 1)
                 {
                     --hh;
                     mm = 59;
                     ss = 60 - (18 - ss);
                 }
                 else
                 {
                     hh = 23;
                     mm = 59;
                     ss = 60 - (18 - ss);
                 }
             }
         }
         boost::format fmt = boost::format("%02u%02u%02u.%02u") % hh % mm % ss % hs;
         std::string utc_string = fmt.str();
         //ROS_DEBUG("UTC string (still need to subtract 18 seconds) is %s", utc_string.c_str());
         double utc_double;
         string_utilities::ToDouble(utc_string, utc_double);
         time_t unix_time_seconds = rosaic_driver::UTCtoUnix(utc_double);
         uint32_t unix_time_nanoseconds = (static_cast<uint32_t>(utc_double*100)%100)*10000000;  // works since there are two digits after the decimal point in the utc_double
         ros::Time time_obj(unix_time_seconds, unix_time_nanoseconds);
         return time_obj;
     }
     else
     {
         time_t time_now = time(NULL);
         ros::Time time_obj((uint32_t) time_now, 0);
         return time_obj;
     }
 }
Variable Documentation
Baudrates
const uint32_t io_comm_mosaic::Baudrates[] static
Initial value:
= {1200, 2400, 4800, 9600, 19200, 38400, 57600,
                                        115200, 230400, 460800, 500000, 576000, 921600,
                                        1000000, 1152000, 1500000, 2000000, 2500000,
                                        3000000, 3500000, 4000000}
Definition at line 106 of file communication_core.hpp.
Referenced by io_comm_mosaic::Comm_IO::InitializeSerial().
debug
int io_comm_mosaic::debug
Definition at line 103 of file communication_core.hpp.
Referenced by rosaic_node::ROSaicNode::InitializeIO(), and main().