ROSaic: string_utilities Namespace Reference
string_utilities Namespace Reference
Functions
bool toDouble (const std::string &string, double &value)
Interprets the contents of "string" as a floating point number of type double It stores the "string"'s value in "value" and returns whether or not all went well.
bool toFloat (const std::string &string, float &value)
Interprets the contents of "string" as a floating point number of type float.
bool toInt32 (const std::string &string, int32_t &value, int32_t base=10)
Interprets the contents of "string" as a floating point number of whatever integer type your system has that is exactly 32 bits.
bool toUInt32 (const std::string &string, uint32_t &value, int32_t base=10)
Interprets the contents of "string" as a floating point number of whatever unsigned integer type your system has that is exactly 32 bits.
int8_t toInt8 (const std::string &string, int8_t &value, int32_t base=10)
Interprets the contents of "string" as a floating point number of whatever integer type your system has that is exactly 8 bits.
uint8_t toUInt8 (const std::string &string, uint8_t &value, int32_t base=10)
Interprets the contents of "string" as a floating point number of whatever unsigned integer type your system has that is exactly 8 bits.
std::string trimString (std::string str)
Removes trailing zeros from a string representing a float or double except for the first zero after the decimal point.
Detailed Description
This namespace is for the functions that encapsulate basic string manipulation and conversion techniques.
Function Documentation
toDouble()
bool string_utilities::toDouble (const std::string & string, double & value)
Interprets the contents of "string" as a floating point number of type double It stores the "string"'s value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative and the string is non-empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The double variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
Definition at line 51 of file string_utilities.cpp.
Referenced by GpggaParser::parseASCII(), GprmcParser::parseASCII(), parsing_utilities::parseDouble(), and io_comm_rx::timestampSBF().
     {
         if (string.empty())
         {
             return false;
         }
         char* end;
         errno = 0;
         double value_new = std::strtod(string.c_str(), &end);
         if (errno != 0 || end != string.c_str() + string.length())
         {
             return false;
         }
         value = value_new;
         return true;
     }
toFloat()
bool string_utilities::toFloat (const std::string & string, float & value)
Interprets the contents of "string" as a floating point number of type float.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative and the string is non-empty, false otherwise.
It stores the "string"'s value in "value" and returns whether or not all went well.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The float variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
Definition at line 77 of file string_utilities.cpp.
Referenced by parsing_utilities::parseFloat().
     {
         if (string.empty())
         {
             return false;
         }
         char* end;
         errno = 0;
         float value_new = std::strtof(string.c_str(), &end);
         if (errno != 0 || end != string.c_str() + string.length())
         {
             return false;
         }
         value = value_new;
         return true;
     }
toInt32()
bool string_utilities::toInt32 (const std::string & string, int32_t & value, int32_t base)
Interprets the contents of "string" as a floating point number of whatever integer type your system has that is exactly 32 bits.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative and the string is non-empty, false otherwise.
It stores the "string"'s value in "value" and returns whether or not all went well.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The int32_t variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
Definition at line 102 of file string_utilities.cpp.
Referenced by parsing_utilities::parseInt16(), and parsing_utilities::parseInt32().
     {
         if (string.empty())
         {
             return false;
         }
         char* end;
         errno = 0;
         int64_t value_new = std::strtol(string.c_str(), &end, base);
         if (errno != 0 || end != string.c_str() + string.length())
         {
             return false;
         }
         if (value_new > std::numeric_limits<int32_t>::max() ||
          value_new < std::numeric_limits<int32_t>::min())
         {
             return false;
         }
         value = (int32_t) value_new;
         return true;
     }
toInt8()
int8_t string_utilities::toInt8 (const std::string & string, int8_t & value, int32_t base)
Interprets the contents of "string" as a floating point number of whatever integer type your system has that is exactly 8 bits.
Not used as of now..
It stores the "string"'s value in "value".
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The int8_t variable that should be overwritten by the floating point number found in "string"
Returns
The value found in "string"
Definition at line 161 of file string_utilities.cpp.
     {
         char* end;
         errno = 0;
         int64_t value_new = std::strtol(string.c_str(), &end, base);
         value = (int8_t) value_new;
         return value;
     }
toUInt32()
bool string_utilities::toUInt32 (const std::string & string, uint32_t & value, int32_t base)
Interprets the contents of "string" as a floating point number of whatever unsigned integer type your system has that is exactly 32 bits.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative and the string is non-empty, false otherwise.
It stores the "string"'s value in "value" and returns whether or not all went well.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The uint32_t variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
Definition at line 133 of file string_utilities.cpp.
Referenced by parsing_utilities::parseUInt16(), parsing_utilities::parseUInt32(), and parsing_utilities::parseUInt8().
     {
         if (string.empty())
         {
             return false;
         }
         char* end;
         errno = 0;
         int64_t value_new = std::strtol(string.c_str(), &end, base);
         if (errno != 0 || end != string.c_str() + string.length())
         {
             return false;
         }
         if (value_new > std::numeric_limits<uint32_t>::max() || value_new < 0)
         {
             return false;
         }
         value = (uint32_t) value_new;
         return true;
     }
toUInt8()
uint8_t string_utilities::toUInt8 (const std::string & string, uint8_t & value, int32_t base)
Interprets the contents of "string" as a floating point number of whatever unsigned integer type your system has that is exactly 8 bits.
Not used as of now..
It stores the "string"'s value in "value".
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The uint8_t variable that should be overwritten by the floating point number found in "string"
Returns
The value found in "string"
Definition at line 174 of file string_utilities.cpp.
     {
         char* end;
         errno = 0;
         int64_t value_new = std::strtol(string.c_str(), &end, base);
         value = (uint8_t) value_new;
         return true;
     }
trimString()
std::string string_utilities::trimString (std::string str)
Removes trailing zeros from a string representing a float or double except for the first zero after the decimal point.
Parameters
[in] str The string whose trailing zeros shall be removed
Returns
The trimmed string
Definition at line 184 of file string_utilities.cpp.
Referenced by rosaic_node::ROSaicNode::configureRx().
     {
         for(std::string::size_type s=str.length()-1; s>0; --s)
         {
             if(str[s] == '0' && !isdigit(str[s-1])) break;
             else if (str[s] == '0') str.erase(s,1);
             else break;
         }
         return str;
     }