ROSaic: rosaic_driver Namespace Reference
rosaic_driver Namespace Reference
Data Structures
class BaseParser
Base class for parsing NMEA messages and SBF blocks.
class GpggaParser
Derived class for parsing GGA messages.
class NMEASentence
Struct to split an NMEA sentence into its ID (e.g. the standardized "$GPGGA" or proprietary "$PSSN,HRP") and its body, the latter tokenized into a vector of strings.
class ParseException
Ćlass to declare error message format when parsing, derived from the public class "std::runtime_error".
struct SBFBlock
Contains the SBF block's header, its raw data bytes, and its CRC.
struct SBFBlockHeader
Represents the header of an SBF block, excluding the timestamp.
struct TimeHeader
Represents the header of an SBF block, including the timestamp.
Functions
double ParseDouble (const uint8_t *buffer)
Converts an 8-byte-buffer into a double.
bool ParseDouble (const std::string &string, double &value)
Interprets the contents of "string" as a floating point number of type double, stores its value in "value" and returns whether or not all went well.
float ParseFloat (const uint8_t *buffer)
Converts a 4-byte-buffer into a float.
bool ParseFloat (const std::string &string, float &value)
Interprets the contents of "string" as a floating point number of type float, stores its value in "value" and returns whether or not all went well.
int16_t ParseInt16 (const uint8_t *buffer)
Converts a 2-byte-buffer into a signed 16-bit integer.
bool ParseInt16 (const std::string &string, int16_t &value, int32_t base=10)
Interprets the contents of "string" as a integer number of type int16_t, stores its value in "value" and returns whether or not all went well.
int32_t ParseInt32 (const uint8_t *buffer)
Converts a 4-byte-buffer into a signed 32-bit integer.
bool ParseInt32 (const std::string &string, int32_t &value, int32_t base=10)
Interprets the contents of "string" as a integer number of type int32_t, stores its value in "value" and returns whether or not all went well.
bool ParseUInt8 (const std::string &string, uint8_t &value, int32_t base=10)
Interprets the contents of "string" as a unsigned integer number of type uint8_t, stores its value in "value" and returns whether or not all went well.
uint16_t ParseUInt16 (const uint8_t *buffer)
Converts a 2-byte-buffer into an unsigned 16-bit integer.
bool ParseUInt16 (const std::string &string, uint16_t &value, int32_t base=10)
Interprets the contents of "string" as a unsigned integer number of type uint16_t, stores its value in "value" and returns whether or not all went well.
uint32_t ParseUInt32 (const uint8_t *buffer)
Converts a 4-byte-buffer into an unsigned 32-bit integer.
bool ParseUInt32 (const std::string &string, uint32_t &value, int32_t base=10)
Interprets the contents of "string" as a unsigned integer number of type uint32_t, stores its value in "value" and returns whether or not all went well.
double UTCDoubleToSeconds (double utc_double)
Converts the UTC time from the without-colon-delimiter format, type double, to the number-of-seconds-since-midnight format, type double.
double ConvertDMSToDegrees (double dms)
Converts latitude or longitude from the DMS notation (in the without-colon-delimiter format), type double, to the pure degree notation, type double.
time_t UTCtoUnix (double utc_double)
Converts UTC time from the without-colon-delimiter format, type double, to Unix Epoch time (a number-of-seconds-since-1970/01/01 format), type time_t (usually 32 bits)
Function Documentation
ConvertDMSToDegrees()
double rosaic_driver::ConvertDMSToDegrees (double dms)
Converts latitude or longitude from the DMS notation (in the without-colon-delimiter format), type double, to the pure degree notation, type double.
Recall: One degree is divided into 60 minutes (of arc), and in turn one minute into 60 seconds (of arc). Use of the degrees-minutes-seconds system is also called DMS notation.
Parameters
dms The double variable representing latitude or longitude in the DMS notation (in the without-colon-delimiter format)
Returns
The double variable representing latitude or longitude in the pure degree notation
Definition at line 235 of file parsing_utilities.cpp.
Referenced by rosaic_driver::GpggaParser::ParseASCII().
     {
         uint32_t whole_degrees = static_cast<uint32_t>(dms) / 100;
         double minutes = dms - static_cast<double>(whole_degrees * 100);
         double degrees = static_cast<double>(whole_degrees) + minutes / 60.0;
         return degrees;
     }
ParseDouble() [1/2]
double rosaic_driver::ParseDouble (const uint8_t * buffer)
Converts an 8-byte-buffer into a double.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + sizeof(double)) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 8 bytes of data
Returns
The double extracted from the data in the buffer
Definition at line 49 of file parsing_utilities.cpp.
Referenced by rosaic_driver::GpggaParser::ParseASCII().
     {
         double diff_loc;
         std::copy(buffer, buffer + sizeof(double), reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseDouble() [2/2]
bool rosaic_driver::ParseDouble (const std::string & string, double & value)
Interprets the contents of "string" as a floating point number of type double, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The double variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
Definition at line 60 of file parsing_utilities.cpp.
References string_utilities::ToDouble().
     {
         return string_utilities::ToDouble(string, value) || string.empty();
     }
ParseFloat() [1/2]
float rosaic_driver::ParseFloat (const uint8_t * buffer)
Converts a 4-byte-buffer into a float.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + sizeof(double)) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 4 bytes of data
Returns
The float extracted from the data in the buffer
Definition at line 70 of file parsing_utilities.cpp.
Referenced by rosaic_driver::GpggaParser::ParseASCII().
     {
         float diff_loc;
         std::copy(buffer, buffer + sizeof(float), reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseFloat() [2/2]
bool rosaic_driver::ParseFloat (const std::string & string, float & value)
Interprets the contents of "string" as a floating point number of type float, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The float variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
Definition at line 81 of file parsing_utilities.cpp.
References string_utilities::ToFloat().
     {
         return string_utilities::ToFloat(string, value) || string.empty();
     }
ParseInt16() [1/2]
int16_t rosaic_driver::ParseInt16 (const uint8_t * buffer)
Converts a 2-byte-buffer into a signed 16-bit integer.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + 2) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 2 bytes of data
Returns
The int16_t value extracted from the data in the buffer
Definition at line 91 of file parsing_utilities.cpp.
     {
         int16_t diff_loc;
         std::copy(buffer, buffer+2, reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseInt16() [2/2]
bool rosaic_driver::ParseInt16 (const std::string & string, int16_t & value, int32_t base)
Interprets the contents of "string" as a integer number of type int16_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The int16_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 102 of file parsing_utilities.cpp.
References string_utilities::ToInt32().
     {
         value = 0;
         if (string.empty())
         {
           return true;
         }
         int32_t intermd;
         if (string_utilities::ToInt32(string, intermd, base) &&
             intermd <= std::numeric_limits<int16_t>::max() &&
             intermd >= std::numeric_limits<int16_t>::min())
         {
             value = static_cast<int16_t>(intermd);
             return true;
         }
         return false;
     }
ParseInt32() [1/2]
int32_t rosaic_driver::ParseInt32 (const uint8_t * buffer)
Converts a 4-byte-buffer into a signed 32-bit integer.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + 4) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 4 bytes of data
Returns
The int32_t value extracted from the data in the buffer
Definition at line 127 of file parsing_utilities.cpp.
     {
         int32_t diff_loc;
         std::copy(buffer, buffer+4, reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseInt32() [2/2]
bool rosaic_driver::ParseInt32 (const std::string & string, int32_t & value, int32_t base)
Interprets the contents of "string" as a integer number of type int32_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The int32_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 138 of file parsing_utilities.cpp.
References string_utilities::ToInt32().
     {
         return string_utilities::ToInt32(string, value, base) || string.empty();
     }
ParseUInt16() [1/2]
uint16_t rosaic_driver::ParseUInt16 (const uint8_t * buffer)
Converts a 2-byte-buffer into an unsigned 16-bit integer.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + 2) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 2 bytes of data
Returns
The uint16_t value extracted from the data in the buffer
Definition at line 170 of file parsing_utilities.cpp.
     {
         uint16_t number;
         std::copy(buffer, buffer+2, reinterpret_cast<uint8_t*>(&number));
         return number;
     }
ParseUInt16() [2/2]
bool rosaic_driver::ParseUInt16 (const std::string & string, uint16_t & value, int32_t base)
Interprets the contents of "string" as a unsigned integer number of type uint16_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The uint16_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 181 of file parsing_utilities.cpp.
References string_utilities::ToUInt32().
     {
         value = 0;
         if (string.empty())
         {
           return true;
         }
         uint32_t intermd;
         if (string_utilities::ToUInt32(string, intermd, base) && intermd <= std::numeric_limits<uint16_t>::max())
         {
           value = static_cast<uint16_t>(intermd);
           return true;
         }
         return false;
     }
ParseUInt32() [1/2]
uint32_t rosaic_driver::ParseUInt32 (const uint8_t * buffer)
Converts a 4-byte-buffer into an unsigned 32-bit integer.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + 4) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 4 bytes of data
Returns
The uint32_t value extracted from the data in the buffer
Definition at line 204 of file parsing_utilities.cpp.
Referenced by rosaic_driver::GpggaParser::ParseASCII().
     {
         uint32_t diff_loc;
         std::copy(buffer, buffer+4, reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseUInt32() [2/2]
bool rosaic_driver::ParseUInt32 (const std::string & string, uint32_t & value, int32_t base)
Interprets the contents of "string" as a unsigned integer number of type uint32_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The uint32_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 215 of file parsing_utilities.cpp.
References string_utilities::ToUInt32().
     {
         return string_utilities::ToUInt32(string, value, base) || string.empty();
     }
ParseUInt8()
bool rosaic_driver::ParseUInt8 (const std::string & string, uint8_t & value, int32_t base)
Interprets the contents of "string" as a unsigned integer number of type uint8_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The uint8_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 147 of file parsing_utilities.cpp.
References string_utilities::ToUInt32().
     {
         value = 0;
         if (string.empty())
         {
           return true;
         }
         uint32_t intermd;
         if (string_utilities::ToUInt32(string, intermd, base) && intermd <= std::numeric_limits<uint8_t>::max())
         {
           value = static_cast<uint8_t>(intermd);
           return true;
         }
         return false;
     }
UTCDoubleToSeconds()
double rosaic_driver::UTCDoubleToSeconds (double utc_double)
Converts the UTC time from the without-colon-delimiter format, type double, to the number-of-seconds-since-midnight format, type double.
The UTC precision in NMEA messages is down to a tenth of a second, naturally in both the without-colon-delimiter and the number-of-seconds-since-midnight formats.
Parameters
[in] utc_float The double variable representing UTC time in the without-colon-delimiter format
Returns
The double variable representing UTC time in the number-of-seconds-since-midnight format
Definition at line 223 of file parsing_utilities.cpp.
Referenced by rosaic_driver::GpggaParser::ParseASCII().
     {
         uint32_t hours = static_cast<uint32_t>(utc_double) / 10000;
         uint32_t minutes = (static_cast<uint32_t>(utc_double) - hours * 10000) / 100;
         double seconds = utc_double - static_cast<double>(hours * 10000 + minutes * 100);
         seconds += static_cast<double> (hours * 3600 + minutes * 60);
         return seconds;
     }
UTCtoUnix()
time_t rosaic_driver::UTCtoUnix (double utc_double)
Converts UTC time from the without-colon-delimiter format, type double, to Unix Epoch time (a number-of-seconds-since-1970/01/01 format), type time_t (usually 32 bits)
Time information (hours, minutes, seconds) is extracted from the given double and augmented with the date, which is taken from the current system time on the host computer (i.e. current UTC+some_shift time via time(0)). The date ambiguity is resolved by adding/subtracting a day to the current date if the host time is more than 12 hours behind/ahead the NMEA time (i.e. UTC time). Recall time(0), time(NULL): If argument is a null pointer, the parameter is not used (the function still returns the current calendar time of type time_t). Otherwise, the return value is the same as the one stored in the location pointed by the argument. Note that the function assumes that utc_double has two significant digits after the decimal point, i.e. hhmmss.ss, and rounds the number of seconds to the nearest unsigned integer.
Parameters
[in] utc_float The double variable representing UTC time in the without-colon-delimiter format
Returns
The time_t variable representing Unix Epoch time
Definition at line 251 of file parsing_utilities.cpp.
Referenced by rosaic_driver::GpggaParser::ParseASCII(), and io_comm_mosaic::timestampSBF().
     {
         time_t time_now = time(0);
         struct tm * timeinfo;
         // The function localtime uses the value pointed by its argument to fill a tm structure with the values that represent the corresponding time, expressed for the local timezone.
         timeinfo = gmtime(&time_now);
         uint32_t year = timeinfo->tm_year; // year, starting from 1900
         uint32_t month = timeinfo->tm_mon; // months since January - [0,11]
         uint32_t day = timeinfo->tm_mday;  //day of the month - [1,31]
         uint32_t hours = static_cast<uint32_t>(utc_double + 0.5f) / 10000;
         uint32_t minutes = (static_cast<uint32_t>(utc_double + 0.5f) - hours * 10000) / 100;
         uint32_t seconds = (static_cast<uint32_t>(utc_double + 0.5f) - hours * 10000 - minutes * 100);
         //ROS_DEBUG("Checking year %u, month %u, day %u", year, month, day);
         // Overwriting timeinfo with UTC time as extracted from utc_double..
         timeinfo->tm_hour   = hours;            // hours since midnight - [0,23]
         timeinfo->tm_min    = minutes;          // minutes after the hour - [0,59]
         timeinfo->tm_sec    = seconds;          // seconds after the minute - [0,59]
         // Inverse of gmtime, the latter converts time_t (Unix time) to tm (UTC time)
         time_t date = timegm(timeinfo);
         //ROS_DEBUG("Since 1970/01/01 %jd seconds have passed.\n", (intmax_t) date);
         return date;
     }