ROSaic: io_comm_rx Namespace Reference
io_comm_rx Namespace Reference
Data Structures
class AbstractCallbackHandler
class AsyncManager
This is the central interface between ROSaic and the Rx(s), managing I/O operations such as reading messages and sending commands..
class CallbackHandler
Abstract class representing a generic callback handler, includes high-level functionality such as wait.
class CallbackHandlers
Represents ensemble of (to be constructed) ROS messages, to be handled at once by this class.
class Comm_IO
Handles communication with and configuration of the mosaic (and beyond) receiver(s)
class Manager
Interface (in C++ terms), that could be used for any I/O manager, synchronous and asynchronous alike.
class RxMessage
Can search buffer for messages, read/parse them, and so on.
Functions
ros::Time timestampSBF (uint32_t tow, bool use_gnss)
Calculates the timestamp, in the Unix Epoch time format This is either done using the TOW as transmitted with the SBF block (if "use_gnss" is true), or using the current time.
Variables
static const uint32_t BAUDRATES []
Possible baudrates for the Rx.
Detailed Description
This namespace is for the communication interface, handling all aspects related to serial and TCP/IP communication..
Function Documentation
timestampSBF()
ros::Time io_comm_rx::timestampSBF (uint32_t tow, bool use_gnss)
Calculates the timestamp, in the Unix Epoch time format This is either done using the TOW as transmitted with the SBF block (if "use_gnss" is true), or using the current time.
Parameters
[in] tow (Time of Week) Number of milliseconds that elapsed since the beginning of the current GPS week as transmitted by the SBF block
[in] use_gnss If true, the TOW as transmitted with the SBF block is used, otherwise the current time
Returns
ros::Time object containing seconds and nanoseconds since last epoch
If the current time shall be employed, it is calculated via the time(NULL) function found in the <ctime> library At the time of writing the code (2020), the GPS time was ahead of UTC time by 18 (leap) seconds. Adapt the g_leap_seconds ROSaic parameter accordingly as soon as the next leap second is inserted into the UTC time.
Definition at line 768 of file rx_message.cpp.
References parsing_utilities::convertUTCtoUnix(), g_leap_seconds, and string_utilities::toDouble().
Referenced by io_comm_rx::RxMessage::read().
 {
     if (use_gnss)
     {
         uint16_t hh = (tow%(1000*60*60*24))/(60*60*1000);
         uint16_t mm = ((tow%(1000*60*60*24))-hh*(60*60*1000))/(60*1000);
         uint16_t ss = ((tow%(1000*60*60*24))-hh*(60*60*1000)-mm*(60*1000))/(1000);
         uint16_t hs = ((tow%(1000*60*60*24))-hh*(60*60*1000)-mm*(60*1000)-ss*1000)/10; // hundredths of a second
         if (ss >= g_leap_seconds)
         {
             ss = ss - g_leap_seconds;
         }
         else
         {
             if (mm >= 1)
             {
                 --mm;
                 ss = 60 - (g_leap_seconds - ss);
             }
             else
             {
                 if (hh >= 1)
                 {
                     --hh;
                     mm = 59;
                     ss = 60 - (g_leap_seconds - ss);
                 }
                 else
                 {
                     hh = 23;
                     mm = 59;
                     ss = 60 - (g_leap_seconds - ss);
                 }
             }
         }
         boost::format fmt = boost::format("%02u%02u%02u.%02u") % hh % mm % ss % hs;
         std::string utc_string = fmt.str();
         //ROS_DEBUG("UTC string is %s", utc_string.c_str());
         double utc_double;
         string_utilities::toDouble(utc_string, utc_double);
         time_t unix_time_seconds = parsing_utilities::convertUTCtoUnix(utc_double); // This only deals with full seconds.
         // The following works since there are two digits after the decimal point in the utc_double:
         uint32_t unix_time_nanoseconds = (static_cast<uint32_t>(utc_double*100)%100)*10000000;
         ros::Time time_obj(unix_time_seconds, unix_time_nanoseconds);
         return time_obj;
     }
     else
     {
         return ros::Time::now();
     }
 }
Variable Documentation
BAUDRATES
const uint32_t io_comm_rx::BAUDRATES[] static
Initial value:
= {1200, 2400, 4800, 9600, 19200, 38400, 57600,
                                        115200, 230400, 460800, 500000, 576000, 921600,
                                        1000000, 1152000, 1500000, 2000000, 2500000,
                                        3000000, 3500000, 4000000}
Possible baudrates for the Rx.
Definition at line 93 of file communication_core.hpp.
Referenced by io_comm_rx::Comm_IO::initializeSerial().