ROSaic: rosaic_node Namespace Reference
rosaic_node Namespace Reference
Data Structures
class ROSaicNode
This class represents the ROsaic node, to be extended..
Functions
double defaultGetTimeHandler ()
Determines current time via BOOST, using the type boost::gregorian::date.
template<typename MessageT >
void publish (const MessageT &m, const std::string &topic)
Publishes a ROS message of type MessageT to topic "topic".
template<typename V , typename T >
void checkRange (V val, T min, T max, std::string name)
Checks whether the parameter is in the given range.
template<typename V , typename T >
void checkRange (std::vector< V > val, T min, T max, std::string name)
Check whether the elements of the vector are in the given range.
template<typename U >
bool GetROSInt (const std::string &key, U &u)
Gets an integer or unsigned integer value from the parameter server.
template<typename U , typename V >
void GetROSInt (const std::string &key, U &u, V default_val)
Gets an integer or unsigned integer value from the parameter server.
template<typename U >
bool GetROSInt (const std::string &key, std::vector< U > &u)
Gets an unsigned integer or integer vector from the parameter server.
Variables
static constexpr uint32_t ROSQueueSize = 1
Queue size for ROS publishers.
static constexpr float poll_pub_pvt_period = 0.05
Default period in seconds between the polling of two consecutive PVTGeodetic, PosCovGeodetic, PVTCartesian and PosCovCartesian blocks and - if published - between the publishing of two of the corresponding ROS messages.
static constexpr float poll_pub_orientation_period = 0.05
Default period in seconds between the polling of two consecutive AttEuler, AttCovEuler blocks as well as the HRP NMEA sentence, and - if published - between the publishing of AttEuler and AttCovEuler.
static constexpr float poll_pub_rest_period = 0.05
Default period in seconds between the polling of all other SBF blocks and NMEA sentences not addressed by the previous two ROS parameters, and - if published - between the publishing of all other ROS messages.
boost::shared_ptr< ros::NodeHandle > nh
io_comm_mosaic::Comm_IO IO
Handles communication with the mosaic.
std::map< std::string, bool > enabled
Whether or not to publish the given mosaic message.
Detailed Description
This namespace is for the ROSaic node, handling all aspects regarding ROS parameters, ROS message publishing etc.
Function Documentation
checkRange() [1/2]
template<typename V , typename T > void rosaic_node::checkRange (V val, T min, T max, std::string name)
Checks whether the parameter is in the given range.
Parameters
val The value to check
min The minimum for this value
max The maximum for this value
name The name of the parameter
Exceptions
std::runtime_error if it is out of bounds
Definition at line 144 of file rosaic_node.hpp.
Referenced by checkRange(), and GetROSInt().
     {
         if(val < min || val > max)
         {
             std::stringstream oss;
             oss << "Invalid settings: " << name << " must be in range [" << min <<
                 ", " << max << "].";
             throw std::runtime_error(oss.str());
         }
     }
checkRange() [2/2]
template<typename V , typename T > void rosaic_node::checkRange (std::vector< V > val, T min, T max, std::string name)
Check whether the elements of the vector are in the given range.
Parameters
[in] val The vector to check
[in] min The minimum for this value
[in] max The maximum for this value
[in] name The name of the parameter
Exceptions
std::runtime_error value if it is out of bounds
Definition at line 164 of file rosaic_node.hpp.
References checkRange().
     {
         for(size_t i = 0; i < val.size(); i++)
         {
             std::stringstream oss;
             oss << name << "[" << i << "]";
             checkRange(val[i], min, max, oss.str());
         }
     }
defaultGetTimeHandler()
double rosaic_node::defaultGetTimeHandler ()
Determines current time via BOOST, using the type boost::gregorian::date.
Returns
Total number of seconds since midnight
Definition at line 112 of file rosaic_node.hpp.
     {
         boost::posix_time::ptime present_time(boost::posix_time::microsec_clock::universal_time());
         boost::posix_time::time_duration duration(present_time.time_of_day());
         return duration.total_seconds();
     }
GetROSInt() [1/3]
template<typename U > bool rosaic_node::GetROSInt (const std::string & key, U & u)
Gets an integer or unsigned integer value from the parameter server.
Parameters
[in] key The key to be used in the parameter server's dictionary
[out] u Storage for the retrieved value, of type U, which can be either unsigned int or int
Exceptions
std::runtime_error if the parameter is out of bounds
Returns
True if found, false if not found
Definition at line 182 of file rosaic_node.hpp.
References checkRange().
Referenced by GetROSInt(), and rosaic_node::ROSaicNode::GetROSParams().
{
         int param;
         if (!nh->getParam(key, param)) return false;
         // Check the bounds
         U min = std::numeric_limits<U>::lowest();
         U max = std::numeric_limits<U>::max();
         checkRange((U) param, min, max, key);
         // set the output
         u = (U) param;
         return true;
     }
GetROSInt() [2/3]
template<typename U , typename V > void rosaic_node::GetROSInt (const std::string & key, U & u, V default_val)
Gets an integer or unsigned integer value from the parameter server.
Parameters
[in] key The key to be used in the parameter server's dictionary
[out] u Storage for the retrieved value, of type U, which can be either unsigned int or int
[in] val Value to use if the server doesn't contain this parameter
Exceptions
std::runtime_error if the parameter is out of bounds
Returns
True if found, false if not found
Definition at line 203 of file rosaic_node.hpp.
References GetROSInt().
     {
         if(!GetROSInt(key, u))
             u = default_val;
     }
GetROSInt() [3/3]
template<typename U > bool rosaic_node::GetROSInt (const std::string & key, std::vector< U > & u)
Gets an unsigned integer or integer vector from the parameter server.
Exceptions
std::runtime_error if the parameter is out of bounds
Parameters
[in] key The key to be used in the parameter server's dictionary
[out] u Storage for the retrieved value, of type std::vector<U>, where U can be either unsigned int or int
Returns
True if found, false if not found
Definition at line 217 of file rosaic_node.hpp.
References checkRange().
     {
         std::vector<int> param;
         if (!nh->getParam(key, param)) return false;
         // Check the bounds
         U min = std::numeric_limits<U>::lowest();
         U max = std::numeric_limits<U>::max();
         checkRange(param, min, max, key);
         // set the output
         u.insert(u.begin(), param.begin(), param.end());
         return true;
     }
publish()
template<typename MessageT > void rosaic_node::publish (const MessageT & m, const std::string & topic)
Publishes a ROS message of type MessageT to topic "topic".
Parameters
m The message to publish
topic The topic to publish the message to
Definition at line 125 of file rosaic_node.hpp.
References ROSQueueSize.
     {
         //ROS_DEBUG("About to publish message");
         // long read_timestamp = defaultGetTimeHandler();
         // cpu timestamp could be used for whatever purposes, otherwise you get unused warning from compiler
         static ros::Publisher publisher = nh->advertise<MessageT>(topic, ROSQueueSize);
         publisher.publish(m);
     }
Variable Documentation
enabled
std::map<std::string, bool> rosaic_node::enabled
Whether or not to publish the given mosaic message.
The key is the message name, i.e. the message ID for SBF blocks embedded in inverted commas (a string) or the message ID for NMEA messages. The value indicates whether or not to enable that message.
Definition at line 106 of file rosaic_node.hpp.
IO
io_comm_mosaic::Comm_IO rosaic_node::IO
Handles communication with the mosaic.
Definition at line 100 of file rosaic_node.hpp.
Referenced by rosaic_node::ROSaicNode::InitializeIO(), rosaic_node::ROSaicNode::Reconnect(), and rosaic_node::ROSaicNode::Subscribe().
nh
boost::shared_ptr<ros::NodeHandle> rosaic_node::nh
Node Handle for the ROSaic node You must initialize the NodeHandle in the "main" function (or in any method called indirectly or directly by the main function). One can declare a pointer to the NodeHandle to be a global variable and then initialize it afterwards only...
Definition at line 98 of file rosaic_node.hpp.
Referenced by rosaic_node::ROSaicNode::GetROSParams(), main(), and rosaic_node::ROSaicNode::Subscribe().
poll_pub_orientation_period
constexpr float rosaic_node::poll_pub_orientation_period = 0.05 static
Default period in seconds between the polling of two consecutive AttEuler, AttCovEuler blocks as well as the HRP NMEA sentence, and - if published - between the publishing of AttEuler and AttCovEuler.
Definition at line 92 of file rosaic_node.hpp.
poll_pub_pvt_period
constexpr float rosaic_node::poll_pub_pvt_period = 0.05 static
Default period in seconds between the polling of two consecutive PVTGeodetic, PosCovGeodetic, PVTCartesian and PosCovCartesian blocks and - if published - between the publishing of two of the corresponding ROS messages.
Definition at line 90 of file rosaic_node.hpp.
poll_pub_rest_period
constexpr float rosaic_node::poll_pub_rest_period = 0.05 static
Default period in seconds between the polling of all other SBF blocks and NMEA sentences not addressed by the previous two ROS parameters, and - if published - between the publishing of all other ROS messages.
Definition at line 94 of file rosaic_node.hpp.
ROSQueueSize
constexpr uint32_t rosaic_node::ROSQueueSize = 1 static
Queue size for ROS publishers.
Definition at line 88 of file rosaic_node.hpp.
Referenced by publish().