ROSaic: parsing_utilities Namespace Reference
parsing_utilities Namespace Reference
Functions
double ParseDouble (const uint8_t *buffer)
Converts an 8-byte-buffer into a double.
bool ParseDouble (const std::string &string, double &value)
Interprets the contents of "string" as a floating point number of type double, stores its value in "value" and returns whether or not all went well.
float ParseFloat (const uint8_t *buffer)
Converts a 4-byte-buffer into a float.
bool ParseFloat (const std::string &string, float &value)
Interprets the contents of "string" as a floating point number of type float, stores its value in "value" and returns whether or not all went well.
int16_t ParseInt16 (const uint8_t *buffer)
Converts a 2-byte-buffer into a signed 16-bit integer.
bool ParseInt16 (const std::string &string, int16_t &value, int32_t base=10)
Interprets the contents of "string" as a integer number of type int16_t, stores its value in "value" and returns whether or not all went well.
int32_t ParseInt32 (const uint8_t *buffer)
Converts a 4-byte-buffer into a signed 32-bit integer.
bool ParseInt32 (const std::string &string, int32_t &value, int32_t base=10)
Interprets the contents of "string" as a integer number of type int32_t, stores its value in "value" and returns whether or not all went well.
bool ParseUInt8 (const std::string &string, uint8_t &value, int32_t base=10)
Interprets the contents of "string" as a unsigned integer number of type uint8_t, stores its value in "value" and returns whether or not all went well.
uint16_t ParseUInt16 (const uint8_t *buffer)
Converts a 2-byte-buffer into an unsigned 16-bit integer.
bool ParseUInt16 (const std::string &string, uint16_t &value, int32_t base=10)
Interprets the contents of "string" as a unsigned integer number of type uint16_t, stores its value in "value" and returns whether or not all went well.
uint32_t ParseUInt32 (const uint8_t *buffer)
Converts a 4-byte-buffer into an unsigned 32-bit integer.
bool ParseUInt32 (const std::string &string, uint32_t &value, int32_t base=10)
Interprets the contents of "string" as a unsigned integer number of type uint32_t, stores its value in "value" and returns whether or not all went well.
double UTCDoubleToSeconds (double utc_double)
Converts the UTC time from the without-colon-delimiter format, type double, to the number-of-seconds-since-midnight format, type double.
double ConvertDMSToDegrees (double dms)
Converts latitude or longitude from the DMS notation (in the without-colon-delimiter format), type double, to the pure degree notation, type double.
time_t UTCtoUnix (double utc_double)
Converts UTC time from the without-colon-delimiter format, type double, to Unix Epoch time (a number-of-seconds-since-1970/01/01 format), type time_t (usually 32 bits)
geometry_msgs::Quaternion ToQuaternion (double yaw, double pitch, double roll)
Transforms Euler angles to a quaternion.
uint32_t UserPeriodToMosaicPeriod (uint32_t period_user)
Transforms the input polling period [milliseconds] into a uint32_t number that can be appended to either sec or msec for mosaic commands.
Function Documentation
ConvertDMSToDegrees()
double parsing_utilities::ConvertDMSToDegrees (double dms)
Converts latitude or longitude from the DMS notation (in the without-colon-delimiter format), type double, to the pure degree notation, type double.
Recall: One degree is divided into 60 minutes (of arc), and in turn one minute into 60 seconds (of arc). Use of the degrees-minutes-seconds system is also called DMS notation.
Parameters
[in] dms The double variable representing latitude or longitude in the DMS notation (in the without-colon-delimiter format)
Returns
The double variable representing latitude or longitude in the pure degree notation
Definition at line 237 of file parsing_utilities.cpp.
Referenced by GpggaParser::ParseASCII(), and GprmcParser::ParseASCII().
     {
         uint32_t whole_degrees = static_cast<uint32_t>(dms) / 100;
         double minutes = dms - static_cast<double>(whole_degrees * 100);
         double degrees = static_cast<double>(whole_degrees) + minutes / 60.0;
         return degrees;
     }
ParseDouble() [1/2]
double parsing_utilities::ParseDouble (const uint8_t * buffer)
Converts an 8-byte-buffer into a double.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + sizeof(double)) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 8 bytes of data
Returns
The double extracted from the data in the buffer
Definition at line 51 of file parsing_utilities.cpp.
Referenced by GpggaParser::ParseASCII(), and GprmcParser::ParseASCII().
     {
         double diff_loc;
         std::copy(buffer, buffer + sizeof(double), reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseDouble() [2/2]
bool parsing_utilities::ParseDouble (const std::string & string, double & value)
Interprets the contents of "string" as a floating point number of type double, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The double variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
Definition at line 62 of file parsing_utilities.cpp.
References string_utilities::ToDouble().
     {
         return string_utilities::ToDouble(string, value) || string.empty();
     }
ParseFloat() [1/2]
float parsing_utilities::ParseFloat (const uint8_t * buffer)
Converts a 4-byte-buffer into a float.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + sizeof(double)) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 4 bytes of data
Returns
The float extracted from the data in the buffer
Definition at line 72 of file parsing_utilities.cpp.
Referenced by GpggaParser::ParseASCII(), GprmcParser::ParseASCII(), GpgsvParser::ParseASCII(), and GpgsaParser::ParseASCII().
     {
         float diff_loc;
         std::copy(buffer, buffer + sizeof(float), reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseFloat() [2/2]
bool parsing_utilities::ParseFloat (const std::string & string, float & value)
Interprets the contents of "string" as a floating point number of type float, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The float variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
Definition at line 83 of file parsing_utilities.cpp.
References string_utilities::ToFloat().
     {
         return string_utilities::ToFloat(string, value) || string.empty();
     }
ParseInt16() [1/2]
int16_t parsing_utilities::ParseInt16 (const uint8_t * buffer)
Converts a 2-byte-buffer into a signed 16-bit integer.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + 2) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 2 bytes of data
Returns
The int16_t value extracted from the data in the buffer
Definition at line 93 of file parsing_utilities.cpp.
     {
         int16_t diff_loc;
         std::copy(buffer, buffer+2, reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseInt16() [2/2]
bool parsing_utilities::ParseInt16 (const std::string & string, int16_t & value, int32_t base)
Interprets the contents of "string" as a integer number of type int16_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The int16_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 104 of file parsing_utilities.cpp.
References string_utilities::ToInt32().
     {
         value = 0;
         if (string.empty())
         {
           return true;
         }
         int32_t intermd;
         if (string_utilities::ToInt32(string, intermd, base) &&
             intermd <= std::numeric_limits<int16_t>::max() &&
             intermd >= std::numeric_limits<int16_t>::min())
         {
             value = static_cast<int16_t>(intermd);
             return true;
         }
         return false;
     }
ParseInt32() [1/2]
int32_t parsing_utilities::ParseInt32 (const uint8_t * buffer)
Converts a 4-byte-buffer into a signed 32-bit integer.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + 4) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 4 bytes of data
Returns
The int32_t value extracted from the data in the buffer
Definition at line 129 of file parsing_utilities.cpp.
     {
         int32_t diff_loc;
         std::copy(buffer, buffer+4, reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseInt32() [2/2]
bool parsing_utilities::ParseInt32 (const std::string & string, int32_t & value, int32_t base)
Interprets the contents of "string" as a integer number of type int32_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The int32_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 140 of file parsing_utilities.cpp.
References string_utilities::ToInt32().
     {
         return string_utilities::ToInt32(string, value, base) || string.empty();
     }
ParseUInt16() [1/2]
uint16_t parsing_utilities::ParseUInt16 (const uint8_t * buffer)
Converts a 2-byte-buffer into an unsigned 16-bit integer.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + 2) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 2 bytes of data
Returns
The uint16_t value extracted from the data in the buffer
Definition at line 172 of file parsing_utilities.cpp.
     {
         uint16_t number;
         std::copy(buffer, buffer+2, reinterpret_cast<uint8_t*>(&number));
         return number;
     }
ParseUInt16() [2/2]
bool parsing_utilities::ParseUInt16 (const std::string & string, uint16_t & value, int32_t base)
Interprets the contents of "string" as a unsigned integer number of type uint16_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The uint16_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 183 of file parsing_utilities.cpp.
References string_utilities::ToUInt32().
     {
         value = 0;
         if (string.empty())
         {
           return true;
         }
         uint32_t intermd;
         if (string_utilities::ToUInt32(string, intermd, base) && intermd <= std::numeric_limits<uint16_t>::max())
         {
           value = static_cast<uint16_t>(intermd);
           return true;
         }
         return false;
     }
ParseUInt32() [1/2]
uint32_t parsing_utilities::ParseUInt32 (const uint8_t * buffer)
Converts a 4-byte-buffer into an unsigned 32-bit integer.
The function assumes that the bytes in the buffer are already arranged with the same endianness as the local platform. It copies the elements in the range [buffer,buffer + 4) into the range beginning at reinterpret_cast<uint8_t*>(&x). Recall: data_type *var_name = reinterpret_cast <data_type *>(pointer_variable) converts the pointer type, no return type
Parameters
[in] buffer A pointer to a buffer containing 4 bytes of data
Returns
The uint32_t value extracted from the data in the buffer
Definition at line 206 of file parsing_utilities.cpp.
Referenced by GpggaParser::ParseASCII().
     {
         uint32_t diff_loc;
         std::copy(buffer, buffer+4, reinterpret_cast<uint8_t*>(&diff_loc));
         return diff_loc;
     }
ParseUInt32() [2/2]
bool parsing_utilities::ParseUInt32 (const std::string & string, uint32_t & value, int32_t base)
Interprets the contents of "string" as a unsigned integer number of type uint32_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The uint32_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 217 of file parsing_utilities.cpp.
References string_utilities::ToUInt32().
     {
         return string_utilities::ToUInt32(string, value, base) || string.empty();
     }
ParseUInt8()
bool parsing_utilities::ParseUInt8 (const std::string & string, uint8_t & value, int32_t base)
Interprets the contents of "string" as a unsigned integer number of type uint8_t, stores its value in "value" and returns whether or not all went well.
It checks whether an error occurred (via errno) and whether junk characters exist within "string", and returns true if the latter two tests are negative or when the string is empty, false otherwise.
Parameters
[in] string The string whose content should be interpreted as an integer number
[out] value The uint8_t variable that should be overwritten by the integer number found in "string"
[in] base The numerical base of the integer in the string, default being 10
Returns
True if all went fine, false if not
Definition at line 149 of file parsing_utilities.cpp.
References string_utilities::ToUInt32().
Referenced by GpgsvParser::ParseASCII(), and GpgsaParser::ParseASCII().
     {
         value = 0;
         if (string.empty())
         {
           return true;
         }
         uint32_t intermd;
         if (string_utilities::ToUInt32(string, intermd, base) && intermd <= std::numeric_limits<uint8_t>::max())
         {
           value = static_cast<uint8_t>(intermd);
           return true;
         }
         return false;
     }
ToQuaternion()
geometry_msgs::Quaternion parsing_utilities::ToQuaternion (double yaw, double pitch, double roll)
Transforms Euler angles to a quaternion.
The rotational sequence convention we adopt here (and mosaic receivers' pitch, roll, yaw definition too) is the yaw-pitch-roll sequence, i.e. the 3-2-1 sequence: The body first does yaw around the Z=Down-axis, then pitches around the new Y=East=right-axis and finally rolls around the new X=North=forward-axis.
Parameters
[in] yaw Yaw, i.e. heading, about the Up-axis
[in] pitch Pitch about the new North-axis
[in] roll Roll about the new East-axis
Returns
ROS message representing a quaternion
Definition at line 287 of file parsing_utilities.cpp.
Referenced by io_comm_mosaic::mosaicMessage::PoseWithCovarianceStampedCallback().
     {
         // Abbreviations for the angular functions
         double cy = cos(yaw * 0.5);
         double sy = sin(yaw * 0.5);
         double cp = cos(pitch * 0.5);
         double sp = sin(pitch * 0.5);
         double cr = cos(roll * 0.5);
         double sr = sin(roll * 0.5);
         geometry_msgs::Quaternion q;
         q.w = cr * cp * cy + sr * sp * sy;
         q.x = sr * cp * cy - cr * sp * sy;
         q.y = cr * sp * cy + sr * cp * sy;
         q.z = cr * cp * sy - sr * sp * cy;
         return q;
     }
UserPeriodToMosaicPeriod()
uint32_t parsing_utilities::UserPeriodToMosaicPeriod (uint32_t period_user)
Transforms the input polling period [milliseconds] into a uint32_t number that can be appended to either sec or msec for mosaic commands.
Parameters
[in] period_user Polling period in milliseconds as specified by the ROSaic user
Returns
Number to be appended to either sec or msec when sending commands to mosaic
Definition at line 306 of file parsing_utilities.cpp.
Referenced by rosaic_node::ROSaicNode::ConfigureMosaic().
     {
         if (period_user <= 500 && period_user >= 10) return period_user;
         else
         {
             return period_user/1000;
         }
     }
UTCDoubleToSeconds()
double parsing_utilities::UTCDoubleToSeconds (double utc_double)
Converts the UTC time from the without-colon-delimiter format, type double, to the number-of-seconds-since-midnight format, type double.
The UTC precision in NMEA messages is down to a tenth of a second, naturally in both the without-colon-delimiter and the number-of-seconds-since-midnight formats.
Parameters
[in] utc_float The double variable representing UTC time in the without-colon-delimiter format
Returns
The double variable representing UTC time in the number-of-seconds-since-midnight format
Definition at line 225 of file parsing_utilities.cpp.
Referenced by GpggaParser::ParseASCII(), and GprmcParser::ParseASCII().
     {
         uint32_t hours = static_cast<uint32_t>(utc_double) / 10000;
         uint32_t minutes = (static_cast<uint32_t>(utc_double) - hours * 10000) / 100;
         double seconds = utc_double - static_cast<double>(hours * 10000 + minutes * 100);
         seconds += static_cast<double> (hours * 3600 + minutes * 60);
         return seconds;
     }
UTCtoUnix()
time_t parsing_utilities::UTCtoUnix (double utc_double)
Converts UTC time from the without-colon-delimiter format, type double, to Unix Epoch time (a number-of-seconds-since-1970/01/01 format), type time_t (usually 32 bits)
Time information (hours, minutes, seconds) is extracted from the given double and augmented with the date, which is taken from the current system time on the host computer (i.e. current UTC+some_shift time via time(0)). The date ambiguity is resolved by adding/subtracting a day to the current date if the host time is more than 12 hours behind/ahead the NMEA time (i.e. UTC time). Recall time(0), time(NULL): If argument is a null pointer, the parameter is not used (the function still returns the current calendar time of type time_t). Otherwise, the return value is the same as the one stored in the location pointed by the argument. Note that the function assumes that utc_double has two significant digits after the decimal point, i.e. hhmmss.ss, yet it does not round the number of seconds to the nearest unsigned integer, but instead disregards ss. This is since we use this function for the "header.stamp.sec" field of ROS messages, while "header.stamp.nsec" is taken care of separately.
Parameters
[in] utc_float The double variable representing UTC time in the without-colon-delimiter format
Returns
The time_t variable representing Unix Epoch time
Definition at line 255 of file parsing_utilities.cpp.
Referenced by GpggaParser::ParseASCII(), GprmcParser::ParseASCII(), and io_comm_mosaic::TimestampSBF().
     {
         time_t time_now = time(0);
         struct tm * timeinfo;
         // The function localtime uses the value pointed by its argument to fill a tm structure with the values that represent the corresponding time, expressed for the local timezone.
         timeinfo = gmtime(&time_now);
         uint32_t year = timeinfo->tm_year; // year, starting from 1900
         uint32_t month = timeinfo->tm_mon; // months since January - [0,11]
         uint32_t day = timeinfo->tm_mday;  //day of the month - [1,31]
         uint32_t hours = static_cast<uint32_t>(utc_double) / 10000;
         uint32_t minutes = (static_cast<uint32_t>(utc_double) - hours * 10000) / 100;
         uint32_t seconds = (static_cast<uint32_t>(utc_double) - hours * 10000 - minutes * 100);
         //ROS_DEBUG("Checking year %u, month %u, day %u", year, month, day);
         // Overwriting timeinfo with UTC time as extracted from utc_double..
         timeinfo->tm_hour   = hours;            // hours since midnight - [0,23]
         timeinfo->tm_min    = minutes;          // minutes after the hour - [0,59]
         timeinfo->tm_sec    = seconds;          // seconds after the minute - [0,59]
         // Inverse of gmtime, the latter converts time_t (Unix time) to tm (UTC time)
         time_t date = timegm(timeinfo);
         //ROS_DEBUG("Since 1970/01/01 %jd seconds have passed.\n", (intmax_t) date);
         return date;
     }