MinROS: CallbackHandler_< T > Class Template Reference
CallbackHandler_< T > Class Template Reference
#include <minros.hpp>
Public Types
typedef boost::function< void(const T &)> Callback
Public Member Functions
CallbackHandler_ (const Callback &func=Callback())
virtual const T & get ()
void handle (mosaicMessage &mMessage)
Public Member Functions inherited from CallbackHandler
bool wait (const boost::posix_time::time_duration &timeout)
Private Attributes
Callback func_
T message_
Additional Inherited Members
Protected Attributes inherited from CallbackHandler
boost::mutex mutex_
boost::condition_variable condition_
Detailed Description
template<typename T>
class CallbackHandler_< T >
Definition at line 161 of file minros.hpp.
Member Typedef Documentation
Callback
template<typename T> typedef boost::function<void(const T&)> CallbackHandler_< T >::Callback
Definition at line 163 of file minros.hpp.
Constructor & Destructor Documentation
CallbackHandler_()
template<typename T> CallbackHandler_< T >::CallbackHandler_ (const Callback & func = Callback()) inline
Definition at line 165 of file minros.hpp.
 : func_(func) {}
Member Function Documentation
get()
template<typename T> virtual const T& CallbackHandler_< T >::get () inline virtual
Definition at line 167 of file minros.hpp.
Referenced by CallbackHandlers::poll().
 { return message_; }
handle()
template<typename T> void CallbackHandler_< T >::handle (mosaicMessage & mMessage) inline virtual
Implements CallbackHandler.
Definition at line 169 of file minros.hpp.
References CallbackHandler::condition_, debug, mosaicMessage::MessageID(), CallbackHandler::mutex_, and mosaicMessage::read().
{
             boost::mutex::scoped_lock lock(mutex_);
             try {
                 if (!mMessage.read<T>(message_)) {
                     std::stringstream ss;
                     ss << "mosaic decoder error for message with ID " << mMessage.MessageID();
                     ROS_DEBUG_COND(debug >= 2, ss.str());
                     condition_.notify_all();
                     return;
                 }
             } catch (std::runtime_error& e) {
                 std::stringstream ss;
                 ss << "mosaic decoder error for message with ID " << mMessage.MessageID();
                 ROS_DEBUG_COND(debug >= 2, ss.str());
                 condition_.notify_all();
                 return;
             }
             if (func_) func_(message_); // i dont want func_ to return false, hence modify read to add sensible callbackfunction for that message type
             condition_.notify_all();
         }
Field Documentation
func_
template<typename T> Callback CallbackHandler_< T >::func_ private
Definition at line 192 of file minros.hpp.
message_
template<typename T> T CallbackHandler_< T >::message_ private
Definition at line 193 of file minros.hpp.
The documentation for this class was generated from the following file:
include/MinROS/minros.hpp