MinROS: minros_node::MinROSNode Class Reference
minros_node::MinROSNode Class Reference
This class represents the MinROS node for mosaic-X5, to be extended..
#include <minros_node.hpp>
Public Member Functions
MinROSNode ()
void GetROSParams ()
Get the node parameters from the ROS Parameter Server, parts of which are specified in a YAML file, other parts of which are specified via the command line.
void Subscribe ()
Subscribe (= read in) to all requested mosaic messages and publish them.
void InitializeIO ()
Initialize the I/O handling.
void Reconnect (const ros::TimerEvent &event)
Attempts to (re)connect every reconnect_delay_s_ seconds.
Private Attributes
std::string device_
Device port.
uint32_t baudrate_
Baudrate.
float reconnect_delay_s_
Delay in seconds between reconnection attempts to the connection type specified in the parameter connection_type.
ros::Timer reconnect_timer_
Our ROS timer governing the reconnection.
bool connected_ = false
Whether or not connection has been successful so far.
bool publish_gpgga_
Whether or not to publsh GGA messages.
Detailed Description
This class represents the MinROS node for mosaic-X5, to be extended..
Definition at line 237 of file minros_node.hpp.
Constructor & Destructor Documentation
MinROSNode()
minros_node::MinROSNode::MinROSNode ()
The constructor initializes and runs the MinROS node, if all works out fine. It loads the user-defined ROS parameters, subscribes to mosaic messages, and publishes requested ROS messages (for now, 1-1 or GGA-like, not yet NavSatFix that needs multiple messages as input..)
Definition at line 42 of file minros_node.cpp.
References GetROSParams(), InitializeIO(), StringValues_Initialize(), and Subscribe().
 {
     ROS_DEBUG("Entered MinROSNode() constructor..");
     // Params must be set before initializing IO
     GetROSParams();
     StringValues_Initialize();
     ROS_DEBUG("About to call InitializeIO() method");
     InitializeIO();
     // Subscribe to all requested mosaic messages and publish them
     Subscribe();
     ros::spin();
 }
Member Function Documentation
GetROSParams()
void minros_node::MinROSNode::GetROSParams ()
Get the node parameters from the ROS Parameter Server, parts of which are specified in a YAML file, other parts of which are specified via the command line.
Definition at line 57 of file minros_node.cpp.
References baudrate_, device_, minros_node::GetROSInt(), and minros_node::nh.
Referenced by MinROSNode().
 {
     nh->param("device", device_, std::string("/dev/ttyACM0"));
     // Serial params
     GetROSInt("serial/baudrate", baudrate_, 115200);
     // To be implemented: RTCM, setting datum, raw data settings, PPP, SBAS, fix mode...
     ROS_DEBUG("Finished GetROSParams() method");
 }
InitializeIO()
void minros_node::MinROSNode::InitializeIO ()
Initialize the I/O handling.
Definition at line 68 of file minros_node.cpp.
References baudrate_, io_comm_mosaic::debug, device_, io_comm_mosaic::Comm_IO::InitializeSerial(), and minros_node::IO.
Referenced by MinROSNode().
 {
     ROS_DEBUG("Called InitializeIO() method");
     boost::smatch match;
     // In fact: typedef match_results<string::const_iterator> smatch;
     if (boost::regex_match(device_, match,
                          boost::regex("(tcp|udp)://(.+):(\\d+)")))
     // regex_match can be used with a smatch object to store results, or without. In any case, true is returned if and only if it matches the !complete! string.
     {
         // The first sub_match (index 0) contained in a match_result always represents the full match within a target sequence made by a regex,
         // and subsequent sub_matches represent sub-expression matches corresponding in sequence to the left parenthesis delimiting the sub-expression in the regex,
         // i.e. $n Perl is equivalent to m[n] in boost regex.
         std::string proto(match[1]);
         if (proto == "tcp")
         {
             // To be written
             /*
             std::string host(match[2]);
             std::string port(match[3]);
             ROS_INFO("Connecting to %s://%s:%s ...", proto.str(), host.str(), port.str());
             IO.InitializeTCP(host, port);
             */
         }
         else
         {
             throw std::runtime_error("Protocol '" + proto + "' is unsupported");
         }
     }
     else
     {
         // To be modified here, or clarified: how to use reconnect_delay_s properly? Is respawn (roslaunch parameter) enough?
         ROS_DEBUG("Setting timer for calling InitializeSerial() method");
         //nh->param("reconnect_delay_s", reconnect_delay_s_, 0.5f);
         //reconnect_timer_ = nh->createTimer(ros::Duration(reconnect_delay_s_), &MinROSNode::Reconnect, this);
         //reconnect_timer_.start();
         //ros::spin(); // otherwise callback will never be called, with ros::spin i cannot leave InitializeIO(), yet with ros::spinOnce can enter reconnect() even once
         ROS_DEBUG("Current debug value before calling initializeserial() method is %u", io_comm_mosaic::debug);
         IO.InitializeSerial(device_, baudrate_);
         //ROS_DEBUG("Started timer"); //not printed if error in callback of course
     }
     ROS_DEBUG("Leaving InitializeIO()");
 }
Reconnect()
void minros_node::MinROSNode::Reconnect (const ros::TimerEvent & event)
Attempts to (re)connect every reconnect_delay_s_ seconds.
Definition at line 111 of file minros_node.cpp.
References baudrate_, connected_, device_, io_comm_mosaic::Comm_IO::InitializeSerial(), minros_node::IO, and reconnect_timer_.
 {
     ROS_DEBUG("Inside reconnect");
     if(IO.InitializeSerial(device_, baudrate_))
     {
         connected_ = true;
     }
     if (connected_ == true)
     {
         reconnect_timer_.stop();
         ROS_DEBUG("Ended timer");
     }
     ROS_DEBUG("Leaving reconnect");
 }
Subscribe()
void minros_node::MinROSNode::Subscribe ()
Subscribe (= read in) to all requested mosaic messages and publish them.
Definition at line 126 of file minros_node.cpp.
References io_comm_mosaic::CallbackHandlers::callback_mutex_, io_comm_mosaic::CallbackHandlers::callbacks_, io_comm_mosaic::debug, io_comm_mosaic::Comm_IO::get_handlers(), io_comm_mosaic::Comm_IO::handlers_, io_comm_mosaic::CallbackHandlers::insert(), minros_node::IO, minros_node::nh, and publish_gpgga_.
Referenced by MinROSNode().
 {
     ROS_DEBUG("Entered subscribe() method");
     nh->param("publish/gpgga", publish_gpgga_, true);
     if (publish_gpgga_ == true)
     {
         //ROS_DEBUG("Since publish_gpgga is true, insert to map");
         IO.handlers_.callbacks_ = IO.get_handlers().insert<nmea_msgs::Gpgga>("$GPGGA", boost::bind(publish<nmea_msgs::Gpgga>, _1, "/gpgga"));
         std::multimap<std::string, boost::shared_ptr<io_comm_mosaic::CallbackHandler> >::key_type key = "$GPGGA";
         //ROS_DEBUG("Back to subscribe() method: The element exists in our map: %u", (unsigned int) IO.handlers_.callbacks_.count(key));
     }
     ROS_DEBUG("Leaving subscribe() method");
     // and so on
 }
Field Documentation
baudrate_
uint32_t minros_node::MinROSNode::baudrate_ private
Baudrate.
Definition at line 270 of file minros_node.hpp.
Referenced by GetROSParams(), InitializeIO(), and Reconnect().
connected_
bool minros_node::MinROSNode::connected_ = false private
Whether or not connection has been successful so far.
Definition at line 276 of file minros_node.hpp.
Referenced by Reconnect().
device_
std::string minros_node::MinROSNode::device_ private
Device port.
Definition at line 268 of file minros_node.hpp.
Referenced by GetROSParams(), InitializeIO(), and Reconnect().
publish_gpgga_
bool minros_node::MinROSNode::publish_gpgga_ private
Whether or not to publsh GGA messages.
Definition at line 278 of file minros_node.hpp.
Referenced by Subscribe().
reconnect_delay_s_
float minros_node::MinROSNode::reconnect_delay_s_ private
Delay in seconds between reconnection attempts to the connection type specified in the parameter connection_type.
Definition at line 272 of file minros_node.hpp.
reconnect_timer_
ros::Timer minros_node::MinROSNode::reconnect_timer_ private
Our ROS timer governing the reconnection.
Definition at line 274 of file minros_node.hpp.
Referenced by Reconnect().
The documentation for this class was generated from the following files:
include/MinROS/nodelets/minros_node.hpp
src/MinROS/nodelets/minros_node.cpp