MinROS: Septentrio Class Reference
Septentrio Class Reference
#include <minros.hpp>
Public Member Functions
Septentrio ()
~Septentrio ()
Private Member Functions
void bufferIncomingData (uint8_t *msg, size_t length)
data read from serial port is passed to this method
void ParseNMEAASCII (uint8_t *block)
void ParseBinary (uint8_t *block, unsigned short ID)
Parses one septentrio block.
Private Attributes
double read_timestamp
Serial port object for communicating with sensor.
uint8_t dataBuf [4096]
Holds incoming data; Buffer for incoming data. (FYI: An 8-bit signed char is guaranteed to be able to hold values from -127 through 127.)
unsigned int bytesRemaining
Number of bytes to be read in current message.
unsigned int bufIndex
index to dataBuf
bool readingNMEAASCII
BlockHeader_t latest_header
GetTimeHandler time_handler
PvtCartesianCallback pvt_cartesian_callback
PosCovCartesianCallback pos_cov_cartesian_callback
Detailed Description
Definition at line 374 of file minros.hpp.
Constructor & Destructor Documentation
Septentrio()
Septentrio::Septentrio ()
Definition at line 226 of file minros.cpp.
References bufIndex, bytesRemaining, defaultGetTimeHandler(), defaultPosCovCartesianCallback(), defaultPvtCartesianCallback(), pos_cov_cartesian_callback, pvt_cartesian_callback, and time_handler.
 {
   /* initialize serial reader values */
   // good_antenna_locations = true;
   bytesRemaining = 0;
   bufIndex = 0;
   // is_connected = false;
   time_handler =                    defaultGetTimeHandler;
   /*
   receiver_time_callback =          defaultReceiverTimeCallback;
   */
   pvt_cartesian_callback =          defaultPvtCartesianCallback;
   pos_cov_cartesian_callback =      defaultPosCovCartesianCallback;
   /*
   vel_cov_cartesian_callback =      defaultVelCovCartesianCallback;
   attitude_euler_callback =         defaultAttitudeEulerCallback;
   attitude_cov_euler_callback =     defaultAttitudeCovEulerCallback;
   output_rate = "1";
   range_output_rate = "1";
   manual_position = false;
   x1 = 0.0;
   y1 = 0.0;
   z1 = 0.0;
   x2 = 0.0;
   y2 = 0.0;
   z2 = 0.0;
   */
    //Specifically for Sarnoff
   //spits out NMEA messages over COM3 (5 pin output)
   // string NMEACOM3 = "0";//for false - default is not to do it
   // string RTK_com="COM2";
   // string RTK_baud="115200";
   // string RTK_correction_type="CMR";
   // bool rtk_input;
   // if(m_MissionReader.GetConfigurationParam("NMEA_COM3",NMEACOM3)) //Be sure to set in mission file
   // {
   //   if(NMEACOM3 == "1")
   //     RequestNMEACOM3();
   // } else {
   //   MOOSTrace("NMEA_COM3 not set in mission file - Warning Septentrio Default set to False\n");
   // }
   // if(m_MissionReader.GetConfigurationParam("USE_RTK",rtk_input)) //Be sure to set in mission file
   // {
   // } else {
   //   MOOSTrace("USE_RTK not set in mission file - Warning Septentrio Default to false\n");
   //   rtk_input = false;
   // }
   // if (rtk_input)
   // {
   //   if(m_MissionReader.GetConfigurationParam("RTK_COM",RTK_com))
   //   {
   //   }else{
   //     MOOSTrace("RTK_COM not set in mission file - Warning Septentrio Default COM2 set\n");
   //   }
   //   if(m_MissionReader.GetConfigurationParam("RTK_BAUD",RTK_baud))
   //   {
   //   }else{
   //     MOOSTrace("RTK_BAUD not set in mission file - Warning Septentrio Default 115200 set\n");
   //   }
   //   if(m_MissionReader.GetConfigurationParam("RTK_CORRECTION_TYPE",RTK_correction_type))
   //   {
   //   }else{
   //     MOOSTrace("RTK_CORRECTION_TYPE not set in mission file - Warning Septentrio Default CMR set\n");
   //   }
   //   SetRTK(RTK_com,RTK_baud,RTK_correction_type);
   // }
 }
~Septentrio()
Septentrio::~Septentrio ()
Definition at line 304 of file minros.cpp.
 {
   //disconnect();
 }
Member Function Documentation
bufferIncomingData()
void Septentrio::bufferIncomingData (uint8_t * msg, size_t length) private
data read from serial port is passed to this method
< How many bytes are left to read in the !message!, Length tells us length of message, remember..
Definition at line 492 of file minros.cpp.
References bufIndex, bytesRemaining, CRCIsValid(), dataBuf, BlockHeader_t::ID, latest_header, BlockHeader_t::Length, MAX_MSG_SIZE, ParseBinary(), ParseNMEAASCII(), readingNMEAASCII, SEP_SYNC_BYTE_1, SEP_SYNC_BYTE_2, SEP_SYNC_BYTE_3, and SEP_SYNC_BYTE_4.
 {
     // std::cout<<"Buffering\n";
     // std::cout<<"Size of msg: " << length << std::endl;
     // add incoming data to buffer
     for (unsigned int i=0; i<length; i++)
     {
         // i will become very large!
         // cout << i << ": " << hex << (int)msg[i] << dec  << " : " << bytesRemaining  << " : " << bufIndex << endl;
         // make sure bufIndex is not larger than buffer
         if (bufIndex >= MAX_MSG_SIZE)
         {
             bufIndex = 0;
             std::cout << "Septentrio: Overflowed receive buffer. Reset.." << std::endl; // In fact, '\n' is preferred over 'endl' for new line in c++ because 'endl' inserts new line and flushes the stream: Flushing a stream ensures that all data that has been written to that stream is output, including clearing any that may have been buffered.
         }
         // looking for beginning of message
         if (bufIndex == 0)
         {
             if (msg[i] == SEP_SYNC_BYTE_1)
             {
                 // recallint number[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }; cout << "\n number    :  " << Number; will yield the address, same as &number[0], but number[0] gives value
                 // above comparison works since internally, hexadecimal number is also stored as binary data..
                 // beginning of msg found - add to buffer
                 // std::cout << "Beginning of message found\n";
                 dataBuf[bufIndex++] = msg[i]; // post increment operator: first assign, then increment
                 bytesRemaining = 0;
                 readingNMEAASCII = false;
             }
         }
         else if (bufIndex==1)
         {
             // verify 2nd character of header
             if (msg[i] == SEP_SYNC_BYTE_2)
             {
                 // 2nd byte ok - add to buffer
                 dataBuf[bufIndex++]=msg[i];
                 // std::cout<<"Binary Message\n";
             }
             else if (msg[i] == SEP_SYNC_BYTE_3 or msg[i] == SEP_SYNC_BYTE_4)
             {
                 readingNMEAASCII = true;
                 dataBuf[bufIndex++] = msg[i];
                 // std::cout<<"ASCII Message\n";
             }
             else
             {
                 // start looking for new message again
                 // std::cout << "start looking for new message again" << std::endl;
                 bufIndex=0;
                 bytesRemaining=0;
                 readingNMEAASCII=false;
             }
         }
         else if (bufIndex == 7)
         {
             // reading last byte of header
             // std::cout<<"(bufIndex==7)\n";
             dataBuf[bufIndex++]=msg[i];
             //we should have the entire header now
             if (!readingNMEAASCII)
             {
                 memcpy(&latest_header, dataBuf, 8);
                 bytesRemaining = latest_header.Length - 8;
             }
         }
         else if (bytesRemaining==1)
         {
             // add last byte of !message! and parse
             // std::cout<<"(bytesRemaining==1)\n";
             dataBuf[bufIndex++]=msg[i];
             // CRC Check
             bool CRCcheck = CRCIsValid(dataBuf);
             if (CRCcheck == true)
             {
                 std::cout<<"CRC Check returned True. Continue with parsing.. \n";
             }
             else
             {
                 std::cout<<"CRC Check returned False. Not a valid data block, perhaps noisy. Move on to next message/block of data stream..\n";
                 // bufIndex = 0;
                 // bytesRemaining = 0;
                 // readingNMEAASCII = false; // does not make any difference whether included or not
                 break;
             }
             ParseBinary(dataBuf,latest_header.ID); // you dont just parse header!!
             // reset counters
             bufIndex=0;
             bytesRemaining=0;
             // std::cout << "Message Done." << std::endl;
         }
         else if ((bytesRemaining>1)||((bufIndex>1)&&(bufIndex<7)))
         {
             // add data to buffer, this part is very important, either there are many many bytes from message to add to databuf, or from header
             dataBuf[bufIndex++] = msg[i];
             if (!readingNMEAASCII)
             {
                 bytesRemaining--; // recall: post and predecrement don't differ in this case
             }
         }
         else if ( (readingNMEAASCII) && (bufIndex > 7) )
         {
             // std::cout<<"reading ascii message\n";
             // std::cout<<hex<<(int)msg[i]<< std::endl;
             if (!(msg[i]==0x0A))
             {
                 //looking for end of line character, line feed (after carriage return, NMEA message always ends with line feed)
                 dataBuf[bufIndex++]=msg[i];
             }
             else
             {
                 dataBuf[bufIndex++]=msg[i]; // this is = 0, if you search for 0x24 instead
                 ParseNMEAASCII(dataBuf);
                 readingNMEAASCII=false;
                 bufIndex=0;
             }
         }
     }
 }
ParseBinary()
void Septentrio::ParseBinary (uint8_t * block, unsigned short ID) private
Parses one septentrio block.
Definition at line 713 of file minros.cpp.
References pos_cov_cartesian_callback, pvt_cartesian_callback, read_timestamp, and time_handler.
Referenced by bufferIncomingData().
 {
   // std::cout << "Septentrio::ParseBinary" << std::endl;
   switch(ID) {
     /*
     // Reciever time (Current GPS and UTC time)
     case 5914:
       memcpy(&latest_receivertime, block+8, sizeof(latest_receivertime)); // copy block of memory: void * memcpy(void *to, const void *from, size_t numBytes); so the function takes addresses
       receiver_time_callback(latest_receivertime, read_timestamp);
       break;
     */
     // Postion and velocity in XYZ
     case 5903:
       PvtCartesian latest_pvtxyz;
       memcpy(&latest_pvtxyz, block+8, sizeof(latest_pvtxyz)); // you cut out the block you are interested in via sizeof(..) since you do not care about the header of the block..
       read_timestamp = time_handler(); // Caution: This should be part of Septentrio::readSerialPort(), since you want the timestamp when message came in, not after all these calculations...
       pvt_cartesian_callback(latest_pvtxyz, read_timestamp);
       // now do latest_pvtxyz.GPS_ms for instance
       break;
     // Position Covariance block
     case 5905:
       PosCovCartesian latest_pvtxyz_pos_cov;
       memcpy(&latest_pvtxyz_pos_cov, block+8, sizeof(latest_pvtxyz_pos_cov));
       read_timestamp = time_handler();
       pos_cov_cartesian_callback(latest_pvtxyz_pos_cov, read_timestamp);
       break;
     /*
     // Velocity Covariance block
     case 5907:
       VelCovCartesian latest_pvtxyz_vel_cov;
       memcpy(&latest_pvtxyz_vel_cov, block+8, sizeof(latest_pvtxyz_vel_cov));
       vel_cov_cartesian_callback(latest_pvtxyz_vel_cov, read_timestamp);
       break;
     // Attitude expressed as Euler Angle
     case 5938:
       AttitudeEuler latest_atteuler;
       memcpy(&latest_atteuler, block+8, sizeof(latest_atteuler));
       attitude_euler_callback(latest_atteuler, read_timestamp);
       break;
     //Attitude covariance (cross terms not currently given)
     case 5939:
       AttitudeCovEuler latest_atteuler_cov;
       memcpy(&latest_atteuler_cov, block+8, sizeof(latest_atteuler_cov));
       attitude_cov_euler_callback(latest_atteuler_cov, read_timestamp);
       break;
     // //Range (MeasEpoch)
     // case 5889:
     //   update_range(block, blockTime);
     //   break;
     // //Ephemeris (GPSVav)
     // case 5891:
     //   SEP_EPHEMERIS latest_ephemeris;
     //   memcpy(&latest_ephemeris, block+8, sizeof(latest_ephemeris));
     //   update_ephemeris(blockTime);
     //   break;
     */
   }
 }
ParseNMEAASCII()
void Septentrio::ParseNMEAASCII (uint8_t * block) private
Definition at line 615 of file minros.cpp.
References minros_driver::GpggaParser::GetMessageID(), and minros_driver::GpggaParser::ParseASCII().
Referenced by bufferIncomingData().
 {
     // std::stringstream ss (std::stringstream::in | std::stringstream::out); // | is Bitwise inclusive OR, i.e. not XOR, not sure why RHS (right of ss) is needed
     // e.g. int countWords(string str)
     // {     // breaking input into word using string stream
     // std::stringstream s(str); // Used for breaking words
     // string word; // to store individual words
     // int count = 0;
     // while (s >> word)
     //  count++;
     // return count; }
     // std::string block2;
     // E.g. PolaRx: string block="$PolaRx: SetAntennaLocation auto, 2, 5.23, 10.00, -2.000\n $PolaRx: SetAntennaLocation manual, 2, 0.47355, 10.51, -2.143\n";
     std::cout << "ASCII BLOCK:\n" << block << std::endl;
     // ss << block; // Storing the whole string into string stream ss
     // getline(ss,block2); // i think block 2 then does not contain anything other than 1 line, hence seems faulty...
     // part of the <string> header. The getline() function extracts characters from the input stream and appends it to the string object until the delimiting character is encountered. While doing so the previously stored value in the string object str will be replaced by the input string if any.
     // delimitation character here is by default new line(\n)character.
     // std::cout << block2 << std::endl;
     // boost::char_separator<char> sep("\n");
     // The char_separator class breaks a sequence of characters into tokens based on character delimiters
     // boost::tokenizer<boost::char_separator<char> > lines(block2,sep); // lines name is fitting
     // BOOST_FOREACH(std::string line, lines) { // BOOST_FOREACH is great for iterating over sequences, here iterating over lines
         // Example Code for understanding <boost/tokenizer.hpp>..
         /* char_sep_example.cpp
         #include <iostream>
         #include <boost/tokenizer.hpp>
         #include <string>
         int main()
         {
             std::string str = ";;Hello|world||-foo--bar;yow;baz|";
             typedef boost::tokenizer<boost::char_separator<char> >
             tokenizer;
             boost::char_separator<char> sep("-;|");
             tokenizer tokens(str, sep);
             for (tokenizer::iterator tok_iter = tokens.begin();
                tok_iter != tokens.end(); ++tok_iter)
             {
                 std::cout << "<" << *tok_iter << "> ";
                 std::cout << "\n";
             }
             return EXIT_SUCCESS;
         }
         */
         // std::cout << "LINE:\n";
     boost::char_separator<char> sep(","); // needed empty space ", " for SetAntennaLocation for PolaRx..
     typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
     std::string block_in_string(reinterpret_cast<char*>(block));
     // We cannot uses overloaded '=' operator from string class since that converts char* to string
     // Instead, reinterpret_cast<char*>(name) casts from uint8_t* to char* in an unsafe way but that's the one which should be used here. Then you call the ordinary constructor of std::string
     tokenizer tokens(block_in_string,sep);
     minros_driver::GpggaParser parser_obj;
     if (*tokens.begin() == parser_obj.GetMessageID())
     {
         std::string id = parser_obj.GetMessageID();
         std::vector<std::string> body;
         for (tokenizer::iterator tok_iter = tokens.begin(); tok_iter != tokens.end(); ++tok_iter) // perhaps str.erase from <string.h> would be faster, but i would not know what exactly to do..
         {
             // create NmeaSentence struct to pass to GpggaParser::ParseAscii
             body.push_back(*tok_iter);
         }
         minros_driver::NMEASentence gga_message;
         gga_message = {id, body};
         // Pass NmeaSentence struct to GGA-Parser
         nmea_msgs::GpggaPtr gpgga_ros_message_ptr;
         try
         {
             gpgga_ros_message_ptr = parser_obj.ParseASCII(gga_message);
         }
         catch (minros_driver::ParseException& e)
         {
             std::cout << "GGA parsing failed: " << e.what() << "\n";
         }
         // Publish GGA ROS Message to topic /gpgga topic
         // ros::init(argc, argv, "topic_publisher"); // will only be in int main() part of our code...
         ros::NodeHandle nhgga;  //the elegant solution does not have any nodehandle instantiation here I guess.., same for next line perhaps
         ros::Publisher gpgga_pub = nhgga.advertise<nmea_msgs::Gpgga>("/gpgga", 1);
         ROS_INFO("Node and publisher created, now publishing data");
         ros::Rate loop_rate(10);
         while (ros::ok())
         {
             gpgga_pub.publish(*gpgga_ros_message_ptr); // not sure *... works...
             ros::spinOnce();
             loop_rate.sleep();
         }
     }
     // std::cout << "\nASCII MESSAGE!!!\n";
     //cout<<block;
 }
Field Documentation
bufIndex
unsigned int Septentrio::bufIndex private
index to dataBuf
Definition at line 461 of file minros.hpp.
Referenced by bufferIncomingData(), and Septentrio().
bytesRemaining
unsigned int Septentrio::bytesRemaining private
Number of bytes to be read in current message.
Definition at line 460 of file minros.hpp.
Referenced by bufferIncomingData(), and Septentrio().
dataBuf
uint8_t Septentrio::dataBuf[4096] private
Holds incoming data; Buffer for incoming data. (FYI: An 8-bit signed char is guaranteed to be able to hold values from -127 through 127.)
Definition at line 459 of file minros.hpp.
Referenced by bufferIncomingData().
latest_header
BlockHeader_t Septentrio::latest_header private
Definition at line 470 of file minros.hpp.
Referenced by bufferIncomingData().
pos_cov_cartesian_callback
PosCovCartesianCallback Septentrio::pos_cov_cartesian_callback private
Definition at line 483 of file minros.hpp.
Referenced by ParseBinary(), and Septentrio().
pvt_cartesian_callback
PvtCartesianCallback Septentrio::pvt_cartesian_callback private
Definition at line 482 of file minros.hpp.
Referenced by ParseBinary(), and Septentrio().
read_timestamp
double Septentrio::read_timestamp private
Serial port object for communicating with sensor.
shared pointer to Boost thread for listening for data from novatel
Definition at line 451 of file minros.hpp.
Referenced by ParseBinary().
readingNMEAASCII
bool Septentrio::readingNMEAASCII private
Definition at line 462 of file minros.hpp.
Referenced by bufferIncomingData().
time_handler
GetTimeHandler Septentrio::time_handler private
Definition at line 480 of file minros.hpp.
Referenced by ParseBinary(), and Septentrio().
The documentation for this class was generated from the following files:
include/MinROS/minros.hpp
src/MinROS/minros.cpp