MinROS: mosaicMessage Class Reference
mosaicMessage Class Reference
Can search buffer for messages, jump to next one (in case of SBF block), and so on.
#include <mosaicMessage.hpp>
Public Member Functions
mosaicMessage (const uint8_t *data, std::size_t &size)
Constructor of the mosaicMessage class.
bool checksum ()
Calculates the CRC of the SBF block where data_ is pointing to at the moment.
bool isMessage (const uint64_t ID)
Determines whether data_ points to the SBF block with ID "ID", e.g. 5003.
bool isMessage (std::string ID)
Determines whether data_ points to the NMEA message with ID "ID", e.g. "$GPGGA".
std::string MessageID ()
Returns the MessageID of the message where data_ is pointing at at the moment, SBF identifiers embellished with inverted commas, e.g. "5003".
const uint8_t * search ()
Searches the buffer for the beginning of the next message (NMEA or SBF)
uint32_t block_length ()
Gets the length of the SBF block.
const uint8_t * pos ()
Gets the current position in the read buffer.
const uint8_t * end ()
Gets the end position in the read buffer.
bool found ()
Has an NMEA message or SBF block been found in the buffer?
const uint8_t * next ()
Goes to the start of the next message based on the calculated length of current message.
template<typename T >
bool read (typename boost::call_traits< T >::reference message, bool search=false)
Performs CRC check (if SBF block) and populates message with the necessary content (mapped 1-to-1 if SBF, parsed if NMEA), works for pure ROS message mapping.
Private Attributes
const uint8_t * data_
The pointer to the buffer of messages.
uint32_t count_
The number of bytes in the buffer, decremented as the buffer is read (so it is the buffer's size in the beginning)
const uint16_t checksum_
The checksum that is calculated when bool checksum() is called is stored here.
bool found_
Whether or not a message has been found.
Detailed Description
Can search buffer for messages, jump to next one (in case of SBF block), and so on.
Definition at line 55 of file mosaicMessage.hpp.
Constructor & Destructor Documentation
mosaicMessage()
mosaicMessage::mosaicMessage (const uint8_t * data, std::size_t & size) inline
Constructor of the mosaicMessage class.
Parameters
[out] data Pointer to the buffer that is about to be analyzed
[in] size Size of the buffer (as handed over by async_read_some)
Definition at line 63 of file mosaicMessage.hpp.
References block_length(), checksum(), end(), found(), isMessage(), MessageID(), next(), pos(), read(), and search().
 : data_(data), count_(size) {}
Member Function Documentation
block_length()
uint32_t mosaicMessage::block_length ()
Gets the length of the SBF block.
It determines the length from the header of the SBF block and thus includes the header length.
Returns
The length of the SBF block
Definition at line 153 of file mosaicMessage.hpp.
References data_, and SEP_SYNC_BYTE_2.
Referenced by mosaicMessage(), next(), and CallbackHandlers::readCallback().
 {
     if (data_[1] == SEP_SYNC_BYTE_2)
     {
         return static_cast<uint32_t>(static_cast<uint16_t>(data_[6]));
     }
     else
     {
         return 0;
     }
 }
checksum()
bool mosaicMessage::checksum ()
Calculates the CRC of the SBF block where data_ is pointing to at the moment.
Referenced by mosaicMessage(), and search().
end()
const uint8_t * mosaicMessage::end ()
Gets the end position in the read buffer.
Returns
A pointer pointing to just after the read buffer (matches search()'s pointer if no valid message is found)
Definition at line 149 of file mosaicMessage.hpp.
References count_, and data_.
Referenced by mosaicMessage(), and CallbackHandlers::readCallback().
 {
     return data_ + count_;
 }
found()
bool mosaicMessage::found ()
Has an NMEA message or SBF block been found in the buffer?
Returns
True if a message with the correct header & length has been found.
Definition at line 187 of file mosaicMessage.hpp.
References data_, found_, SEP_SYNC_BYTE_2, SEP_SYNC_BYTE_3, and SEP_SYNC_BYTE_4.
Referenced by mosaicMessage(), next(), and CallbackHandlers::readCallback().
 {
     if (found_) return true;
     // Verify header bytes
     if (!(data_[1] == SEP_SYNC_BYTE_2 || (data_[1] == SEP_SYNC_BYTE_3 || data_[1] == SEP_SYNC_BYTE_4)))
         return false;
     found_ = true;
     return true;
 }
isMessage() [1/2]
bool mosaicMessage::isMessage (const uint64_t ID)
Determines whether data_ points to the SBF block with ID "ID", e.g. 5003.
Referenced by mosaicMessage().
isMessage() [2/2]
bool mosaicMessage::isMessage (std::string ID)
Determines whether data_ points to the NMEA message with ID "ID", e.g. "$GPGGA".
MessageID()
std::string mosaicMessage::MessageID ()
Returns the MessageID of the message where data_ is pointing at at the moment, SBF identifiers embellished with inverted commas, e.g. "5003".
Referenced by CallbackHandler_< T >::handle(), CallbackHandlers::handle(), mosaicMessage(), and CallbackHandlers::readCallback().
next()
const uint8_t * mosaicMessage::next ()
Goes to the start of the next message based on the calculated length of current message.
Warning: Won't jump to next message if current one is an NMEA message. search() will then check bytes one by one for new message start.
Definition at line 168 of file mosaicMessage.hpp.
References block_length(), count_, data_, found(), found_, SEP_SYNC_BYTE_3, and SEP_SYNC_BYTE_4.
Referenced by mosaicMessage(), and search().
 {
     if (found())
     {
         if (data_[1] == SEP_SYNC_BYTE_3 || data_[1] == SEP_SYNC_BYTE_4)
         {
             return data_;
         }
         else
         {
             uint32_t size = block_length();
             data_ += size; count_ -= size;
         }
     }
     found_ = false;
     return data_;
 }
pos()
const uint8_t* mosaicMessage::pos ()
Gets the current position in the read buffer.
Returns
The current position of the read buffer
Referenced by mosaicMessage(), and CallbackHandlers::readCallback().
read()
template<typename T > bool mosaicMessage::read (typename boost::call_traits< T >::reference message, bool search = false)
Performs CRC check (if SBF block) and populates message with the necessary content (mapped 1-to-1 if SBF, parsed if NMEA), works for pure ROS message mapping.
Returns
True if read was successful, false otherwise
Referenced by CallbackHandler_< T >::handle(), and mosaicMessage().
search()
const uint8_t * mosaicMessage::search ()
Searches the buffer for the beginning of the next message (NMEA or SBF)
Returns
A pointer to the start of the next message.
Note: Will have to think about what to do in more complex case (e.g. for GPSFix, we need to store values SBF blocks to wait for others).. Note that boost::call_traits<T>::reference is more robust than traditional T&. Note that this function also assigns the appropriate derived parser in case T is an NMEA message.
Definition at line 199 of file mosaicMessage.hpp.
References checksum(), count_, data_, found_, next(), SEP_SYNC_BYTE_2, SEP_SYNC_BYTE_3, and SEP_SYNC_BYTE_4.
Referenced by mosaicMessage(), and CallbackHandlers::readCallback().
Field Documentation
checksum_
const uint16_t mosaicMessage::checksum_ private
The checksum that is calculated when bool checksum() is called is stored here.
Definition at line 135 of file mosaicMessage.hpp.
count_
uint32_t mosaicMessage::count_ private
The number of bytes in the buffer, decremented as the buffer is read (so it is the buffer's size in the beginning)
Definition at line 130 of file mosaicMessage.hpp.
Referenced by end(), next(), and search().
data_
const uint8_t* mosaicMessage::data_ private
The pointer to the buffer of messages.
Definition at line 125 of file mosaicMessage.hpp.
Referenced by block_length(), end(), found(), mosaicMessage(), next(), pos(), and search().
found_
bool mosaicMessage::found_ private
Whether or not a message has been found.
Definition at line 140 of file mosaicMessage.hpp.
Referenced by found(), next(), and search().
The documentation for this class was generated from the following file:
include/MinROS/communication/mosaicMessage.hpp