MinROS: src/MinROS/minros.cpp File Reference
minros.cpp File Reference
#include <include/MinROS/minros.hpp>
#include <memory>
#include <ros/ros.h>
Functions
double defaultGetTimeHandler ()
void defaultPvtCartesianCallback (PvtCartesian &data, double &cpu_stamp)
void defaultPosCovCartesianCallback (PosCovCartesian &data, double &cpu_stamp)
int main (int argc, char **argv)
Function Documentation
defaultGetTimeHandler()
double defaultGetTimeHandler ()
Definition at line 185 of file minros.cpp.
Referenced by Septentrio::Septentrio().
{
   boost::posix_time::ptime present_time(boost::posix_time::microsec_clock::universal_time());
   boost::posix_time::time_duration duration(present_time.time_of_day());
   return duration.total_seconds();
 }
defaultPosCovCartesianCallback()
void defaultPosCovCartesianCallback (PosCovCartesian & data, double & cpu_stamp)
Definition at line 202 of file minros.cpp.
Referenced by Septentrio::Septentrio().
{
   std::cout << "defaultPosCovCartesianCallback: Received PosCovCartesian" << std::endl;
 }
defaultPvtCartesianCallback()
void defaultPvtCartesianCallback (PvtCartesian & data, double & cpu_stamp)
Definition at line 197 of file minros.cpp.
Referenced by Septentrio::Septentrio().
{
   std::cout << "defaultPvtCartesianCallback: Received PvtCartesian" << std::endl;
 }
main()
int main (int argc, char ** argv)
Definition at line 831 of file minros.cpp.
 {
     ros::init(argc, argv, "main");
     Septentrio Testing;
     ros::spin();
     return 0;
 }