MinROS: string_util Namespace Reference
string_util Namespace Reference
Functions
bool ToDouble (const std::string &string, double &value)
Interprets the contents of "string" as a floating point number, stores its value in "value" and returns whether all went well.
bool ToFloat (const std::string &string, float &value)
bool ToInt32 (const std::string &string, int32_t &value, int32_t base=10)
bool ToUInt32 (const std::string &string, uint32_t &value, int32_t base=10)
Function Documentation
ToDouble()
bool string_util::ToDouble (const std::string & string, double & value)
Interprets the contents of "string" as a floating point number, stores its value in "value" and returns whether all went well.
Parameters
[in] string The string whose content should be interpreted as a floating point number
[out] value The double variable that should be overwritten by the floating point number found in "string"
Returns
True if all went fine, false if not
It checks whether or not an error occurred (via errno) and whether junk characters existed within "string", and returns true if the latter two tests are negative, false otherwise.
Definition at line 43 of file string_utilities.cpp.
Referenced by minros_driver::GpggaParser::ParseASCII(), and minros_driver::ParseDouble().
     {
         if (string.empty())
         {
             return false;
         }
         char* end;
         errno = 0;
         double value_new = strtod(string.c_str(), &end);
         if (errno != 0 || end != string.c_str() + string.length())
         {
             return false;
         }
         value = value_new;
         return true;
     }
ToFloat()
bool string_util::ToFloat (const std::string & string, float & value)
Definition at line 64 of file string_utilities.cpp.
Referenced by minros_driver::ParseFloat().
     {
         if (string.empty())
         {
             return false;
         }
         char* end;
         errno = 0;
         float number = strtof(string.c_str(), &end);
         // Check if an error occured or if there are junk characters at the end.
         if (errno != 0 || end != string.c_str() + string.length())
         {
             return false;
         }
         value = number;
         return true;
     }
ToInt32()
bool string_util::ToInt32 (const std::string & string, int32_t & value, int32_t base = 10)
Definition at line 85 of file string_utilities.cpp.
Referenced by minros_driver::ParseInt16(), and minros_driver::ParseInt32().
     {
         if (string.empty())
         {
             return false;
         }
         char* end;
         errno = 0;
         int64_t number = strtol(string.c_str(), &end, base);
         // Check if an error occured or if there are junk characters at the end.
         if (errno != 0 || end != string.c_str() + string.length())
         {
             return false;
         }
         if (number > std::numeric_limits<int32_t>::max() ||
          number < std::numeric_limits<int32_t>::min())
         {
             return false;
         }
         value = number;
         return true;
     }
ToUInt32()
bool string_util::ToUInt32 (const std::string & string, uint32_t & value, int32_t base = 10)
Definition at line 112 of file string_utilities.cpp.
Referenced by minros_driver::ParseUInt16(), minros_driver::ParseUInt32(), and minros_driver::ParseUInt8().
     {
         if (string.empty())
         {
             return false;
         }
         char* end;
         errno = 0;
         int64_t number = strtol(string.c_str(), &end, base);
         // Check if an error occured or if there are junk characters at the end.
         if (errno != 0 || end != string.c_str() + string.length())
         {
             return false;
         }
         if (number > std::numeric_limits<uint32_t>::max() || number < 0)
         {
             return false;
         }
         value = number;
         return true;
     }