MinROS: Serializer< T > Struct Template Reference
Serializer< T > Struct Template Reference
#include <serializer.hpp>
Static Public Member Functions
static void read (const uint8_t *data, uint32_t count, typename boost::call_traits< T >::reference message)
static uint32_t serializedLength (typename boost::call_traits< T >::param_type message)
static void write (uint8_t *data, uint32_t size, typename boost::call_traits< T >::param_type message)
Detailed Description
template<typename T>
struct Serializer< T >
Definition at line 49 of file serializer.hpp.
Member Function Documentation
read()
template<typename T > static void Serializer< T >::read (const uint8_t * data, uint32_t count, typename boost::call_traits< T >::reference message) static
Referenced by Reader::read().
serializedLength()
template<typename T > static uint32_t Serializer< T >::serializedLength (typename boost::call_traits< T >::param_type message) static
Referenced by Writer::write().
write()
template<typename T > static void Serializer< T >::write (uint8_t * data, uint32_t size, typename boost::call_traits< T >::param_type message) static
Referenced by Writer::write().
The documentation for this struct was generated from the following file:
include/MinROS/serial_comm/serializer.hpp